In [2]:
%%time
%matplotlib inline
import pandas as pd
import numpy as np
import re
import os
import time


raw_path = 'C:\\Finance_team\\raw_data' 
out_path = 'C:\\Finance_team\\Testing_result'
file_list = os.listdir('C:\\Finance_team\\raw_data')

product_id = ''
product_code = ''
date = ''
all_columns = ['time', 'cur_price', 'exec_q', 'inv_t', 'l_lvl1_q', 's_lvl1_q', 'inv_l_q', 'inv_s_q', 's_or_l']
int_columns = ['cur_price', 'exec_q', 'inv_t', 'l_lvl1_q', 's_lvl1_q', 'inv_l_q', 'inv_s_q', 's_or_l']

def is_target_product_ID(line):
    return line[17:19] == 'A0' and line[425:428] == 'BM3' and line[471:474] == '001'

for i in file_list:
    print(i)
    with open('{0}\\{1}'.format(raw_path, i), 'r', encoding='ISO-8859-1') as f:
        result = []
        lines = f.readlines()
        data_in_array = []

        for line in lines:
            if is_target_product_ID(line):
                product_id = line[53:64]
                product_code = line[35:47]
                date = line[27:35]
                break
        
        for line in lines:
            data_in_array.append(np.array(line.split(',')))
        
        for line in data_in_array:
            
            if (line[0][1:3] < '09'): continue

            if (line[0][1:3] == '15' and line[0][4:6] == '45' and line[0][7:9] >= '01'): break
                  
            if (line[0][22:34] == product_code) or (line[0][38:49] == product_id):
        
                if line[0][17:19] == 'A3':
                    result.append([line[0][:17], line[0][40:48], line[0][48:54],np.nan, 
                                    np.nan, np.nan, np.nan, np.nan, line[0][152:153]])
                elif line[0][17:19] == 'B6':
                    result.append([line[0][:17], np.nan, np.nan, np.nan, line[0][57:63], 
                                    line[0][139:145], np.nan, np.nan, np.nan])  
                elif line[0][17:19] == 'G7':
                    result.append([line[0][:17], line[0][40:48], line[0][48:54],
                                   np.nan, line[0][169:175], line[0][251:257], 
                                   np.nan, np.nan, line[0][152:153]])
                elif (line[0][17:19] == 'H1' and (line[0][49:53] == '1000' or line[0][49:53] == '4000' or line[0][49:53] == '9000')):
                    if (line[0][1:3] == '15' and line[0][4:6] == '35' and line[0][7:9] >= '01'): break
                    result.append([line[0][:17], np.nan, np.nan, line[0][49:53],
                                  np.nan, np.nan, line[0][53:62], line[0][62:71],
                                  np.nan])
            
        result_frame = pd.DataFrame(result, columns = all_columns)
        result_frame.drop(0, inplace=True)
        
result_frame
        
#         result_frame.to_csv('C:\\Finance_team\\Testing_result\\{0}_{1}.csv'.format(product_code, date)) # Data Save as csv file

sise2local.ALL_CMDT.0201
Wall time: 6.35 s

In [3]:
result_frame

,time,cur_price,exec_q,inv_t,l_lvl1_q,s_lvl1_q,inv_l_q,inv_s_q,s_or_l
1,[09:00:01-039271],NaN,NaN,NaN,000850,000187,NaN,NaN,NaN
2,[09:00:01-066900],NaN,NaN,NaN,000850,000187,NaN,NaN,NaN
3,[09:00:01-090882],00010745,000001,NaN,000849,000187,NaN,NaN,1
4,[09:00:01-103833],NaN,NaN,NaN,000852,000187,NaN,NaN,NaN
5,[09:00:01-105408],NaN,NaN,NaN,000003,000187,NaN,NaN,NaN
6,[09:00:01-168950],NaN,NaN,NaN,000852,000187,NaN,NaN,NaN
7,[09:00:01-198520],NaN,NaN,NaN,000852,000240,NaN,NaN,NaN
8,[09:00:01-501859],NaN,NaN,NaN,000852,000240,NaN,NaN,NaN
9,[09:00:01-931889],NaN,NaN,NaN,000552,000240,NaN,NaN,NaN
10,[09:00:02-120073],NaN,NaN,NaN,000552,000540,NaN,NaN,NaN
11,[09:00:02-121579],NaN,NaN,NaN,000552,000543,NaN,NaN,NaN
12,[09:00:02-273956],NaN,NaN,NaN,000552,000003,NaN,NaN,NaN
13,[09:00:02-276686],00010746,000003,NaN,000552,000543,NaN,NaN,2
14,[09:00:02-372071],NaN,NaN,NaN,000552,000490,NaN,NaN,NaN
15,[09:00:02-499330],NaN,NaN,NaN,000552,000543,NaN,NaN,NaN
16,[09:00:02-500928],NaN,NaN,NaN,000552,000003,NaN,NaN,NaN
17,[09:00:02-542597],NaN,NaN,NaN,000652,000003,NaN,NaN,NaN
18,[09:00:02-543942],NaN,NaN,NaN,000652,000543,NaN,NaN,NaN
19,[09:00:02-645389],NaN,NaN,NaN,000652,000490,NaN,NaN,NaN
20,[09:00:02-678634],NaN,NaN,NaN,000602,000490,NaN,NaN,NaN
21,[09:00:02-686589],00010745,000050,NaN,000552,000490,NaN,NaN,1
22,[09:00:02-712156],NaN,NaN,NaN,000552,000490,NaN,NaN,NaN
23,[09:00:02-729089],NaN,NaN,NaN,000552,000540,NaN,NaN,NaN
24,[09:00:02-731958],NaN,NaN,NaN,000552,000540,NaN,NaN,NaN
25,[09:00:02-778266],NaN,NaN,NaN,000552,000593,NaN,NaN,NaN
26,[09:00:02-810954],NaN,NaN,NaN,000602,000593,NaN,NaN,NaN
27,[09:00:02-815299],NaN,NaN,NaN,000602,000593,NaN,NaN,NaN
28,[09:00:02-994660],NaN,NaN,NaN,000652,000593,NaN,NaN,NaN
29,[09:00:03-234146],00010747,000100,NaN,000652,000493,NaN,NaN,2
30,[09:00:03-677248],NaN,NaN,NaN,000100,000493,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
17522,[15:34:48-878139],NaN,NaN,NaN,000201,001981,NaN,NaN,NaN
17523,[15:34:49-075886],NaN,NaN,NaN,000201,001981,NaN,NaN,NaN
17524,[15:34:49-246462],NaN,NaN,NaN,000201,001981,NaN,NaN,NaN
17525,[15:34:49-389275],NaN,NaN,NaN,000201,001981,NaN,NaN,NaN
17526,[15:34:49-620608],NaN,NaN,NaN,000201,002081,NaN,NaN,NaN
17527,[15:34:51-799631],NaN,NaN,NaN,000201,002081,NaN,NaN,NaN
17528,[15:34:53-932194],NaN,NaN,NaN,000201,002081,NaN,NaN,NaN
17529,[15:34:55-606274],NaN,NaN,NaN,000201,002081,NaN,NaN,NaN
17530,[15:34:56-150192],NaN,NaN,NaN,000201,002081,NaN,NaN,NaN
17531,[15:34:57-206129],NaN,NaN,NaN,000201,002081,NaN,NaN,NaN
17532,[15:34:57-481088],NaN,NaN,NaN,000201,002081,NaN,NaN,NaN
17533,[15:34:58-009056],NaN,NaN,NaN,000201,002081,NaN,NaN,NaN
17534,[15:34:58-009200],NaN,NaN,NaN,000201,002081,NaN,NaN,NaN
17535,[15:34:58-225199],NaN,NaN,NaN,000201,002081,NaN,NaN,NaN
17536,[15:34:58-830607],NaN,NaN,NaN,000301,002081,NaN,NaN,NaN
17537,[15:34:59-119018],NaN,NaN,NaN,000301,002081,NaN,NaN,NaN
17538,[15:34:59-674355],00010752,000100,NaN,000201,002081,NaN,NaN,1
17539,[15:34:59-851793],00010752,000001,NaN,000200,002081,NaN,NaN,1
17540,[15:34:59-863208],00010753,000010,NaN,000200,002071,NaN,NaN,2
17541,[15:35:01-758048],NaN,NaN,NaN,000000,000000,NaN,NaN,NaN
17542,[15:35:01-759712],NaN,NaN,NaN,000000,000000,NaN,NaN,NaN
17543,[15:35:01-759940],NaN,NaN,NaN,000000,000000,NaN,NaN,NaN
17544,[15:35:02-004205],NaN,NaN,NaN,000000,000000,NaN,NaN,NaN
17545,[15:35:02-773814],NaN,NaN,NaN,000000,000000,NaN,NaN,NaN
17546,[15:35:02-773994],NaN,NaN,NaN,000000,000000,NaN,NaN,NaN
17547,[15:35:02-775132],NaN,NaN,NaN,000000,000000,NaN,NaN,NaN
17548,[15:35:03-070129],NaN,NaN,NaN,000000,000000,NaN,NaN,NaN
17549,[15:35:03-070345],NaN,NaN,NaN,000000,000000,NaN,NaN,NaN
17550,[15:35:03-390240],NaN,NaN,NaN,000000,000000,NaN,NaN,NaN
17551,[15:35:03-390545],NaN,NaN,NaN,000000,000000,NaN,NaN,NaN

In [4]:
# a = result_frame[['time','cur_price']].dropna().reset_index(drop=True)

In [5]:
# df = pd.DataFrame(columns=['time', 'price', 'data_type'])
# df['time'] = ['090001', '090002', '090003', '090004', '090005', '090006', '090007']
# df['price'] = ['101792', '101793', '101792', '101795', '101793', '101792', '101795']
# df['data_type'] = ['A3', 'G7', 'A3', 'G7', 'A3', 'G7', 'A3']
df[(df['price'] == '101792') & (df['data_type'] == 'A3')]

### H1코드 작업

In [6]:
h1 = result_frame[(result_frame['inv_t'] == '1000')]

In [7]:
h1[['inv_l_q', 'inv_s_q']] = h1[['inv_l_q', 'inv_s_q']].astype('int')

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:2540: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]

In [8]:
## pct_change()함수 활용하여 H1 data 원하는 형태로 만든 후, 차이값 찾기
h1['l_q_cur-prev'] = h1.inv_l_q.pct_change() * 100
h1['s_q_cur-prev'] = h1.inv_s_q.pct_change() * 100
h1[['time', 'inv_l_q', 'inv_s_q', 'l_q_cur-prev', 's_q_cur-prev']]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

                    time  inv_l_q  inv_s_q  l_q_cur-prev  s_q_cur-prev
166    [09:00:36-918856]     2734     1239           NaN           NaN
229    [09:01:04-218414]     3014     1559     10.241405     25.827280
271    [09:01:34-112279]     3046     1591      1.061712      2.052598
403    [09:02:04-268661]     3604     2049     18.319107     28.786926
514    [09:02:34-022089]     4294     2612     19.145394     27.476818
553    [09:03:04-133248]     4294     2695      0.000000      3.177642
613    [09:03:34-103406]     4304     2904      0.232883      7.755102
656    [09:04:03-918109]     4367     2954      1.463755      1.721763
724    [09:04:34-222003]     4507     3028      3.205862      2.505078
754    [09:05:04-348090]     4894     3138      8.586643      3.632761
797    [09:05:34-453325]     4894     3138      0.000000      0.000000
888    [09:06:04-369131]     5210     3282      6.456886      4.588910
963    [09:06:34-628930]     5670     3522      8.829175      7.312614
1030   [09:07:04-024014]     5680     3522      0.176367      0.000000
1055   [09:07:34-173080]     6018     3860      5.950704      9.596820
1107   [09:08:04-437056]     6474     3862      7.577268      0.051813
1129   [09:08:34-512227]     6474     3862      0.000000      0.000000
1149   [09:09:04-409159]     6474     3925      0.000000      1.631279
1166   [09:09:36-423615]     6474     4005      0.000000      2.038217
1272   [09:10:04-621671]     7309     4355     12.897745      8.739076
1324   [09:10:34-312856]     8409     4615     15.049938      5.970149
1380   [09:11:04-154519]     8409     4621      0.000000      0.130011
1446   [09:11:34-229596]     8479     4676      0.832441      1.190219
1471   [09:12:04-497672]     8709     4976      2.712584      6.415740
1604   [09:12:34-125193]     8838     5366      1.481226      7.837621
1650   [09:13:03-982166]     8926     5373      0.995700      0.130451
1712   [09:13:34-152245]     9026     5595      1.120323      4.131770
1773   [09:14:04-005669]     9376     5596      3.877687      0.017873
1790   [09:14:34-068397]     9376     5596      0.000000      0.000000
1826   [09:15:03-788802]     9647     5596      2.890358      0.000000
...                  ...      ...      ...           ...           ...
17005  [15:20:03-840401]    55287    38496      0.000000      0.000000
17016  [15:20:34-401423]    55333    38496      0.083202      0.000000
17024  [15:21:04-571116]    55334    38496      0.001807      0.000000
17032  [15:21:34-565239]    55334    38496      0.000000      0.000000
17037  [15:22:04-221763]    55334    38496      0.000000      0.000000
17040  [15:22:34-513638]    55334    38496      0.000000      0.000000
17045  [15:23:03-756635]    55334    38496      0.000000      0.000000
17050  [15:23:33-937592]    55334    38496      0.000000      0.000000
17066  [15:24:03-788210]    55334    38496      0.000000      0.000000
17071  [15:24:33-823876]    55334    38496      0.000000      0.000000
17092  [15:25:03-686035]    55334    38496      0.000000      0.000000
17121  [15:25:33-683433]    55534    38665      0.361441      0.439007
17130  [15:26:03-804365]    55534    38665      0.000000      0.000000
17144  [15:26:33-863210]    55784    38810      0.450175      0.375016
17188  [15:27:04-050293]    55811    38895      0.048401      0.219016
17198  [15:27:33-844187]    55811    38895      0.000000      0.000000
17203  [15:28:03-913822]    55811    38895      0.000000      0.000000
17207  [15:28:33-900691]    55811    38895      0.000000      0.000000
17220  [15:29:03-858225]    55811    38895      0.000000      0.000000
17238  [15:29:33-811910]    55811    38895      0.000000      0.000000
17268  [15:30:04-895931]    56076    39161      0.474817      0.683893
17334  [15:30:36-011290]    56270    39474      0.345959      0.799265
17346  [15:31:04-582571]    56270    39487      0.000000      0.032933
17369  [15:31:34-268702]    56280    39547      0.017771      0.151949
17402  [15:32:04-186799]    56612    39878      0.589908      0.836979
17410  [15:32:34-192790]    56612    39878      0.000000      0.000000
17440  [15:33:04-263606]    56800    40082      0.332085      0.511560
17450  [15:33:33-792973]    56800    40190      0.000000      0.269448
17473  [15:34:04-349309]    56820    40310      0.035211      0.298582
17495  [15:34:34-584608]    56830    40349      0.017599      0.096750

[789 rows x 5 columns]

In [9]:
## diff()함수 활용하여 H1 data 원하는 형태로 만든 후, 차이값 찾기
h1['l_q_cur-prev'] = h1.inv_l_q.diff()
h1['s_q_cur-prev'] = h1.inv_s_q.diff()
h1[['time', 'inv_l_q', 'inv_s_q', 'l_q_cur-prev', 's_q_cur-prev']]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

                    time  inv_l_q  inv_s_q  l_q_cur-prev  s_q_cur-prev
166    [09:00:36-918856]     2734     1239           NaN           NaN
229    [09:01:04-218414]     3014     1559         280.0         320.0
271    [09:01:34-112279]     3046     1591          32.0          32.0
403    [09:02:04-268661]     3604     2049         558.0         458.0
514    [09:02:34-022089]     4294     2612         690.0         563.0
553    [09:03:04-133248]     4294     2695           0.0          83.0
613    [09:03:34-103406]     4304     2904          10.0         209.0
656    [09:04:03-918109]     4367     2954          63.0          50.0
724    [09:04:34-222003]     4507     3028         140.0          74.0
754    [09:05:04-348090]     4894     3138         387.0         110.0
797    [09:05:34-453325]     4894     3138           0.0           0.0
888    [09:06:04-369131]     5210     3282         316.0         144.0
963    [09:06:34-628930]     5670     3522         460.0         240.0
1030   [09:07:04-024014]     5680     3522          10.0           0.0
1055   [09:07:34-173080]     6018     3860         338.0         338.0
1107   [09:08:04-437056]     6474     3862         456.0           2.0
1129   [09:08:34-512227]     6474     3862           0.0           0.0
1149   [09:09:04-409159]     6474     3925           0.0          63.0
1166   [09:09:36-423615]     6474     4005           0.0          80.0
1272   [09:10:04-621671]     7309     4355         835.0         350.0
1324   [09:10:34-312856]     8409     4615        1100.0         260.0
1380   [09:11:04-154519]     8409     4621           0.0           6.0
1446   [09:11:34-229596]     8479     4676          70.0          55.0
1471   [09:12:04-497672]     8709     4976         230.0         300.0
1604   [09:12:34-125193]     8838     5366         129.0         390.0
1650   [09:13:03-982166]     8926     5373          88.0           7.0
1712   [09:13:34-152245]     9026     5595         100.0         222.0
1773   [09:14:04-005669]     9376     5596         350.0           1.0
1790   [09:14:34-068397]     9376     5596           0.0           0.0
1826   [09:15:03-788802]     9647     5596         271.0           0.0
...                  ...      ...      ...           ...           ...
17005  [15:20:03-840401]    55287    38496           0.0           0.0
17016  [15:20:34-401423]    55333    38496          46.0           0.0
17024  [15:21:04-571116]    55334    38496           1.0           0.0
17032  [15:21:34-565239]    55334    38496           0.0           0.0
17037  [15:22:04-221763]    55334    38496           0.0           0.0
17040  [15:22:34-513638]    55334    38496           0.0           0.0
17045  [15:23:03-756635]    55334    38496           0.0           0.0
17050  [15:23:33-937592]    55334    38496           0.0           0.0
17066  [15:24:03-788210]    55334    38496           0.0           0.0
17071  [15:24:33-823876]    55334    38496           0.0           0.0
17092  [15:25:03-686035]    55334    38496           0.0           0.0
17121  [15:25:33-683433]    55534    38665         200.0         169.0
17130  [15:26:03-804365]    55534    38665           0.0           0.0
17144  [15:26:33-863210]    55784    38810         250.0         145.0
17188  [15:27:04-050293]    55811    38895          27.0          85.0
17198  [15:27:33-844187]    55811    38895           0.0           0.0
17203  [15:28:03-913822]    55811    38895           0.0           0.0
17207  [15:28:33-900691]    55811    38895           0.0           0.0
17220  [15:29:03-858225]    55811    38895           0.0           0.0
17238  [15:29:33-811910]    55811    38895           0.0           0.0
17268  [15:30:04-895931]    56076    39161         265.0         266.0
17334  [15:30:36-011290]    56270    39474         194.0         313.0
17346  [15:31:04-582571]    56270    39487           0.0          13.0
17369  [15:31:34-268702]    56280    39547          10.0          60.0
17402  [15:32:04-186799]    56612    39878         332.0         331.0
17410  [15:32:34-192790]    56612    39878           0.0           0.0
17440  [15:33:04-263606]    56800    40082         188.0         204.0
17450  [15:33:33-792973]    56800    40190           0.0         108.0
17473  [15:34:04-349309]    56820    40310          20.0         120.0
17495  [15:34:34-584608]    56830    40349          10.0          39.0

[789 rows x 5 columns]

In [10]:
h1.columns

Index(['time', 'cur_price', 'exec_q', 'inv_t', 'l_lvl1_q', 's_lvl1_q',
       'inv_l_q', 'inv_s_q', 's_or_l', 'l_q_cur-prev', 's_q_cur-prev'],
      dtype='object')