In [1]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import KFold
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

In [2]:
weather = pd.read_csv("weather3_180703.csv")
weather['date'] = pd.to_datetime(weather["date"])
station = weather[weather['station_nbr'] == 13]

In [3]:
station['date'].count()

1035

In [4]:
# ls == 모든 값이 0인 것

ls = []
ls1 = []
for i in station.columns:
    if station[i].count() == 0:
        ls.append(i)
    if station[i].isna().sum() != 0:
        ls1.append(i)
ls, ls1

(['depart', 'sunrise', 'sunset', 'snowfall', 'daytime'],
 ['depart', 'sunrise', 'sunset', 'snowfall', 'daytime'])

In [5]:
for i in station.columns:
    count_null = station[i].isna().sum()
    print(i, ":", count_null, "(",round((count_null / len(station) * 100),2),"%",")")

station_nbr : 0 ( 0.0 % )
date : 0 ( 0.0 % )
tmax : 0 ( 0.0 % )
tmin : 0 ( 0.0 % )
tavg : 0 ( 0.0 % )
depart : 1035 ( 100.0 % )
dewpoint : 0 ( 0.0 % )
wetbulb : 0 ( 0.0 % )
heat : 0 ( 0.0 % )
cool : 0 ( 0.0 % )
sunrise : 1035 ( 100.0 % )
sunset : 1035 ( 100.0 % )
codesum : 0 ( 0.0 % )
snowfall : 1035 ( 100.0 % )
preciptotal : 0 ( 0.0 % )
stnpressure : 0 ( 0.0 % )
sealevel : 0 ( 0.0 % )
resultspeed : 0 ( 0.0 % )
resultdir : 0 ( 0.0 % )
avgspeed : 0 ( 0.0 % )
year : 0 ( 0.0 % )
month : 0 ( 0.0 % )
day : 0 ( 0.0 % )
relative_humility : 0 ( 0.0 % )
windchill : 0 ( 0.0 % )
daytime : 1035 ( 100.0 % )
week7 : 0 ( 0.0 % )
weekend : 0 ( 0.0 % )
code_change : 0 ( 0.0 % )
rainY : 0 ( 0.0 % )
otherY : 0 ( 0.0 % )
nothing : 0 ( 0.0 % )

In [6]:
train = pd.read_csv("train.csv")
train.date = pd.to_datetime(train.date)
train.tail()

              date  store_nbr  item_nbr  units
4617595 2014-10-31         45       107      0
4617596 2014-10-31         45       108      0
4617597 2014-10-31         45       109      0
4617598 2014-10-31         45       110      0
4617599 2014-10-31         45       111      0

In [7]:
key = pd.read_csv("key.csv")
station = station.merge(key)

In [8]:
station = station.merge(train)
station.tail()

,station_nbr,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,...,daytime,week7,weekend,code_change,rainY,otherY,nothing,store_nbr,item_nbr,units
561100,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,107,0
561101,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,108,0
561102,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,109,0
561103,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,110,0
561104,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,111,0

In [9]:
station['log1p_units'] = np.log1p(station.units)

In [10]:
target1 = station['units']
target2 = station['log1p_units']

station.drop(columns=['units','log1p_units'],inplace=True)
station.tail()

,station_nbr,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,...,windchill,daytime,week7,weekend,code_change,rainY,otherY,nothing,store_nbr,item_nbr
561100,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,42.873464,NaN,4,0,0,0,0,1,40,107
561101,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,42.873464,NaN,4,0,0,0,0,1,40,108
561102,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,42.873464,NaN,4,0,0,0,0,1,40,109
561103,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,42.873464,NaN,4,0,0,0,0,1,40,110
561104,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,42.873464,NaN,4,0,0,0,0,1,40,111

In [11]:
df1 = pd.concat([station,target1], axis=1)
df2 = pd.concat([station,target2], axis=1)

In [12]:
df2.to_csv('station13.csv', sep=',', index=False)

In [13]:
if df2.columns.tolist() and ls:
    print('공통 변수 있음')
    print(df2.columns.tolist() and ls)
else:
    print('공통 변수 없음')

공통 변수 있음
['depart', 'sunrise', 'sunset', 'snowfall', 'daytime']

In [14]:
df2.columns

Index(['station_nbr', 'date', 'tmax', 'tmin', 'tavg', 'depart', 'dewpoint',
       'wetbulb', 'heat', 'cool', 'sunrise', 'sunset', 'codesum', 'snowfall',
       'preciptotal', 'stnpressure', 'sealevel', 'resultspeed', 'resultdir',
       'avgspeed', 'year', 'month', 'day', 'relative_humility', 'windchill',
       'daytime', 'week7', 'weekend', 'code_change', 'rainY', 'otherY',
       'nothing', 'store_nbr', 'item_nbr', 'log1p_units'],
      dtype='object')

In [15]:
ls, ls1

(['depart', 'sunrise', 'sunset', 'snowfall', 'daytime'],
 ['depart', 'sunrise', 'sunset', 'snowfall', 'daytime'])

### 1. 변수변환: df2 (log1p_units)

In [19]:
all_var = 'log1p_units ~ scale(tmax) + scale(tmin) + scale(tavg) + scale(depart) + scale(dewpoint) + scale(wetbulb) + scale(heat) + scale(cool)\
                            + scale(sunrise) + scale(sunset) + scale(snowfall) + scale(preciptotal) + scale(stnpressure) + scale(sealevel) + scale(resultspeed)  \
                            + C(resultdir) + scale(avgspeed) + C(year) + C(month) + scale(relative_humility) + scale(windchill) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + C(daytime) + 0'

In [16]:
model2 = sm.OLS.from_formula('log1p_units ~ scale(tmax) + scale(tmin) + scale(tavg) + scale(dewpoint) + scale(wetbulb) + scale(heat) + scale(cool)\
                            + scale(preciptotal) + scale(stnpressure) + scale(sealevel) + scale(resultspeed)  \
                            + C(resultdir) + scale(avgspeed) + C(year) + C(month) + scale(relative_humility) + scale(windchill) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2)
result2 = model2.fit()
print(result2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.704
Model:                            OLS   Adj. R-squared:                  0.704
Method:                 Least Squares   F-statistic:                     7544.
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:39:48   Log-Likelihood:            -1.2232e+05
No. Observations:              561105   AIC:                         2.450e+05
Df Residuals:                  560927   BIC:                         2.470e+05
Df Model:                         177
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
C(resultdir)[1.0]            0.0188      0.005      3.461      0.001       0.008       0.029
C(resultdir)[2.0]            0.0149      0.006      2.582      0.010       0.004       0.026
C(resultdir)[3.0]            0.0130      0.006      2.029      0.043       0.000       0.026
C(resultdir)[4.0]            0.0172      0.006      2.944      0.003       0.006       0.029
C(resultdir)[5.0]            0.0156      0.006      2.715      0.007       0.004       0.027
C(resultdir)[6.0]            0.0189      0.007      2.900      0.004       0.006       0.032
C(resultdir)[7.0]            0.0145      0.006      2.319      0.020       0.002       0.027
C(resultdir)[8.0]            0.0126      0.006      2.037      0.042       0.000       0.025
C(resultdir)[9.0]            0.0144      0.006      2.558      0.011       0.003       0.025
C(resultdir)[10.0]           0.0174      0.006      3.013      0.003       0.006       0.029
C(resultdir)[11.0]           0.0152      0.007      2.209      0.027       0.002       0.029
C(resultdir)[12.0]           0.0143      0.006      2.497      0.013       0.003       0.026
C(resultdir)[13.0]           0.0147      0.005      2.770      0.006       0.004       0.025
C(resultdir)[14.0]           0.0138      0.005      2.587      0.010       0.003       0.024
C(resultdir)[15.0]           0.0161      0.005      3.130      0.002       0.006       0.026
C(resultdir)[16.0]           0.0150      0.005      3.034      0.002       0.005       0.025
C(resultdir)[17.0]           0.0145      0.005      2.900      0.004       0.005       0.024
C(resultdir)[18.0]           0.0160      0.005      3.221      0.001       0.006       0.026
C(resultdir)[19.0]           0.0151      0.005      3.005      0.003       0.005       0.025
C(resultdir)[20.0]           0.0151      0.005      2.983      0.003       0.005       0.025
C(resultdir)[21.0]           0.0164      0.005      3.277      0.001       0.007       0.026
C(resultdir)[22.0]           0.0175      0.005      3.433      0.001       0.007       0.027
C(resultdir)[23.0]           0.0168      0.005      3.240      0.001       0.007       0.027
C(resultdir)[24.0]           0.0165      0.005      3.079      0.002       0.006       0.027
C(resultdir)[25.0]           0.0167      0.005      3.177      0.001       0.006       0.027
C(resultdir)[26.0]           0.0141      0.006      2.533      0.011       0.003       0.025
C(resultdir)[27.0]           0.0158      0.006      2.745      0.006       0.005       0.027
C(resultdir)[28.0]           0.0164      0.006      2.886      0.004       0.005       0.028
C(resultdir)[29.0]           0.0149      0.005      2.755      0.006       0.004       0.026
C(resultdir)[30.0]           0.0177      0.006      3.143      0.002       0.007       0.029
C(resultdir)[31.0]           0.0173      0.006      3.106      0.002       0.006       0.028
C(resultdir)[32.0]           0.0170      0.006      2.882      0.004       0.005       0.029
C(resultdir)[33.0]           0.0184      0.005      3.371      0.001       0.008       0.029
C(resultdir)[34.0]           0.0165      0.006      2.956      0.003       0.006       0.027
C(resultdir)[35.0]           0.0172      0.005      3.221      0.001       0.007       0.028
C(resultdir)[36.0]           0.0147      0.005      2.697      0.007       0.004       0.025
C(year)[T.2013]             -0.0109      0.001    -10.755      0.000      -0.013      -0.009
C(year)[T.2014]             -0.0164      0.001    -15.220      0.000      -0.018      -0.014
C(month)[T.2]               -0.0060      0.002     -2.964      0.003      -0.010      -0.002
C(month)[T.3]               -0.0085      0.002     -4.231      0.000      -0.012      -0.005
C(month)[T.4]               -0.0094      0.002     -4.240      0.000      -0.014      -0.005
C(month)[T.5]               -0.0070      0.003     -2.654      0.008      -0.012      -0.002
C(month)[T.6]               -0.0029      0.003     -0.893      0.372      -0.009       0.003
C(month)[T.7]               -0.0047      0.004     -1.241      0.215      -0.012       0.003
C(month)[T.8]               -0.0035      0.003     -1.030      0.303      -0.010       0.003
C(month)[T.9]               -0.0067      0.003     -2.198      0.028      -0.013      -0.001
C(month)[T.10]              -0.0071      0.002     -3.010      0.003      -0.012      -0.002
C(month)[T.11]              -0.0065      0.002     -2.860      0.004      -0.011      -0.002
C(month)[T.12]              -0.0036      0.002     -1.631      0.103      -0.008       0.001
C(weekend)[T.1]              0.0108      0.001     11.769      0.000       0.009       0.013
C(rainY)[T.1]                0.0011      0.001      0.909      0.363      -0.001       0.003
C(store_nbr)[T.25]           0.0048      0.001      3.744      0.000       0.002       0.007
C(store_nbr)[T.32]          -0.0111      0.001     -8.749      0.000      -0.014      -0.009
C(store_nbr)[T.37]          -0.0100      0.001     -7.887      0.000      -0.013      -0.008
C(store_nbr)[T.40]          -0.0097      0.001     -7.641      0.000      -0.012      -0.007
C(item_nbr)[T.2]          1.046e-14      0.006   1.75e-12      1.000      -0.012       0.012
C(item_nbr)[T.3]          2.093e-15      0.006    3.5e-13      1.000      -0.012       0.012
C(item_nbr)[T.4]          8.163e-15      0.006   1.36e-12      1.000      -0.012       0.012
C(item_nbr)[T.5]             2.2696      0.006    379.120      0.000       2.258       2.281
C(item_nbr)[T.6]          6.223e-15      0.006   1.04e-12      1.000      -0.012       0.012
C(item_nbr)[T.7]          5.562e-15      0.006   9.29e-13      1.000      -0.012       0.012
C(item_nbr)[T.8]           4.19e-15      0.006      7e-13      1.000      -0.012       0.012
C(item_nbr)[T.9]             1.6134      0.006    269.509      0.000       1.602       1.625
C(item_nbr)[T.10]         5.821e-15      0.006   9.72e-13      1.000      -0.012       0.012
C(item_nbr)[T.11]        -4.155e-15      0.006  -6.94e-13      1.000      -0.012       0.012
C(item_nbr)[T.12]            0.0587      0.006      9.802      0.000       0.047       0.070
C(item_nbr)[T.13]         7.793e-15      0.006    1.3e-12      1.000      -0.012       0.012
C(item_nbr)[T.14]         4.259e-15      0.006   7.11e-13      1.000      -0.012       0.012
C(item_nbr)[T.15]            0.1383      0.006     23.098      0.000       0.127       0.150
C(item_nbr)[T.16]         2.913e-15      0.006   4.87e-13      1.000      -0.012       0.012
C(item_nbr)[T.17]            0.0752      0.006     12.556      0.000       0.063       0.087
C(item_nbr)[T.18]         2.748e-15      0.006   4.59e-13      1.000      -0.012       0.012
C(item_nbr)[T.19]            0.0636      0.006     10.628      0.000       0.052       0.075
C(item_nbr)[T.20]         1.061e-15      0.006   1.77e-13      1.000      -0.012       0.012
C(item_nbr)[T.21]         4.915e-15      0.006   8.21e-13      1.000      -0.012       0.012
C(item_nbr)[T.22]         5.044e-15      0.006   8.43e-13      1.000      -0.012       0.012
C(item_nbr)[T.23]         3.507e-15      0.006   5.86e-13      1.000      -0.012       0.012
C(item_nbr)[T.24]         4.266e-15      0.006   7.13e-13      1.000      -0.012       0.012
C(item_nbr)[T.25]         3.894e-15      0.006    6.5e-13      1.000      -0.012       0.012
C(item_nbr)[T.26]         8.055e-15      0.006   1.35e-12      1.000      -0.012       0.012
C(item_nbr)[T.27]         6.354e-15      0.006   1.06e-12      1.000      -0.012       0.012
C(item_nbr)[T.28]         2.972e-15      0.006   4.96e-13      1.000      -0.012       0.012
C(item_nbr)[T.29]         3.809e-15      0.006   6.36e-13      1.000      -0.012       0.012
C(item_nbr)[T.30]         5.532e-15      0.006   9.24e-13      1.000      -0.012       0.012
C(item_nbr)[T.31]         3.382e-15      0.006   5.65e-13      1.000      -0.012       0.012
C(item_nbr)[T.32]         3.992e-15      0.006   6.67e-13      1.000      -0.012       0.012
C(item_nbr)[T.33]         3.994e-15      0.006   6.67e-13      1.000      -0.012       0.012
C(item_nbr)[T.34]         3.382e-15      0.006   5.65e-13      1.000      -0.012       0.012
C(item_nbr)[T.35]         3.908e-15      0.006   6.53e-13      1.000      -0.012       0.012
C(item_nbr)[T.36]          3.14e-15      0.006   5.25e-13      1.000      -0.012       0.012
C(item_nbr)[T.37]         3.514e-15      0.006   5.87e-13      1.000      -0.012       0.012
C(item_nbr)[T.38]            0.1102      0.006     18.408      0.000       0.098       0.122
C(item_nbr)[T.39]         6.689e-15      0.006   1.12e-12      1.000      -0.012       0.012
C(item_nbr)[T.40]         7.614e-15      0.006   1.27e-12      1.000      -0.012       0.012
C(item_nbr)[T.41]         9.728e-15      0.006   1.62e-12      1.000      -0.012       0.012
C(item_nbr)[T.42]         6.562e-15      0.006    1.1e-12      1.000      -0.012       0.012
C(item_nbr)[T.43]        -2.021e-15      0.006  -3.38e-13      1.000      -0.012       0.012
C(item_nbr)[T.44]          5.77e-15      0.006   9.64e-13      1.000      -0.012       0.012
C(item_nbr)[T.45]            4.0980      0.006    684.556      0.000       4.086       4.110
C(item_nbr)[T.46]          2.68e-15      0.006   4.48e-13      1.000      -0.012       0.012
C(item_nbr)[T.47]         2.832e-15      0.006   4.73e-13      1.000      -0.012       0.012
C(item_nbr)[T.48]         3.486e-15      0.006   5.82e-13      1.000      -0.012       0.012
C(item_nbr)[T.49]            0.0232      0.006      3.880      0.000       0.011       0.035
C(item_nbr)[T.50]            0.0284      0.006      4.743      0.000       0.017       0.040
C(item_nbr)[T.51]            0.0627      0.006     10.466      0.000       0.051       0.074
C(item_nbr)[T.52]         5.994e-15      0.006      1e-12      1.000      -0.012       0.012
C(item_nbr)[T.53]            0.0613      0.006     10.247      0.000       0.050       0.073
C(item_nbr)[T.54]         7.442e-15      0.006   1.24e-12      1.000      -0.012       0.012
C(item_nbr)[T.55]            0.0869      0.006     14.515      0.000       0.075       0.099
C(item_nbr)[T.56]         2.644e-15      0.006   4.42e-13      1.000      -0.012       0.012
C(item_nbr)[T.57]         3.861e-15      0.006   6.45e-13      1.000      -0.012       0.012
C(item_nbr)[T.58]            0.0830      0.006     13.864      0.000       0.071       0.095
C(item_nbr)[T.59]         5.056e-15      0.006   8.45e-13      1.000      -0.012       0.012
C(item_nbr)[T.60]         9.064e-15      0.006   1.51e-12      1.000      -0.012       0.012
C(item_nbr)[T.61]            0.0745      0.006     12.441      0.000       0.063       0.086
C(item_nbr)[T.62]         3.904e-15      0.006   6.52e-13      1.000      -0.012       0.012
C(item_nbr)[T.63]         2.925e-15      0.006   4.89e-13      1.000      -0.012       0.012
C(item_nbr)[T.64]        -1.288e-16      0.006  -2.15e-14      1.000      -0.012       0.012
C(item_nbr)[T.65]         3.626e-15      0.006   6.06e-13      1.000      -0.012       0.012
C(item_nbr)[T.66]         1.926e-15      0.006   3.22e-13      1.000      -0.012       0.012
C(item_nbr)[T.67]         2.661e-15      0.006   4.44e-13      1.000      -0.012       0.012
C(item_nbr)[T.68]         9.635e-15      0.006   1.61e-12      1.000      -0.012       0.012
C(item_nbr)[T.69]         1.848e-15      0.006   3.09e-13      1.000      -0.012       0.012
C(item_nbr)[T.70]         2.402e-15      0.006   4.01e-13      1.000      -0.012       0.012
C(item_nbr)[T.71]         4.137e-15      0.006   6.91e-13      1.000      -0.012       0.012
C(item_nbr)[T.72]         7.866e-16      0.006   1.31e-13      1.000      -0.012       0.012
C(item_nbr)[T.73]         2.624e-15      0.006   4.38e-13      1.000      -0.012       0.012
C(item_nbr)[T.74]         4.095e-15      0.006   6.84e-13      1.000      -0.012       0.012
C(item_nbr)[T.75]         2.655e-15      0.006   4.44e-13      1.000      -0.012       0.012
C(item_nbr)[T.76]         5.079e-15      0.006   8.49e-13      1.000      -0.012       0.012
C(item_nbr)[T.77]         2.645e-15      0.006   4.42e-13      1.000      -0.012       0.012
C(item_nbr)[T.78]          2.48e-16      0.006   4.14e-14      1.000      -0.012       0.012
C(item_nbr)[T.79]         1.826e-15      0.006   3.05e-13      1.000      -0.012       0.012
C(item_nbr)[T.80]         2.489e-15      0.006   4.16e-13      1.000      -0.012       0.012
C(item_nbr)[T.81]            0.1852      0.006     30.941      0.000       0.173       0.197
C(item_nbr)[T.82]         3.419e-15      0.006   5.71e-13      1.000      -0.012       0.012
C(item_nbr)[T.83]          3.15e-15      0.006   5.26e-13      1.000      -0.012       0.012
C(item_nbr)[T.84]            0.0081      0.006      1.361      0.173      -0.004       0.020
C(item_nbr)[T.85]        -1.822e-15      0.006  -3.04e-13      1.000      -0.012       0.012
C(item_nbr)[T.86]            0.0264      0.006      4.418      0.000       0.015       0.038
C(item_nbr)[T.87]         6.885e-16      0.006   1.15e-13      1.000      -0.012       0.012
C(item_nbr)[T.88]         2.644e-15      0.006   4.42e-13      1.000      -0.012       0.012
C(item_nbr)[T.89]         2.195e-15      0.006   3.67e-13      1.000      -0.012       0.012
C(item_nbr)[T.90]         1.164e-14      0.006   1.94e-12      1.000      -0.012       0.012
C(item_nbr)[T.91]          2.56e-15      0.006   4.28e-13      1.000      -0.012       0.012
C(item_nbr)[T.92]         3.981e-15      0.006   6.65e-13      1.000      -0.012       0.012
C(item_nbr)[T.93]            0.2020      0.006     33.745      0.000       0.190       0.214
C(item_nbr)[T.94]         2.717e-15      0.006   4.54e-13      1.000      -0.012       0.012
C(item_nbr)[T.95]         3.237e-15      0.006   5.41e-13      1.000      -0.012       0.012
C(item_nbr)[T.96]         4.789e-15      0.006      8e-13      1.000      -0.012       0.012
C(item_nbr)[T.97]         4.479e-15      0.006   7.48e-13      1.000      -0.012       0.012
C(item_nbr)[T.98]         1.258e-15      0.006    2.1e-13      1.000      -0.012       0.012
C(item_nbr)[T.99]         1.904e-15      0.006   3.18e-13      1.000      -0.012       0.012
C(item_nbr)[T.100]        1.062e-15      0.006   1.77e-13      1.000      -0.012       0.012
C(item_nbr)[T.101]        3.568e-15      0.006   5.96e-13      1.000      -0.012       0.012
C(item_nbr)[T.102]        9.148e-16      0.006   1.53e-13      1.000      -0.012       0.012
C(item_nbr)[T.103]       -2.499e-15      0.006  -4.17e-13      1.000      -0.012       0.012
C(item_nbr)[T.104]           0.0364      0.006      6.080      0.000       0.025       0.048
C(item_nbr)[T.105]           0.0226      0.006      3.781      0.000       0.011       0.034
C(item_nbr)[T.106]           0.0082      0.006      1.376      0.169      -0.003       0.020
C(item_nbr)[T.107]        2.223e-15      0.006   3.71e-13      1.000      -0.012       0.012
C(item_nbr)[T.108]         1.21e-15      0.006   2.02e-13      1.000      -0.012       0.012
C(item_nbr)[T.109]        4.965e-15      0.006   8.29e-13      1.000      -0.012       0.012
C(item_nbr)[T.110]        5.461e-15      0.006   9.12e-13      1.000      -0.012       0.012
C(item_nbr)[T.111]        6.603e-15      0.006    1.1e-12      1.000      -0.012       0.012
scale(tmax)                 -0.0030      0.005     -0.583      0.560      -0.013       0.007
scale(tmin)                 -0.0035      0.005     -0.712      0.476      -0.013       0.006
scale(tavg)                 -0.0033      0.005     -0.670      0.503      -0.013       0.006
scale(dewpoint)              0.0023      0.003      0.725      0.469      -0.004       0.008
scale(wetbulb)              -0.0009      0.005     -0.168      0.867      -0.011       0.009
scale(heat)                  0.0019      0.004      0.490      0.624      -0.006       0.010
scale(cool)                  0.0006      0.001      0.727      0.467      -0.001       0.002
scale(preciptotal)           0.0001      0.000      0.318      0.751      -0.001       0.001
scale(stnpressure)          -0.0015      0.004     -0.424      0.672      -0.008       0.005
scale(sealevel)              0.0007      0.004      0.172      0.863      -0.007       0.008
scale(resultspeed)          -0.0001      0.001     -0.159      0.874      -0.002       0.002
scale(avgspeed)              0.0009      0.001      0.779      0.436      -0.001       0.003
scale(relative_humility)    -0.0004      0.002     -0.209      0.835      -0.005       0.004
scale(windchill)             0.0084      0.012      0.698      0.485      -0.015       0.032
==============================================================================
Omnibus:                   360498.285   Durbin-Watson:                   1.999
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         62342375.622
Skew:                           2.090   Prob(JB):                         0.00
Kurtosis:                      54.469   Cond. No.                     2.25e+15
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 8.24e-25. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

### 2. 변수변환 : df2 (log1p_units) + 아웃라이어 제거

In [17]:
# 아웃라이어 제거
# Cook's distance > 2 인 값 제거
influence = result2.get_influence()
cooks_d2, pvals = influence.cooks_distance
fox_cr = 4 / (len(df2) - 2)
idx_outlier = np.where(cooks_d2 > fox_cr)[0]
len(idx_outlier)

15186

In [18]:
idx = list(set(range(len(df2))).difference(idx_outlier))
df2_1 = df2.iloc[idx, :].reset_index(drop=True)
df2_1

,station_nbr,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,...,daytime,week7,weekend,code_change,rainY,otherY,nothing,store_nbr,item_nbr,log1p_units
0,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,1,0.0
1,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,2,0.0
2,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,3,0.0
3,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,4,0.0
4,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,6,0.0
5,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,7,0.0
6,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,8,0.0
7,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,10,0.0
8,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,11,0.0
9,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,12,0.0
10,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,13,0.0
11,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,14,0.0
12,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,15,0.0
13,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,16,0.0
14,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,18,0.0
15,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,19,0.0
16,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,20,0.0
17,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,21,0.0
18,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,22,0.0
19,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,23,0.0
20,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,24,0.0
21,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,25,0.0
22,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,26,0.0
23,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,27,0.0
24,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,28,0.0
25,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,29,0.0
26,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,30,0.0
27,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,31,0.0
28,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,32,0.0
29,13,2012-01-01,38.0,18.0,28.0,NaN,12.0,21.0,37.0,0.0,...,NaN,6,1,0,0,0,1,15,33,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545889,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,82,0.0
545890,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,83,0.0
545891,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,84,0.0
545892,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,85,0.0
545893,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,86,0.0
545894,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,87,0.0
545895,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,88,0.0
545896,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,89,0.0
545897,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,90,0.0
545898,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,91,0.0
545899,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,92,0.0
545900,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,93,0.0
545901,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,94,0.0
545902,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,95,0.0
545903,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,96,0.0
545904,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,97,0.0
545905,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,98,0.0
545906,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,99,0.0
545907,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,100,0.0
545908,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,101,0.0
545909,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,102,0.0
545910,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,103,0.0
545911,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,104,0.0
545912,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,105,0.0
545913,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,106,0.0
545914,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,107,0.0
545915,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,108,0.0
545916,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,109,0.0
545917,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,110,0.0
545918,13,2014-10-31,58.0,35.0,46.5,NaN,28.0,37.0,18.0,0.0,...,NaN,4,0,0,0,0,1,40,111,0.0

In [19]:
# OLS - df2_1
model2_1 = sm.OLS.from_formula('log1p_units ~ scale(tmax) + scale(tmin) + scale(tavg) + scale(dewpoint) + scale(wetbulb) + scale(heat) + scale(cool)\
                            + scale(preciptotal) + scale(stnpressure) + scale(sealevel) + scale(resultspeed)  \
                            + C(resultdir) + scale(avgspeed) + C(year) + C(month) + scale(relative_humility) + scale(windchill) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2_1)
result2_1 = model2_1.fit()
print(result2_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.989
Model:                            OLS   Adj. R-squared:                  0.989
Method:                 Least Squares   F-statistic:                 2.685e+05
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:45:34   Log-Likelihood:             9.9667e+05
No. Observations:              545919   AIC:                        -1.993e+06
Df Residuals:                  545741   BIC:                        -1.991e+06
Df Model:                         177
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
C(resultdir)[1.0]            0.0030      0.001      4.202      0.000       0.002       0.004
C(resultdir)[2.0]            0.0018      0.001      2.327      0.020       0.000       0.003
C(resultdir)[3.0]            0.0022      0.001      2.673      0.008       0.001       0.004
C(resultdir)[4.0]            0.0026      0.001      3.401      0.001       0.001       0.004
C(resultdir)[5.0]            0.0023      0.001      3.033      0.002       0.001       0.004
C(resultdir)[6.0]            0.0016      0.001      1.873      0.061   -7.44e-05       0.003
C(resultdir)[7.0]            0.0016      0.001      1.924      0.054   -2.89e-05       0.003
C(resultdir)[8.0]            0.0026      0.001      3.193      0.001       0.001       0.004
C(resultdir)[9.0]            0.0016      0.001      2.132      0.033       0.000       0.003
C(resultdir)[10.0]           0.0018      0.001      2.329      0.020       0.000       0.003
C(resultdir)[11.0]           0.0024      0.001      2.720      0.007       0.001       0.004
C(resultdir)[12.0]           0.0019      0.001      2.478      0.013       0.000       0.003
C(resultdir)[13.0]           0.0020      0.001      2.935      0.003       0.001       0.003
C(resultdir)[14.0]           0.0027      0.001      3.946      0.000       0.001       0.004
C(resultdir)[15.0]           0.0034      0.001      5.101      0.000       0.002       0.005
C(resultdir)[16.0]           0.0036      0.001      5.617      0.000       0.002       0.005
C(resultdir)[17.0]           0.0039      0.001      6.041      0.000       0.003       0.005
C(resultdir)[18.0]           0.0046      0.001      7.053      0.000       0.003       0.006
C(resultdir)[19.0]           0.0039      0.001      5.950      0.000       0.003       0.005
C(resultdir)[20.0]           0.0037      0.001      5.685      0.000       0.002       0.005
C(resultdir)[21.0]           0.0044      0.001      6.723      0.000       0.003       0.006
C(resultdir)[22.0]           0.0038      0.001      5.814      0.000       0.003       0.005
C(resultdir)[23.0]           0.0036      0.001      5.288      0.000       0.002       0.005
C(resultdir)[24.0]           0.0020      0.001      2.908      0.004       0.001       0.003
C(resultdir)[25.0]           0.0031      0.001      4.546      0.000       0.002       0.004
C(resultdir)[26.0]           0.0020      0.001      2.764      0.006       0.001       0.003
C(resultdir)[27.0]           0.0023      0.001      3.032      0.002       0.001       0.004
C(resultdir)[28.0]           0.0026      0.001      3.513      0.000       0.001       0.004
C(resultdir)[29.0]           0.0026      0.001      3.698      0.000       0.001       0.004
C(resultdir)[30.0]           0.0027      0.001      3.715      0.000       0.001       0.004
C(resultdir)[31.0]           0.0025      0.001      3.384      0.001       0.001       0.004
C(resultdir)[32.0]           0.0023      0.001      2.951      0.003       0.001       0.004
C(resultdir)[33.0]           0.0021      0.001      2.904      0.004       0.001       0.003
C(resultdir)[34.0]           0.0028      0.001      3.838      0.000       0.001       0.004
C(resultdir)[35.0]           0.0028      0.001      4.077      0.000       0.001       0.004
C(resultdir)[36.0]           0.0023      0.001      3.197      0.001       0.001       0.004
C(year)[T.2013]             -0.0009      0.000     -6.850      0.000      -0.001      -0.001
C(year)[T.2014]             -0.0028      0.000    -19.881      0.000      -0.003      -0.003
C(month)[T.2]               -0.0002      0.000     -0.667      0.505      -0.001       0.000
C(month)[T.3]               -0.0006      0.000     -2.205      0.027      -0.001   -6.49e-05
C(month)[T.4]               -0.0008      0.000     -2.805      0.005      -0.001      -0.000
C(month)[T.5]               -0.0004      0.000     -1.141      0.254      -0.001       0.000
C(month)[T.6]             6.596e-05      0.000      0.157      0.875      -0.001       0.001
C(month)[T.7]               -0.0002      0.000     -0.334      0.738      -0.001       0.001
C(month)[T.8]               -0.0005      0.000     -1.129      0.259      -0.001       0.000
C(month)[T.9]               -0.0009      0.000     -2.177      0.030      -0.002    -8.7e-05
C(month)[T.10]              -0.0011      0.000     -3.631      0.000      -0.002      -0.001
C(month)[T.11]              -0.0010      0.000     -3.278      0.001      -0.002      -0.000
C(month)[T.12]              -0.0009      0.000     -3.046      0.002      -0.001      -0.000
C(weekend)[T.1]              0.0017      0.000     14.382      0.000       0.001       0.002
C(rainY)[T.1]            -6.828e-05      0.000     -0.436      0.663      -0.000       0.000
C(store_nbr)[T.25]          -0.0006      0.000     -3.375      0.001      -0.001      -0.000
C(store_nbr)[T.32]          -0.0033      0.000    -19.612      0.000      -0.004      -0.003
C(store_nbr)[T.37]          -0.0036      0.000    -21.351      0.000      -0.004      -0.003
C(store_nbr)[T.40]          -0.0022      0.000    -13.212      0.000      -0.003      -0.002
C(item_nbr)[T.2]         -4.911e-16      0.001  -6.33e-13      1.000      -0.002       0.002
C(item_nbr)[T.3]         -1.271e-15      0.001  -1.64e-12      1.000      -0.002       0.002
C(item_nbr)[T.4]          6.936e-16      0.001   8.94e-13      1.000      -0.002       0.002
C(item_nbr)[T.5]             2.5900      0.003    854.073      0.000       2.584       2.596
C(item_nbr)[T.6]         -3.668e-16      0.001  -4.73e-13      1.000      -0.002       0.002
C(item_nbr)[T.7]          5.031e-16      0.001   6.49e-13      1.000      -0.002       0.002
C(item_nbr)[T.8]         -1.209e-15      0.001  -1.56e-12      1.000      -0.002       0.002
C(item_nbr)[T.9]             1.9343      0.008    257.054      0.000       1.920       1.949
C(item_nbr)[T.10]         -3.81e-15      0.001  -4.91e-12      1.000      -0.002       0.002
C(item_nbr)[T.11]         5.837e-16      0.001   7.53e-13      1.000      -0.002       0.002
C(item_nbr)[T.12]            0.0133      0.001     16.926      0.000       0.012       0.015
C(item_nbr)[T.13]         9.403e-15      0.001   1.21e-11      1.000      -0.002       0.002
C(item_nbr)[T.14]        -3.629e-16      0.001  -4.68e-13      1.000      -0.002       0.002
C(item_nbr)[T.15]            0.0177      0.001     22.405      0.000       0.016       0.019
C(item_nbr)[T.16]        -9.726e-16      0.001  -1.25e-12      1.000      -0.002       0.002
C(item_nbr)[T.17]            0.0151      0.001     19.168      0.000       0.014       0.017
C(item_nbr)[T.18]        -2.891e-17      0.001  -3.73e-14      1.000      -0.002       0.002
C(item_nbr)[T.19]            0.0129      0.001     16.355      0.000       0.011       0.014
C(item_nbr)[T.20]        -3.405e-16      0.001  -4.39e-13      1.000      -0.002       0.002
C(item_nbr)[T.21]        -3.495e-16      0.001  -4.51e-13      1.000      -0.002       0.002
C(item_nbr)[T.22]         5.256e-17      0.001   6.78e-14      1.000      -0.002       0.002
C(item_nbr)[T.23]        -2.998e-16      0.001  -3.87e-13      1.000      -0.002       0.002
C(item_nbr)[T.24]        -7.984e-17      0.001  -1.03e-13      1.000      -0.002       0.002
C(item_nbr)[T.25]        -1.685e-16      0.001  -2.17e-13      1.000      -0.002       0.002
C(item_nbr)[T.26]        -3.143e-17      0.001  -4.05e-14      1.000      -0.002       0.002
C(item_nbr)[T.27]        -2.761e-16      0.001  -3.56e-13      1.000      -0.002       0.002
C(item_nbr)[T.28]        -1.507e-16      0.001  -1.94e-13      1.000      -0.002       0.002
C(item_nbr)[T.29]        -2.781e-16      0.001  -3.59e-13      1.000      -0.002       0.002
C(item_nbr)[T.30]        -1.402e-16      0.001  -1.81e-13      1.000      -0.002       0.002
C(item_nbr)[T.31]          6.02e-17      0.001   7.76e-14      1.000      -0.002       0.002
C(item_nbr)[T.32]        -1.034e-16      0.001  -1.33e-13      1.000      -0.002       0.002
C(item_nbr)[T.33]        -3.746e-16      0.001  -4.83e-13      1.000      -0.002       0.002
C(item_nbr)[T.34]        -4.018e-16      0.001  -5.18e-13      1.000      -0.002       0.002
C(item_nbr)[T.35]        -1.378e-16      0.001  -1.78e-13      1.000      -0.002       0.002
C(item_nbr)[T.36]         1.501e-16      0.001   1.94e-13      1.000      -0.002       0.002
C(item_nbr)[T.37]        -5.774e-16      0.001  -7.45e-13      1.000      -0.002       0.002
C(item_nbr)[T.38]            0.0010      0.001      1.256      0.209      -0.001       0.003
C(item_nbr)[T.39]         7.175e-17      0.001   9.25e-14      1.000      -0.002       0.002
C(item_nbr)[T.40]        -4.241e-16      0.001  -5.47e-13      1.000      -0.002       0.002
C(item_nbr)[T.41]        -2.972e-16      0.001  -3.83e-13      1.000      -0.002       0.002
C(item_nbr)[T.42]        -2.419e-16      0.001  -3.12e-13      1.000      -0.002       0.002
C(item_nbr)[T.43]        -4.335e-17      0.001  -5.59e-14      1.000      -0.002       0.002
C(item_nbr)[T.44]         3.792e-16      0.001   4.89e-13      1.000      -0.002       0.002
C(item_nbr)[T.45]            4.1101      0.001   5061.531      0.000       4.109       4.112
C(item_nbr)[T.46]        -3.486e-17      0.001  -4.49e-14      1.000      -0.002       0.002
C(item_nbr)[T.47]         1.103e-16      0.001   1.42e-13      1.000      -0.002       0.002
C(item_nbr)[T.48]         -2.49e-16      0.001  -3.21e-13      1.000      -0.002       0.002
C(item_nbr)[T.49]            0.0003      0.001      0.425      0.671      -0.001       0.002
C(item_nbr)[T.50]            0.0013      0.001      1.659      0.097      -0.000       0.003
C(item_nbr)[T.51]            0.0068      0.001      8.596      0.000       0.005       0.008
C(item_nbr)[T.52]         3.282e-16      0.001   4.23e-13      1.000      -0.002       0.002
C(item_nbr)[T.53]            0.0092      0.001     11.662      0.000       0.008       0.011
C(item_nbr)[T.54]         2.227e-16      0.001   2.87e-13      1.000      -0.002       0.002
C(item_nbr)[T.55]            0.0094      0.001     11.867      0.000       0.008       0.011
C(item_nbr)[T.56]         2.541e-16      0.001   3.28e-13      1.000      -0.002       0.002
C(item_nbr)[T.57]         3.049e-16      0.001   3.93e-13      1.000      -0.002       0.002
C(item_nbr)[T.58]            0.0085      0.001     10.824      0.000       0.007       0.010
C(item_nbr)[T.59]        -4.263e-17      0.001   -5.5e-14      1.000      -0.002       0.002
C(item_nbr)[T.60]         7.345e-17      0.001   9.47e-14      1.000      -0.002       0.002
C(item_nbr)[T.61]            0.0087      0.001     11.041      0.000       0.007       0.010
C(item_nbr)[T.62]         9.264e-17      0.001   1.19e-13      1.000      -0.002       0.002
C(item_nbr)[T.63]         1.813e-16      0.001   2.34e-13      1.000      -0.002       0.002
C(item_nbr)[T.64]         5.056e-16      0.001   6.52e-13      1.000      -0.002       0.002
C(item_nbr)[T.65]         3.986e-16      0.001   5.14e-13      1.000      -0.002       0.002
C(item_nbr)[T.66]         1.117e-16      0.001   1.44e-13      1.000      -0.002       0.002
C(item_nbr)[T.67]         1.005e-16      0.001    1.3e-13      1.000      -0.002       0.002
C(item_nbr)[T.68]         5.561e-17      0.001   7.17e-14      1.000      -0.002       0.002
C(item_nbr)[T.69]        -3.513e-17      0.001  -4.53e-14      1.000      -0.002       0.002
C(item_nbr)[T.70]         1.811e-16      0.001   2.33e-13      1.000      -0.002       0.002
C(item_nbr)[T.71]         2.143e-16      0.001   2.76e-13      1.000      -0.002       0.002
C(item_nbr)[T.72]         2.446e-17      0.001   3.15e-14      1.000      -0.002       0.002
C(item_nbr)[T.73]        -1.208e-16      0.001  -1.56e-13      1.000      -0.002       0.002
C(item_nbr)[T.74]         6.498e-17      0.001   8.38e-14      1.000      -0.002       0.002
C(item_nbr)[T.75]         1.179e-16      0.001   1.52e-13      1.000      -0.002       0.002
C(item_nbr)[T.76]         3.369e-16      0.001   4.34e-13      1.000      -0.002       0.002
C(item_nbr)[T.77]         2.184e-16      0.001   2.82e-13      1.000      -0.002       0.002
C(item_nbr)[T.78]         1.219e-17      0.001   1.57e-14      1.000      -0.002       0.002
C(item_nbr)[T.79]        -3.196e-16      0.001  -4.12e-13      1.000      -0.002       0.002
C(item_nbr)[T.80]         1.477e-16      0.001    1.9e-13      1.000      -0.002       0.002
C(item_nbr)[T.81]            0.0003      0.001      0.440      0.660      -0.001       0.002
C(item_nbr)[T.82]         7.227e-17      0.001   9.32e-14      1.000      -0.002       0.002
C(item_nbr)[T.83]         1.511e-17      0.001   1.95e-14      1.000      -0.002       0.002
C(item_nbr)[T.84]         2.477e-05      0.001      0.032      0.975      -0.001       0.002
C(item_nbr)[T.85]         -3.22e-18      0.001  -4.15e-15      1.000      -0.002       0.002
C(item_nbr)[T.86]            0.0007      0.001      0.925      0.355      -0.001       0.002
C(item_nbr)[T.87]         2.825e-16      0.001   3.64e-13      1.000      -0.002       0.002
C(item_nbr)[T.88]          1.54e-16      0.001   1.99e-13      1.000      -0.002       0.002
C(item_nbr)[T.89]         2.587e-16      0.001   3.34e-13      1.000      -0.002       0.002
C(item_nbr)[T.90]         7.083e-17      0.001   9.13e-14      1.000      -0.002       0.002
C(item_nbr)[T.91]         1.461e-16      0.001   1.88e-13      1.000      -0.002       0.002
C(item_nbr)[T.92]         1.311e-16      0.001   1.69e-13      1.000      -0.002       0.002
C(item_nbr)[T.93]            0.0149      0.001     18.637      0.000       0.013       0.016
C(item_nbr)[T.94]          3.27e-16      0.001   4.22e-13      1.000      -0.002       0.002
C(item_nbr)[T.95]         2.684e-16      0.001   3.46e-13      1.000      -0.002       0.002
C(item_nbr)[T.96]         2.912e-16      0.001   3.76e-13      1.000      -0.002       0.002
C(item_nbr)[T.97]           3.5e-16      0.001   4.51e-13      1.000      -0.002       0.002
C(item_nbr)[T.98]         9.639e-17      0.001   1.24e-13      1.000      -0.002       0.002
C(item_nbr)[T.99]         5.251e-16      0.001   6.77e-13      1.000      -0.002       0.002
C(item_nbr)[T.100]       -8.181e-17      0.001  -1.05e-13      1.000      -0.002       0.002
C(item_nbr)[T.101]       -5.192e-17      0.001  -6.69e-14      1.000      -0.002       0.002
C(item_nbr)[T.102]        1.526e-16      0.001   1.97e-13      1.000      -0.002       0.002
C(item_nbr)[T.103]        9.464e-16      0.001   1.22e-12      1.000      -0.002       0.002
C(item_nbr)[T.104]       -6.382e-05      0.001     -0.082      0.935      -0.002       0.001
C(item_nbr)[T.105]       -3.896e-05      0.001     -0.050      0.960      -0.002       0.001
C(item_nbr)[T.106]       -5.793e-06      0.001     -0.007      0.994      -0.002       0.002
C(item_nbr)[T.107]        5.159e-16      0.001   6.65e-13      1.000      -0.002       0.002
C(item_nbr)[T.108]       -3.276e-16      0.001  -4.22e-13      1.000      -0.002       0.002
C(item_nbr)[T.109]       -2.233e-16      0.001  -2.88e-13      1.000      -0.002       0.002
C(item_nbr)[T.110]        -1.54e-16      0.001  -1.99e-13      1.000      -0.002       0.002
C(item_nbr)[T.111]       -1.815e-16      0.001  -2.34e-13      1.000      -0.002       0.002
scale(tmax)                 -0.0010      0.001     -1.392      0.164      -0.002       0.000
scale(tmin)                 -0.0005      0.001     -0.767      0.443      -0.002       0.001
scale(tavg)                 -0.0008      0.001     -1.160      0.246      -0.002       0.001
scale(dewpoint)              0.0013      0.000      3.059      0.002       0.000       0.002
scale(wetbulb)              -0.0001      0.001     -0.190      0.849      -0.001       0.001
scale(heat)              -1.745e-05      0.001     -0.034      0.973      -0.001       0.001
scale(cool)                  0.0002      0.000      1.491      0.136   -4.73e-05       0.000
scale(preciptotal)        3.057e-05   6.08e-05      0.502      0.615   -8.87e-05       0.000
scale(stnpressure)           0.0006      0.000      1.253      0.210      -0.000       0.001
scale(sealevel)             -0.0007      0.001     -1.369      0.171      -0.002       0.000
scale(resultspeed)        7.621e-05      0.000      0.696      0.486      -0.000       0.000
scale(avgspeed)             -0.0003      0.000     -2.038      0.042      -0.001   -1.17e-05
scale(relative_humility)    -0.0010      0.000     -3.744      0.000      -0.002      -0.000
scale(windchill)          9.405e-06      0.002      0.006      0.995      -0.003       0.003
==============================================================================
Omnibus:                   765338.339   Durbin-Watson:                   2.007
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        999234216.952
Skew:                           7.685   Prob(JB):                         0.00
Kurtosis:                     212.028   Cond. No.                     2.25e+15
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 8.02e-25. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

### 3. VIF 확인

In [22]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
# all_cols = ['tmax','tmin','tavg','dewpoint','wetbulb','heat','cool','preciptotal',\
#         'stnpressure','sealevel','resultspeed','avgspeed','relative_humility',\
#         'windchill', 'depart', 'sunrise', 'sunset', 'snowfall' ]
cols = ['tmax','tmin','tavg','dewpoint','wetbulb','heat','cool','preciptotal',\
        'stnpressure','sealevel','resultspeed','avgspeed','relative_humility',\
        'windchill' ]

y = df2_1.loc[:,cols]
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(y.values, i) for i in range(y.shape[1])]
vif["features"] = y.columns
vif = vif.sort_values("VIF Factor", ascending=False).reset_index(drop=True)
vif

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\stats\outliers_influence.py:167: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)

      VIF Factor           features
0            inf               tmax
1            inf               tmin
2            inf               tavg
3   1.506697e+06        stnpressure
4   1.461076e+06           sealevel
5   4.885527e+03          windchill
6   1.426444e+03            wetbulb
7   2.575549e+02           dewpoint
8   1.439019e+02  relative_humility
9   1.365119e+02               heat
10  5.476200e+01           avgspeed
11  9.672304e+00        resultspeed
12  3.922803e+00               cool
13  1.307407e+00        preciptotal

### 4. VIF 근거, tmax, tmin, tavg, stnpre, sea, wind, wetbult, dewpoint, relative, heat 빼고 다시 Model 돌림.

In [23]:
# OLS - df2_1
model2_1 = sm.OLS.from_formula('log1p_units ~ scale(dewpoint) + scale(cool)\
                            + scale(preciptotal) + scale(resultspeed)  \
                            + C(resultdir) + scale(avgspeed) + C(year) + C(month) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2_1)
result2_1 = model2_1.fit()
print(result2_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.989
Model:                            OLS   Adj. R-squared:                  0.989
Method:                 Least Squares   F-statistic:                 2.812e+05
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        12:06:37   Log-Likelihood:             9.9666e+05
No. Observations:              545919   AIC:                        -1.993e+06
Df Residuals:                  545749   BIC:                        -1.991e+06
Df Model:                         169
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
C(resultdir)[1.0]      0.0034      0.001      4.962      0.000       0.002       0.005
C(resultdir)[2.0]      0.0023      0.001      3.154      0.002       0.001       0.004
C(resultdir)[3.0]      0.0027      0.001      3.262      0.001       0.001       0.004
C(resultdir)[4.0]      0.0030      0.001      3.960      0.000       0.001       0.004
C(resultdir)[5.0]      0.0027      0.001      3.698      0.000       0.001       0.004
C(resultdir)[6.0]      0.0021      0.001      2.549      0.011       0.000       0.004
C(resultdir)[7.0]      0.0020      0.001      2.505      0.012       0.000       0.004
C(resultdir)[8.0]      0.0030      0.001      3.783      0.000       0.001       0.005
C(resultdir)[9.0]      0.0021      0.001      2.913      0.004       0.001       0.004
C(resultdir)[10.0]     0.0022      0.001      2.983      0.003       0.001       0.004
C(resultdir)[11.0]     0.0028      0.001      3.084      0.002       0.001       0.005
C(resultdir)[12.0]     0.0023      0.001      3.137      0.002       0.001       0.004
C(resultdir)[13.0]     0.0025      0.001      3.627      0.000       0.001       0.004
C(resultdir)[14.0]     0.0032      0.001      4.624      0.000       0.002       0.005
C(resultdir)[15.0]     0.0038      0.001      5.722      0.000       0.002       0.005
C(resultdir)[16.0]     0.0040      0.001      6.274      0.000       0.003       0.005
C(resultdir)[17.0]     0.0043      0.001      6.688      0.000       0.003       0.006
C(resultdir)[18.0]     0.0049      0.001      7.652      0.000       0.004       0.006
C(resultdir)[19.0]     0.0043      0.001      6.549      0.000       0.003       0.006
C(resultdir)[20.0]     0.0041      0.001      6.251      0.000       0.003       0.005
C(resultdir)[21.0]     0.0046      0.001      7.112      0.000       0.003       0.006
C(resultdir)[22.0]     0.0042      0.001      6.386      0.000       0.003       0.005
C(resultdir)[23.0]     0.0039      0.001      5.770      0.000       0.003       0.005
C(resultdir)[24.0]     0.0024      0.001      3.455      0.001       0.001       0.004
C(resultdir)[25.0]     0.0034      0.001      5.004      0.000       0.002       0.005
C(resultdir)[26.0]     0.0023      0.001      3.256      0.001       0.001       0.004
C(resultdir)[27.0]     0.0027      0.001      3.604      0.000       0.001       0.004
C(resultdir)[28.0]     0.0029      0.001      4.014      0.000       0.002       0.004
C(resultdir)[29.0]     0.0031      0.001      4.447      0.000       0.002       0.004
C(resultdir)[30.0]     0.0032      0.001      4.512      0.000       0.002       0.005
C(resultdir)[31.0]     0.0030      0.001      4.146      0.000       0.002       0.004
C(resultdir)[32.0]     0.0028      0.001      3.758      0.000       0.001       0.004
C(resultdir)[33.0]     0.0025      0.001      3.595      0.000       0.001       0.004
C(resultdir)[34.0]     0.0032      0.001      4.517      0.000       0.002       0.005
C(resultdir)[35.0]     0.0032      0.001      4.605      0.000       0.002       0.005
C(resultdir)[36.0]     0.0027      0.001      3.935      0.000       0.001       0.004
C(year)[T.2013]       -0.0009      0.000     -6.668      0.000      -0.001      -0.001
C(year)[T.2014]       -0.0028      0.000    -20.066      0.000      -0.003      -0.002
C(month)[T.2]         -0.0003      0.000     -1.049      0.294      -0.001       0.000
C(month)[T.3]         -0.0008      0.000     -3.172      0.002      -0.001      -0.000
C(month)[T.4]         -0.0011      0.000     -4.089      0.000      -0.002      -0.001
C(month)[T.5]         -0.0009      0.000     -3.054      0.002      -0.002      -0.000
C(month)[T.6]         -0.0007      0.000     -1.981      0.048      -0.001   -7.65e-06
C(month)[T.7]         -0.0009      0.000     -2.142      0.032      -0.002   -7.76e-05
C(month)[T.8]         -0.0012      0.000     -3.029      0.002      -0.002      -0.000
C(month)[T.9]         -0.0015      0.000     -4.285      0.000      -0.002      -0.001
C(month)[T.10]        -0.0015      0.000     -5.162      0.000      -0.002      -0.001
C(month)[T.11]        -0.0011      0.000     -3.738      0.000      -0.002      -0.001
C(month)[T.12]        -0.0009      0.000     -3.140      0.002      -0.001      -0.000
C(weekend)[T.1]        0.0017      0.000     14.521      0.000       0.002       0.002
C(rainY)[T.1]         -0.0001      0.000     -1.012      0.311      -0.000       0.000
C(store_nbr)[T.25]    -0.0006      0.000     -3.375      0.001      -0.001      -0.000
C(store_nbr)[T.32]    -0.0033      0.000    -19.612      0.000      -0.004      -0.003
C(store_nbr)[T.37]    -0.0036      0.000    -21.351      0.000      -0.004      -0.003
C(store_nbr)[T.40]    -0.0022      0.000    -13.212      0.000      -0.003      -0.002
C(item_nbr)[T.2]   -2.782e-15      0.001  -3.59e-12      1.000      -0.002       0.002
C(item_nbr)[T.3]   -2.646e-15      0.001  -3.41e-12      1.000      -0.002       0.002
C(item_nbr)[T.4]    8.263e-17      0.001   1.07e-13      1.000      -0.002       0.002
C(item_nbr)[T.5]       2.5900      0.003    854.065      0.000       2.584       2.596
C(item_nbr)[T.6]   -5.581e-16      0.001   -7.2e-13      1.000      -0.002       0.002
C(item_nbr)[T.7]   -4.525e-16      0.001  -5.83e-13      1.000      -0.002       0.002
C(item_nbr)[T.8]   -6.853e-16      0.001  -8.84e-13      1.000      -0.002       0.002
C(item_nbr)[T.9]       1.9343      0.008    257.046      0.000       1.920       1.949
C(item_nbr)[T.10]  -7.141e-16      0.001  -9.21e-13      1.000      -0.002       0.002
C(item_nbr)[T.11]  -7.588e-16      0.001  -9.78e-13      1.000      -0.002       0.002
C(item_nbr)[T.12]      0.0133      0.001     16.926      0.000       0.012       0.015
C(item_nbr)[T.13]  -7.905e-16      0.001  -1.02e-12      1.000      -0.002       0.002
C(item_nbr)[T.14]  -7.978e-16      0.001  -1.03e-12      1.000      -0.002       0.002
C(item_nbr)[T.15]      0.0177      0.001     22.405      0.000       0.016       0.019
C(item_nbr)[T.16]  -8.178e-16      0.001  -1.05e-12      1.000      -0.002       0.002
C(item_nbr)[T.17]      0.0151      0.001     19.169      0.000       0.014       0.017
C(item_nbr)[T.18]  -6.845e-16      0.001  -8.83e-13      1.000      -0.002       0.002
C(item_nbr)[T.19]      0.0129      0.001     16.355      0.000       0.011       0.014
C(item_nbr)[T.20]  -7.867e-16      0.001  -1.01e-12      1.000      -0.002       0.002
C(item_nbr)[T.21]  -7.191e-16      0.001  -9.27e-13      1.000      -0.002       0.002
C(item_nbr)[T.22]  -8.057e-16      0.001  -1.04e-12      1.000      -0.002       0.002
C(item_nbr)[T.23]    -5.8e-16      0.001  -7.48e-13      1.000      -0.002       0.002
C(item_nbr)[T.24]  -6.734e-16      0.001  -8.68e-13      1.000      -0.002       0.002
C(item_nbr)[T.25]  -7.732e-16      0.001  -9.97e-13      1.000      -0.002       0.002
C(item_nbr)[T.26]  -4.736e-16      0.001  -6.11e-13      1.000      -0.002       0.002
C(item_nbr)[T.27]  -7.555e-16      0.001  -9.74e-13      1.000      -0.002       0.002
C(item_nbr)[T.28]  -5.246e-16      0.001  -6.76e-13      1.000      -0.002       0.002
C(item_nbr)[T.29]  -5.197e-16      0.001   -6.7e-13      1.000      -0.002       0.002
C(item_nbr)[T.30]  -5.677e-16      0.001  -7.32e-13      1.000      -0.002       0.002
C(item_nbr)[T.31]  -7.245e-16      0.001  -9.34e-13      1.000      -0.002       0.002
C(item_nbr)[T.32]  -5.962e-16      0.001  -7.69e-13      1.000      -0.002       0.002
C(item_nbr)[T.33]  -6.872e-16      0.001  -8.86e-13      1.000      -0.002       0.002
C(item_nbr)[T.34]  -6.748e-16      0.001   -8.7e-13      1.000      -0.002       0.002
C(item_nbr)[T.35]  -6.166e-16      0.001  -7.95e-13      1.000      -0.002       0.002
C(item_nbr)[T.36]  -5.784e-16      0.001  -7.46e-13      1.000      -0.002       0.002
C(item_nbr)[T.37]  -6.061e-16      0.001  -7.81e-13      1.000      -0.002       0.002
C(item_nbr)[T.38]      0.0010      0.001      1.257      0.209      -0.001       0.003
C(item_nbr)[T.39]  -4.766e-16      0.001  -6.15e-13      1.000      -0.002       0.002
C(item_nbr)[T.40]  -8.106e-16      0.001  -1.05e-12      1.000      -0.002       0.002
C(item_nbr)[T.41]  -5.857e-16      0.001  -7.55e-13      1.000      -0.002       0.002
C(item_nbr)[T.42]  -4.922e-16      0.001  -6.35e-13      1.000      -0.002       0.002
C(item_nbr)[T.43]  -4.117e-16      0.001  -5.31e-13      1.000      -0.002       0.002
C(item_nbr)[T.44]   1.557e-16      0.001   2.01e-13      1.000      -0.002       0.002
C(item_nbr)[T.45]      4.1101      0.001   5061.485      0.000       4.109       4.112
C(item_nbr)[T.46]  -3.205e-16      0.001  -4.13e-13      1.000      -0.002       0.002
C(item_nbr)[T.47]  -3.819e-16      0.001  -4.92e-13      1.000      -0.002       0.002
C(item_nbr)[T.48]  -2.914e-16      0.001  -3.76e-13      1.000      -0.002       0.002
C(item_nbr)[T.49]      0.0003      0.001      0.426      0.670      -0.001       0.002
C(item_nbr)[T.50]      0.0013      0.001      1.660      0.097      -0.000       0.003
C(item_nbr)[T.51]      0.0068      0.001      8.595      0.000       0.005       0.008
C(item_nbr)[T.52]  -1.307e-16      0.001  -1.69e-13      1.000      -0.002       0.002
C(item_nbr)[T.53]      0.0092      0.001     11.662      0.000       0.008       0.011
C(item_nbr)[T.54]  -4.938e-17      0.001  -6.37e-14      1.000      -0.002       0.002
C(item_nbr)[T.55]      0.0094      0.001     11.866      0.000       0.008       0.011
C(item_nbr)[T.56]  -2.508e-16      0.001  -3.23e-13      1.000      -0.002       0.002
C(item_nbr)[T.57]  -3.879e-16      0.001     -5e-13      1.000      -0.002       0.002
C(item_nbr)[T.58]      0.0085      0.001     10.824      0.000       0.007       0.010
C(item_nbr)[T.59]  -2.925e-16      0.001  -3.77e-13      1.000      -0.002       0.002
C(item_nbr)[T.60]  -2.739e-16      0.001  -3.53e-13      1.000      -0.002       0.002
C(item_nbr)[T.61]      0.0087      0.001     11.042      0.000       0.007       0.010
C(item_nbr)[T.62]  -2.284e-16      0.001  -2.94e-13      1.000      -0.002       0.002
C(item_nbr)[T.63]  -2.941e-16      0.001  -3.79e-13      1.000      -0.002       0.002
C(item_nbr)[T.64]  -2.848e-16      0.001  -3.67e-13      1.000      -0.002       0.002
C(item_nbr)[T.65]  -1.765e-16      0.001  -2.28e-13      1.000      -0.002       0.002
C(item_nbr)[T.66]  -1.935e-16      0.001   -2.5e-13      1.000      -0.002       0.002
C(item_nbr)[T.67]  -2.091e-16      0.001   -2.7e-13      1.000      -0.002       0.002
C(item_nbr)[T.68]  -1.512e-16      0.001  -1.95e-13      1.000      -0.002       0.002
C(item_nbr)[T.69]  -3.198e-16      0.001  -4.12e-13      1.000      -0.002       0.002
C(item_nbr)[T.70]  -2.082e-16      0.001  -2.68e-13      1.000      -0.002       0.002
C(item_nbr)[T.71]   -2.94e-16      0.001  -3.79e-13      1.000      -0.002       0.002
C(item_nbr)[T.72]  -2.547e-16      0.001  -3.28e-13      1.000      -0.002       0.002
C(item_nbr)[T.73]  -1.945e-16      0.001  -2.51e-13      1.000      -0.002       0.002
C(item_nbr)[T.74]  -2.502e-16      0.001  -3.23e-13      1.000      -0.002       0.002
C(item_nbr)[T.75]  -2.915e-16      0.001  -3.76e-13      1.000      -0.002       0.002
C(item_nbr)[T.76]  -1.672e-16      0.001  -2.16e-13      1.000      -0.002       0.002
C(item_nbr)[T.77]  -3.711e-16      0.001  -4.79e-13      1.000      -0.002       0.002
C(item_nbr)[T.78]  -2.487e-16      0.001  -3.21e-13      1.000      -0.002       0.002
C(item_nbr)[T.79]  -2.861e-16      0.001  -3.69e-13      1.000      -0.002       0.002
C(item_nbr)[T.80]  -1.723e-16      0.001  -2.22e-13      1.000      -0.002       0.002
C(item_nbr)[T.81]      0.0003      0.001      0.440      0.660      -0.001       0.002
C(item_nbr)[T.82]  -1.879e-16      0.001  -2.42e-13      1.000      -0.002       0.002
C(item_nbr)[T.83]  -3.734e-16      0.001  -4.82e-13      1.000      -0.002       0.002
C(item_nbr)[T.84]   2.416e-05      0.001      0.031      0.975      -0.001       0.002
C(item_nbr)[T.85]  -1.991e-16      0.001  -2.57e-13      1.000      -0.002       0.002
C(item_nbr)[T.86]      0.0007      0.001      0.924      0.355      -0.001       0.002
C(item_nbr)[T.87]  -2.503e-16      0.001  -3.23e-13      1.000      -0.002       0.002
C(item_nbr)[T.88]  -1.788e-16      0.001  -2.31e-13      1.000      -0.002       0.002
C(item_nbr)[T.89]  -2.895e-16      0.001  -3.73e-13      1.000      -0.002       0.002
C(item_nbr)[T.90]  -2.477e-16      0.001  -3.19e-13      1.000      -0.002       0.002
C(item_nbr)[T.91]  -3.108e-16      0.001  -4.01e-13      1.000      -0.002       0.002
C(item_nbr)[T.92]  -3.226e-16      0.001  -4.16e-13      1.000      -0.002       0.002
C(item_nbr)[T.93]      0.0149      0.001     18.635      0.000       0.013       0.016
C(item_nbr)[T.94]  -1.138e-16      0.001  -1.47e-13      1.000      -0.002       0.002
C(item_nbr)[T.95]  -1.662e-16      0.001  -2.14e-13      1.000      -0.002       0.002
C(item_nbr)[T.96]  -5.626e-16      0.001  -7.25e-13      1.000      -0.002       0.002
C(item_nbr)[T.97]  -2.832e-16      0.001  -3.65e-13      1.000      -0.002       0.002
C(item_nbr)[T.98]  -8.711e-17      0.001  -1.12e-13      1.000      -0.002       0.002
C(item_nbr)[T.99]  -4.194e-16      0.001  -5.41e-13      1.000      -0.002       0.002
C(item_nbr)[T.100] -3.514e-16      0.001  -4.53e-13      1.000      -0.002       0.002
C(item_nbr)[T.101] -4.278e-16      0.001  -5.52e-13      1.000      -0.002       0.002
C(item_nbr)[T.102] -6.288e-18      0.001  -8.11e-15      1.000      -0.002       0.002
C(item_nbr)[T.103]  1.923e-16      0.001   2.48e-13      1.000      -0.002       0.002
C(item_nbr)[T.104] -6.453e-05      0.001     -0.083      0.934      -0.002       0.001
C(item_nbr)[T.105] -3.987e-05      0.001     -0.051      0.959      -0.002       0.001
C(item_nbr)[T.106] -6.062e-06      0.001     -0.008      0.994      -0.002       0.002
C(item_nbr)[T.107]  5.045e-16      0.001   6.51e-13      1.000      -0.002       0.002
C(item_nbr)[T.108] -2.717e-16      0.001   -3.5e-13      1.000      -0.002       0.002
C(item_nbr)[T.109]  2.494e-17      0.001   3.22e-14      1.000      -0.002       0.002
C(item_nbr)[T.110]  4.244e-16      0.001   5.47e-13      1.000      -0.002       0.002
C(item_nbr)[T.111] -1.476e-15      0.001   -1.9e-12      1.000      -0.002       0.002
scale(dewpoint)     1.342e-06      0.000      0.011      0.991      -0.000       0.000
scale(cool)         6.886e-05   7.38e-05      0.933      0.351   -7.59e-05       0.000
scale(preciptotal)  1.586e-05   5.97e-05      0.266      0.790      -0.000       0.000
scale(resultspeed)  1.819e-05      0.000      0.176      0.860      -0.000       0.000
scale(avgspeed)       -0.0002      0.000     -2.191      0.028      -0.000   -2.42e-05
==============================================================================
Omnibus:                   765403.780   Durbin-Watson:                   2.007
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        999480506.592
Skew:                           7.686   Prob(JB):                         0.00
Kurtosis:                     212.054   Cond. No.                         197.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [26]:
ls1

['depart', 'sunrise', 'sunset', 'snowfall', 'daytime']

### 5. VIF 재확인 (tmax, tmin, tavg 제외함)

In [27]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
# all_cols = ['tmax','tmin','tavg','dewpoint','wetbulb','heat','cool','preciptotal',\
#         'stnpressure','sealevel','resultspeed','avgspeed','relative_humility',\
#         'windchill', 'depart', 'sunrise', 'sunset', 'snowfall' ]
cols = ['dewpoint','cool','preciptotal',\
        'resultspeed','avgspeed']

y = df2_1.loc[:,cols]
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(y.values, i) for i in range(y.shape[1])]
vif["features"] = y.columns
vif = vif.sort_values("VIF Factor", ascending=False).reset_index(drop=True)
vif

   VIF Factor     features
0   14.456026     avgspeed
1    8.128052  resultspeed
2    5.014932     dewpoint
3    1.417994         cool
4    1.134908  preciptotal

### 6. VIF 근거, avg speed 제외하고  Model 돌림.

In [28]:
# OLS - df2_1
model2_1 = sm.OLS.from_formula('log1p_units ~ scale(dewpoint) + scale(cool)\
                            + scale(preciptotal) + scale(resultspeed)  \
                            + C(resultdir) + C(year) + C(month) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2_1)
result2_1 = model2_1.fit()
print(result2_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.989
Model:                            OLS   Adj. R-squared:                  0.989
Method:                 Least Squares   F-statistic:                 2.828e+05
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        12:12:17   Log-Likelihood:             9.9666e+05
No. Observations:              545919   AIC:                        -1.993e+06
Df Residuals:                  545750   BIC:                        -1.991e+06
Df Model:                         168
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
C(resultdir)[1.0]      0.0035      0.001      4.993      0.000       0.002       0.005
C(resultdir)[2.0]      0.0023      0.001      3.176      0.001       0.001       0.004
C(resultdir)[3.0]      0.0027      0.001      3.280      0.001       0.001       0.004
C(resultdir)[4.0]      0.0030      0.001      3.950      0.000       0.001       0.004
C(resultdir)[5.0]      0.0027      0.001      3.708      0.000       0.001       0.004
C(resultdir)[6.0]      0.0021      0.001      2.541      0.011       0.000       0.004
C(resultdir)[7.0]      0.0020      0.001      2.526      0.012       0.000       0.004
C(resultdir)[8.0]      0.0030      0.001      3.739      0.000       0.001       0.005
C(resultdir)[9.0]      0.0021      0.001      2.948      0.003       0.001       0.004
C(resultdir)[10.0]     0.0023      0.001      3.034      0.002       0.001       0.004
C(resultdir)[11.0]     0.0028      0.001      3.099      0.002       0.001       0.005
C(resultdir)[12.0]     0.0024      0.001      3.202      0.001       0.001       0.004
C(resultdir)[13.0]     0.0025      0.001      3.630      0.000       0.001       0.004
C(resultdir)[14.0]     0.0032      0.001      4.748      0.000       0.002       0.005
C(resultdir)[15.0]     0.0039      0.001      5.854      0.000       0.003       0.005
C(resultdir)[16.0]     0.0041      0.001      6.405      0.000       0.003       0.005
C(resultdir)[17.0]     0.0044      0.001      6.814      0.000       0.003       0.006
C(resultdir)[18.0]     0.0050      0.001      7.747      0.000       0.004       0.006
C(resultdir)[19.0]     0.0043      0.001      6.580      0.000       0.003       0.006
C(resultdir)[20.0]     0.0041      0.001      6.278      0.000       0.003       0.005
C(resultdir)[21.0]     0.0046      0.001      7.147      0.000       0.003       0.006
C(resultdir)[22.0]     0.0042      0.001      6.418      0.000       0.003       0.005
C(resultdir)[23.0]     0.0038      0.001      5.737      0.000       0.003       0.005
C(resultdir)[24.0]     0.0024      0.001      3.417      0.001       0.001       0.004
C(resultdir)[25.0]     0.0034      0.001      4.963      0.000       0.002       0.005
C(resultdir)[26.0]     0.0023      0.001      3.268      0.001       0.001       0.004
C(resultdir)[27.0]     0.0026      0.001      3.553      0.000       0.001       0.004
C(resultdir)[28.0]     0.0029      0.001      3.974      0.000       0.001       0.004
C(resultdir)[29.0]     0.0031      0.001      4.400      0.000       0.002       0.004
C(resultdir)[30.0]     0.0032      0.001      4.427      0.000       0.002       0.005
C(resultdir)[31.0]     0.0030      0.001      4.129      0.000       0.002       0.004
C(resultdir)[32.0]     0.0028      0.001      3.735      0.000       0.001       0.004
C(resultdir)[33.0]     0.0025      0.001      3.618      0.000       0.001       0.004
C(resultdir)[34.0]     0.0032      0.001      4.477      0.000       0.002       0.005
C(resultdir)[35.0]     0.0032      0.001      4.680      0.000       0.002       0.005
C(resultdir)[36.0]     0.0028      0.001      3.979      0.000       0.001       0.004
C(year)[T.2013]       -0.0009      0.000     -6.591      0.000      -0.001      -0.001
C(year)[T.2014]       -0.0028      0.000    -20.290      0.000      -0.003      -0.003
C(month)[T.2]         -0.0003      0.000     -1.181      0.238      -0.001       0.000
C(month)[T.3]         -0.0008      0.000     -3.317      0.001      -0.001      -0.000
C(month)[T.4]         -0.0012      0.000     -4.422      0.000      -0.002      -0.001
C(month)[T.5]         -0.0010      0.000     -3.138      0.002      -0.002      -0.000
C(month)[T.6]         -0.0008      0.000     -2.155      0.031      -0.001    -6.9e-05
C(month)[T.7]         -0.0009      0.000     -2.221      0.026      -0.002      -0.000
C(month)[T.8]         -0.0012      0.000     -2.993      0.003      -0.002      -0.000
C(month)[T.9]         -0.0015      0.000     -4.228      0.000      -0.002      -0.001
C(month)[T.10]        -0.0015      0.000     -5.096      0.000      -0.002      -0.001
C(month)[T.11]        -0.0011      0.000     -3.690      0.000      -0.002      -0.001
C(month)[T.12]        -0.0009      0.000     -3.086      0.002      -0.001      -0.000
C(weekend)[T.1]        0.0017      0.000     14.501      0.000       0.002       0.002
C(rainY)[T.1]         -0.0001      0.000     -1.043      0.297      -0.000       0.000
C(store_nbr)[T.25]    -0.0006      0.000     -3.375      0.001      -0.001      -0.000
C(store_nbr)[T.32]    -0.0033      0.000    -19.612      0.000      -0.004      -0.003
C(store_nbr)[T.37]    -0.0036      0.000    -21.351      0.000      -0.004      -0.003
C(store_nbr)[T.40]    -0.0022      0.000    -13.212      0.000      -0.003      -0.002
C(item_nbr)[T.2]   -1.393e-15      0.001   -1.8e-12      1.000      -0.002       0.002
C(item_nbr)[T.3]   -2.785e-15      0.001  -3.59e-12      1.000      -0.002       0.002
C(item_nbr)[T.4]    7.392e-16      0.001   9.53e-13      1.000      -0.002       0.002
C(item_nbr)[T.5]       2.5900      0.003    854.065      0.000       2.584       2.596
C(item_nbr)[T.6]   -7.108e-16      0.001  -9.17e-13      1.000      -0.002       0.002
C(item_nbr)[T.7]   -1.293e-15      0.001  -1.67e-12      1.000      -0.002       0.002
C(item_nbr)[T.8]   -1.099e-15      0.001  -1.42e-12      1.000      -0.002       0.002
C(item_nbr)[T.9]       1.9342      0.008    257.044      0.000       1.919       1.949
C(item_nbr)[T.10]  -1.054e-15      0.001  -1.36e-12      1.000      -0.002       0.002
C(item_nbr)[T.11]  -1.041e-15      0.001  -1.34e-12      1.000      -0.002       0.002
C(item_nbr)[T.12]      0.0133      0.001     16.926      0.000       0.012       0.015
C(item_nbr)[T.13]   -1.32e-15      0.001   -1.7e-12      1.000      -0.002       0.002
C(item_nbr)[T.14]  -1.208e-15      0.001  -1.56e-12      1.000      -0.002       0.002
C(item_nbr)[T.15]      0.0177      0.001     22.404      0.000       0.016       0.019
C(item_nbr)[T.16]   -1.22e-15      0.001  -1.57e-12      1.000      -0.002       0.002
C(item_nbr)[T.17]      0.0151      0.001     19.169      0.000       0.014       0.017
C(item_nbr)[T.18]  -1.194e-15      0.001  -1.54e-12      1.000      -0.002       0.002
C(item_nbr)[T.19]      0.0129      0.001     16.355      0.000       0.011       0.014
C(item_nbr)[T.20]  -1.002e-15      0.001  -1.29e-12      1.000      -0.002       0.002
C(item_nbr)[T.21]  -1.198e-15      0.001  -1.55e-12      1.000      -0.002       0.002
C(item_nbr)[T.22]  -1.276e-15      0.001  -1.65e-12      1.000      -0.002       0.002
C(item_nbr)[T.23]  -1.219e-15      0.001  -1.57e-12      1.000      -0.002       0.002
C(item_nbr)[T.24]  -1.318e-15      0.001   -1.7e-12      1.000      -0.002       0.002
C(item_nbr)[T.25]  -1.199e-15      0.001  -1.55e-12      1.000      -0.002       0.002
C(item_nbr)[T.26]  -1.528e-15      0.001  -1.97e-12      1.000      -0.002       0.002
C(item_nbr)[T.27]  -1.303e-15      0.001  -1.68e-12      1.000      -0.002       0.002
C(item_nbr)[T.28]  -1.384e-15      0.001  -1.78e-12      1.000      -0.002       0.002
C(item_nbr)[T.29]  -1.099e-15      0.001  -1.42e-12      1.000      -0.002       0.002
C(item_nbr)[T.30]  -1.304e-15      0.001  -1.68e-12      1.000      -0.002       0.002
C(item_nbr)[T.31]  -1.295e-15      0.001  -1.67e-12      1.000      -0.002       0.002
C(item_nbr)[T.32]  -1.185e-15      0.001  -1.53e-12      1.000      -0.002       0.002
C(item_nbr)[T.33]  -1.203e-15      0.001  -1.55e-12      1.000      -0.002       0.002
C(item_nbr)[T.34]  -1.044e-15      0.001  -1.35e-12      1.000      -0.002       0.002
C(item_nbr)[T.35]  -1.124e-15      0.001  -1.45e-12      1.000      -0.002       0.002
C(item_nbr)[T.36]  -1.084e-15      0.001   -1.4e-12      1.000      -0.002       0.002
C(item_nbr)[T.37]  -1.126e-15      0.001  -1.45e-12      1.000      -0.002       0.002
C(item_nbr)[T.38]      0.0010      0.001      1.257      0.209      -0.001       0.003
C(item_nbr)[T.39]  -1.094e-15      0.001  -1.41e-12      1.000      -0.002       0.002
C(item_nbr)[T.40]  -1.262e-15      0.001  -1.63e-12      1.000      -0.002       0.002
C(item_nbr)[T.41]  -1.005e-15      0.001   -1.3e-12      1.000      -0.002       0.002
C(item_nbr)[T.42]  -1.008e-15      0.001   -1.3e-12      1.000      -0.002       0.002
C(item_nbr)[T.43]   -1.12e-15      0.001  -1.44e-12      1.000      -0.002       0.002
C(item_nbr)[T.44]  -3.825e-16      0.001  -4.93e-13      1.000      -0.002       0.002
C(item_nbr)[T.45]      4.1101      0.001   5061.469      0.000       4.109       4.112
C(item_nbr)[T.46]  -8.944e-16      0.001  -1.15e-12      1.000      -0.002       0.002
C(item_nbr)[T.47]  -9.268e-16      0.001   -1.2e-12      1.000      -0.002       0.002
C(item_nbr)[T.48]  -7.687e-16      0.001  -9.91e-13      1.000      -0.002       0.002
C(item_nbr)[T.49]      0.0003      0.001      0.426      0.670      -0.001       0.002
C(item_nbr)[T.50]      0.0013      0.001      1.660      0.097      -0.000       0.003
C(item_nbr)[T.51]      0.0068      0.001      8.595      0.000       0.005       0.008
C(item_nbr)[T.52]  -8.211e-16      0.001  -1.06e-12      1.000      -0.002       0.002
C(item_nbr)[T.53]      0.0092      0.001     11.662      0.000       0.008       0.011
C(item_nbr)[T.54]  -9.258e-16      0.001  -1.19e-12      1.000      -0.002       0.002
C(item_nbr)[T.55]      0.0094      0.001     11.867      0.000       0.008       0.011
C(item_nbr)[T.56]  -7.259e-16      0.001  -9.36e-13      1.000      -0.002       0.002
C(item_nbr)[T.57]  -1.034e-15      0.001  -1.33e-12      1.000      -0.002       0.002
C(item_nbr)[T.58]      0.0085      0.001     10.824      0.000       0.007       0.010
C(item_nbr)[T.59]  -6.329e-16      0.001  -8.16e-13      1.000      -0.002       0.002
C(item_nbr)[T.60]  -7.069e-16      0.001  -9.12e-13      1.000      -0.002       0.002
C(item_nbr)[T.61]      0.0087      0.001     11.042      0.000       0.007       0.010
C(item_nbr)[T.62]  -6.636e-16      0.001  -8.56e-13      1.000      -0.002       0.002
C(item_nbr)[T.63]  -7.535e-16      0.001  -9.72e-13      1.000      -0.002       0.002
C(item_nbr)[T.64]  -7.387e-16      0.001  -9.52e-13      1.000      -0.002       0.002
C(item_nbr)[T.65]  -5.781e-16      0.001  -7.45e-13      1.000      -0.002       0.002
C(item_nbr)[T.66]  -5.683e-16      0.001  -7.33e-13      1.000      -0.002       0.002
C(item_nbr)[T.67]  -7.072e-16      0.001  -9.12e-13      1.000      -0.002       0.002
C(item_nbr)[T.68]  -6.637e-16      0.001  -8.56e-13      1.000      -0.002       0.002
C(item_nbr)[T.69]  -9.072e-16      0.001  -1.17e-12      1.000      -0.002       0.002
C(item_nbr)[T.70]   -6.94e-16      0.001  -8.95e-13      1.000      -0.002       0.002
C(item_nbr)[T.71]  -6.225e-16      0.001  -8.03e-13      1.000      -0.002       0.002
C(item_nbr)[T.72]  -6.426e-16      0.001  -8.29e-13      1.000      -0.002       0.002
C(item_nbr)[T.73]  -7.423e-16      0.001  -9.57e-13      1.000      -0.002       0.002
C(item_nbr)[T.74]  -7.856e-16      0.001  -1.01e-12      1.000      -0.002       0.002
C(item_nbr)[T.75]  -7.423e-16      0.001  -9.57e-13      1.000      -0.002       0.002
C(item_nbr)[T.76]   -6.79e-16      0.001  -8.75e-13      1.000      -0.002       0.002
C(item_nbr)[T.77]  -7.195e-16      0.001  -9.28e-13      1.000      -0.002       0.002
C(item_nbr)[T.78]  -6.997e-16      0.001  -9.02e-13      1.000      -0.002       0.002
C(item_nbr)[T.79]   -6.12e-16      0.001  -7.89e-13      1.000      -0.002       0.002
C(item_nbr)[T.80]  -8.282e-16      0.001  -1.07e-12      1.000      -0.002       0.002
C(item_nbr)[T.81]      0.0003      0.001      0.440      0.660      -0.001       0.002
C(item_nbr)[T.82]  -8.496e-16      0.001   -1.1e-12      1.000      -0.002       0.002
C(item_nbr)[T.83]  -6.193e-16      0.001  -7.98e-13      1.000      -0.002       0.002
C(item_nbr)[T.84]   2.402e-05      0.001      0.031      0.975      -0.001       0.002
C(item_nbr)[T.85]  -6.831e-16      0.001  -8.81e-13      1.000      -0.002       0.002
C(item_nbr)[T.86]      0.0007      0.001      0.924      0.355      -0.001       0.002
C(item_nbr)[T.87]  -7.805e-16      0.001  -1.01e-12      1.000      -0.002       0.002
C(item_nbr)[T.88]  -7.696e-16      0.001  -9.92e-13      1.000      -0.002       0.002
C(item_nbr)[T.89]  -7.578e-16      0.001  -9.77e-13      1.000      -0.002       0.002
C(item_nbr)[T.90]  -5.371e-16      0.001  -6.93e-13      1.000      -0.002       0.002
C(item_nbr)[T.91]    -8.1e-16      0.001  -1.04e-12      1.000      -0.002       0.002
C(item_nbr)[T.92]  -5.022e-16      0.001  -6.47e-13      1.000      -0.002       0.002
C(item_nbr)[T.93]      0.0149      0.001     18.636      0.000       0.013       0.016
C(item_nbr)[T.94]  -6.444e-16      0.001  -8.31e-13      1.000      -0.002       0.002
C(item_nbr)[T.95]  -8.963e-16      0.001  -1.16e-12      1.000      -0.002       0.002
C(item_nbr)[T.96]  -7.291e-16      0.001   -9.4e-13      1.000      -0.002       0.002
C(item_nbr)[T.97]  -6.089e-16      0.001  -7.85e-13      1.000      -0.002       0.002
C(item_nbr)[T.98]  -8.101e-16      0.001  -1.04e-12      1.000      -0.002       0.002
C(item_nbr)[T.99]  -8.103e-16      0.001  -1.04e-12      1.000      -0.002       0.002
C(item_nbr)[T.100]  -4.54e-16      0.001  -5.85e-13      1.000      -0.002       0.002
C(item_nbr)[T.101] -7.442e-16      0.001   -9.6e-13      1.000      -0.002       0.002
C(item_nbr)[T.102] -1.174e-15      0.001  -1.51e-12      1.000      -0.002       0.002
C(item_nbr)[T.103]   1.31e-16      0.001   1.69e-13      1.000      -0.002       0.002
C(item_nbr)[T.104] -6.427e-05      0.001     -0.082      0.934      -0.002       0.001
C(item_nbr)[T.105] -3.977e-05      0.001     -0.051      0.959      -0.002       0.001
C(item_nbr)[T.106] -5.974e-06      0.001     -0.008      0.994      -0.002       0.002
C(item_nbr)[T.107] -5.332e-16      0.001  -6.88e-13      1.000      -0.002       0.002
C(item_nbr)[T.108]  2.931e-16      0.001   3.78e-13      1.000      -0.002       0.002
C(item_nbr)[T.109] -8.204e-16      0.001  -1.06e-12      1.000      -0.002       0.002
C(item_nbr)[T.110] -1.062e-15      0.001  -1.37e-12      1.000      -0.002       0.002
C(item_nbr)[T.111] -1.212e-15      0.001  -1.56e-12      1.000      -0.002       0.002
scale(dewpoint)    -1.287e-05      0.000     -0.106      0.916      -0.000       0.000
scale(cool)         6.719e-05   7.38e-05      0.910      0.363   -7.75e-05       0.000
scale(preciptotal)  6.841e-06   5.95e-05      0.115      0.909      -0.000       0.000
scale(resultspeed)    -0.0002   5.87e-05     -2.875      0.004      -0.000   -5.37e-05
==============================================================================
Omnibus:                   765418.229   Durbin-Watson:                   2.007
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        999535640.232
Skew:                           7.687   Prob(JB):                         0.00
Kurtosis:                     212.059   Cond. No.                         182.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### Anova 분석을 통해 p-value가 0.05보다 큰것은 제외

In [29]:
anova_result2_1 = sm.stats.anova_lm(result2_1).sort_values(by=['PR(>F)'], ascending = False)
anova_result2_1[anova_result2_1['PR(>F)'] <= 0.05]

C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)

,df,sum_sq,mean_sq,F,PR(>F)
scale(resultspeed),1.0,0.012565,0.012565,8.264788,4.042294e-03
C(rainY),1.0,0.047129,0.047129,31.000255,2.581154e-08
C(weekend),1.0,0.474252,0.474252,311.952155,8.579099e-70
C(month),11.0,0.803121,0.073011,48.024923,3.366251e-106
C(year),2.0,1.679739,0.839870,552.446620,2.079805e-240
C(store_nbr),4.0,1.952923,0.488231,321.146764,1.551068e-276
C(resultdir),36.0,628.161302,17.448925,11477.494462,0.000000e+00
C(item_nbr),110.0,72233.031193,656.663920,431938.155491,0.000000e+00

### 최종 Anova 분석과 TIF 통과한 변수들을 바탕으로 최종 모델생성

In [30]:
# OLS - df2_1
model2_1 = sm.OLS.from_formula('log1p_units ~ scale(resultspeed)  \
                            + C(resultdir) + C(year) + C(month) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2_1)
result2_1 = model2_1.fit()
print(result2_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.989
Model:                            OLS   Adj. R-squared:                  0.989
Method:                 Least Squares   F-statistic:                 2.880e+05
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        12:16:24   Log-Likelihood:             9.9666e+05
No. Observations:              545919   AIC:                        -1.993e+06
Df Residuals:                  545753   BIC:                        -1.991e+06
Df Model:                         165
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
C(resultdir)[1.0]      0.0034      0.001      5.114      0.000       0.002       0.005
C(resultdir)[2.0]      0.0023      0.001      3.203      0.001       0.001       0.004
C(resultdir)[3.0]      0.0027      0.001      3.331      0.001       0.001       0.004
C(resultdir)[4.0]      0.0029      0.001      3.978      0.000       0.001       0.004
C(resultdir)[5.0]      0.0027      0.001      3.750      0.000       0.001       0.004
C(resultdir)[6.0]      0.0021      0.001      2.582      0.010       0.001       0.004
C(resultdir)[7.0]      0.0020      0.001      2.557      0.011       0.000       0.004
C(resultdir)[8.0]      0.0030      0.001      3.779      0.000       0.001       0.005
C(resultdir)[9.0]      0.0021      0.001      2.996      0.003       0.001       0.003
C(resultdir)[10.0]     0.0022      0.001      3.048      0.002       0.001       0.004
C(resultdir)[11.0]     0.0027      0.001      3.134      0.002       0.001       0.004
C(resultdir)[12.0]     0.0023      0.001      3.237      0.001       0.001       0.004
C(resultdir)[13.0]     0.0025      0.001      3.683      0.000       0.001       0.004
C(resultdir)[14.0]     0.0032      0.001      4.812      0.000       0.002       0.005
C(resultdir)[15.0]     0.0038      0.001      5.954      0.000       0.003       0.005
C(resultdir)[16.0]     0.0040      0.001      6.514      0.000       0.003       0.005
C(resultdir)[17.0]     0.0043      0.001      6.959      0.000       0.003       0.006
C(resultdir)[18.0]     0.0049      0.001      7.921      0.000       0.004       0.006
C(resultdir)[19.0]     0.0042      0.001      6.727      0.000       0.003       0.005
C(resultdir)[20.0]     0.0041      0.001      6.464      0.000       0.003       0.005
C(resultdir)[21.0]     0.0046      0.001      7.360      0.000       0.003       0.006
C(resultdir)[22.0]     0.0042      0.001      6.568      0.000       0.003       0.005
C(resultdir)[23.0]     0.0038      0.001      5.933      0.000       0.003       0.005
C(resultdir)[24.0]     0.0024      0.001      3.490      0.000       0.001       0.004
C(resultdir)[25.0]     0.0034      0.001      5.077      0.000       0.002       0.005
C(resultdir)[26.0]     0.0023      0.001      3.335      0.001       0.001       0.004
C(resultdir)[27.0]     0.0026      0.001      3.610      0.000       0.001       0.004
C(resultdir)[28.0]     0.0029      0.001      4.051      0.000       0.001       0.004
C(resultdir)[29.0]     0.0030      0.001      4.475      0.000       0.002       0.004
C(resultdir)[30.0]     0.0032      0.001      4.522      0.000       0.002       0.005
C(resultdir)[31.0]     0.0029      0.001      4.153      0.000       0.002       0.004
C(resultdir)[32.0]     0.0028      0.001      3.843      0.000       0.001       0.004
C(resultdir)[33.0]     0.0025      0.001      3.686      0.000       0.001       0.004
C(resultdir)[34.0]     0.0032      0.001      4.530      0.000       0.002       0.005
C(resultdir)[35.0]     0.0032      0.001      4.782      0.000       0.002       0.004
C(resultdir)[36.0]     0.0027      0.001      4.042      0.000       0.001       0.004
C(year)[T.2013]       -0.0009      0.000     -6.617      0.000      -0.001      -0.001
C(year)[T.2014]       -0.0028      0.000    -20.502      0.000      -0.003      -0.003
C(month)[T.2]         -0.0003      0.000     -1.122      0.262      -0.001       0.000
C(month)[T.3]         -0.0008      0.000     -3.352      0.001      -0.001      -0.000
C(month)[T.4]         -0.0012      0.000     -4.783      0.000      -0.002      -0.001
C(month)[T.5]         -0.0009      0.000     -3.764      0.000      -0.001      -0.000
C(month)[T.6]         -0.0007      0.000     -2.725      0.006      -0.001      -0.000
C(month)[T.7]         -0.0008      0.000     -3.267      0.001      -0.001      -0.000
C(month)[T.8]         -0.0011      0.000     -4.334      0.000      -0.002      -0.001
C(month)[T.9]         -0.0015      0.000     -5.615      0.000      -0.002      -0.001
C(month)[T.10]        -0.0015      0.000     -5.873      0.000      -0.002      -0.001
C(month)[T.11]        -0.0011      0.000     -3.754      0.000      -0.002      -0.001
C(month)[T.12]        -0.0009      0.000     -3.083      0.002      -0.001      -0.000
C(weekend)[T.1]        0.0017      0.000     14.497      0.000       0.002       0.002
C(rainY)[T.1]         -0.0001      0.000     -1.202      0.229      -0.000    9.17e-05
C(store_nbr)[T.25]    -0.0006      0.000     -3.375      0.001      -0.001      -0.000
C(store_nbr)[T.32]    -0.0033      0.000    -19.612      0.000      -0.004      -0.003
C(store_nbr)[T.37]    -0.0036      0.000    -21.351      0.000      -0.004      -0.003
C(store_nbr)[T.40]    -0.0022      0.000    -13.212      0.000      -0.003      -0.002
C(item_nbr)[T.2]   -3.932e-16      0.001  -5.07e-13      1.000      -0.002       0.002
C(item_nbr)[T.3]   -9.986e-16      0.001  -1.29e-12      1.000      -0.002       0.002
C(item_nbr)[T.4]   -1.021e-15      0.001  -1.32e-12      1.000      -0.002       0.002
C(item_nbr)[T.5]       2.5900      0.003    854.073      0.000       2.584       2.596
C(item_nbr)[T.6]     -9.1e-16      0.001  -1.17e-12      1.000      -0.002       0.002
C(item_nbr)[T.7]   -9.098e-16      0.001  -1.17e-12      1.000      -0.002       0.002
C(item_nbr)[T.8]   -1.326e-15      0.001  -1.71e-12      1.000      -0.002       0.002
C(item_nbr)[T.9]       1.9342      0.008    257.046      0.000       1.920       1.949
C(item_nbr)[T.10]  -6.444e-16      0.001  -8.31e-13      1.000      -0.002       0.002
C(item_nbr)[T.11]  -7.937e-16      0.001  -1.02e-12      1.000      -0.002       0.002
C(item_nbr)[T.12]      0.0133      0.001     16.926      0.000       0.012       0.015
C(item_nbr)[T.13]  -8.476e-16      0.001  -1.09e-12      1.000      -0.002       0.002
C(item_nbr)[T.14]  -7.566e-16      0.001  -9.76e-13      1.000      -0.002       0.002
C(item_nbr)[T.15]      0.0177      0.001     22.403      0.000       0.016       0.019
C(item_nbr)[T.16]  -6.648e-16      0.001  -8.57e-13      1.000      -0.002       0.002
C(item_nbr)[T.17]      0.0151      0.001     19.168      0.000       0.014       0.017
C(item_nbr)[T.18]  -1.016e-15      0.001  -1.31e-12      1.000      -0.002       0.002
C(item_nbr)[T.19]      0.0129      0.001     16.355      0.000       0.011       0.014
C(item_nbr)[T.20]  -7.918e-16      0.001  -1.02e-12      1.000      -0.002       0.002
C(item_nbr)[T.21]  -6.661e-16      0.001  -8.59e-13      1.000      -0.002       0.002
C(item_nbr)[T.22]  -8.206e-16      0.001  -1.06e-12      1.000      -0.002       0.002
C(item_nbr)[T.23]   -8.06e-16      0.001  -1.04e-12      1.000      -0.002       0.002
C(item_nbr)[T.24]  -8.729e-16      0.001  -1.13e-12      1.000      -0.002       0.002
C(item_nbr)[T.25]  -7.761e-16      0.001     -1e-12      1.000      -0.002       0.002
C(item_nbr)[T.26]  -8.814e-16      0.001  -1.14e-12      1.000      -0.002       0.002
C(item_nbr)[T.27]  -9.328e-16      0.001   -1.2e-12      1.000      -0.002       0.002
C(item_nbr)[T.28]  -7.555e-16      0.001  -9.74e-13      1.000      -0.002       0.002
C(item_nbr)[T.29]  -6.674e-16      0.001  -8.61e-13      1.000      -0.002       0.002
C(item_nbr)[T.30]  -8.959e-16      0.001  -1.16e-12      1.000      -0.002       0.002
C(item_nbr)[T.31]  -8.042e-16      0.001  -1.04e-12      1.000      -0.002       0.002
C(item_nbr)[T.32]  -8.472e-16      0.001  -1.09e-12      1.000      -0.002       0.002
C(item_nbr)[T.33]  -7.097e-16      0.001  -9.15e-13      1.000      -0.002       0.002
C(item_nbr)[T.34]  -6.529e-16      0.001  -8.42e-13      1.000      -0.002       0.002
C(item_nbr)[T.35]  -1.027e-15      0.001  -1.32e-12      1.000      -0.002       0.002
C(item_nbr)[T.36]  -8.214e-16      0.001  -1.06e-12      1.000      -0.002       0.002
C(item_nbr)[T.37]  -8.866e-16      0.001  -1.14e-12      1.000      -0.002       0.002
C(item_nbr)[T.38]      0.0010      0.001      1.257      0.209      -0.001       0.003
C(item_nbr)[T.39]  -7.847e-16      0.001  -1.01e-12      1.000      -0.002       0.002
C(item_nbr)[T.40]   -8.63e-16      0.001  -1.11e-12      1.000      -0.002       0.002
C(item_nbr)[T.41]  -7.096e-16      0.001  -9.15e-13      1.000      -0.002       0.002
C(item_nbr)[T.42]  -7.751e-16      0.001  -9.99e-13      1.000      -0.002       0.002
C(item_nbr)[T.43]  -5.495e-16      0.001  -7.09e-13      1.000      -0.002       0.002
C(item_nbr)[T.44]  -1.097e-16      0.001  -1.41e-13      1.000      -0.002       0.002
C(item_nbr)[T.45]      4.1101      0.001   5061.485      0.000       4.109       4.112
C(item_nbr)[T.46]  -2.266e-16      0.001  -2.92e-13      1.000      -0.002       0.002
C(item_nbr)[T.47]  -4.509e-16      0.001  -5.81e-13      1.000      -0.002       0.002
C(item_nbr)[T.48]  -1.166e-16      0.001   -1.5e-13      1.000      -0.002       0.002
C(item_nbr)[T.49]      0.0003      0.001      0.426      0.670      -0.001       0.002
C(item_nbr)[T.50]      0.0013      0.001      1.660      0.097      -0.000       0.003
C(item_nbr)[T.51]      0.0068      0.001      8.595      0.000       0.005       0.008
C(item_nbr)[T.52]  -4.523e-16      0.001  -5.83e-13      1.000      -0.002       0.002
C(item_nbr)[T.53]      0.0092      0.001     11.663      0.000       0.008       0.011
C(item_nbr)[T.54]  -4.979e-16      0.001  -6.42e-13      1.000      -0.002       0.002
C(item_nbr)[T.55]      0.0094      0.001     11.867      0.000       0.008       0.011
C(item_nbr)[T.56]   -5.16e-16      0.001  -6.65e-13      1.000      -0.002       0.002
C(item_nbr)[T.57]  -6.465e-16      0.001  -8.34e-13      1.000      -0.002       0.002
C(item_nbr)[T.58]      0.0085      0.001     10.824      0.000       0.007       0.010
C(item_nbr)[T.59]  -4.736e-16      0.001  -6.11e-13      1.000      -0.002       0.002
C(item_nbr)[T.60]  -4.747e-16      0.001  -6.12e-13      1.000      -0.002       0.002
C(item_nbr)[T.61]      0.0087      0.001     11.042      0.000       0.007       0.010
C(item_nbr)[T.62]   -3.65e-16      0.001  -4.71e-13      1.000      -0.002       0.002
C(item_nbr)[T.63]  -4.806e-16      0.001   -6.2e-13      1.000      -0.002       0.002
C(item_nbr)[T.64]  -2.926e-16      0.001  -3.77e-13      1.000      -0.002       0.002
C(item_nbr)[T.65]  -2.933e-16      0.001  -3.78e-13      1.000      -0.002       0.002
C(item_nbr)[T.66]  -4.885e-16      0.001   -6.3e-13      1.000      -0.002       0.002
C(item_nbr)[T.67]  -4.381e-16      0.001  -5.65e-13      1.000      -0.002       0.002
C(item_nbr)[T.68]  -4.058e-16      0.001  -5.23e-13      1.000      -0.002       0.002
C(item_nbr)[T.69]   -2.97e-16      0.001  -3.83e-13      1.000      -0.002       0.002
C(item_nbr)[T.70]  -3.066e-16      0.001  -3.95e-13      1.000      -0.002       0.002
C(item_nbr)[T.71]  -3.876e-16      0.001     -5e-13      1.000      -0.002       0.002
C(item_nbr)[T.72]  -4.934e-16      0.001  -6.36e-13      1.000      -0.002       0.002
C(item_nbr)[T.73]  -7.317e-16      0.001  -9.43e-13      1.000      -0.002       0.002
C(item_nbr)[T.74]  -3.397e-16      0.001  -4.38e-13      1.000      -0.002       0.002
C(item_nbr)[T.75]  -5.018e-16      0.001  -6.47e-13      1.000      -0.002       0.002
C(item_nbr)[T.76]  -3.995e-16      0.001  -5.15e-13      1.000      -0.002       0.002
C(item_nbr)[T.77]   -3.76e-16      0.001  -4.85e-13      1.000      -0.002       0.002
C(item_nbr)[T.78]  -4.611e-16      0.001  -5.95e-13      1.000      -0.002       0.002
C(item_nbr)[T.79]  -6.496e-16      0.001  -8.38e-13      1.000      -0.002       0.002
C(item_nbr)[T.80]  -5.716e-16      0.001  -7.37e-13      1.000      -0.002       0.002
C(item_nbr)[T.81]      0.0003      0.001      0.440      0.660      -0.001       0.002
C(item_nbr)[T.82]  -3.324e-16      0.001  -4.29e-13      1.000      -0.002       0.002
C(item_nbr)[T.83]  -5.902e-16      0.001  -7.61e-13      1.000      -0.002       0.002
C(item_nbr)[T.84]   2.398e-05      0.001      0.031      0.975      -0.001       0.002
C(item_nbr)[T.85]  -2.882e-16      0.001  -3.72e-13      1.000      -0.002       0.002
C(item_nbr)[T.86]      0.0007      0.001      0.924      0.355      -0.001       0.002
C(item_nbr)[T.87]  -4.214e-16      0.001  -5.43e-13      1.000      -0.002       0.002
C(item_nbr)[T.88]  -5.018e-16      0.001  -6.47e-13      1.000      -0.002       0.002
C(item_nbr)[T.89]  -5.293e-16      0.001  -6.83e-13      1.000      -0.002       0.002
C(item_nbr)[T.90]   -6.34e-16      0.001  -8.17e-13      1.000      -0.002       0.002
C(item_nbr)[T.91]  -6.772e-16      0.001  -8.73e-13      1.000      -0.002       0.002
C(item_nbr)[T.92]  -5.152e-16      0.001  -6.64e-13      1.000      -0.002       0.002
C(item_nbr)[T.93]      0.0149      0.001     18.635      0.000       0.013       0.016
C(item_nbr)[T.94]  -4.785e-16      0.001  -6.17e-13      1.000      -0.002       0.002
C(item_nbr)[T.95]   -1.76e-16      0.001  -2.27e-13      1.000      -0.002       0.002
C(item_nbr)[T.96]  -3.978e-16      0.001  -5.13e-13      1.000      -0.002       0.002
C(item_nbr)[T.97]  -5.662e-16      0.001   -7.3e-13      1.000      -0.002       0.002
C(item_nbr)[T.98]  -4.921e-16      0.001  -6.35e-13      1.000      -0.002       0.002
C(item_nbr)[T.99]  -3.254e-16      0.001   -4.2e-13      1.000      -0.002       0.002
C(item_nbr)[T.100]  -6.19e-16      0.001  -7.98e-13      1.000      -0.002       0.002
C(item_nbr)[T.101] -7.413e-17      0.001  -9.56e-14      1.000      -0.002       0.002
C(item_nbr)[T.102]  5.391e-16      0.001   6.95e-13      1.000      -0.002       0.002
C(item_nbr)[T.103]  2.129e-16      0.001   2.75e-13      1.000      -0.002       0.002
C(item_nbr)[T.104] -6.416e-05      0.001     -0.082      0.935      -0.002       0.001
C(item_nbr)[T.105] -3.974e-05      0.001     -0.051      0.959      -0.002       0.001
C(item_nbr)[T.106] -5.838e-06      0.001     -0.008      0.994      -0.002       0.002
C(item_nbr)[T.107]  3.397e-16      0.001   4.38e-13      1.000      -0.002       0.002
C(item_nbr)[T.108]  9.995e-16      0.001   1.29e-12      1.000      -0.002       0.002
C(item_nbr)[T.109] -1.206e-15      0.001  -1.55e-12      1.000      -0.002       0.002
C(item_nbr)[T.110] -3.708e-15      0.001  -4.78e-12      1.000      -0.002       0.002
C(item_nbr)[T.111]  7.264e-15      0.001   9.37e-12      1.000      -0.002       0.002
scale(resultspeed)    -0.0002    5.8e-05     -2.910      0.004      -0.000   -5.51e-05
==============================================================================
Omnibus:                   765422.618   Durbin-Watson:                   2.007
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        999543550.394
Skew:                           7.687   Prob(JB):                         0.00
Kurtosis:                     212.060   Cond. No.                         145.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [31]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import KFold
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score


dfX = df2[['year', 'month', 'weekend', 'rainY', 'store_nbr', 'item_nbr', 'resultdir', 'resultspeed']]
dfy = df2['log1p_units']

model = LinearRegression()

cv = KFold(10, shuffle=True)

cross_val_score(model, dfX, dfy, scoring="r2", cv=cv)

array([0.01402272, 0.01390284, 0.01402932, 0.01573242, 0.01621126,
       0.01548514, 0.01520941, 0.01328605, 0.01397981, 0.01452603])

In [32]:
from patsy import dmatrix
# 독립변수와 종속변수로 나누기
df2_1_X = df2_1.drop(columns=['log1p_units'])
df2_1_target = df2_1['log1p_units']

In [33]:
formula = 'C(year) + C(month) + C(weekend) + C(resultdir) \
        + C(rainY) + C(store_nbr) + C(item_nbr) + scale(resultspeed) + 0'
dfX = dmatrix(formula, df2_1_X, return_type='dataframe')
dfy = pd.DataFrame(df2_1_target, columns=["log1p_units"])

In [34]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold
from sklearn.metrics import r2_score

model = LinearRegression()
cv = KFold(10)

scores = np.zeros(10)
for i, (train_index, test_index) in enumerate(cv.split(dfX)):
    X_train = dfX.values[train_index]
    y_train = dfy.values[train_index]
    X_test = dfX.values[test_index]
    y_test = dfy.values[test_index]
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    scores[i] = r2_score(y_test, y_pred)

scores

array([0.98665732, 0.98702967, 0.98836085, 0.98355483, 0.99107122,
       0.99017401, 0.98870186, 0.99002734, 0.99141449, 0.98789855])