In [1]:
weather = pd.read_csv("weather3_180703.csv")
weather['date'] = pd.to_datetime(weather["date"])
station = weather[weather['station_nbr'] == 12]

In [2]:
station['date'].count()

1035

In [3]:
# ls == 모든 값이 0인 것

ls = []
ls1 = []
for i in station.columns:
    if station[i].count() == 0:
        ls.append(i)
    if station[i].isna().sum() != 0:
        ls1.append(i)
ls, ls1

(['depart', 'sunrise', 'sunset', 'daytime'],
 ['depart', 'sunrise', 'sunset', 'snowfall', 'resultdir', 'daytime'])

In [4]:
for i in station.columns:
    count_null = station[i].isna().sum()
    print(i, ":", count_null, "(",round((count_null / len(station) * 100),2),"%",")")

station_nbr : 0 ( 0.0 % )
date : 0 ( 0.0 % )
tmax : 0 ( 0.0 % )
tmin : 0 ( 0.0 % )
tavg : 0 ( 0.0 % )
depart : 1035 ( 100.0 % )
dewpoint : 0 ( 0.0 % )
wetbulb : 0 ( 0.0 % )
heat : 0 ( 0.0 % )
cool : 0 ( 0.0 % )
sunrise : 1035 ( 100.0 % )
sunset : 1035 ( 100.0 % )
codesum : 0 ( 0.0 % )
snowfall : 30 ( 2.9 % )
preciptotal : 0 ( 0.0 % )
stnpressure : 0 ( 0.0 % )
sealevel : 0 ( 0.0 % )
resultspeed : 0 ( 0.0 % )
resultdir : 1 ( 0.1 % )
avgspeed : 0 ( 0.0 % )
year : 0 ( 0.0 % )
month : 0 ( 0.0 % )
day : 0 ( 0.0 % )
relative_humility : 0 ( 0.0 % )
windchill : 0 ( 0.0 % )
daytime : 1035 ( 100.0 % )
week7 : 0 ( 0.0 % )
weekend : 0 ( 0.0 % )
code_change : 0 ( 0.0 % )
rainY : 0 ( 0.0 % )
otherY : 0 ( 0.0 % )
nothing : 0 ( 0.0 % )

In [5]:
train = pd.read_csv("train.csv")
train.date = pd.to_datetime(train.date)
train.tail()

              date  store_nbr  item_nbr  units
4617595 2014-10-31         45       107      0
4617596 2014-10-31         45       108      0
4617597 2014-10-31         45       109      0
4617598 2014-10-31         45       110      0
4617599 2014-10-31         45       111      0

In [6]:
key = pd.read_csv("key.csv")
station = station.merge(key)

In [7]:
station = station.merge(train)
station.tail()

,station_nbr,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,...,daytime,week7,weekend,code_change,rainY,otherY,nothing,store_nbr,item_nbr,units
394267,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,107,0
394268,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,108,0
394269,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,109,0
394270,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,110,0
394271,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,111,0

In [8]:
station['log1p_units'] = np.log1p(station.units)

In [9]:
target1 = station['units']
target2 = station['log1p_units']

station.drop(columns=['units','log1p_units'],inplace=True)
station.tail()

,station_nbr,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,...,windchill,daytime,week7,weekend,code_change,rainY,otherY,nothing,store_nbr,item_nbr
394267,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,68.175011,NaN,4,0,1,1,0,0,44,107
394268,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,68.175011,NaN,4,0,1,1,0,0,44,108
394269,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,68.175011,NaN,4,0,1,1,0,0,44,109
394270,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,68.175011,NaN,4,0,1,1,0,0,44,110
394271,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,68.175011,NaN,4,0,1,1,0,0,44,111

In [10]:
df1 = pd.concat([station,target1], axis=1)
df2 = pd.concat([station,target2], axis=1)

In [11]:
df2.to_csv('station12.csv', sep=',', index=False)

In [12]:
if df2.columns.tolist() and ls:
    print('공통 변수 있음')
    print(df2.columns.tolist() and ls)
else:
    print('공통 변수 없음')

공통 변수 있음
['depart', 'sunrise', 'sunset', 'daytime']

In [13]:
df2.columns

Index(['station_nbr', 'date', 'tmax', 'tmin', 'tavg', 'depart', 'dewpoint',
       'wetbulb', 'heat', 'cool', 'sunrise', 'sunset', 'codesum', 'snowfall',
       'preciptotal', 'stnpressure', 'sealevel', 'resultspeed', 'resultdir',
       'avgspeed', 'year', 'month', 'day', 'relative_humility', 'windchill',
       'daytime', 'week7', 'weekend', 'code_change', 'rainY', 'otherY',
       'nothing', 'store_nbr', 'item_nbr', 'log1p_units'],
      dtype='object')

In [14]:
ls, ls1

(['depart', 'sunrise', 'sunset', 'daytime'],
 ['depart', 'sunrise', 'sunset', 'snowfall', 'resultdir', 'daytime'])

### 1. 변수변환: df2 (log1p_units)

In [19]:
all_var = 'log1p_units ~ scale(tmax) + scale(tmin) + scale(tavg) + scale(depart) + scale(dewpoint) + scale(wetbulb) + scale(heat) + scale(cool)\
                            + scale(sunrise) + scale(sunset) + scale(snowfall) + scale(preciptotal) + scale(stnpressure) + scale(sealevel) + scale(resultspeed)  \
                            + C(resultdir) + scale(avgspeed) + C(year) + C(month) + scale(relative_humility) + scale(windchill) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + C(daytime) + 0'

In [16]:
model2 = sm.OLS.from_formula('log1p_units ~ scale(tmax) + scale(tmin) + scale(tavg) + scale(dewpoint) + scale(wetbulb) + scale(heat) + scale(cool)\
                           + scale(preciptotal) + scale(stnpressure) + scale(sealevel) + scale(resultspeed) \
                            + scale(avgspeed) + C(year) + C(month) + scale(relative_humility) + scale(windchill) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2)
result2 = model2.fit()
print(result2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.449
Model:                            OLS   Adj. R-squared:                  0.449
Method:                 Least Squares   F-statistic:                     2282.
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:35:54   Log-Likelihood:            -1.4655e+05
No. Observations:              394272   AIC:                         2.934e+05
Df Residuals:                  394130   BIC:                         2.949e+05
Df Model:                         141
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
C(year)[2012]               -0.0015      0.007     -0.226      0.821      -0.014       0.011
C(year)[2013]               -0.0074      0.007     -1.128      0.260      -0.020       0.005
C(year)[2014]               -0.0112      0.007     -1.690      0.091      -0.024       0.002
C(month)[T.2]               -0.0013      0.003     -0.479      0.632      -0.007       0.004
C(month)[T.3]               -0.0037      0.003     -1.351      0.177      -0.009       0.002
C(month)[T.4]               -0.0055      0.003     -1.802      0.072      -0.011       0.000
C(month)[T.5]               -0.0060      0.003     -1.813      0.070      -0.012       0.000
C(month)[T.6]               -0.0047      0.004     -1.194      0.232      -0.012       0.003
C(month)[T.7]               -0.0074      0.004     -1.736      0.083      -0.016       0.001
C(month)[T.8]               -0.0049      0.004     -1.199      0.231      -0.013       0.003
C(month)[T.9]               -0.0065      0.004     -1.613      0.107      -0.014       0.001
C(month)[T.10]              -0.0069      0.003     -2.154      0.031      -0.013      -0.001
C(month)[T.11]              -0.0089      0.003     -2.966      0.003      -0.015      -0.003
C(month)[T.12]              -0.0056      0.003     -1.891      0.059      -0.011       0.000
C(weekend)[T.1]              0.0071      0.001      5.689      0.000       0.005       0.010
C(rainY)[T.1]                0.0005      0.001      0.332      0.740      -0.002       0.003
C(store_nbr)[T.10]           0.0072      0.002      4.550      0.000       0.004       0.010
C(store_nbr)[T.41]           0.0129      0.002      8.135      0.000       0.010       0.016
C(store_nbr)[T.44]           0.0141      0.002      8.943      0.000       0.011       0.017
C(item_nbr)[T.2]         -1.005e-15      0.008  -1.21e-13      1.000      -0.016       0.016
C(item_nbr)[T.3]          2.156e-15      0.008   2.59e-13      1.000      -0.016       0.016
C(item_nbr)[T.4]          9.008e-16      0.008   1.08e-13      1.000      -0.016       0.016
C(item_nbr)[T.5]             1.9007      0.008    228.223      0.000       1.884       1.917
C(item_nbr)[T.6]          3.842e-15      0.008   4.61e-13      1.000      -0.016       0.016
C(item_nbr)[T.7]         -9.232e-16      0.008  -1.11e-13      1.000      -0.016       0.016
C(item_nbr)[T.8]          1.059e-15      0.008   1.27e-13      1.000      -0.016       0.016
C(item_nbr)[T.9]           1.87e-15      0.008   2.25e-13      1.000      -0.016       0.016
C(item_nbr)[T.10]        -2.248e-15      0.008   -2.7e-13      1.000      -0.016       0.016
C(item_nbr)[T.11]         1.695e-16      0.008   2.04e-14      1.000      -0.016       0.016
C(item_nbr)[T.12]         3.017e-15      0.008   3.62e-13      1.000      -0.016       0.016
C(item_nbr)[T.13]          3.95e-15      0.008   4.74e-13      1.000      -0.016       0.016
C(item_nbr)[T.14]         8.998e-16      0.008   1.08e-13      1.000      -0.016       0.016
C(item_nbr)[T.15]         4.498e-16      0.008    5.4e-14      1.000      -0.016       0.016
C(item_nbr)[T.16]            1.6882      0.008    202.708      0.000       1.672       1.704
C(item_nbr)[T.17]         2.617e-15      0.008   3.14e-13      1.000      -0.016       0.016
C(item_nbr)[T.18]         2.987e-15      0.008   3.59e-13      1.000      -0.016       0.016
C(item_nbr)[T.19]         1.704e-15      0.008   2.05e-13      1.000      -0.016       0.016
C(item_nbr)[T.20]            0.1331      0.008     15.978      0.000       0.117       0.149
C(item_nbr)[T.21]            0.1081      0.008     12.980      0.000       0.092       0.124
C(item_nbr)[T.22]        -3.701e-16      0.008  -4.44e-14      1.000      -0.016       0.016
C(item_nbr)[T.23]         3.455e-16      0.008   4.15e-14      1.000      -0.016       0.016
C(item_nbr)[T.24]         5.112e-16      0.008   6.14e-14      1.000      -0.016       0.016
C(item_nbr)[T.25]         1.988e-15      0.008   2.39e-13      1.000      -0.016       0.016
C(item_nbr)[T.26]         1.118e-16      0.008   1.34e-14      1.000      -0.016       0.016
C(item_nbr)[T.27]         1.762e-15      0.008   2.12e-13      1.000      -0.016       0.016
C(item_nbr)[T.28]         1.136e-15      0.008   1.36e-13      1.000      -0.016       0.016
C(item_nbr)[T.29]        -6.667e-16      0.008  -8.01e-14      1.000      -0.016       0.016
C(item_nbr)[T.30]         1.162e-15      0.008    1.4e-13      1.000      -0.016       0.016
C(item_nbr)[T.31]         2.509e-15      0.008   3.01e-13      1.000      -0.016       0.016
C(item_nbr)[T.32]            0.0816      0.008      9.796      0.000       0.065       0.098
C(item_nbr)[T.33]          7.81e-16      0.008   9.38e-14      1.000      -0.016       0.016
C(item_nbr)[T.34]          7.96e-16      0.008   9.56e-14      1.000      -0.016       0.016
C(item_nbr)[T.35]         3.945e-15      0.008   4.74e-13      1.000      -0.016       0.016
C(item_nbr)[T.36]         1.493e-15      0.008   1.79e-13      1.000      -0.016       0.016
C(item_nbr)[T.37]            1.3183      0.008    158.290      0.000       1.302       1.335
C(item_nbr)[T.38]         1.318e-15      0.008   1.58e-13      1.000      -0.016       0.016
C(item_nbr)[T.39]         2.102e-16      0.008   2.52e-14      1.000      -0.016       0.016
C(item_nbr)[T.40]          1.41e-15      0.008   1.69e-13      1.000      -0.016       0.016
C(item_nbr)[T.41]         4.733e-15      0.008   5.68e-13      1.000      -0.016       0.016
C(item_nbr)[T.42]         1.067e-15      0.008   1.28e-13      1.000      -0.016       0.016
C(item_nbr)[T.43]         1.804e-15      0.008   2.17e-13      1.000      -0.016       0.016
C(item_nbr)[T.44]         2.718e-15      0.008   3.26e-13      1.000      -0.016       0.016
C(item_nbr)[T.45]        -1.689e-15      0.008  -2.03e-13      1.000      -0.016       0.016
C(item_nbr)[T.46]         8.742e-16      0.008   1.05e-13      1.000      -0.016       0.016
C(item_nbr)[T.47]         2.319e-15      0.008   2.78e-13      1.000      -0.016       0.016
C(item_nbr)[T.48]        -1.518e-15      0.008  -1.82e-13      1.000      -0.016       0.016
C(item_nbr)[T.49]         1.676e-15      0.008   2.01e-13      1.000      -0.016       0.016
C(item_nbr)[T.50]          1.23e-16      0.008   1.48e-14      1.000      -0.016       0.016
C(item_nbr)[T.51]        -3.974e-16      0.008  -4.77e-14      1.000      -0.016       0.016
C(item_nbr)[T.52]         1.064e-15      0.008   1.28e-13      1.000      -0.016       0.016
C(item_nbr)[T.53]        -5.422e-15      0.008  -6.51e-13      1.000      -0.016       0.016
C(item_nbr)[T.54]         -9.66e-16      0.008  -1.16e-13      1.000      -0.016       0.016
C(item_nbr)[T.55]         6.478e-16      0.008   7.78e-14      1.000      -0.016       0.016
C(item_nbr)[T.56]         2.364e-15      0.008   2.84e-13      1.000      -0.016       0.016
C(item_nbr)[T.57]         2.144e-16      0.008   2.57e-14      1.000      -0.016       0.016
C(item_nbr)[T.58]         3.112e-15      0.008   3.74e-13      1.000      -0.016       0.016
C(item_nbr)[T.59]        -5.489e-16      0.008  -6.59e-14      1.000      -0.016       0.016
C(item_nbr)[T.60]         1.784e-15      0.008   2.14e-13      1.000      -0.016       0.016
C(item_nbr)[T.61]            0.1068      0.008     12.822      0.000       0.090       0.123
C(item_nbr)[T.62]            0.0801      0.008      9.624      0.000       0.064       0.096
C(item_nbr)[T.63]         8.801e-16      0.008   1.06e-13      1.000      -0.016       0.016
C(item_nbr)[T.64]        -4.748e-16      0.008   -5.7e-14      1.000      -0.016       0.016
C(item_nbr)[T.65]         7.715e-16      0.008   9.26e-14      1.000      -0.016       0.016
C(item_nbr)[T.66]         4.531e-16      0.008   5.44e-14      1.000      -0.016       0.016
C(item_nbr)[T.67]         1.202e-15      0.008   1.44e-13      1.000      -0.016       0.016
C(item_nbr)[T.68]            1.8126      0.008    217.644      0.000       1.796       1.829
C(item_nbr)[T.69]        -2.019e-15      0.008  -2.42e-13      1.000      -0.016       0.016
C(item_nbr)[T.70]        -5.634e-16      0.008  -6.76e-14      1.000      -0.016       0.016
C(item_nbr)[T.71]         1.168e-15      0.008    1.4e-13      1.000      -0.016       0.016
C(item_nbr)[T.72]        -1.894e-15      0.008  -2.27e-13      1.000      -0.016       0.016
C(item_nbr)[T.73]         1.584e-16      0.008    1.9e-14      1.000      -0.016       0.016
C(item_nbr)[T.74]         2.384e-15      0.008   2.86e-13      1.000      -0.016       0.016
C(item_nbr)[T.75]         2.172e-15      0.008   2.61e-13      1.000      -0.016       0.016
C(item_nbr)[T.76]         3.011e-15      0.008   3.62e-13      1.000      -0.016       0.016
C(item_nbr)[T.77]         1.256e-15      0.008   1.51e-13      1.000      -0.016       0.016
C(item_nbr)[T.78]         3.401e-16      0.008   4.08e-14      1.000      -0.016       0.016
C(item_nbr)[T.79]         1.522e-15      0.008   1.83e-13      1.000      -0.016       0.016
C(item_nbr)[T.80]         6.442e-16      0.008   7.74e-14      1.000      -0.016       0.016
C(item_nbr)[T.81]         2.166e-15      0.008    2.6e-13      1.000      -0.016       0.016
C(item_nbr)[T.82]        -5.939e-16      0.008  -7.13e-14      1.000      -0.016       0.016
C(item_nbr)[T.83]         6.512e-16      0.008   7.82e-14      1.000      -0.016       0.016
C(item_nbr)[T.84]         1.286e-15      0.008   1.54e-13      1.000      -0.016       0.016
C(item_nbr)[T.85]         1.402e-15      0.008   1.68e-13      1.000      -0.016       0.016
C(item_nbr)[T.86]            0.0371      0.008      4.459      0.000       0.021       0.053
C(item_nbr)[T.87]         9.607e-16      0.008   1.15e-13      1.000      -0.016       0.016
C(item_nbr)[T.88]         2.912e-15      0.008    3.5e-13      1.000      -0.016       0.016
C(item_nbr)[T.89]         1.625e-15      0.008   1.95e-13      1.000      -0.016       0.016
C(item_nbr)[T.90]        -7.677e-16      0.008  -9.22e-14      1.000      -0.016       0.016
C(item_nbr)[T.91]         2.174e-15      0.008   2.61e-13      1.000      -0.016       0.016
C(item_nbr)[T.92]        -5.756e-16      0.008  -6.91e-14      1.000      -0.016       0.016
C(item_nbr)[T.93]            0.3730      0.008     44.791      0.000       0.357       0.389
C(item_nbr)[T.94]            0.1195      0.008     14.354      0.000       0.103       0.136
C(item_nbr)[T.95]          7.97e-16      0.008   9.57e-14      1.000      -0.016       0.016
C(item_nbr)[T.96]         9.033e-16      0.008   1.08e-13      1.000      -0.016       0.016
C(item_nbr)[T.97]         3.709e-16      0.008   4.45e-14      1.000      -0.016       0.016
C(item_nbr)[T.98]          7.88e-16      0.008   9.46e-14      1.000      -0.016       0.016
C(item_nbr)[T.99]         6.482e-16      0.008   7.78e-14      1.000      -0.016       0.016
C(item_nbr)[T.100]       -8.525e-16      0.008  -1.02e-13      1.000      -0.016       0.016
C(item_nbr)[T.101]        2.254e-15      0.008   2.71e-13      1.000      -0.016       0.016
C(item_nbr)[T.102]       -1.471e-15      0.008  -1.77e-13      1.000      -0.016       0.016
C(item_nbr)[T.103]        4.375e-15      0.008   5.25e-13      1.000      -0.016       0.016
C(item_nbr)[T.104]        2.007e-16      0.008   2.41e-14      1.000      -0.016       0.016
C(item_nbr)[T.105]           0.0269      0.008      3.224      0.001       0.011       0.043
C(item_nbr)[T.106]        3.774e-16      0.008   4.53e-14      1.000      -0.016       0.016
C(item_nbr)[T.107]        2.184e-15      0.008   2.62e-13      1.000      -0.016       0.016
C(item_nbr)[T.108]           0.1534      0.008     18.416      0.000       0.137       0.170
C(item_nbr)[T.109]        7.473e-16      0.008   8.97e-14      1.000      -0.016       0.016
C(item_nbr)[T.110]        5.069e-15      0.008   6.09e-13      1.000      -0.016       0.016
C(item_nbr)[T.111]       -1.962e-15      0.008  -2.36e-13      1.000      -0.016       0.016
scale(tmax)                 -0.0091      0.008     -1.149      0.251      -0.025       0.006
scale(tmin)                 -0.0050      0.008     -0.602      0.547      -0.021       0.011
scale(tavg)                 -0.0071      0.008     -0.864      0.387      -0.023       0.009
scale(dewpoint)              0.0044      0.015      0.297      0.766      -0.025       0.034
scale(wetbulb)               0.0027      0.009      0.294      0.768      -0.015       0.021
scale(heat)                  0.0013      0.004      0.305      0.760      -0.007       0.010
scale(cool)                 -0.0012      0.006     -0.191      0.848      -0.014       0.011
scale(preciptotal)           0.0009      0.001      1.435      0.151      -0.000       0.002
scale(stnpressure)          -0.0028      0.006     -0.472      0.637      -0.015       0.009
scale(sealevel)              0.0019      0.006      0.320      0.749      -0.010       0.014
scale(resultspeed)           0.0001      0.002      0.068      0.946      -0.004       0.004
scale(avgspeed)              0.0002      0.002      0.082      0.934      -0.004       0.004
scale(relative_humility)    -0.0022      0.006     -0.367      0.713      -0.014       0.010
scale(windchill)             0.0173      0.017      0.990      0.322      -0.017       0.051
==============================================================================
Omnibus:                   157229.845   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         11559634.650
Skew:                           1.058   Prob(JB):                         0.00
Kurtosis:                      29.442   Cond. No.                     2.18e+15
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 6.62e-25. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

### 2. 변수변환 : df2 (log1p_units) + 아웃라이어 제거

In [17]:
# 아웃라이어 제거
# Cook's distance > 2 인 값 제거
influence = result2.get_influence()
cooks_d2, pvals = influence.cooks_distance
fox_cr = 4 / (len(df2) - 2)
idx_outlier = np.where(cooks_d2 > fox_cr)[0]
len(idx_outlier)

16092

In [18]:
idx = list(set(range(len(df2))).difference(idx_outlier))
df2_1 = df2.iloc[idx, :].reset_index(drop=True)
df2_1

,station_nbr,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,...,daytime,week7,weekend,code_change,rainY,otherY,nothing,store_nbr,item_nbr,log1p_units
0,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,1,0.000000
1,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,2,0.000000
2,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,3,0.000000
3,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,4,0.000000
4,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,6,0.000000
5,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,7,0.000000
6,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,8,0.000000
7,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,9,0.000000
8,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,10,0.000000
9,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,11,0.000000
10,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,12,0.000000
11,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,13,0.000000
12,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,14,0.000000
13,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,15,0.000000
14,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,17,0.000000
15,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,18,0.000000
16,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,19,0.000000
17,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,20,0.000000
18,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,21,0.000000
19,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,22,0.000000
20,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,23,0.000000
21,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,24,0.000000
22,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,25,0.000000
23,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,26,0.000000
24,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,27,0.000000
25,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,28,0.000000
26,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,29,0.000000
27,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,30,0.000000
28,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,31,0.000000
29,12,2012-01-01,72.0,48.0,60.0,NaN,54.0,57.0,5.0,0.0,...,NaN,6,1,1,1,0,0,5,32,0.693147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378150,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,82,0.000000
378151,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,83,0.000000
378152,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,84,0.000000
378153,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,85,0.000000
378154,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,86,0.000000
378155,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,87,0.000000
378156,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,88,0.000000
378157,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,89,0.000000
378158,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,90,0.000000
378159,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,91,0.000000
378160,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,92,0.000000
378161,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,93,0.000000
378162,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,94,0.693147
378163,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,95,0.000000
378164,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,96,0.000000
378165,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,97,0.000000
378166,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,98,0.000000
378167,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,99,0.000000
378168,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,100,0.000000
378169,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,101,0.000000
378170,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,102,0.000000
378171,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,103,0.000000
378172,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,104,0.000000
378173,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,105,0.000000
378174,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,106,0.000000
378175,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,107,0.000000
378176,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,108,0.000000
378177,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,109,0.000000
378178,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,110,0.000000
378179,12,2014-10-31,75.0,60.0,67.5,NaN,53.0,59.0,0.0,3.0,...,NaN,4,0,1,1,0,0,44,111,0.000000

In [19]:
# OLS - df2_1
model2_1 = sm.OLS.from_formula('log1p_units ~ scale(tmax) + scale(tmin) + scale(tavg) + scale(dewpoint) + scale(wetbulb) + scale(heat) + scale(cool)\
                           + scale(preciptotal) + scale(stnpressure) + scale(sealevel) + scale(resultspeed) \
                            + scale(avgspeed) + C(year) + C(month) + scale(relative_humility) + scale(windchill) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2_1)
result2_1 = model2_1.fit()
print(result2_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.618
Model:                            OLS   Adj. R-squared:                  0.618
Method:                 Least Squares   F-statistic:                     4335.
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:40:18   Log-Likelihood:             6.5121e+05
No. Observations:              378180   AIC:                        -1.302e+06
Df Residuals:                  378038   BIC:                        -1.301e+06
Df Model:                         141
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
C(year)[2012]                0.0018      0.001      2.200      0.028       0.000       0.003
C(year)[2013]                0.0008      0.001      1.040      0.298      -0.001       0.002
C(year)[2014]               -0.0007      0.001     -0.814      0.415      -0.002       0.001
C(month)[T.2]                0.0002      0.000      0.458      0.647      -0.001       0.001
C(month)[T.3]               -0.0003      0.000     -0.902      0.367      -0.001       0.000
C(month)[T.4]             1.745e-05      0.000      0.046      0.963      -0.001       0.001
C(month)[T.5]               -0.0004      0.000     -0.982      0.326      -0.001       0.000
C(month)[T.6]               -0.0005      0.000     -1.089      0.276      -0.002       0.000
C(month)[T.7]               -0.0003      0.001     -0.592      0.554      -0.001       0.001
C(month)[T.8]               -0.0002      0.001     -0.395      0.693      -0.001       0.001
C(month)[T.9]               -0.0009      0.001     -1.742      0.082      -0.002       0.000
C(month)[T.10]              -0.0013      0.000     -3.155      0.002      -0.002      -0.000
C(month)[T.11]              -0.0013      0.000     -3.450      0.001      -0.002      -0.001
C(month)[T.12]              -0.0010      0.000     -2.762      0.006      -0.002      -0.000
C(weekend)[T.1]           9.451e-06      0.000      0.060      0.952      -0.000       0.000
C(rainY)[T.1]                0.0003      0.000      1.578      0.115   -6.63e-05       0.001
C(store_nbr)[T.10]          -0.0010      0.000     -5.202      0.000      -0.001      -0.001
C(store_nbr)[T.41]          -0.0013      0.000     -6.340      0.000      -0.002      -0.001
C(store_nbr)[T.44]           0.0002      0.000      0.807      0.420      -0.000       0.001
C(item_nbr)[T.2]          9.886e-17      0.001   9.63e-14      1.000      -0.002       0.002
C(item_nbr)[T.3]         -6.364e-16      0.001   -6.2e-13      1.000      -0.002       0.002
C(item_nbr)[T.4]         -1.995e-16      0.001  -1.94e-13      1.000      -0.002       0.002
C(item_nbr)[T.5]             2.3133      0.006    407.359      0.000       2.302       2.324
C(item_nbr)[T.6]          1.573e-17      0.001   1.53e-14      1.000      -0.002       0.002
C(item_nbr)[T.7]          8.845e-16      0.001   8.62e-13      1.000      -0.002       0.002
C(item_nbr)[T.8]          3.281e-16      0.001    3.2e-13      1.000      -0.002       0.002
C(item_nbr)[T.9]         -1.024e-15      0.001  -9.98e-13      1.000      -0.002       0.002
C(item_nbr)[T.10]        -2.115e-17      0.001  -2.06e-14      1.000      -0.002       0.002
C(item_nbr)[T.11]         4.983e-15      0.001   4.85e-12      1.000      -0.002       0.002
C(item_nbr)[T.12]         8.393e-16      0.001   8.18e-13      1.000      -0.002       0.002
C(item_nbr)[T.13]          2.83e-17      0.001   2.76e-14      1.000      -0.002       0.002
C(item_nbr)[T.14]         6.047e-16      0.001   5.89e-13      1.000      -0.002       0.002
C(item_nbr)[T.15]         4.118e-16      0.001   4.01e-13      1.000      -0.002       0.002
C(item_nbr)[T.16]            2.0528      0.008    245.645      0.000       2.036       2.069
C(item_nbr)[T.17]          2.19e-17      0.001   2.13e-14      1.000      -0.002       0.002
C(item_nbr)[T.18]         1.331e-16      0.001    1.3e-13      1.000      -0.002       0.002
C(item_nbr)[T.19]        -7.974e-17      0.001  -7.77e-14      1.000      -0.002       0.002
C(item_nbr)[T.20]            0.0498      0.001     47.649      0.000       0.048       0.052
C(item_nbr)[T.21]            0.0462      0.001     44.352      0.000       0.044       0.048
C(item_nbr)[T.22]         4.769e-17      0.001   4.65e-14      1.000      -0.002       0.002
C(item_nbr)[T.23]         2.743e-17      0.001   2.67e-14      1.000      -0.002       0.002
C(item_nbr)[T.24]         2.705e-17      0.001   2.64e-14      1.000      -0.002       0.002
C(item_nbr)[T.25]        -1.805e-16      0.001  -1.76e-13      1.000      -0.002       0.002
C(item_nbr)[T.26]         8.319e-17      0.001   8.11e-14      1.000      -0.002       0.002
C(item_nbr)[T.27]         1.355e-18      0.001   1.32e-15      1.000      -0.002       0.002
C(item_nbr)[T.28]         7.671e-17      0.001   7.47e-14      1.000      -0.002       0.002
C(item_nbr)[T.29]         7.495e-17      0.001    7.3e-14      1.000      -0.002       0.002
C(item_nbr)[T.30]         4.893e-17      0.001   4.77e-14      1.000      -0.002       0.002
C(item_nbr)[T.31]         1.748e-18      0.001    1.7e-15      1.000      -0.002       0.002
C(item_nbr)[T.32]            0.0278      0.001     26.755      0.000       0.026       0.030
C(item_nbr)[T.33]         1.122e-16      0.001   1.09e-13      1.000      -0.002       0.002
C(item_nbr)[T.34]         9.229e-17      0.001   8.99e-14      1.000      -0.002       0.002
C(item_nbr)[T.35]        -8.873e-17      0.001  -8.65e-14      1.000      -0.002       0.002
C(item_nbr)[T.36]         5.159e-17      0.001   5.03e-14      1.000      -0.002       0.002
C(item_nbr)[T.37]            1.6939      0.004    480.019      0.000       1.687       1.701
C(item_nbr)[T.38]         6.321e-17      0.001   6.16e-14      1.000      -0.002       0.002
C(item_nbr)[T.39]         5.607e-17      0.001   5.46e-14      1.000      -0.002       0.002
C(item_nbr)[T.40]         6.449e-17      0.001   6.28e-14      1.000      -0.002       0.002
C(item_nbr)[T.41]         2.434e-17      0.001   2.37e-14      1.000      -0.002       0.002
C(item_nbr)[T.42]         8.635e-18      0.001   8.41e-15      1.000      -0.002       0.002
C(item_nbr)[T.43]         6.042e-17      0.001   5.89e-14      1.000      -0.002       0.002
C(item_nbr)[T.44]         7.038e-17      0.001   6.86e-14      1.000      -0.002       0.002
C(item_nbr)[T.45]        -6.375e-18      0.001  -6.21e-15      1.000      -0.002       0.002
C(item_nbr)[T.46]         4.603e-17      0.001   4.48e-14      1.000      -0.002       0.002
C(item_nbr)[T.47]         2.622e-17      0.001   2.55e-14      1.000      -0.002       0.002
C(item_nbr)[T.48]        -6.414e-18      0.001  -6.25e-15      1.000      -0.002       0.002
C(item_nbr)[T.49]         2.598e-17      0.001   2.53e-14      1.000      -0.002       0.002
C(item_nbr)[T.50]         2.988e-17      0.001   2.91e-14      1.000      -0.002       0.002
C(item_nbr)[T.51]        -4.968e-17      0.001  -4.84e-14      1.000      -0.002       0.002
C(item_nbr)[T.52]         4.115e-17      0.001   4.01e-14      1.000      -0.002       0.002
C(item_nbr)[T.53]         3.154e-17      0.001   3.07e-14      1.000      -0.002       0.002
C(item_nbr)[T.54]        -3.062e-17      0.001  -2.98e-14      1.000      -0.002       0.002
C(item_nbr)[T.55]         6.323e-17      0.001   6.16e-14      1.000      -0.002       0.002
C(item_nbr)[T.56]         5.944e-17      0.001   5.79e-14      1.000      -0.002       0.002
C(item_nbr)[T.57]         5.551e-17      0.001   5.41e-14      1.000      -0.002       0.002
C(item_nbr)[T.58]         1.689e-16      0.001   1.65e-13      1.000      -0.002       0.002
C(item_nbr)[T.59]         5.404e-17      0.001   5.27e-14      1.000      -0.002       0.002
C(item_nbr)[T.60]         1.729e-18      0.001   1.68e-15      1.000      -0.002       0.002
C(item_nbr)[T.61]            0.0282      0.001     27.040      0.000       0.026       0.030
C(item_nbr)[T.62]            0.0319      0.001     30.749      0.000       0.030       0.034
C(item_nbr)[T.63]         1.206e-16      0.001   1.17e-13      1.000      -0.002       0.002
C(item_nbr)[T.64]         7.023e-17      0.001   6.84e-14      1.000      -0.002       0.002
C(item_nbr)[T.65]         1.135e-16      0.001   1.11e-13      1.000      -0.002       0.002
C(item_nbr)[T.66]         1.558e-18      0.001   1.52e-15      1.000      -0.002       0.002
C(item_nbr)[T.67]         1.122e-17      0.001   1.09e-14      1.000      -0.002       0.002
C(item_nbr)[T.68]            2.2899      0.007    348.937      0.000       2.277       2.303
C(item_nbr)[T.69]         3.513e-17      0.001   3.42e-14      1.000      -0.002       0.002
C(item_nbr)[T.70]         7.779e-17      0.001   7.58e-14      1.000      -0.002       0.002
C(item_nbr)[T.71]         8.451e-18      0.001   8.23e-15      1.000      -0.002       0.002
C(item_nbr)[T.72]         5.469e-17      0.001   5.33e-14      1.000      -0.002       0.002
C(item_nbr)[T.73]         5.689e-17      0.001   5.54e-14      1.000      -0.002       0.002
C(item_nbr)[T.74]         3.885e-17      0.001   3.79e-14      1.000      -0.002       0.002
C(item_nbr)[T.75]        -6.674e-18      0.001   -6.5e-15      1.000      -0.002       0.002
C(item_nbr)[T.76]         7.288e-17      0.001    7.1e-14      1.000      -0.002       0.002
C(item_nbr)[T.77]         4.398e-17      0.001   4.29e-14      1.000      -0.002       0.002
C(item_nbr)[T.78]        -1.466e-17      0.001  -1.43e-14      1.000      -0.002       0.002
C(item_nbr)[T.79]         3.863e-17      0.001   3.76e-14      1.000      -0.002       0.002
C(item_nbr)[T.80]         4.972e-17      0.001   4.84e-14      1.000      -0.002       0.002
C(item_nbr)[T.81]         9.393e-17      0.001   9.15e-14      1.000      -0.002       0.002
C(item_nbr)[T.82]         5.099e-17      0.001   4.97e-14      1.000      -0.002       0.002
C(item_nbr)[T.83]         6.739e-17      0.001   6.57e-14      1.000      -0.002       0.002
C(item_nbr)[T.84]          2.48e-17      0.001   2.42e-14      1.000      -0.002       0.002
C(item_nbr)[T.85]         4.836e-17      0.001   4.71e-14      1.000      -0.002       0.002
C(item_nbr)[T.86]            0.0151      0.001     14.637      0.000       0.013       0.017
C(item_nbr)[T.87]          6.82e-17      0.001   6.65e-14      1.000      -0.002       0.002
C(item_nbr)[T.88]         1.186e-16      0.001   1.16e-13      1.000      -0.002       0.002
C(item_nbr)[T.89]         3.538e-17      0.001   3.45e-14      1.000      -0.002       0.002
C(item_nbr)[T.90]         2.574e-17      0.001   2.51e-14      1.000      -0.002       0.002
C(item_nbr)[T.91]         7.336e-17      0.001   7.15e-14      1.000      -0.002       0.002
C(item_nbr)[T.92]         7.459e-17      0.001   7.27e-14      1.000      -0.002       0.002
C(item_nbr)[T.93]            0.0491      0.001     45.424      0.000       0.047       0.051
C(item_nbr)[T.94]            0.0438      0.001     42.008      0.000       0.042       0.046
C(item_nbr)[T.95]         2.617e-17      0.001   2.55e-14      1.000      -0.002       0.002
C(item_nbr)[T.96]         6.314e-17      0.001   6.15e-14      1.000      -0.002       0.002
C(item_nbr)[T.97]          3.17e-17      0.001   3.09e-14      1.000      -0.002       0.002
C(item_nbr)[T.98]          3.51e-17      0.001   3.42e-14      1.000      -0.002       0.002
C(item_nbr)[T.99]         1.274e-16      0.001   1.24e-13      1.000      -0.002       0.002
C(item_nbr)[T.100]        3.521e-17      0.001   3.43e-14      1.000      -0.002       0.002
C(item_nbr)[T.101]        1.039e-16      0.001   1.01e-13      1.000      -0.002       0.002
C(item_nbr)[T.102]        1.388e-16      0.001   1.35e-13      1.000      -0.002       0.002
C(item_nbr)[T.103]        1.183e-16      0.001   1.15e-13      1.000      -0.002       0.002
C(item_nbr)[T.104]        3.103e-18      0.001   3.02e-15      1.000      -0.002       0.002
C(item_nbr)[T.105]           0.0095      0.001      9.224      0.000       0.007       0.012
C(item_nbr)[T.106]        3.961e-17      0.001   3.86e-14      1.000      -0.002       0.002
C(item_nbr)[T.107]         7.97e-17      0.001   7.77e-14      1.000      -0.002       0.002
C(item_nbr)[T.108]           0.0041      0.001      3.874      0.000       0.002       0.006
C(item_nbr)[T.109]       -1.541e-16      0.001   -1.5e-13      1.000      -0.002       0.002
C(item_nbr)[T.110]        2.184e-16      0.001   2.13e-13      1.000      -0.002       0.002
C(item_nbr)[T.111]       -9.066e-17      0.001  -8.83e-14      1.000      -0.002       0.002
scale(tmax)                 -0.0004      0.001     -0.373      0.709      -0.002       0.002
scale(tmin)                 -0.0002      0.001     -0.196      0.844      -0.002       0.002
scale(tavg)                 -0.0003      0.001     -0.281      0.779      -0.002       0.002
scale(dewpoint)              0.0040      0.002      2.154      0.031       0.000       0.008
scale(wetbulb)               0.0006      0.001      0.553      0.581      -0.002       0.003
scale(heat)                  0.0004      0.001      0.790      0.430      -0.001       0.002
scale(cool)                 -0.0004      0.001     -0.516      0.606      -0.002       0.001
scale(preciptotal)          -0.0002   7.83e-05     -2.192      0.028      -0.000   -1.82e-05
scale(stnpressure)           0.0005      0.001      0.695      0.487      -0.001       0.002
scale(sealevel)             -0.0006      0.001     -0.805      0.421      -0.002       0.001
scale(resultspeed)           0.0003      0.000      1.146      0.252      -0.000       0.001
scale(avgspeed)             -0.0004      0.000     -1.549      0.121      -0.001       0.000
scale(relative_humility)    -0.0017      0.001     -2.240      0.025      -0.003      -0.000
scale(windchill)            -0.0023      0.002     -1.064      0.288      -0.007       0.002
==============================================================================
Omnibus:                   706353.795   Durbin-Watson:                   2.026
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        997440667.313
Skew:                          14.435   Prob(JB):                         0.00
Kurtosis:                     252.932   Cond. No.                     2.27e+15
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.9e-25. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [20]:
ls1

['depart', 'sunrise', 'sunset', 'snowfall', 'resultdir', 'daytime']

### 3. VIF 확인

In [21]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
cols = ['tmax','tmin','tavg','dewpoint','wetbulb','heat','cool','preciptotal',\
        'stnpressure','sealevel','resultspeed','avgspeed','relative_humility',\
        'windchill']

y = df2_1.loc[:,cols]
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(y.values, i) for i in range(y.shape[1])]
vif["features"] = y.columns
vif

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\stats\outliers_influence.py:167: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)

      VIF Factor           features
0            inf               tmax
1            inf               tmin
2            inf               tavg
3   1.409909e+04           dewpoint
4   9.187217e+03            wetbulb
5   6.732456e+01               heat
6   2.587522e+02               cool
7   1.208382e+00        preciptotal
8   5.608215e+06        stnpressure
9   5.638878e+06           sealevel
10  3.999506e+01        resultspeed
11  7.678050e+01           avgspeed
12  3.781095e+03  relative_humility
13  2.795207e+04          windchill

### 4. VIF 근거, tmax, tmin, tavg 빼고 다시 Model 돌림.

In [22]:
# OLS - df2_1
model2_1 = sm.OLS.from_formula('log1p_units ~ scale(dewpoint) + scale(wetbulb) + scale(heat) + scale(cool)\
                           + scale(preciptotal) + scale(stnpressure) + scale(sealevel) + scale(resultspeed) \
                            + scale(avgspeed) + C(year) + C(month) + scale(relative_humility) + scale(windchill) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2_1)
result2_1 = model2_1.fit()
print(result2_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.618
Model:                            OLS   Adj. R-squared:                  0.618
Method:                 Least Squares   F-statistic:                     4397.
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:45:57   Log-Likelihood:             6.5121e+05
No. Observations:              378180   AIC:                        -1.302e+06
Df Residuals:                  378040   BIC:                        -1.301e+06
Df Model:                         139
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
C(year)[2012]                0.0017      0.001      2.162      0.031       0.000       0.003
C(year)[2013]                0.0008      0.001      1.008      0.314      -0.001       0.002
C(year)[2014]               -0.0007      0.001     -0.861      0.389      -0.002       0.001
C(month)[T.2]                0.0002      0.000      0.542      0.588      -0.000       0.001
C(month)[T.3]               -0.0003      0.000     -0.871      0.384      -0.001       0.000
C(month)[T.4]             4.769e-05      0.000      0.127      0.899      -0.001       0.001
C(month)[T.5]               -0.0004      0.000     -0.906      0.365      -0.001       0.000
C(month)[T.6]               -0.0005      0.000     -0.997      0.319      -0.001       0.000
C(month)[T.7]               -0.0003      0.001     -0.507      0.612      -0.001       0.001
C(month)[T.8]               -0.0001      0.001     -0.288      0.773      -0.001       0.001
C(month)[T.9]               -0.0008      0.000     -1.665      0.096      -0.002       0.000
C(month)[T.10]              -0.0012      0.000     -3.114      0.002      -0.002      -0.000
C(month)[T.11]              -0.0013      0.000     -3.415      0.001      -0.002      -0.001
C(month)[T.12]              -0.0010      0.000     -2.737      0.006      -0.002      -0.000
C(weekend)[T.1]           1.695e-05      0.000      0.108      0.914      -0.000       0.000
C(rainY)[T.1]                0.0003      0.000      1.555      0.120   -7.01e-05       0.001
C(store_nbr)[T.10]          -0.0010      0.000     -5.202      0.000      -0.001      -0.001
C(store_nbr)[T.41]          -0.0013      0.000     -6.340      0.000      -0.002      -0.001
C(store_nbr)[T.44]           0.0002      0.000      0.807      0.420      -0.000       0.001
C(item_nbr)[T.2]          -1.25e-15      0.001  -1.22e-12      1.000      -0.002       0.002
C(item_nbr)[T.3]          8.629e-16      0.001   8.41e-13      1.000      -0.002       0.002
C(item_nbr)[T.4]         -1.505e-15      0.001  -1.47e-12      1.000      -0.002       0.002
C(item_nbr)[T.5]             2.3133      0.006    407.360      0.000       2.302       2.324
C(item_nbr)[T.6]          5.737e-16      0.001   5.59e-13      1.000      -0.002       0.002
C(item_nbr)[T.7]         -1.292e-15      0.001  -1.26e-12      1.000      -0.002       0.002
C(item_nbr)[T.8]             -6e-16      0.001  -5.85e-13      1.000      -0.002       0.002
C(item_nbr)[T.9]          1.556e-16      0.001   1.52e-13      1.000      -0.002       0.002
C(item_nbr)[T.10]        -1.309e-15      0.001  -1.28e-12      1.000      -0.002       0.002
C(item_nbr)[T.11]        -4.268e-15      0.001  -4.16e-12      1.000      -0.002       0.002
C(item_nbr)[T.12]        -3.272e-16      0.001  -3.19e-13      1.000      -0.002       0.002
C(item_nbr)[T.13]        -7.557e-16      0.001  -7.36e-13      1.000      -0.002       0.002
C(item_nbr)[T.14]         2.252e-16      0.001   2.19e-13      1.000      -0.002       0.002
C(item_nbr)[T.15]        -6.467e-16      0.001   -6.3e-13      1.000      -0.002       0.002
C(item_nbr)[T.16]            2.0528      0.008    245.645      0.000       2.036       2.069
C(item_nbr)[T.17]        -4.552e-16      0.001  -4.44e-13      1.000      -0.002       0.002
C(item_nbr)[T.18]        -9.468e-16      0.001  -9.22e-13      1.000      -0.002       0.002
C(item_nbr)[T.19]         -3.97e-16      0.001  -3.87e-13      1.000      -0.002       0.002
C(item_nbr)[T.20]            0.0498      0.001     47.650      0.000       0.048       0.052
C(item_nbr)[T.21]            0.0462      0.001     44.352      0.000       0.044       0.048
C(item_nbr)[T.22]        -3.202e-16      0.001  -3.12e-13      1.000      -0.002       0.002
C(item_nbr)[T.23]        -6.397e-16      0.001  -6.23e-13      1.000      -0.002       0.002
C(item_nbr)[T.24]         -5.99e-16      0.001  -5.84e-13      1.000      -0.002       0.002
C(item_nbr)[T.25]        -5.194e-16      0.001  -5.06e-13      1.000      -0.002       0.002
C(item_nbr)[T.26]         -6.65e-16      0.001  -6.48e-13      1.000      -0.002       0.002
C(item_nbr)[T.27]        -6.191e-16      0.001  -6.03e-13      1.000      -0.002       0.002
C(item_nbr)[T.28]         -6.57e-16      0.001   -6.4e-13      1.000      -0.002       0.002
C(item_nbr)[T.29]        -6.272e-16      0.001  -6.11e-13      1.000      -0.002       0.002
C(item_nbr)[T.30]        -5.779e-16      0.001  -5.63e-13      1.000      -0.002       0.002
C(item_nbr)[T.31]        -5.946e-16      0.001  -5.79e-13      1.000      -0.002       0.002
C(item_nbr)[T.32]            0.0278      0.001     26.754      0.000       0.026       0.030
C(item_nbr)[T.33]        -6.655e-16      0.001  -6.48e-13      1.000      -0.002       0.002
C(item_nbr)[T.34]         -6.41e-16      0.001  -6.25e-13      1.000      -0.002       0.002
C(item_nbr)[T.35]        -6.448e-16      0.001  -6.28e-13      1.000      -0.002       0.002
C(item_nbr)[T.36]        -6.145e-16      0.001  -5.99e-13      1.000      -0.002       0.002
C(item_nbr)[T.37]            1.6939      0.004    480.020      0.000       1.687       1.701
C(item_nbr)[T.38]        -5.429e-16      0.001  -5.29e-13      1.000      -0.002       0.002
C(item_nbr)[T.39]        -6.546e-16      0.001  -6.38e-13      1.000      -0.002       0.002
C(item_nbr)[T.40]        -6.247e-16      0.001  -6.09e-13      1.000      -0.002       0.002
C(item_nbr)[T.41]        -4.847e-16      0.001  -4.72e-13      1.000      -0.002       0.002
C(item_nbr)[T.42]         -5.33e-16      0.001  -5.19e-13      1.000      -0.002       0.002
C(item_nbr)[T.43]        -5.484e-16      0.001  -5.34e-13      1.000      -0.002       0.002
C(item_nbr)[T.44]        -5.381e-16      0.001  -5.24e-13      1.000      -0.002       0.002
C(item_nbr)[T.45]        -6.149e-16      0.001  -5.99e-13      1.000      -0.002       0.002
C(item_nbr)[T.46]        -6.246e-16      0.001  -6.09e-13      1.000      -0.002       0.002
C(item_nbr)[T.47]        -5.906e-16      0.001  -5.75e-13      1.000      -0.002       0.002
C(item_nbr)[T.48]        -6.442e-16      0.001  -6.28e-13      1.000      -0.002       0.002
C(item_nbr)[T.49]        -5.476e-16      0.001  -5.34e-13      1.000      -0.002       0.002
C(item_nbr)[T.50]        -6.051e-16      0.001   -5.9e-13      1.000      -0.002       0.002
C(item_nbr)[T.51]        -5.775e-16      0.001  -5.63e-13      1.000      -0.002       0.002
C(item_nbr)[T.52]        -5.619e-16      0.001  -5.47e-13      1.000      -0.002       0.002
C(item_nbr)[T.53]         -5.62e-16      0.001  -5.48e-13      1.000      -0.002       0.002
C(item_nbr)[T.54]        -6.613e-16      0.001  -6.44e-13      1.000      -0.002       0.002
C(item_nbr)[T.55]        -5.502e-16      0.001  -5.36e-13      1.000      -0.002       0.002
C(item_nbr)[T.56]        -5.955e-16      0.001   -5.8e-13      1.000      -0.002       0.002
C(item_nbr)[T.57]        -6.073e-16      0.001  -5.92e-13      1.000      -0.002       0.002
C(item_nbr)[T.58]        -3.931e-16      0.001  -3.83e-13      1.000      -0.002       0.002
C(item_nbr)[T.59]        -6.222e-16      0.001  -6.06e-13      1.000      -0.002       0.002
C(item_nbr)[T.60]        -6.336e-16      0.001  -6.17e-13      1.000      -0.002       0.002
C(item_nbr)[T.61]            0.0282      0.001     27.039      0.000       0.026       0.030
C(item_nbr)[T.62]            0.0319      0.001     30.749      0.000       0.030       0.034
C(item_nbr)[T.63]        -5.394e-16      0.001  -5.26e-13      1.000      -0.002       0.002
C(item_nbr)[T.64]         -5.73e-16      0.001  -5.58e-13      1.000      -0.002       0.002
C(item_nbr)[T.65]        -5.598e-16      0.001  -5.45e-13      1.000      -0.002       0.002
C(item_nbr)[T.66]         -5.79e-16      0.001  -5.64e-13      1.000      -0.002       0.002
C(item_nbr)[T.67]        -6.509e-16      0.001  -6.34e-13      1.000      -0.002       0.002
C(item_nbr)[T.68]            2.2900      0.007    348.939      0.000       2.277       2.303
C(item_nbr)[T.69]        -5.648e-16      0.001   -5.5e-13      1.000      -0.002       0.002
C(item_nbr)[T.70]        -5.622e-16      0.001  -5.48e-13      1.000      -0.002       0.002
C(item_nbr)[T.71]        -6.011e-16      0.001  -5.86e-13      1.000      -0.002       0.002
C(item_nbr)[T.72]        -6.029e-16      0.001  -5.87e-13      1.000      -0.002       0.002
C(item_nbr)[T.73]        -5.628e-16      0.001  -5.48e-13      1.000      -0.002       0.002
C(item_nbr)[T.74]        -5.546e-16      0.001   -5.4e-13      1.000      -0.002       0.002
C(item_nbr)[T.75]        -5.512e-16      0.001  -5.37e-13      1.000      -0.002       0.002
C(item_nbr)[T.76]        -5.795e-16      0.001  -5.65e-13      1.000      -0.002       0.002
C(item_nbr)[T.77]        -5.666e-16      0.001  -5.52e-13      1.000      -0.002       0.002
C(item_nbr)[T.78]        -5.771e-16      0.001  -5.62e-13      1.000      -0.002       0.002
C(item_nbr)[T.79]        -5.977e-16      0.001  -5.82e-13      1.000      -0.002       0.002
C(item_nbr)[T.80]        -5.675e-16      0.001  -5.53e-13      1.000      -0.002       0.002
C(item_nbr)[T.81]        -6.167e-16      0.001  -6.01e-13      1.000      -0.002       0.002
C(item_nbr)[T.82]        -5.456e-16      0.001  -5.32e-13      1.000      -0.002       0.002
C(item_nbr)[T.83]        -5.371e-16      0.001  -5.23e-13      1.000      -0.002       0.002
C(item_nbr)[T.84]        -5.837e-16      0.001  -5.69e-13      1.000      -0.002       0.002
C(item_nbr)[T.85]        -6.165e-16      0.001  -6.01e-13      1.000      -0.002       0.002
C(item_nbr)[T.86]            0.0151      0.001     14.637      0.000       0.013       0.017
C(item_nbr)[T.87]        -6.271e-16      0.001  -6.11e-13      1.000      -0.002       0.002
C(item_nbr)[T.88]        -5.917e-16      0.001  -5.76e-13      1.000      -0.002       0.002
C(item_nbr)[T.89]        -6.318e-16      0.001  -6.16e-13      1.000      -0.002       0.002
C(item_nbr)[T.90]         -6.46e-16      0.001  -6.29e-13      1.000      -0.002       0.002
C(item_nbr)[T.91]        -5.253e-16      0.001  -5.12e-13      1.000      -0.002       0.002
C(item_nbr)[T.92]         -6.83e-16      0.001  -6.65e-13      1.000      -0.002       0.002
C(item_nbr)[T.93]            0.0491      0.001     45.423      0.000       0.047       0.051
C(item_nbr)[T.94]            0.0438      0.001     42.008      0.000       0.042       0.046
C(item_nbr)[T.95]        -6.308e-16      0.001  -6.15e-13      1.000      -0.002       0.002
C(item_nbr)[T.96]        -6.365e-16      0.001   -6.2e-13      1.000      -0.002       0.002
C(item_nbr)[T.97]         -5.16e-16      0.001  -5.03e-13      1.000      -0.002       0.002
C(item_nbr)[T.98]        -6.039e-16      0.001  -5.88e-13      1.000      -0.002       0.002
C(item_nbr)[T.99]        -6.307e-16      0.001  -6.15e-13      1.000      -0.002       0.002
C(item_nbr)[T.100]       -6.086e-16      0.001  -5.93e-13      1.000      -0.002       0.002
C(item_nbr)[T.101]       -6.514e-16      0.001  -6.35e-13      1.000      -0.002       0.002
C(item_nbr)[T.102]       -5.612e-16      0.001  -5.47e-13      1.000      -0.002       0.002
C(item_nbr)[T.103]       -5.851e-16      0.001   -5.7e-13      1.000      -0.002       0.002
C(item_nbr)[T.104]       -7.247e-16      0.001  -7.06e-13      1.000      -0.002       0.002
C(item_nbr)[T.105]           0.0095      0.001      9.224      0.000       0.007       0.012
C(item_nbr)[T.106]       -6.444e-16      0.001  -6.28e-13      1.000      -0.002       0.002
C(item_nbr)[T.107]        -6.86e-16      0.001  -6.68e-13      1.000      -0.002       0.002
C(item_nbr)[T.108]           0.0041      0.001      3.874      0.000       0.002       0.006
C(item_nbr)[T.109]       -7.219e-16      0.001  -7.03e-13      1.000      -0.002       0.002
C(item_nbr)[T.110]       -4.506e-16      0.001  -4.39e-13      1.000      -0.002       0.002
C(item_nbr)[T.111]       -7.845e-16      0.001  -7.64e-13      1.000      -0.002       0.002
scale(dewpoint)              0.0037      0.002      2.170      0.030       0.000       0.007
scale(wetbulb)               0.0005      0.001      0.446      0.656      -0.002       0.003
scale(heat)                  0.0005      0.001      0.910      0.363      -0.001       0.001
scale(cool)                 -0.0004      0.001     -0.605      0.545      -0.002       0.001
scale(preciptotal)          -0.0002   7.82e-05     -2.169      0.030      -0.000   -1.64e-05
scale(stnpressure)           0.0005      0.001      0.672      0.502      -0.001       0.002
scale(sealevel)             -0.0006      0.001     -0.780      0.435      -0.002       0.001
scale(resultspeed)           0.0003      0.000      1.276      0.202      -0.000       0.001
scale(avgspeed)             -0.0004      0.000     -1.750      0.080      -0.001     5.3e-05
scale(relative_humility)    -0.0015      0.001     -2.360      0.018      -0.003      -0.000
scale(windchill)            -0.0027      0.002     -1.730      0.084      -0.006       0.000
==============================================================================
Omnibus:                   706354.125   Durbin-Watson:                   2.026
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        997445731.038
Skew:                          14.435   Prob(JB):                         0.00
Kurtosis:                     252.933   Cond. No.                         279.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### 5. VIF 재확인 (tmax, tmin, tavg 제외함)

In [23]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
# all_cols = ['tmax','tmin','tavg','dewpoint','wetbulb','heat','cool','preciptotal',\
#         'stnpressure','sealevel','resultspeed','avgspeed','relative_humility',\
#         'windchill', 'depart', 'sunrise', 'sunset', 'snowfall' ]
cols = ['dewpoint','wetbulb','heat','cool','preciptotal',\
        'stnpressure','sealevel','resultspeed','avgspeed','relative_humility',\
        'windchill']

y = df2_1.loc[:,cols]
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(y.values, i) for i in range(y.shape[1])]
vif["features"] = y.columns
vif = vif.sort_values("VIF Factor", ascending=False).reset_index(drop=True)
vif

      VIF Factor           features
0   5.415995e+06        stnpressure
1   5.401734e+06           sealevel
2   1.290266e+04          windchill
3   1.242529e+04           dewpoint
4   8.019518e+03            wetbulb
5   2.919795e+03  relative_humility
6   2.203728e+02               cool
7   6.046898e+01           avgspeed
8   5.925402e+01               heat
9   3.713330e+01        resultspeed
10  1.204168e+00        preciptotal

### 6. VIF 근거, stnpressure, sealevel, dewpoint, windchill, wetbulb, relative_humility, cool 제외하고  Model 돌림.

In [24]:
# OLS - df2_1
model2_1 = sm.OLS.from_formula('log1p_units ~ scale(heat)\
                           + scale(preciptotal) + scale(resultspeed) \
                            + scale(avgspeed) + C(year) + C(month) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2_1)
result2_1 = model2_1.fit()
print(result2_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.618
Model:                            OLS   Adj. R-squared:                  0.618
Method:                 Least Squares   F-statistic:                     4630.
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:53:48   Log-Likelihood:             6.5120e+05
No. Observations:              378180   AIC:                        -1.302e+06
Df Residuals:                  378047   BIC:                        -1.301e+06
Df Model:                         132
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
C(year)[2012]          0.0015      0.001      1.951      0.051   -7.34e-06       0.003
C(year)[2013]          0.0006      0.001      0.822      0.411      -0.001       0.002
C(year)[2014]         -0.0009      0.001     -1.111      0.266      -0.002       0.001
C(month)[T.2]          0.0002      0.000      0.629      0.529      -0.000       0.001
C(month)[T.3]         -0.0002      0.000     -0.628      0.530      -0.001       0.000
C(month)[T.4]          0.0002      0.000      0.602      0.547      -0.000       0.001
C(month)[T.5]         -0.0001      0.000     -0.380      0.704      -0.001       0.001
C(month)[T.6]         -0.0001      0.000     -0.364      0.716      -0.001       0.001
C(month)[T.7]          0.0001      0.000      0.310      0.756      -0.001       0.001
C(month)[T.8]          0.0003      0.000      0.741      0.459      -0.000       0.001
C(month)[T.9]         -0.0004      0.000     -1.088      0.277      -0.001       0.000
C(month)[T.10]        -0.0010      0.000     -2.758      0.006      -0.002      -0.000
C(month)[T.11]        -0.0013      0.000     -3.404      0.001      -0.002      -0.001
C(month)[T.12]        -0.0011      0.000     -2.934      0.003      -0.002      -0.000
C(weekend)[T.1]     1.912e-05      0.000      0.122      0.903      -0.000       0.000
C(rainY)[T.1]          0.0003      0.000      1.706      0.088   -3.87e-05       0.001
C(store_nbr)[T.10]    -0.0010      0.000     -5.202      0.000      -0.001      -0.001
C(store_nbr)[T.41]    -0.0013      0.000     -6.340      0.000      -0.002      -0.001
C(store_nbr)[T.44]     0.0002      0.000      0.808      0.419      -0.000       0.001
C(item_nbr)[T.2]    7.848e-17      0.001   7.65e-14      1.000      -0.002       0.002
C(item_nbr)[T.3]   -6.732e-16      0.001  -6.56e-13      1.000      -0.002       0.002
C(item_nbr)[T.4]    1.061e-15      0.001   1.03e-12      1.000      -0.002       0.002
C(item_nbr)[T.5]       2.3133      0.006    407.362      0.000       2.302       2.324
C(item_nbr)[T.6]    7.511e-16      0.001   7.32e-13      1.000      -0.002       0.002
C(item_nbr)[T.7]    4.353e-16      0.001   4.24e-13      1.000      -0.002       0.002
C(item_nbr)[T.8]    2.728e-16      0.001   2.66e-13      1.000      -0.002       0.002
C(item_nbr)[T.9]   -1.985e-16      0.001  -1.93e-13      1.000      -0.002       0.002
C(item_nbr)[T.10]   1.721e-16      0.001   1.68e-13      1.000      -0.002       0.002
C(item_nbr)[T.11]  -9.248e-17      0.001  -9.01e-14      1.000      -0.002       0.002
C(item_nbr)[T.12]   5.425e-16      0.001   5.29e-13      1.000      -0.002       0.002
C(item_nbr)[T.13]   4.766e-17      0.001   4.64e-14      1.000      -0.002       0.002
C(item_nbr)[T.14]    1.05e-16      0.001   1.02e-13      1.000      -0.002       0.002
C(item_nbr)[T.15]  -3.514e-16      0.001  -3.42e-13      1.000      -0.002       0.002
C(item_nbr)[T.16]      2.0529      0.008    245.659      0.000       2.036       2.069
C(item_nbr)[T.17]  -1.096e-16      0.001  -1.07e-13      1.000      -0.002       0.002
C(item_nbr)[T.18]  -7.985e-17      0.001  -7.78e-14      1.000      -0.002       0.002
C(item_nbr)[T.19]  -1.023e-16      0.001  -9.97e-14      1.000      -0.002       0.002
C(item_nbr)[T.20]      0.0498      0.001     47.648      0.000       0.048       0.052
C(item_nbr)[T.21]      0.0462      0.001     44.353      0.000       0.044       0.048
C(item_nbr)[T.22]  -8.903e-17      0.001  -8.67e-14      1.000      -0.002       0.002
C(item_nbr)[T.23]  -3.013e-18      0.001  -2.94e-15      1.000      -0.002       0.002
C(item_nbr)[T.24]  -6.147e-17      0.001  -5.99e-14      1.000      -0.002       0.002
C(item_nbr)[T.25]  -5.006e-17      0.001  -4.88e-14      1.000      -0.002       0.002
C(item_nbr)[T.26]   -6.55e-17      0.001  -6.38e-14      1.000      -0.002       0.002
C(item_nbr)[T.27]   -4.92e-17      0.001  -4.79e-14      1.000      -0.002       0.002
C(item_nbr)[T.28]  -5.436e-18      0.001   -5.3e-15      1.000      -0.002       0.002
C(item_nbr)[T.29]  -4.206e-17      0.001   -4.1e-14      1.000      -0.002       0.002
C(item_nbr)[T.30]  -4.606e-17      0.001  -4.49e-14      1.000      -0.002       0.002
C(item_nbr)[T.31]  -6.645e-17      0.001  -6.47e-14      1.000      -0.002       0.002
C(item_nbr)[T.32]      0.0278      0.001     26.755      0.000       0.026       0.030
C(item_nbr)[T.33]  -1.348e-16      0.001  -1.31e-13      1.000      -0.002       0.002
C(item_nbr)[T.34]  -1.036e-16      0.001  -1.01e-13      1.000      -0.002       0.002
C(item_nbr)[T.35]  -1.308e-16      0.001  -1.27e-13      1.000      -0.002       0.002
C(item_nbr)[T.36]   2.842e-17      0.001   2.77e-14      1.000      -0.002       0.002
C(item_nbr)[T.37]      1.6939      0.004    480.024      0.000       1.687       1.701
C(item_nbr)[T.38]    1.23e-18      0.001    1.2e-15      1.000      -0.002       0.002
C(item_nbr)[T.39]    3.42e-17      0.001   3.33e-14      1.000      -0.002       0.002
C(item_nbr)[T.40]  -6.029e-17      0.001  -5.87e-14      1.000      -0.002       0.002
C(item_nbr)[T.41]  -6.605e-17      0.001  -6.44e-14      1.000      -0.002       0.002
C(item_nbr)[T.42]   5.087e-17      0.001   4.96e-14      1.000      -0.002       0.002
C(item_nbr)[T.43]   -2.81e-17      0.001  -2.74e-14      1.000      -0.002       0.002
C(item_nbr)[T.44]  -2.696e-17      0.001  -2.63e-14      1.000      -0.002       0.002
C(item_nbr)[T.45]  -2.808e-17      0.001  -2.74e-14      1.000      -0.002       0.002
C(item_nbr)[T.46]  -4.723e-17      0.001   -4.6e-14      1.000      -0.002       0.002
C(item_nbr)[T.47]  -9.625e-17      0.001  -9.38e-14      1.000      -0.002       0.002
C(item_nbr)[T.48]   1.243e-18      0.001   1.21e-15      1.000      -0.002       0.002
C(item_nbr)[T.49]  -7.391e-17      0.001   -7.2e-14      1.000      -0.002       0.002
C(item_nbr)[T.50]   6.769e-18      0.001    6.6e-15      1.000      -0.002       0.002
C(item_nbr)[T.51]   2.776e-18      0.001   2.71e-15      1.000      -0.002       0.002
C(item_nbr)[T.52]  -6.652e-17      0.001  -6.48e-14      1.000      -0.002       0.002
C(item_nbr)[T.53]  -3.196e-17      0.001  -3.11e-14      1.000      -0.002       0.002
C(item_nbr)[T.54]  -5.672e-17      0.001  -5.53e-14      1.000      -0.002       0.002
C(item_nbr)[T.55]  -4.999e-17      0.001  -4.87e-14      1.000      -0.002       0.002
C(item_nbr)[T.56]   7.312e-17      0.001   7.12e-14      1.000      -0.002       0.002
C(item_nbr)[T.57]  -6.175e-17      0.001  -6.02e-14      1.000      -0.002       0.002
C(item_nbr)[T.58]   2.666e-17      0.001    2.6e-14      1.000      -0.002       0.002
C(item_nbr)[T.59]  -3.574e-17      0.001  -3.48e-14      1.000      -0.002       0.002
C(item_nbr)[T.60]  -4.705e-17      0.001  -4.58e-14      1.000      -0.002       0.002
C(item_nbr)[T.61]      0.0282      0.001     27.040      0.000       0.026       0.030
C(item_nbr)[T.62]      0.0319      0.001     30.750      0.000       0.030       0.034
C(item_nbr)[T.63]   6.206e-18      0.001   6.05e-15      1.000      -0.002       0.002
C(item_nbr)[T.64]   -1.24e-16      0.001  -1.21e-13      1.000      -0.002       0.002
C(item_nbr)[T.65]  -6.657e-17      0.001  -6.49e-14      1.000      -0.002       0.002
C(item_nbr)[T.66]  -6.592e-17      0.001  -6.42e-14      1.000      -0.002       0.002
C(item_nbr)[T.67]  -5.581e-18      0.001  -5.44e-15      1.000      -0.002       0.002
C(item_nbr)[T.68]      2.2899      0.007    348.938      0.000       2.277       2.303
C(item_nbr)[T.69]  -5.299e-17      0.001  -5.16e-14      1.000      -0.002       0.002
C(item_nbr)[T.70]   4.004e-17      0.001    3.9e-14      1.000      -0.002       0.002
C(item_nbr)[T.71]  -1.177e-17      0.001  -1.15e-14      1.000      -0.002       0.002
C(item_nbr)[T.72]  -1.528e-17      0.001  -1.49e-14      1.000      -0.002       0.002
C(item_nbr)[T.73]  -6.159e-17      0.001     -6e-14      1.000      -0.002       0.002
C(item_nbr)[T.74]   1.974e-17      0.001   1.92e-14      1.000      -0.002       0.002
C(item_nbr)[T.75]  -6.347e-17      0.001  -6.18e-14      1.000      -0.002       0.002
C(item_nbr)[T.76]  -6.612e-17      0.001  -6.44e-14      1.000      -0.002       0.002
C(item_nbr)[T.77]  -1.027e-16      0.001     -1e-13      1.000      -0.002       0.002
C(item_nbr)[T.78]  -9.843e-17      0.001  -9.59e-14      1.000      -0.002       0.002
C(item_nbr)[T.79]   6.253e-17      0.001   6.09e-14      1.000      -0.002       0.002
C(item_nbr)[T.80]    2.01e-17      0.001   1.96e-14      1.000      -0.002       0.002
C(item_nbr)[T.81]   -4.32e-17      0.001  -4.21e-14      1.000      -0.002       0.002
C(item_nbr)[T.82]    1.27e-17      0.001   1.24e-14      1.000      -0.002       0.002
C(item_nbr)[T.83]   -1.37e-18      0.001  -1.34e-15      1.000      -0.002       0.002
C(item_nbr)[T.84]   9.606e-17      0.001   9.36e-14      1.000      -0.002       0.002
C(item_nbr)[T.85]  -2.675e-17      0.001  -2.61e-14      1.000      -0.002       0.002
C(item_nbr)[T.86]      0.0151      0.001     14.637      0.000       0.013       0.017
C(item_nbr)[T.87]   1.877e-17      0.001   1.83e-14      1.000      -0.002       0.002
C(item_nbr)[T.88]   5.204e-17      0.001   5.07e-14      1.000      -0.002       0.002
C(item_nbr)[T.89]  -1.748e-16      0.001   -1.7e-13      1.000      -0.002       0.002
C(item_nbr)[T.90]  -1.615e-17      0.001  -1.57e-14      1.000      -0.002       0.002
C(item_nbr)[T.91]  -2.615e-17      0.001  -2.55e-14      1.000      -0.002       0.002
C(item_nbr)[T.92]    3.53e-18      0.001   3.44e-15      1.000      -0.002       0.002
C(item_nbr)[T.93]      0.0491      0.001     45.423      0.000       0.047       0.051
C(item_nbr)[T.94]      0.0438      0.001     42.008      0.000       0.042       0.046
C(item_nbr)[T.95]  -1.589e-17      0.001  -1.55e-14      1.000      -0.002       0.002
C(item_nbr)[T.96]  -9.565e-17      0.001  -9.32e-14      1.000      -0.002       0.002
C(item_nbr)[T.97]  -3.928e-17      0.001  -3.83e-14      1.000      -0.002       0.002
C(item_nbr)[T.98]  -4.714e-17      0.001  -4.59e-14      1.000      -0.002       0.002
C(item_nbr)[T.99]   8.162e-18      0.001   7.95e-15      1.000      -0.002       0.002
C(item_nbr)[T.100] -4.346e-17      0.001  -4.23e-14      1.000      -0.002       0.002
C(item_nbr)[T.101]  3.615e-17      0.001   3.52e-14      1.000      -0.002       0.002
C(item_nbr)[T.102] -6.959e-17      0.001  -6.78e-14      1.000      -0.002       0.002
C(item_nbr)[T.103] -1.482e-16      0.001  -1.44e-13      1.000      -0.002       0.002
C(item_nbr)[T.104] -1.216e-16      0.001  -1.19e-13      1.000      -0.002       0.002
C(item_nbr)[T.105]     0.0095      0.001      9.224      0.000       0.007       0.012
C(item_nbr)[T.106] -1.661e-16      0.001  -1.62e-13      1.000      -0.002       0.002
C(item_nbr)[T.107]  2.271e-16      0.001   2.21e-13      1.000      -0.002       0.002
C(item_nbr)[T.108]     0.0041      0.001      3.875      0.000       0.002       0.006
C(item_nbr)[T.109] -2.008e-16      0.001  -1.96e-13      1.000      -0.002       0.002
C(item_nbr)[T.110]  4.703e-16      0.001   4.58e-13      1.000      -0.002       0.002
C(item_nbr)[T.111]  3.282e-17      0.001    3.2e-14      1.000      -0.002       0.002
scale(heat)         3.486e-05   9.12e-05      0.382      0.702      -0.000       0.000
scale(preciptotal)    -0.0002   7.57e-05     -2.351      0.019      -0.000   -2.96e-05
scale(resultspeed)     0.0002      0.000      0.870      0.384      -0.000       0.001
scale(avgspeed)       -0.0002      0.000     -0.993      0.320      -0.001       0.000
==============================================================================
Omnibus:                   706365.555   Durbin-Watson:                   2.026
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        997569940.959
Skew:                          14.435   Prob(JB):                         0.00
Kurtosis:                     252.948   Cond. No.                         172.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### 5. VIF 재확인 (stnpressure, sealevel, dewpoint, windchill, wetbulb, relative_humility, sunset제외)

In [25]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
# all_cols = ['tmax','tmin','tavg','dewpoint','wetbulb','heat','cool','preciptotal',\
#         'stnpressure','sealevel','resultspeed','avgspeed','relative_humility',\
#         'windchill', 'depart', 'sunrise', 'sunset', 'snowfall' ]
cols = ['heat','preciptotal',\
        'resultspeed','avgspeed']

y = df2_1.loc[:,cols]
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(y.values, i) for i in range(y.shape[1])]
vif["features"] = y.columns
vif = vif.sort_values("VIF Factor", ascending=False).reset_index(drop=True)
vif

   VIF Factor     features
0   29.560625     avgspeed
1   29.283008  resultspeed
2    1.288675         heat
3    1.106266  preciptotal

### 6. VIF 근거, avgspeed, resultspeed 제외하고  Model 돌림.

In [26]:
# OLS - df2_1
model2_1 = sm.OLS.from_formula('log1p_units ~ scale(heat)\
                           + scale(preciptotal) \
                            + C(year) + C(month) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2_1)
result2_1 = model2_1.fit()
print(result2_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.618
Model:                            OLS   Adj. R-squared:                  0.618
Method:                 Least Squares   F-statistic:                     4701.
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:56:24   Log-Likelihood:             6.5120e+05
No. Observations:              378180   AIC:                        -1.302e+06
Df Residuals:                  378049   BIC:                        -1.301e+06
Df Model:                         130
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
C(year)[2012]          0.0016      0.001      1.974      0.048    1.13e-05       0.003
C(year)[2013]          0.0007      0.001      0.845      0.398      -0.001       0.002
C(year)[2014]         -0.0009      0.001     -1.121      0.262      -0.002       0.001
C(month)[T.2]          0.0002      0.000      0.578      0.563      -0.000       0.001
C(month)[T.3]         -0.0002      0.000     -0.741      0.459      -0.001       0.000
C(month)[T.4]          0.0002      0.000      0.504      0.614      -0.001       0.001
C(month)[T.5]         -0.0002      0.000     -0.446      0.656      -0.001       0.001
C(month)[T.6]         -0.0002      0.000     -0.458      0.647      -0.001       0.001
C(month)[T.7]          0.0001      0.000      0.305      0.760      -0.001       0.001
C(month)[T.8]          0.0003      0.000      0.718      0.473      -0.000       0.001
C(month)[T.9]         -0.0004      0.000     -1.048      0.295      -0.001       0.000
C(month)[T.10]        -0.0010      0.000     -2.686      0.007      -0.002      -0.000
C(month)[T.11]        -0.0013      0.000     -3.421      0.001      -0.002      -0.001
C(month)[T.12]        -0.0011      0.000     -2.958      0.003      -0.002      -0.000
C(weekend)[T.1]      2.48e-05      0.000      0.159      0.874      -0.000       0.000
C(rainY)[T.1]          0.0003      0.000      1.690      0.091   -4.09e-05       0.001
C(store_nbr)[T.10]    -0.0010      0.000     -5.202      0.000      -0.001      -0.001
C(store_nbr)[T.41]    -0.0013      0.000     -6.340      0.000      -0.002      -0.001
C(store_nbr)[T.44]     0.0002      0.000      0.808      0.419      -0.000       0.001
C(item_nbr)[T.2]   -1.377e-16      0.001  -1.34e-13      1.000      -0.002       0.002
C(item_nbr)[T.3]    1.059e-15      0.001   1.03e-12      1.000      -0.002       0.002
C(item_nbr)[T.4]     9.15e-17      0.001   8.92e-14      1.000      -0.002       0.002
C(item_nbr)[T.5]       2.3133      0.006    407.362      0.000       2.302       2.324
C(item_nbr)[T.6]    8.668e-16      0.001   8.45e-13      1.000      -0.002       0.002
C(item_nbr)[T.7]   -4.796e-16      0.001  -4.67e-13      1.000      -0.002       0.002
C(item_nbr)[T.8]   -7.116e-16      0.001  -6.93e-13      1.000      -0.002       0.002
C(item_nbr)[T.9]   -5.017e-16      0.001  -4.89e-13      1.000      -0.002       0.002
C(item_nbr)[T.10]  -6.034e-16      0.001  -5.88e-13      1.000      -0.002       0.002
C(item_nbr)[T.11]  -3.525e-16      0.001  -3.43e-13      1.000      -0.002       0.002
C(item_nbr)[T.12]  -7.719e-16      0.001  -7.52e-13      1.000      -0.002       0.002
C(item_nbr)[T.13]  -3.453e-16      0.001  -3.36e-13      1.000      -0.002       0.002
C(item_nbr)[T.14]  -5.301e-16      0.001  -5.16e-13      1.000      -0.002       0.002
C(item_nbr)[T.15]  -5.338e-16      0.001   -5.2e-13      1.000      -0.002       0.002
C(item_nbr)[T.16]      2.0529      0.008    245.662      0.000       2.036       2.069
C(item_nbr)[T.17]  -5.364e-16      0.001  -5.23e-13      1.000      -0.002       0.002
C(item_nbr)[T.18]  -5.546e-16      0.001   -5.4e-13      1.000      -0.002       0.002
C(item_nbr)[T.19]   -5.28e-16      0.001  -5.14e-13      1.000      -0.002       0.002
C(item_nbr)[T.20]      0.0498      0.001     47.648      0.000       0.048       0.052
C(item_nbr)[T.21]      0.0462      0.001     44.353      0.000       0.044       0.048
C(item_nbr)[T.22]  -5.951e-16      0.001   -5.8e-13      1.000      -0.002       0.002
C(item_nbr)[T.23]  -4.964e-16      0.001  -4.84e-13      1.000      -0.002       0.002
C(item_nbr)[T.24]  -5.815e-16      0.001  -5.67e-13      1.000      -0.002       0.002
C(item_nbr)[T.25]  -4.132e-16      0.001  -4.03e-13      1.000      -0.002       0.002
C(item_nbr)[T.26]  -5.347e-16      0.001  -5.21e-13      1.000      -0.002       0.002
C(item_nbr)[T.27]  -4.814e-16      0.001  -4.69e-13      1.000      -0.002       0.002
C(item_nbr)[T.28]  -5.603e-16      0.001  -5.46e-13      1.000      -0.002       0.002
C(item_nbr)[T.29]  -4.974e-16      0.001  -4.85e-13      1.000      -0.002       0.002
C(item_nbr)[T.30]   -5.93e-16      0.001  -5.78e-13      1.000      -0.002       0.002
C(item_nbr)[T.31]  -4.144e-16      0.001  -4.04e-13      1.000      -0.002       0.002
C(item_nbr)[T.32]      0.0278      0.001     26.755      0.000       0.026       0.030
C(item_nbr)[T.33]  -4.875e-16      0.001  -4.75e-13      1.000      -0.002       0.002
C(item_nbr)[T.34]  -5.361e-16      0.001  -5.22e-13      1.000      -0.002       0.002
C(item_nbr)[T.35]  -5.662e-16      0.001  -5.52e-13      1.000      -0.002       0.002
C(item_nbr)[T.36]  -4.766e-16      0.001  -4.64e-13      1.000      -0.002       0.002
C(item_nbr)[T.37]      1.6939      0.004    480.023      0.000       1.687       1.701
C(item_nbr)[T.38]  -4.746e-16      0.001  -4.62e-13      1.000      -0.002       0.002
C(item_nbr)[T.39]   -4.74e-16      0.001  -4.62e-13      1.000      -0.002       0.002
C(item_nbr)[T.40]  -5.264e-16      0.001  -5.13e-13      1.000      -0.002       0.002
C(item_nbr)[T.41]  -5.463e-16      0.001  -5.32e-13      1.000      -0.002       0.002
C(item_nbr)[T.42]   -4.39e-16      0.001  -4.28e-13      1.000      -0.002       0.002
C(item_nbr)[T.43]  -4.559e-16      0.001  -4.44e-13      1.000      -0.002       0.002
C(item_nbr)[T.44]  -5.837e-16      0.001  -5.69e-13      1.000      -0.002       0.002
C(item_nbr)[T.45]  -5.228e-16      0.001  -5.09e-13      1.000      -0.002       0.002
C(item_nbr)[T.46]  -4.797e-16      0.001  -4.67e-13      1.000      -0.002       0.002
C(item_nbr)[T.47]   -4.26e-16      0.001  -4.15e-13      1.000      -0.002       0.002
C(item_nbr)[T.48]  -5.682e-16      0.001  -5.54e-13      1.000      -0.002       0.002
C(item_nbr)[T.49]  -4.405e-16      0.001  -4.29e-13      1.000      -0.002       0.002
C(item_nbr)[T.50]   -4.73e-16      0.001  -4.61e-13      1.000      -0.002       0.002
C(item_nbr)[T.51]  -4.624e-16      0.001  -4.51e-13      1.000      -0.002       0.002
C(item_nbr)[T.52]  -3.711e-16      0.001  -3.62e-13      1.000      -0.002       0.002
C(item_nbr)[T.53]  -5.319e-16      0.001  -5.18e-13      1.000      -0.002       0.002
C(item_nbr)[T.54]  -4.541e-16      0.001  -4.42e-13      1.000      -0.002       0.002
C(item_nbr)[T.55]  -4.746e-16      0.001  -4.62e-13      1.000      -0.002       0.002
C(item_nbr)[T.56]  -5.592e-16      0.001  -5.45e-13      1.000      -0.002       0.002
C(item_nbr)[T.57]  -5.672e-16      0.001  -5.53e-13      1.000      -0.002       0.002
C(item_nbr)[T.58]  -3.656e-16      0.001  -3.56e-13      1.000      -0.002       0.002
C(item_nbr)[T.59]  -5.837e-16      0.001  -5.69e-13      1.000      -0.002       0.002
C(item_nbr)[T.60]  -5.456e-16      0.001  -5.32e-13      1.000      -0.002       0.002
C(item_nbr)[T.61]      0.0282      0.001     27.039      0.000       0.026       0.030
C(item_nbr)[T.62]      0.0319      0.001     30.751      0.000       0.030       0.034
C(item_nbr)[T.63]  -5.177e-16      0.001  -5.04e-13      1.000      -0.002       0.002
C(item_nbr)[T.64]  -4.668e-16      0.001  -4.55e-13      1.000      -0.002       0.002
C(item_nbr)[T.65]  -3.668e-16      0.001  -3.57e-13      1.000      -0.002       0.002
C(item_nbr)[T.66]  -5.486e-16      0.001  -5.35e-13      1.000      -0.002       0.002
C(item_nbr)[T.67]  -4.458e-16      0.001  -4.34e-13      1.000      -0.002       0.002
C(item_nbr)[T.68]      2.2900      0.007    348.943      0.000       2.277       2.303
C(item_nbr)[T.69]  -4.971e-16      0.001  -4.84e-13      1.000      -0.002       0.002
C(item_nbr)[T.70]  -5.063e-16      0.001  -4.93e-13      1.000      -0.002       0.002
C(item_nbr)[T.71]  -5.597e-16      0.001  -5.45e-13      1.000      -0.002       0.002
C(item_nbr)[T.72]  -5.539e-16      0.001   -5.4e-13      1.000      -0.002       0.002
C(item_nbr)[T.73]  -4.904e-16      0.001  -4.78e-13      1.000      -0.002       0.002
C(item_nbr)[T.74]  -5.054e-16      0.001  -4.92e-13      1.000      -0.002       0.002
C(item_nbr)[T.75]  -4.926e-16      0.001   -4.8e-13      1.000      -0.002       0.002
C(item_nbr)[T.76]  -3.819e-16      0.001  -3.72e-13      1.000      -0.002       0.002
C(item_nbr)[T.77]  -4.744e-16      0.001  -4.62e-13      1.000      -0.002       0.002
C(item_nbr)[T.78]  -4.817e-16      0.001  -4.69e-13      1.000      -0.002       0.002
C(item_nbr)[T.79]  -5.976e-16      0.001  -5.82e-13      1.000      -0.002       0.002
C(item_nbr)[T.80]  -5.891e-16      0.001  -5.74e-13      1.000      -0.002       0.002
C(item_nbr)[T.81]  -5.391e-16      0.001  -5.25e-13      1.000      -0.002       0.002
C(item_nbr)[T.82]  -2.782e-16      0.001  -2.71e-13      1.000      -0.002       0.002
C(item_nbr)[T.83]  -3.433e-16      0.001  -3.34e-13      1.000      -0.002       0.002
C(item_nbr)[T.84]  -5.437e-16      0.001   -5.3e-13      1.000      -0.002       0.002
C(item_nbr)[T.85]  -5.053e-16      0.001  -4.92e-13      1.000      -0.002       0.002
C(item_nbr)[T.86]      0.0151      0.001     14.637      0.000       0.013       0.017
C(item_nbr)[T.87]  -5.602e-16      0.001  -5.46e-13      1.000      -0.002       0.002
C(item_nbr)[T.88]  -5.959e-16      0.001  -5.81e-13      1.000      -0.002       0.002
C(item_nbr)[T.89]   -6.59e-16      0.001  -6.42e-13      1.000      -0.002       0.002
C(item_nbr)[T.90]  -5.169e-16      0.001  -5.04e-13      1.000      -0.002       0.002
C(item_nbr)[T.91]  -4.039e-16      0.001  -3.93e-13      1.000      -0.002       0.002
C(item_nbr)[T.92]  -4.105e-16      0.001     -4e-13      1.000      -0.002       0.002
C(item_nbr)[T.93]      0.0491      0.001     45.423      0.000       0.047       0.051
C(item_nbr)[T.94]      0.0438      0.001     42.008      0.000       0.042       0.046
C(item_nbr)[T.95]   -4.26e-16      0.001  -4.15e-13      1.000      -0.002       0.002
C(item_nbr)[T.96]  -7.415e-16      0.001  -7.23e-13      1.000      -0.002       0.002
C(item_nbr)[T.97]  -7.368e-16      0.001  -7.18e-13      1.000      -0.002       0.002
C(item_nbr)[T.98]  -4.469e-16      0.001  -4.35e-13      1.000      -0.002       0.002
C(item_nbr)[T.99]  -3.533e-16      0.001  -3.44e-13      1.000      -0.002       0.002
C(item_nbr)[T.100]   -8.1e-16      0.001  -7.89e-13      1.000      -0.002       0.002
C(item_nbr)[T.101] -6.757e-16      0.001  -6.58e-13      1.000      -0.002       0.002
C(item_nbr)[T.102] -3.525e-16      0.001  -3.43e-13      1.000      -0.002       0.002
C(item_nbr)[T.103] -7.506e-16      0.001  -7.31e-13      1.000      -0.002       0.002
C(item_nbr)[T.104] -7.498e-16      0.001  -7.31e-13      1.000      -0.002       0.002
C(item_nbr)[T.105]     0.0095      0.001      9.224      0.000       0.007       0.012
C(item_nbr)[T.106] -4.297e-16      0.001  -4.19e-13      1.000      -0.002       0.002
C(item_nbr)[T.107] -6.696e-16      0.001  -6.52e-13      1.000      -0.002       0.002
C(item_nbr)[T.108]     0.0041      0.001      3.875      0.000       0.002       0.006
C(item_nbr)[T.109] -5.961e-16      0.001  -5.81e-13      1.000      -0.002       0.002
C(item_nbr)[T.110]  5.265e-16      0.001   5.13e-13      1.000      -0.002       0.002
C(item_nbr)[T.111] -2.343e-15      0.001  -2.28e-12      1.000      -0.002       0.002
scale(heat)          3.54e-05   9.02e-05      0.392      0.695      -0.000       0.000
scale(preciptotal)    -0.0002   7.51e-05     -2.493      0.013      -0.000      -4e-05
==============================================================================
Omnibus:                   706367.209   Durbin-Watson:                   2.026
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        997593339.001
Skew:                          14.435   Prob(JB):                         0.00
Kurtosis:                     252.951   Cond. No.                         134.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### Anova 분석을 통해 p-value가 0.05보다 큰것은 제외

In [27]:
anova_result2_1 = sm.stats.anova_lm(result2_1).sort_values(by=['PR(>F)'], ascending = False)
anova_result2_1[anova_result2_1['PR(>F)'] <= 0.05]

C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)

                       df       sum_sq    mean_sq            F        PR(>F)
scale(preciptotal)    1.0     0.011624   0.011624     6.213627  1.267749e-02
C(month)             11.0     0.134371   0.012216     6.529727  5.497951e-11
C(weekend)            1.0     0.186505   0.186505    99.694456  1.790142e-23
C(store_nbr)          3.0     0.370444   0.123481    66.005905  1.160414e-42
C(year)               3.0     6.634372   2.211457  1182.114495  0.000000e+00
C(item_nbr)         110.0  1142.519741  10.386543  5552.032425  0.000000e+00

### 최종 Anova 분석과 TIF 통과한 변수들을 바탕으로 최종 모델생성

In [28]:
# OLS - df2_1_1
model2_1_1 = sm.OLS.from_formula('log1p_units ~ C(year) + C(month) + \
C(weekend) + + C(store_nbr) + C(item_nbr) + 0', data = df2_1)

result = model2_1_1.fit()
result2_1_1 = model2_1_1.fit()
print(result2_1_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.618
Model:                            OLS   Adj. R-squared:                  0.618
Method:                 Least Squares   F-statistic:                     4812.
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:58:12   Log-Likelihood:             6.5120e+05
No. Observations:              378180   AIC:                        -1.302e+06
Df Residuals:                  378052   BIC:                        -1.301e+06
Df Model:                         127
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
C(year)[2012]          0.0018      0.001      2.267      0.023       0.000       0.003
C(year)[2013]          0.0009      0.001      1.153      0.249      -0.001       0.002
C(year)[2014]         -0.0006      0.001     -0.825      0.409      -0.002       0.001
C(month)[T.2]          0.0002      0.000      0.519      0.604      -0.000       0.001
C(month)[T.3]         -0.0003      0.000     -0.993      0.321      -0.001       0.000
C(month)[T.4]          0.0001      0.000      0.309      0.757      -0.001       0.001
C(month)[T.5]         -0.0003      0.000     -0.849      0.396      -0.001       0.000
C(month)[T.6]         -0.0004      0.000     -1.130      0.258      -0.001       0.000
C(month)[T.7]       2.009e-05      0.000      0.058      0.954      -0.001       0.001
C(month)[T.8]          0.0001      0.000      0.371      0.710      -0.001       0.001
C(month)[T.9]         -0.0005      0.000     -1.408      0.159      -0.001       0.000
C(month)[T.10]        -0.0011      0.000     -3.252      0.001      -0.002      -0.000
C(month)[T.11]        -0.0013      0.000     -3.564      0.000      -0.002      -0.001
C(month)[T.12]        -0.0011      0.000     -2.967      0.003      -0.002      -0.000
C(weekend)[T.1]     3.243e-05      0.000      0.207      0.836      -0.000       0.000
C(store_nbr)[T.10]    -0.0010      0.000     -5.201      0.000      -0.001      -0.001
C(store_nbr)[T.41]    -0.0013      0.000     -6.339      0.000      -0.002      -0.001
C(store_nbr)[T.44]     0.0002      0.000      0.808      0.419      -0.000       0.001
C(item_nbr)[T.2]   -2.404e-15      0.001  -2.34e-12      1.000      -0.002       0.002
C(item_nbr)[T.3]   -1.234e-15      0.001   -1.2e-12      1.000      -0.002       0.002
C(item_nbr)[T.4]    1.374e-15      0.001   1.34e-12      1.000      -0.002       0.002
C(item_nbr)[T.5]       2.3133      0.006    407.362      0.000       2.302       2.324
C(item_nbr)[T.6]   -1.087e-15      0.001  -1.06e-12      1.000      -0.002       0.002
C(item_nbr)[T.7]   -1.456e-15      0.001  -1.42e-12      1.000      -0.002       0.002
C(item_nbr)[T.8]   -5.215e-16      0.001  -5.08e-13      1.000      -0.002       0.002
C(item_nbr)[T.9]   -1.346e-15      0.001  -1.31e-12      1.000      -0.002       0.002
C(item_nbr)[T.10]  -1.509e-15      0.001  -1.47e-12      1.000      -0.002       0.002
C(item_nbr)[T.11]  -1.582e-15      0.001  -1.54e-12      1.000      -0.002       0.002
C(item_nbr)[T.12]  -1.516e-15      0.001  -1.48e-12      1.000      -0.002       0.002
C(item_nbr)[T.13]  -1.461e-15      0.001  -1.42e-12      1.000      -0.002       0.002
C(item_nbr)[T.14]  -1.517e-15      0.001  -1.48e-12      1.000      -0.002       0.002
C(item_nbr)[T.15]  -1.631e-15      0.001  -1.59e-12      1.000      -0.002       0.002
C(item_nbr)[T.16]      2.0528      0.008    245.655      0.000       2.036       2.069
C(item_nbr)[T.17]  -1.547e-15      0.001  -1.51e-12      1.000      -0.002       0.002
C(item_nbr)[T.18]   -1.42e-15      0.001  -1.38e-12      1.000      -0.002       0.002
C(item_nbr)[T.19]  -1.465e-15      0.001  -1.43e-12      1.000      -0.002       0.002
C(item_nbr)[T.20]      0.0498      0.001     47.649      0.000       0.048       0.052
C(item_nbr)[T.21]      0.0462      0.001     44.354      0.000       0.044       0.048
C(item_nbr)[T.22]  -1.439e-15      0.001   -1.4e-12      1.000      -0.002       0.002
C(item_nbr)[T.23]  -1.502e-15      0.001  -1.46e-12      1.000      -0.002       0.002
C(item_nbr)[T.24]    -1.5e-15      0.001  -1.46e-12      1.000      -0.002       0.002
C(item_nbr)[T.25]  -1.515e-15      0.001  -1.48e-12      1.000      -0.002       0.002
C(item_nbr)[T.26]  -1.562e-15      0.001  -1.52e-12      1.000      -0.002       0.002
C(item_nbr)[T.27]  -1.365e-15      0.001  -1.33e-12      1.000      -0.002       0.002
C(item_nbr)[T.28]   -1.57e-15      0.001  -1.53e-12      1.000      -0.002       0.002
C(item_nbr)[T.29]  -1.412e-15      0.001  -1.38e-12      1.000      -0.002       0.002
C(item_nbr)[T.30]  -1.454e-15      0.001  -1.42e-12      1.000      -0.002       0.002
C(item_nbr)[T.31]  -1.487e-15      0.001  -1.45e-12      1.000      -0.002       0.002
C(item_nbr)[T.32]      0.0278      0.001     26.754      0.000       0.026       0.030
C(item_nbr)[T.33]   -1.46e-15      0.001  -1.42e-12      1.000      -0.002       0.002
C(item_nbr)[T.34]  -1.481e-15      0.001  -1.44e-12      1.000      -0.002       0.002
C(item_nbr)[T.35]  -1.556e-15      0.001  -1.52e-12      1.000      -0.002       0.002
C(item_nbr)[T.36]   -1.41e-15      0.001  -1.37e-12      1.000      -0.002       0.002
C(item_nbr)[T.37]      1.6939      0.004    480.022      0.000       1.687       1.701
C(item_nbr)[T.38]    -1.4e-15      0.001  -1.36e-12      1.000      -0.002       0.002
C(item_nbr)[T.39]  -1.487e-15      0.001  -1.45e-12      1.000      -0.002       0.002
C(item_nbr)[T.40]  -1.432e-15      0.001   -1.4e-12      1.000      -0.002       0.002
C(item_nbr)[T.41]  -1.443e-15      0.001  -1.41e-12      1.000      -0.002       0.002
C(item_nbr)[T.42]  -1.438e-15      0.001   -1.4e-12      1.000      -0.002       0.002
C(item_nbr)[T.43]  -1.437e-15      0.001   -1.4e-12      1.000      -0.002       0.002
C(item_nbr)[T.44]  -1.495e-15      0.001  -1.46e-12      1.000      -0.002       0.002
C(item_nbr)[T.45]  -1.495e-15      0.001  -1.46e-12      1.000      -0.002       0.002
C(item_nbr)[T.46]  -1.477e-15      0.001  -1.44e-12      1.000      -0.002       0.002
C(item_nbr)[T.47]  -1.383e-15      0.001  -1.35e-12      1.000      -0.002       0.002
C(item_nbr)[T.48]   -1.49e-15      0.001  -1.45e-12      1.000      -0.002       0.002
C(item_nbr)[T.49]  -1.409e-15      0.001  -1.37e-12      1.000      -0.002       0.002
C(item_nbr)[T.50]  -1.382e-15      0.001  -1.35e-12      1.000      -0.002       0.002
C(item_nbr)[T.51]  -1.569e-15      0.001  -1.53e-12      1.000      -0.002       0.002
C(item_nbr)[T.52]  -1.446e-15      0.001  -1.41e-12      1.000      -0.002       0.002
C(item_nbr)[T.53]  -1.459e-15      0.001  -1.42e-12      1.000      -0.002       0.002
C(item_nbr)[T.54]  -1.409e-15      0.001  -1.37e-12      1.000      -0.002       0.002
C(item_nbr)[T.55]  -1.465e-15      0.001  -1.43e-12      1.000      -0.002       0.002
C(item_nbr)[T.56]  -1.474e-15      0.001  -1.44e-12      1.000      -0.002       0.002
C(item_nbr)[T.57]  -1.338e-15      0.001   -1.3e-12      1.000      -0.002       0.002
C(item_nbr)[T.58]  -1.504e-15      0.001  -1.47e-12      1.000      -0.002       0.002
C(item_nbr)[T.59]  -1.557e-15      0.001  -1.52e-12      1.000      -0.002       0.002
C(item_nbr)[T.60]  -1.472e-15      0.001  -1.43e-12      1.000      -0.002       0.002
C(item_nbr)[T.61]      0.0282      0.001     27.039      0.000       0.026       0.030
C(item_nbr)[T.62]      0.0319      0.001     30.750      0.000       0.030       0.034
C(item_nbr)[T.63]  -1.416e-15      0.001  -1.38e-12      1.000      -0.002       0.002
C(item_nbr)[T.64]  -1.509e-15      0.001  -1.47e-12      1.000      -0.002       0.002
C(item_nbr)[T.65]   -1.51e-15      0.001  -1.47e-12      1.000      -0.002       0.002
C(item_nbr)[T.66]  -1.388e-15      0.001  -1.35e-12      1.000      -0.002       0.002
C(item_nbr)[T.67]  -1.431e-15      0.001  -1.39e-12      1.000      -0.002       0.002
C(item_nbr)[T.68]      2.2900      0.007    348.942      0.000       2.277       2.303
C(item_nbr)[T.69]  -1.461e-15      0.001  -1.42e-12      1.000      -0.002       0.002
C(item_nbr)[T.70]  -1.438e-15      0.001   -1.4e-12      1.000      -0.002       0.002
C(item_nbr)[T.71]  -1.451e-15      0.001  -1.41e-12      1.000      -0.002       0.002
C(item_nbr)[T.72]  -1.474e-15      0.001  -1.44e-12      1.000      -0.002       0.002
C(item_nbr)[T.73]  -1.464e-15      0.001  -1.43e-12      1.000      -0.002       0.002
C(item_nbr)[T.74]   -1.41e-15      0.001  -1.37e-12      1.000      -0.002       0.002
C(item_nbr)[T.75]  -1.448e-15      0.001  -1.41e-12      1.000      -0.002       0.002
C(item_nbr)[T.76]  -1.498e-15      0.001  -1.46e-12      1.000      -0.002       0.002
C(item_nbr)[T.77]  -1.454e-15      0.001  -1.42e-12      1.000      -0.002       0.002
C(item_nbr)[T.78]  -1.419e-15      0.001  -1.38e-12      1.000      -0.002       0.002
C(item_nbr)[T.79]  -1.311e-15      0.001  -1.28e-12      1.000      -0.002       0.002
C(item_nbr)[T.80]  -1.441e-15      0.001   -1.4e-12      1.000      -0.002       0.002
C(item_nbr)[T.81]  -1.557e-15      0.001  -1.52e-12      1.000      -0.002       0.002
C(item_nbr)[T.82]  -1.527e-15      0.001  -1.49e-12      1.000      -0.002       0.002
C(item_nbr)[T.83]  -1.322e-15      0.001  -1.29e-12      1.000      -0.002       0.002
C(item_nbr)[T.84]  -1.399e-15      0.001  -1.36e-12      1.000      -0.002       0.002
C(item_nbr)[T.85]  -1.371e-15      0.001  -1.34e-12      1.000      -0.002       0.002
C(item_nbr)[T.86]      0.0151      0.001     14.641      0.000       0.013       0.017
C(item_nbr)[T.87]  -1.385e-15      0.001  -1.35e-12      1.000      -0.002       0.002
C(item_nbr)[T.88]  -1.492e-15      0.001  -1.45e-12      1.000      -0.002       0.002
C(item_nbr)[T.89]  -1.372e-15      0.001  -1.34e-12      1.000      -0.002       0.002
C(item_nbr)[T.90]  -1.408e-15      0.001  -1.37e-12      1.000      -0.002       0.002
C(item_nbr)[T.91]  -1.436e-15      0.001   -1.4e-12      1.000      -0.002       0.002
C(item_nbr)[T.92]  -1.277e-15      0.001  -1.24e-12      1.000      -0.002       0.002
C(item_nbr)[T.93]      0.0491      0.001     45.431      0.000       0.047       0.051
C(item_nbr)[T.94]      0.0438      0.001     42.008      0.000       0.042       0.046
C(item_nbr)[T.95]   -1.42e-15      0.001  -1.38e-12      1.000      -0.002       0.002
C(item_nbr)[T.96]  -1.604e-15      0.001  -1.56e-12      1.000      -0.002       0.002
C(item_nbr)[T.97]    -1.3e-15      0.001  -1.27e-12      1.000      -0.002       0.002
C(item_nbr)[T.98]  -1.141e-15      0.001  -1.11e-12      1.000      -0.002       0.002
C(item_nbr)[T.99]  -1.338e-15      0.001   -1.3e-12      1.000      -0.002       0.002
C(item_nbr)[T.100]  -1.69e-15      0.001  -1.65e-12      1.000      -0.002       0.002
C(item_nbr)[T.101] -1.215e-15      0.001  -1.18e-12      1.000      -0.002       0.002
C(item_nbr)[T.102]  -1.43e-15      0.001  -1.39e-12      1.000      -0.002       0.002
C(item_nbr)[T.103] -1.579e-15      0.001  -1.54e-12      1.000      -0.002       0.002
C(item_nbr)[T.104] -1.509e-15      0.001  -1.47e-12      1.000      -0.002       0.002
C(item_nbr)[T.105]     0.0095      0.001      9.224      0.000       0.007       0.012
C(item_nbr)[T.106] -1.381e-15      0.001  -1.35e-12      1.000      -0.002       0.002
C(item_nbr)[T.107] -1.622e-15      0.001  -1.58e-12      1.000      -0.002       0.002
C(item_nbr)[T.108]     0.0041      0.001      3.875      0.000       0.002       0.006
C(item_nbr)[T.109] -1.773e-15      0.001  -1.73e-12      1.000      -0.002       0.002
C(item_nbr)[T.110]  2.751e-16      0.001   2.68e-13      1.000      -0.002       0.002
C(item_nbr)[T.111] -5.045e-15      0.001  -4.92e-12      1.000      -0.002       0.002
==============================================================================
Omnibus:                   706378.677   Durbin-Watson:                   2.026
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        997699763.159
Skew:                          14.436   Prob(JB):                         0.00
Kurtosis:                     252.965   Cond. No.                         105.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [29]:
from patsy import dmatrix
# 독립변수와 종속변수로 나누기
df2_1_X = df2_1.drop(columns=['log1p_units'])
df2_1_target = df2_1['log1p_units']

In [30]:
formula = 'C(year) + C(month) + C(weekend) \
        + C(store_nbr) + C(item_nbr) + 0'
dfX = dmatrix(formula, df2_1_X, return_type='dataframe')
dfy = pd.DataFrame(df2_1_target, columns=["log1p_units"])

In [31]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold
from sklearn.metrics import r2_score

model = LinearRegression()
cv = KFold(10)

scores = np.zeros(10)
for i, (train_index, test_index) in enumerate(cv.split(dfX)):
    X_train = dfX.values[train_index]
    y_train = dfy.values[train_index]
    X_test = dfX.values[test_index]
    y_test = dfy.values[test_index]
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    scores[i] = r2_score(y_test, y_pred)

scores

array([0.61312803, 0.56621354, 0.42943142, 0.58763706, 0.47068963,
       0.56792207, 0.56235267, 0.68695836, 0.80667291, 0.82322528])