In [26]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import KFold
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

In [27]:
weather = pd.read_csv("weather3_180703.csv")
weather['date'] = pd.to_datetime(weather["date"])
station = weather[weather['station_nbr'] == 16]

In [28]:
station['date'].count()

1035

In [29]:
# ls == 모든 값이 0인 것

ls = []
ls1 = []
for i in station.columns:
    if station[i].count() == 0:
        ls.append(i)
    if station[i].isna().sum() != 0:
        ls1.append(i)
ls, ls1

(['depart', 'sunrise', 'sunset', 'snowfall', 'daytime'],
 ['depart', 'sunrise', 'sunset', 'snowfall', 'resultdir', 'daytime'])

In [30]:
for i in station.columns:
    count_null = station[i].isna().sum()
    print(i, ":", count_null, "(",round((count_null / len(station) * 100),2),"%",")")

station_nbr : 0 ( 0.0 % )
date : 0 ( 0.0 % )
tmax : 0 ( 0.0 % )
tmin : 0 ( 0.0 % )
tavg : 0 ( 0.0 % )
depart : 1035 ( 100.0 % )
dewpoint : 0 ( 0.0 % )
wetbulb : 0 ( 0.0 % )
heat : 0 ( 0.0 % )
cool : 0 ( 0.0 % )
sunrise : 1035 ( 100.0 % )
sunset : 1035 ( 100.0 % )
codesum : 0 ( 0.0 % )
snowfall : 1035 ( 100.0 % )
preciptotal : 0 ( 0.0 % )
stnpressure : 0 ( 0.0 % )
sealevel : 0 ( 0.0 % )
resultspeed : 0 ( 0.0 % )
resultdir : 7 ( 0.68 % )
avgspeed : 0 ( 0.0 % )
year : 0 ( 0.0 % )
month : 0 ( 0.0 % )
day : 0 ( 0.0 % )
relative_humility : 0 ( 0.0 % )
windchill : 0 ( 0.0 % )
daytime : 1035 ( 100.0 % )
week7 : 0 ( 0.0 % )
weekend : 0 ( 0.0 % )
code_change : 0 ( 0.0 % )
rainY : 0 ( 0.0 % )
otherY : 0 ( 0.0 % )
nothing : 0 ( 0.0 % )

In [31]:
train = pd.read_csv("train.csv")
train.date = pd.to_datetime(train.date)
train.tail()

              date  store_nbr  item_nbr  units
4617595 2014-10-31         45       107      0
4617596 2014-10-31         45       108      0
4617597 2014-10-31         45       109      0
4617598 2014-10-31         45       110      0
4617599 2014-10-31         45       111      0

In [32]:
key = pd.read_csv("key.csv")
station = station.merge(key)

In [33]:
station = station.merge(train)
station.tail()

,station_nbr,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,...,daytime,week7,weekend,code_change,rainY,otherY,nothing,store_nbr,item_nbr,units
211339,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,107,0
211340,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,108,0
211341,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,109,0
211342,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,110,0
211343,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,111,0

In [34]:
station['log1p_units'] = np.log1p(station.units)

In [35]:
target1 = station['units']
target2 = station['log1p_units']

station.drop(columns=['units','log1p_units'],inplace=True)
station.tail()

,station_nbr,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,...,windchill,daytime,week7,weekend,code_change,rainY,otherY,nothing,store_nbr,item_nbr
211339,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,40.375498,NaN,4,0,0,0,0,1,45,107
211340,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,40.375498,NaN,4,0,0,0,0,1,45,108
211341,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,40.375498,NaN,4,0,0,0,0,1,45,109
211342,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,40.375498,NaN,4,0,0,0,0,1,45,110
211343,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,40.375498,NaN,4,0,0,0,0,1,45,111

In [36]:
df1 = pd.concat([station,target1], axis=1)
df2 = pd.concat([station,target2], axis=1)

In [37]:
df2.to_csv('station16.csv', sep=',', index=False)

In [38]:
if df2.columns.tolist() and ls:
    print('공통 변수 있음')
    print(df2.columns.tolist() and ls)
else:
    print('공통 변수 없음')

공통 변수 있음
['depart', 'sunrise', 'sunset', 'snowfall', 'daytime']

In [39]:
df2.columns

Index(['station_nbr', 'date', 'tmax', 'tmin', 'tavg', 'depart', 'dewpoint',
       'wetbulb', 'heat', 'cool', 'sunrise', 'sunset', 'codesum', 'snowfall',
       'preciptotal', 'stnpressure', 'sealevel', 'resultspeed', 'resultdir',
       'avgspeed', 'year', 'month', 'day', 'relative_humility', 'windchill',
       'daytime', 'week7', 'weekend', 'code_change', 'rainY', 'otherY',
       'nothing', 'store_nbr', 'item_nbr', 'log1p_units'],
      dtype='object')

In [40]:
ls, ls1

(['depart', 'sunrise', 'sunset', 'snowfall', 'daytime'],
 ['depart', 'sunrise', 'sunset', 'snowfall', 'resultdir', 'daytime'])

### 1. 변수변환: df2 (log1p_units)

In [19]:
all_var = 'log1p_units ~ scale(tmax) + scale(tmin) + scale(tavg) + scale(depart) + scale(dewpoint) + scale(wetbulb) + scale(heat) + scale(cool)\
                            + scale(sunrise) + scale(sunset) + scale(snowfall) + scale(preciptotal) + scale(stnpressure) + scale(sealevel) + scale(resultspeed)  \
                            + C(resultdir) + scale(avgspeed) + C(year) + C(month) + scale(relative_humility) + scale(windchill) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + C(daytime) + 0'

In [41]:
model2 = sm.OLS.from_formula('log1p_units ~ scale(tmax) + scale(tmin) + scale(tavg) + scale(dewpoint) + scale(wetbulb) + scale(heat) + scale(cool)\
                            + scale(preciptotal) + scale(stnpressure) + scale(sealevel) + scale(resultspeed)  \
                            + scale(avgspeed) + C(year) + C(month) + scale(relative_humility) + scale(windchill) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2)
result2 = model2.fit()
print(result2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.597
Model:                            OLS   Adj. R-squared:                  0.597
Method:                 Least Squares   F-statistic:                     2249.
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        13:15:36   Log-Likelihood:                 33471.
No. Observations:              211344   AIC:                        -6.666e+04
Df Residuals:                  211204   BIC:                        -6.523e+04
Df Model:                         139
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
C(year)[2012]                0.0083      0.005      1.597      0.110      -0.002       0.018
C(year)[2013]                0.0078      0.005      1.491      0.136      -0.002       0.018
C(year)[2014]               -0.0070      0.005     -1.328      0.184      -0.017       0.003
C(month)[T.2]                0.0027      0.002      1.286      0.198      -0.001       0.007
C(month)[T.3]                0.0025      0.002      1.175      0.240      -0.002       0.007
C(month)[T.4]                0.0014      0.002      0.560      0.575      -0.003       0.006
C(month)[T.5]                0.0021      0.003      0.740      0.459      -0.003       0.008
C(month)[T.6]                0.0013      0.003      0.393      0.694      -0.005       0.008
C(month)[T.7]                0.0038      0.004      1.073      0.283      -0.003       0.011
C(month)[T.8]                0.0057      0.003      1.663      0.096      -0.001       0.012
C(month)[T.9]               -0.0007      0.003     -0.219      0.827      -0.007       0.005
C(month)[T.10]              -0.0046      0.003     -1.699      0.089      -0.010       0.001
C(month)[T.11]              -0.0060      0.003     -2.308      0.021      -0.011      -0.001
C(month)[T.12]              -0.0011      0.002     -0.466      0.641      -0.006       0.004
C(weekend)[T.1]              0.0052      0.001      5.155      0.000       0.003       0.007
C(rainY)[T.1]               -0.0003      0.001     -0.242      0.808      -0.003       0.002
C(store_nbr)[T.45]          -0.0120      0.001    -13.335      0.000      -0.014      -0.010
C(item_nbr)[T.2]          6.041e-15      0.007   9.02e-13      1.000      -0.013       0.013
C(item_nbr)[T.3]          1.882e-14      0.007   2.81e-12      1.000      -0.013       0.013
C(item_nbr)[T.4]             0.0964      0.007     14.399      0.000       0.083       0.110
C(item_nbr)[T.5]         -3.649e-15      0.007  -5.45e-13      1.000      -0.013       0.013
C(item_nbr)[T.6]          3.168e-14      0.007   4.73e-12      1.000      -0.013       0.013
C(item_nbr)[T.7]         -4.659e-15      0.007  -6.96e-13      1.000      -0.013       0.013
C(item_nbr)[T.8]          3.617e-15      0.007    5.4e-13      1.000      -0.013       0.013
C(item_nbr)[T.9]             2.2833      0.007    341.000      0.000       2.270       2.296
C(item_nbr)[T.10]         -6.56e-15      0.007   -9.8e-13      1.000      -0.013       0.013
C(item_nbr)[T.11]         5.387e-15      0.007   8.04e-13      1.000      -0.013       0.013
C(item_nbr)[T.12]         5.253e-16      0.007   7.85e-14      1.000      -0.013       0.013
C(item_nbr)[T.13]        -2.258e-15      0.007  -3.37e-13      1.000      -0.013       0.013
C(item_nbr)[T.14]         8.491e-16      0.007   1.27e-13      1.000      -0.013       0.013
C(item_nbr)[T.15]            0.0898      0.007     13.414      0.000       0.077       0.103
C(item_nbr)[T.16]        -3.188e-16      0.007  -4.76e-14      1.000      -0.013       0.013
C(item_nbr)[T.17]           2.6e-16      0.007   3.88e-14      1.000      -0.013       0.013
C(item_nbr)[T.18]         8.884e-17      0.007   1.33e-14      1.000      -0.013       0.013
C(item_nbr)[T.19]         2.895e-16      0.007   4.32e-14      1.000      -0.013       0.013
C(item_nbr)[T.20]        -4.448e-16      0.007  -6.64e-14      1.000      -0.013       0.013
C(item_nbr)[T.21]        -1.676e-15      0.007   -2.5e-13      1.000      -0.013       0.013
C(item_nbr)[T.22]            0.0447      0.007      6.680      0.000       0.032       0.058
C(item_nbr)[T.23]         9.444e-16      0.007   1.41e-13      1.000      -0.013       0.013
C(item_nbr)[T.24]        -4.381e-16      0.007  -6.54e-14      1.000      -0.013       0.013
C(item_nbr)[T.25]            1.2217      0.007    182.454      0.000       1.209       1.235
C(item_nbr)[T.26]            0.6576      0.007     98.210      0.000       0.644       0.671
C(item_nbr)[T.27]        -1.444e-15      0.007  -2.16e-13      1.000      -0.013       0.013
C(item_nbr)[T.28]        -6.215e-17      0.007  -9.28e-15      1.000      -0.013       0.013
C(item_nbr)[T.29]        -7.556e-16      0.007  -1.13e-13      1.000      -0.013       0.013
C(item_nbr)[T.30]         6.911e-16      0.007   1.03e-13      1.000      -0.013       0.013
C(item_nbr)[T.31]        -6.866e-16      0.007  -1.03e-13      1.000      -0.013       0.013
C(item_nbr)[T.32]         2.588e-16      0.007   3.86e-14      1.000      -0.013       0.013
C(item_nbr)[T.33]            0.1056      0.007     15.771      0.000       0.092       0.119
C(item_nbr)[T.34]            0.0264      0.007      3.940      0.000       0.013       0.040
C(item_nbr)[T.35]        -1.401e-15      0.007  -2.09e-13      1.000      -0.013       0.013
C(item_nbr)[T.36]         1.008e-15      0.007    1.5e-13      1.000      -0.013       0.013
C(item_nbr)[T.37]        -9.393e-16      0.007   -1.4e-13      1.000      -0.013       0.013
C(item_nbr)[T.38]        -9.892e-16      0.007  -1.48e-13      1.000      -0.013       0.013
C(item_nbr)[T.39]        -1.303e-16      0.007  -1.95e-14      1.000      -0.013       0.013
C(item_nbr)[T.40]        -6.522e-16      0.007  -9.74e-14      1.000      -0.013       0.013
C(item_nbr)[T.41]         -8.15e-16      0.007  -1.22e-13      1.000      -0.013       0.013
C(item_nbr)[T.42]        -6.354e-16      0.007  -9.49e-14      1.000      -0.013       0.013
C(item_nbr)[T.43]         1.007e-15      0.007    1.5e-13      1.000      -0.013       0.013
C(item_nbr)[T.44]        -1.849e-15      0.007  -2.76e-13      1.000      -0.013       0.013
C(item_nbr)[T.45]        -9.021e-16      0.007  -1.35e-13      1.000      -0.013       0.013
C(item_nbr)[T.46]         2.614e-15      0.007    3.9e-13      1.000      -0.013       0.013
C(item_nbr)[T.47]        -4.789e-16      0.007  -7.15e-14      1.000      -0.013       0.013
C(item_nbr)[T.48]         2.235e-16      0.007   3.34e-14      1.000      -0.013       0.013
C(item_nbr)[T.49]        -3.716e-16      0.007  -5.55e-14      1.000      -0.013       0.013
C(item_nbr)[T.50]            0.1382      0.007     20.637      0.000       0.125       0.151
C(item_nbr)[T.51]        -6.927e-16      0.007  -1.03e-13      1.000      -0.013       0.013
C(item_nbr)[T.52]        -4.852e-16      0.007  -7.25e-14      1.000      -0.013       0.013
C(item_nbr)[T.53]        -6.599e-16      0.007  -9.86e-14      1.000      -0.013       0.013
C(item_nbr)[T.54]        -1.291e-15      0.007  -1.93e-13      1.000      -0.013       0.013
C(item_nbr)[T.55]        -1.044e-15      0.007  -1.56e-13      1.000      -0.013       0.013
C(item_nbr)[T.56]        -1.907e-15      0.007  -2.85e-13      1.000      -0.013       0.013
C(item_nbr)[T.57]        -5.006e-16      0.007  -7.48e-14      1.000      -0.013       0.013
C(item_nbr)[T.58]        -1.494e-15      0.007  -2.23e-13      1.000      -0.013       0.013
C(item_nbr)[T.59]        -1.331e-15      0.007  -1.99e-13      1.000      -0.013       0.013
C(item_nbr)[T.60]        -4.683e-16      0.007  -6.99e-14      1.000      -0.013       0.013
C(item_nbr)[T.61]        -1.382e-15      0.007  -2.06e-13      1.000      -0.013       0.013
C(item_nbr)[T.62]        -4.818e-16      0.007   -7.2e-14      1.000      -0.013       0.013
C(item_nbr)[T.63]        -3.156e-16      0.007  -4.71e-14      1.000      -0.013       0.013
C(item_nbr)[T.64]        -1.976e-16      0.007  -2.95e-14      1.000      -0.013       0.013
C(item_nbr)[T.65]        -7.741e-16      0.007  -1.16e-13      1.000      -0.013       0.013
C(item_nbr)[T.66]         -3.97e-16      0.007  -5.93e-14      1.000      -0.013       0.013
C(item_nbr)[T.67]         -5.99e-16      0.007  -8.95e-14      1.000      -0.013       0.013
C(item_nbr)[T.68]         4.682e-18      0.007   6.99e-16      1.000      -0.013       0.013
C(item_nbr)[T.69]        -4.501e-17      0.007  -6.72e-15      1.000      -0.013       0.013
C(item_nbr)[T.70]            0.1215      0.007     18.142      0.000       0.108       0.135
C(item_nbr)[T.71]        -2.843e-17      0.007  -4.25e-15      1.000      -0.013       0.013
C(item_nbr)[T.72]        -6.066e-16      0.007  -9.06e-14      1.000      -0.013       0.013
C(item_nbr)[T.73]        -2.082e-16      0.007  -3.11e-14      1.000      -0.013       0.013
C(item_nbr)[T.74]        -7.824e-16      0.007  -1.17e-13      1.000      -0.013       0.013
C(item_nbr)[T.75]        -6.471e-16      0.007  -9.66e-14      1.000      -0.013       0.013
C(item_nbr)[T.76]         1.074e-16      0.007    1.6e-14      1.000      -0.013       0.013
C(item_nbr)[T.77]          2.88e-16      0.007    4.3e-14      1.000      -0.013       0.013
C(item_nbr)[T.78]        -5.258e-16      0.007  -7.85e-14      1.000      -0.013       0.013
C(item_nbr)[T.79]        -1.215e-15      0.007  -1.82e-13      1.000      -0.013       0.013
C(item_nbr)[T.80]         -1.04e-15      0.007  -1.55e-13      1.000      -0.013       0.013
C(item_nbr)[T.81]        -1.054e-15      0.007  -1.57e-13      1.000      -0.013       0.013
C(item_nbr)[T.82]          -9.6e-16      0.007  -1.43e-13      1.000      -0.013       0.013
C(item_nbr)[T.83]        -5.086e-16      0.007   -7.6e-14      1.000      -0.013       0.013
C(item_nbr)[T.84]        -6.008e-16      0.007  -8.97e-14      1.000      -0.013       0.013
C(item_nbr)[T.85]        -4.079e-16      0.007  -6.09e-14      1.000      -0.013       0.013
C(item_nbr)[T.86]        -6.198e-16      0.007  -9.26e-14      1.000      -0.013       0.013
C(item_nbr)[T.87]        -4.065e-17      0.007  -6.07e-15      1.000      -0.013       0.013
C(item_nbr)[T.88]            0.0239      0.007      3.574      0.000       0.011       0.037
C(item_nbr)[T.89]        -6.377e-16      0.007  -9.52e-14      1.000      -0.013       0.013
C(item_nbr)[T.90]        -1.407e-15      0.007   -2.1e-13      1.000      -0.013       0.013
C(item_nbr)[T.91]        -1.766e-16      0.007  -2.64e-14      1.000      -0.013       0.013
C(item_nbr)[T.92]        -1.746e-16      0.007  -2.61e-14      1.000      -0.013       0.013
C(item_nbr)[T.93]            0.0961      0.007     14.359      0.000       0.083       0.109
C(item_nbr)[T.94]        -7.962e-16      0.007  -1.19e-13      1.000      -0.013       0.013
C(item_nbr)[T.95]        -1.223e-15      0.007  -1.83e-13      1.000      -0.013       0.013
C(item_nbr)[T.96]        -9.291e-16      0.007  -1.39e-13      1.000      -0.013       0.013
C(item_nbr)[T.97]        -8.179e-16      0.007  -1.22e-13      1.000      -0.013       0.013
C(item_nbr)[T.98]        -3.109e-16      0.007  -4.64e-14      1.000      -0.013       0.013
C(item_nbr)[T.99]        -4.014e-16      0.007  -5.99e-14      1.000      -0.013       0.013
C(item_nbr)[T.100]       -2.703e-16      0.007  -4.04e-14      1.000      -0.013       0.013
C(item_nbr)[T.101]       -7.613e-16      0.007  -1.14e-13      1.000      -0.013       0.013
C(item_nbr)[T.102]       -8.461e-16      0.007  -1.26e-13      1.000      -0.013       0.013
C(item_nbr)[T.103]       -5.837e-16      0.007  -8.72e-14      1.000      -0.013       0.013
C(item_nbr)[T.104]       -9.571e-16      0.007  -1.43e-13      1.000      -0.013       0.013
C(item_nbr)[T.105]       -2.405e-16      0.007  -3.59e-14      1.000      -0.013       0.013
C(item_nbr)[T.106]       -6.168e-16      0.007  -9.21e-14      1.000      -0.013       0.013
C(item_nbr)[T.107]       -1.291e-15      0.007  -1.93e-13      1.000      -0.013       0.013
C(item_nbr)[T.108]       -9.103e-16      0.007  -1.36e-13      1.000      -0.013       0.013
C(item_nbr)[T.109]       -1.085e-15      0.007  -1.62e-13      1.000      -0.013       0.013
C(item_nbr)[T.110]       -8.971e-16      0.007  -1.34e-13      1.000      -0.013       0.013
C(item_nbr)[T.111]       -3.587e-16      0.007  -5.36e-14      1.000      -0.013       0.013
scale(tmax)                 -0.0012      0.007     -0.174      0.862      -0.014       0.012
scale(tmin)                  0.0028      0.006      0.455      0.649      -0.009       0.015
scale(tavg)                  0.0008      0.006      0.117      0.907      -0.012       0.013
scale(dewpoint)             -0.0059      0.010     -0.572      0.567      -0.026       0.014
scale(wetbulb)               0.0023      0.008      0.306      0.760      -0.012       0.017
scale(heat)                  0.0004      0.005      0.098      0.922      -0.008       0.009
scale(cool)                 -0.0002      0.001     -0.184      0.854      -0.002       0.002
scale(preciptotal)           0.0002      0.001      0.334      0.738      -0.001       0.001
scale(stnpressure)           0.0017      0.004      0.445      0.657      -0.006       0.009
scale(sealevel)             -0.0021      0.004     -0.540      0.590      -0.010       0.005
scale(resultspeed)           0.0010      0.001      0.809      0.418      -0.001       0.003
scale(avgspeed)             -0.0014      0.002     -0.774      0.439      -0.005       0.002
scale(relative_humility)     0.0019      0.003      0.560      0.575      -0.005       0.009
scale(windchill)            -0.0016      0.015     -0.112      0.911      -0.030       0.027
==============================================================================
Omnibus:                   154868.655   Durbin-Watson:                   2.345
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         38873695.729
Skew:                           2.514   Prob(JB):                         0.00
Kurtosis:                      69.251   Cond. No.                     2.25e+15
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.19e-25. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

### 2. 변수변환 : df2 (log1p_units) + 아웃라이어 제거

In [42]:
# 아웃라이어 제거
# Cook's distance > 2 인 값 제거
influence = result2.get_influence()
cooks_d2, pvals = influence.cooks_distance
fox_cr = 4 / (len(df2) - 2)
idx_outlier = np.where(cooks_d2 > fox_cr)[0]
len(idx_outlier)

6188

In [43]:
idx = list(set(range(len(df2))).difference(idx_outlier))
df2_1 = df2.iloc[idx, :].reset_index(drop=True)
df2_1

,station_nbr,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,...,daytime,week7,weekend,code_change,rainY,otherY,nothing,store_nbr,item_nbr,log1p_units
0,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,1,0.000000
1,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,2,0.000000
2,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,3,0.000000
3,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,4,0.000000
4,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,5,0.000000
5,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,6,0.000000
6,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,7,0.000000
7,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,8,0.000000
8,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,9,2.197225
9,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,10,0.000000
10,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,11,0.000000
11,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,12,0.000000
12,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,13,0.000000
13,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,14,0.000000
14,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,15,0.000000
15,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,16,0.000000
16,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,17,0.000000
17,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,18,0.000000
18,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,19,0.000000
19,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,20,0.000000
20,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,21,0.000000
21,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,22,0.000000
22,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,23,0.000000
23,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,24,0.000000
24,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,27,0.000000
25,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,28,0.000000
26,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,29,0.000000
27,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,30,0.000000
28,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,31,0.000000
29,16,2012-01-01,50.0,30.0,40.0,NaN,37.0,40.0,25.0,0.0,...,NaN,6,1,2,1,1,0,14,32,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205126,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,82,0.000000
205127,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,83,0.000000
205128,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,84,0.000000
205129,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,85,0.000000
205130,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,86,0.000000
205131,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,87,0.000000
205132,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,88,0.000000
205133,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,89,0.000000
205134,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,90,0.000000
205135,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,91,0.000000
205136,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,92,0.000000
205137,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,93,0.000000
205138,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,94,0.000000
205139,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,95,0.000000
205140,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,96,0.000000
205141,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,97,0.000000
205142,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,98,0.000000
205143,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,99,0.000000
205144,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,100,0.000000
205145,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,101,0.000000
205146,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,102,0.000000
205147,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,103,0.000000
205148,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,104,0.000000
205149,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,105,0.000000
205150,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,106,0.000000
205151,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,107,0.000000
205152,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,108,0.000000
205153,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,109,0.000000
205154,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,110,0.000000
205155,16,2014-10-31,53.0,34.0,43.5,NaN,35.0,41.0,21.0,0.0,...,NaN,4,0,0,0,0,1,45,111,0.000000

In [44]:
# OLS - df2_1
model2_1 = sm.OLS.from_formula('log1p_units ~ scale(tmax) + scale(tmin) + scale(tavg) + scale(dewpoint) + scale(wetbulb) + scale(heat) + scale(cool)\
                            + scale(preciptotal) + scale(stnpressure) + scale(sealevel) + scale(resultspeed)  \
                            + scale(avgspeed) + C(year) + C(month) + scale(relative_humility) + scale(windchill) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2_1)
result2_1 = model2_1.fit()
print(result2_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.988
Model:                            OLS   Adj. R-squared:                  0.988
Method:                 Least Squares   F-statistic:                 1.261e+05
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        13:19:26   Log-Likelihood:             6.0063e+05
No. Observations:              205156   AIC:                        -1.201e+06
Df Residuals:                  205016   BIC:                        -1.200e+06
Df Model:                         139
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
C(year)[2012]                0.0001      0.000      0.351      0.725      -0.001       0.001
C(year)[2013]                0.0002      0.000      0.490      0.624      -0.000       0.001
C(year)[2014]                0.0001      0.000      0.346      0.729      -0.001       0.001
C(month)[T.2]               -0.0002      0.000     -1.567      0.117      -0.000    5.27e-05
C(month)[T.3]             9.409e-06      0.000      0.068      0.945      -0.000       0.000
C(month)[T.4]            -7.051e-05      0.000     -0.447      0.655      -0.000       0.000
C(month)[T.5]             2.572e-05      0.000      0.145      0.885      -0.000       0.000
C(month)[T.6]               -0.0003      0.000     -1.584      0.113      -0.001    7.66e-05
C(month)[T.7]               -0.0003      0.000     -1.190      0.234      -0.001       0.000
C(month)[T.8]               -0.0002      0.000     -0.725      0.468      -0.001       0.000
C(month)[T.9]               -0.0002      0.000     -0.962      0.336      -0.001       0.000
C(month)[T.10]           -2.167e-05      0.000     -0.126      0.900      -0.000       0.000
C(month)[T.11]              -0.0002      0.000     -0.943      0.346      -0.000       0.000
C(month)[T.12]              -0.0002      0.000     -1.436      0.151      -0.001    8.14e-05
C(weekend)[T.1]           4.401e-05   6.39e-05      0.689      0.491   -8.11e-05       0.000
C(rainY)[T.1]            -4.196e-05   7.31e-05     -0.574      0.566      -0.000       0.000
C(store_nbr)[T.45]        6.964e-07   5.72e-05      0.012      0.990      -0.000       0.000
C(item_nbr)[T.2]          -8.31e-16      0.000  -1.98e-12      1.000      -0.001       0.001
C(item_nbr)[T.3]         -1.516e-15      0.000  -3.61e-12      1.000      -0.001       0.001
C(item_nbr)[T.4]          1.989e-06      0.000      0.005      0.996      -0.001       0.001
C(item_nbr)[T.5]         -2.638e-15      0.000  -6.28e-12      1.000      -0.001       0.001
C(item_nbr)[T.6]          4.418e-16      0.000   1.05e-12      1.000      -0.001       0.001
C(item_nbr)[T.7]          -1.54e-15      0.000  -3.67e-12      1.000      -0.001       0.001
C(item_nbr)[T.8]          2.183e-15      0.000    5.2e-12      1.000      -0.001       0.001
C(item_nbr)[T.9]             2.3246      0.001   3592.956      0.000       2.323       2.326
C(item_nbr)[T.10]         6.949e-16      0.000   1.66e-12      1.000      -0.001       0.001
C(item_nbr)[T.11]          2.05e-15      0.000   4.88e-12      1.000      -0.001       0.001
C(item_nbr)[T.12]         2.288e-15      0.000   5.45e-12      1.000      -0.001       0.001
C(item_nbr)[T.13]        -9.467e-16      0.000  -2.25e-12      1.000      -0.001       0.001
C(item_nbr)[T.14]        -9.796e-17      0.000  -2.33e-13      1.000      -0.001       0.001
C(item_nbr)[T.15]        -9.154e-07      0.000     -0.002      0.998      -0.001       0.001
C(item_nbr)[T.16]        -8.277e-16      0.000  -1.97e-12      1.000      -0.001       0.001
C(item_nbr)[T.17]         -1.69e-15      0.000  -4.02e-12      1.000      -0.001       0.001
C(item_nbr)[T.18]        -1.504e-15      0.000  -3.58e-12      1.000      -0.001       0.001
C(item_nbr)[T.19]        -6.538e-16      0.000  -1.56e-12      1.000      -0.001       0.001
C(item_nbr)[T.20]         -1.25e-15      0.000  -2.98e-12      1.000      -0.001       0.001
C(item_nbr)[T.21]        -7.023e-16      0.000  -1.67e-12      1.000      -0.001       0.001
C(item_nbr)[T.22]        -3.361e-07      0.000     -0.001      0.999      -0.001       0.001
C(item_nbr)[T.23]        -7.918e-16      0.000  -1.89e-12      1.000      -0.001       0.001
C(item_nbr)[T.24]        -7.432e-16      0.000  -1.77e-12      1.000      -0.001       0.001
C(item_nbr)[T.25]            1.3554      0.001    905.234      0.000       1.352       1.358
C(item_nbr)[T.26]            0.6932      0.001    592.073      0.000       0.691       0.695
C(item_nbr)[T.27]        -3.866e-16      0.000  -9.21e-13      1.000      -0.001       0.001
C(item_nbr)[T.28]         -8.61e-16      0.000  -2.05e-12      1.000      -0.001       0.001
C(item_nbr)[T.29]        -8.213e-16      0.000  -1.96e-12      1.000      -0.001       0.001
C(item_nbr)[T.30]        -8.344e-16      0.000  -1.99e-12      1.000      -0.001       0.001
C(item_nbr)[T.31]        -7.813e-16      0.000  -1.86e-12      1.000      -0.001       0.001
C(item_nbr)[T.32]         -7.42e-16      0.000  -1.77e-12      1.000      -0.001       0.001
C(item_nbr)[T.33]        -4.599e-07      0.000     -0.001      0.999      -0.001       0.001
C(item_nbr)[T.34]          -2.4e-06      0.000     -0.006      0.995      -0.001       0.001
C(item_nbr)[T.35]        -7.882e-16      0.000  -1.88e-12      1.000      -0.001       0.001
C(item_nbr)[T.36]        -6.794e-16      0.000  -1.62e-12      1.000      -0.001       0.001
C(item_nbr)[T.37]        -7.306e-16      0.000  -1.74e-12      1.000      -0.001       0.001
C(item_nbr)[T.38]         -7.73e-16      0.000  -1.84e-12      1.000      -0.001       0.001
C(item_nbr)[T.39]        -7.659e-16      0.000  -1.82e-12      1.000      -0.001       0.001
C(item_nbr)[T.40]        -7.125e-16      0.000   -1.7e-12      1.000      -0.001       0.001
C(item_nbr)[T.41]        -6.605e-16      0.000  -1.57e-12      1.000      -0.001       0.001
C(item_nbr)[T.42]        -7.085e-16      0.000  -1.69e-12      1.000      -0.001       0.001
C(item_nbr)[T.43]        -7.323e-16      0.000  -1.74e-12      1.000      -0.001       0.001
C(item_nbr)[T.44]        -8.496e-16      0.000  -2.02e-12      1.000      -0.001       0.001
C(item_nbr)[T.45]        -7.266e-16      0.000  -1.73e-12      1.000      -0.001       0.001
C(item_nbr)[T.46]        -7.784e-16      0.000  -1.85e-12      1.000      -0.001       0.001
C(item_nbr)[T.47]        -7.906e-16      0.000  -1.88e-12      1.000      -0.001       0.001
C(item_nbr)[T.48]        -7.135e-16      0.000   -1.7e-12      1.000      -0.001       0.001
C(item_nbr)[T.49]        -7.503e-16      0.000  -1.79e-12      1.000      -0.001       0.001
C(item_nbr)[T.50]        -4.928e-06      0.000     -0.011      0.991      -0.001       0.001
C(item_nbr)[T.51]        -7.008e-16      0.000  -1.67e-12      1.000      -0.001       0.001
C(item_nbr)[T.52]        -7.643e-16      0.000  -1.82e-12      1.000      -0.001       0.001
C(item_nbr)[T.53]        -7.702e-16      0.000  -1.83e-12      1.000      -0.001       0.001
C(item_nbr)[T.54]        -8.257e-16      0.000  -1.97e-12      1.000      -0.001       0.001
C(item_nbr)[T.55]        -7.968e-16      0.000   -1.9e-12      1.000      -0.001       0.001
C(item_nbr)[T.56]        -7.392e-16      0.000  -1.76e-12      1.000      -0.001       0.001
C(item_nbr)[T.57]        -8.853e-16      0.000  -2.11e-12      1.000      -0.001       0.001
C(item_nbr)[T.58]        -7.565e-16      0.000   -1.8e-12      1.000      -0.001       0.001
C(item_nbr)[T.59]        -7.738e-16      0.000  -1.84e-12      1.000      -0.001       0.001
C(item_nbr)[T.60]        -7.573e-16      0.000   -1.8e-12      1.000      -0.001       0.001
C(item_nbr)[T.61]        -7.733e-16      0.000  -1.84e-12      1.000      -0.001       0.001
C(item_nbr)[T.62]        -8.159e-16      0.000  -1.94e-12      1.000      -0.001       0.001
C(item_nbr)[T.63]        -7.491e-16      0.000  -1.78e-12      1.000      -0.001       0.001
C(item_nbr)[T.64]        -7.736e-16      0.000  -1.84e-12      1.000      -0.001       0.001
C(item_nbr)[T.65]        -8.642e-16      0.000  -2.06e-12      1.000      -0.001       0.001
C(item_nbr)[T.66]        -7.673e-16      0.000  -1.83e-12      1.000      -0.001       0.001
C(item_nbr)[T.67]        -8.889e-16      0.000  -2.12e-12      1.000      -0.001       0.001
C(item_nbr)[T.68]        -7.563e-16      0.000   -1.8e-12      1.000      -0.001       0.001
C(item_nbr)[T.69]        -7.158e-16      0.000   -1.7e-12      1.000      -0.001       0.001
C(item_nbr)[T.70]         3.644e-06      0.000      0.008      0.993      -0.001       0.001
C(item_nbr)[T.71]        -7.668e-16      0.000  -1.83e-12      1.000      -0.001       0.001
C(item_nbr)[T.72]        -7.735e-16      0.000  -1.84e-12      1.000      -0.001       0.001
C(item_nbr)[T.73]        -7.342e-16      0.000  -1.75e-12      1.000      -0.001       0.001
C(item_nbr)[T.74]        -8.376e-16      0.000  -1.99e-12      1.000      -0.001       0.001
C(item_nbr)[T.75]        -7.176e-16      0.000  -1.71e-12      1.000      -0.001       0.001
C(item_nbr)[T.76]        -7.683e-16      0.000  -1.83e-12      1.000      -0.001       0.001
C(item_nbr)[T.77]         -7.28e-16      0.000  -1.73e-12      1.000      -0.001       0.001
C(item_nbr)[T.78]        -7.656e-16      0.000  -1.82e-12      1.000      -0.001       0.001
C(item_nbr)[T.79]        -7.438e-16      0.000  -1.77e-12      1.000      -0.001       0.001
C(item_nbr)[T.80]        -7.642e-16      0.000  -1.82e-12      1.000      -0.001       0.001
C(item_nbr)[T.81]        -7.329e-16      0.000  -1.75e-12      1.000      -0.001       0.001
C(item_nbr)[T.82]        -7.479e-16      0.000  -1.78e-12      1.000      -0.001       0.001
C(item_nbr)[T.83]        -7.772e-16      0.000  -1.85e-12      1.000      -0.001       0.001
C(item_nbr)[T.84]        -7.531e-16      0.000  -1.79e-12      1.000      -0.001       0.001
C(item_nbr)[T.85]        -7.458e-16      0.000  -1.78e-12      1.000      -0.001       0.001
C(item_nbr)[T.86]        -8.137e-16      0.000  -1.94e-12      1.000      -0.001       0.001
C(item_nbr)[T.87]        -7.693e-16      0.000  -1.83e-12      1.000      -0.001       0.001
C(item_nbr)[T.88]        -4.192e-08      0.000  -9.92e-05      1.000      -0.001       0.001
C(item_nbr)[T.89]        -7.849e-16      0.000  -1.87e-12      1.000      -0.001       0.001
C(item_nbr)[T.90]        -7.234e-16      0.000  -1.72e-12      1.000      -0.001       0.001
C(item_nbr)[T.91]        -7.694e-16      0.000  -1.83e-12      1.000      -0.001       0.001
C(item_nbr)[T.92]        -7.136e-16      0.000   -1.7e-12      1.000      -0.001       0.001
C(item_nbr)[T.93]        -1.104e-06      0.000     -0.003      0.998      -0.001       0.001
C(item_nbr)[T.94]        -7.906e-16      0.000  -1.88e-12      1.000      -0.001       0.001
C(item_nbr)[T.95]        -7.793e-16      0.000  -1.86e-12      1.000      -0.001       0.001
C(item_nbr)[T.96]        -7.675e-16      0.000  -1.83e-12      1.000      -0.001       0.001
C(item_nbr)[T.97]        -7.374e-16      0.000  -1.76e-12      1.000      -0.001       0.001
C(item_nbr)[T.98]        -7.443e-16      0.000  -1.77e-12      1.000      -0.001       0.001
C(item_nbr)[T.99]        -7.458e-16      0.000  -1.78e-12      1.000      -0.001       0.001
C(item_nbr)[T.100]       -7.466e-16      0.000  -1.78e-12      1.000      -0.001       0.001
C(item_nbr)[T.101]       -7.484e-16      0.000  -1.78e-12      1.000      -0.001       0.001
C(item_nbr)[T.102]       -7.918e-16      0.000  -1.89e-12      1.000      -0.001       0.001
C(item_nbr)[T.103]         -8.1e-16      0.000  -1.93e-12      1.000      -0.001       0.001
C(item_nbr)[T.104]       -7.086e-16      0.000  -1.69e-12      1.000      -0.001       0.001
C(item_nbr)[T.105]       -7.172e-16      0.000  -1.71e-12      1.000      -0.001       0.001
C(item_nbr)[T.106]       -7.458e-16      0.000  -1.78e-12      1.000      -0.001       0.001
C(item_nbr)[T.107]       -9.057e-16      0.000  -2.16e-12      1.000      -0.001       0.001
C(item_nbr)[T.108]       -8.291e-16      0.000  -1.97e-12      1.000      -0.001       0.001
C(item_nbr)[T.109]       -7.582e-16      0.000  -1.81e-12      1.000      -0.001       0.001
C(item_nbr)[T.110]       -8.618e-16      0.000  -2.05e-12      1.000      -0.001       0.001
C(item_nbr)[T.111]       -7.759e-16      0.000  -1.85e-12      1.000      -0.001       0.001
scale(tmax)                 -0.0005      0.000     -1.196      0.232      -0.001       0.000
scale(tmin)                 -0.0005      0.000     -1.202      0.230      -0.001       0.000
scale(tavg)                 -0.0005      0.000     -1.228      0.219      -0.001       0.000
scale(dewpoint)            9.32e-05      0.001      0.143      0.886      -0.001       0.001
scale(wetbulb)            9.327e-06      0.000      0.019      0.984      -0.001       0.001
scale(heat)               2.774e-05      0.000      0.096      0.923      -0.001       0.001
scale(cool)               3.355e-05    6.8e-05      0.494      0.622   -9.96e-05       0.000
scale(preciptotal)       -6.052e-06   3.52e-05     -0.172      0.863    -7.5e-05    6.29e-05
scale(stnpressure)          -0.0001      0.000     -0.466      0.641      -0.001       0.000
scale(sealevel)              0.0001      0.000      0.434      0.664      -0.000       0.001
scale(resultspeed)        4.625e-05   8.01e-05      0.577      0.564      -0.000       0.000
scale(avgspeed)           8.513e-05      0.000      0.755      0.450      -0.000       0.000
scale(relative_humility) -2.406e-05      0.000     -0.110      0.912      -0.000       0.000
scale(windchill)             0.0015      0.001      1.598      0.110      -0.000       0.003
==============================================================================
Omnibus:                   194364.521   Durbin-Watson:                   2.000
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       2967728894.074
Skew:                          -2.958   Prob(JB):                         0.00
Kurtosis:                     592.188   Cond. No.                     2.25e+15
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.1e-25. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [45]:
ls1

['depart', 'sunrise', 'sunset', 'snowfall', 'resultdir', 'daytime']

### 3. VIF 확인

In [46]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
# all_cols = ['tmax','tmin','tavg','dewpoint','wetbulb','heat','cool','preciptotal',\
#         'stnpressure','sealevel','resultspeed','avgspeed','relative_humility',\
#         'windchill', 'depart', 'sunrise', 'sunset', 'snowfall' ]
cols = ['tmax','tmin','tavg','dewpoint','wetbulb','heat','cool','preciptotal',\
        'stnpressure','sealevel','resultspeed','avgspeed','relative_humility',\
        'windchill']

y = df2_1.loc[:,cols]
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(y.values, i) for i in range(y.shape[1])]
vif["features"] = y.columns
vif = vif.sort_values("VIF Factor", ascending=False).reset_index(drop=True)
vif

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\stats\outliers_influence.py:167: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)

      VIF Factor           features
0            inf               tmax
1            inf               tmin
2            inf               tavg
3   1.165961e+06        stnpressure
4   1.145830e+06           sealevel
5   5.948294e+03          windchill
6   2.507198e+03           dewpoint
7   2.343067e+03            wetbulb
8   1.027256e+03  relative_humility
9   1.900435e+02               heat
10  8.408132e+01           avgspeed
11  2.912110e+01        resultspeed
12  6.159631e+00               cool
13  1.673520e+00        preciptotal

### 4. VIF 근거, 빼고 다시 Model 돌림.

In [47]:
# OLS - df2_1
model2_1 = sm.OLS.from_formula('log1p_units ~ scale(cool)\
                            + scale(preciptotal) + scale(resultspeed)  \
                            + scale(avgspeed) + C(year) + C(month) +C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2_1)
result2_1 = model2_1.fit()
print(result2_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.988
Model:                            OLS   Adj. R-squared:                  0.988
Method:                 Least Squares   F-statistic:                 1.348e+05
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        13:21:52   Log-Likelihood:             6.0063e+05
No. Observations:              205156   AIC:                        -1.201e+06
Df Residuals:                  205025   BIC:                        -1.200e+06
Df Model:                         130
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
C(year)[2012]       5.009e-05      0.000      0.159      0.874      -0.001       0.001
C(year)[2013]       8.977e-05      0.000      0.284      0.777      -0.001       0.001
C(year)[2014]       4.117e-05      0.000      0.130      0.897      -0.001       0.001
C(month)[T.2]         -0.0002      0.000     -1.472      0.141      -0.000     6.5e-05
C(month)[T.3]       3.762e-05      0.000      0.285      0.776      -0.000       0.000
C(month)[T.4]      -8.565e-06      0.000     -0.065      0.948      -0.000       0.000
C(month)[T.5]          0.0001      0.000      0.798      0.425      -0.000       0.000
C(month)[T.6]         -0.0002      0.000     -1.533      0.125      -0.001    6.22e-05
C(month)[T.7]         -0.0002      0.000     -1.133      0.257      -0.000       0.000
C(month)[T.8]      -8.402e-05      0.000     -0.561      0.575      -0.000       0.000
C(month)[T.9]         -0.0001      0.000     -0.741      0.459      -0.000       0.000
C(month)[T.10]       6.95e-05      0.000      0.513      0.608      -0.000       0.000
C(month)[T.11]     -9.508e-05      0.000     -0.617      0.537      -0.000       0.000
C(month)[T.12]        -0.0002      0.000     -1.264      0.206      -0.000       0.000
C(weekend)[T.1]     3.775e-05   6.35e-05      0.594      0.552   -8.67e-05       0.000
C(rainY)[T.1]      -1.881e-05   6.17e-05     -0.305      0.761      -0.000       0.000
C(store_nbr)[T.45]  6.595e-07   5.72e-05      0.012      0.991      -0.000       0.000
C(item_nbr)[T.2]   -1.488e-15      0.000  -3.54e-12      1.000      -0.001       0.001
C(item_nbr)[T.3]   -4.793e-15      0.000  -1.14e-11      1.000      -0.001       0.001
C(item_nbr)[T.4]    2.041e-06      0.000      0.005      0.996      -0.001       0.001
C(item_nbr)[T.5]    -8.48e-16      0.000  -2.02e-12      1.000      -0.001       0.001
C(item_nbr)[T.6]    1.203e-16      0.000   2.86e-13      1.000      -0.001       0.001
C(item_nbr)[T.7]   -1.061e-15      0.000  -2.53e-12      1.000      -0.001       0.001
C(item_nbr)[T.8]   -1.228e-15      0.000  -2.92e-12      1.000      -0.001       0.001
C(item_nbr)[T.9]       2.3246      0.001   3593.036      0.000       2.323       2.326
C(item_nbr)[T.10]  -9.655e-16      0.000   -2.3e-12      1.000      -0.001       0.001
C(item_nbr)[T.11]  -1.216e-15      0.000   -2.9e-12      1.000      -0.001       0.001
C(item_nbr)[T.12]  -1.382e-15      0.000  -3.29e-12      1.000      -0.001       0.001
C(item_nbr)[T.13]  -1.267e-15      0.000  -3.02e-12      1.000      -0.001       0.001
C(item_nbr)[T.14]  -1.407e-15      0.000  -3.35e-12      1.000      -0.001       0.001
C(item_nbr)[T.15]  -5.935e-07      0.000     -0.001      0.999      -0.001       0.001
C(item_nbr)[T.16]  -1.262e-15      0.000     -3e-12      1.000      -0.001       0.001
C(item_nbr)[T.17]  -1.366e-15      0.000  -3.25e-12      1.000      -0.001       0.001
C(item_nbr)[T.18]  -1.258e-15      0.000     -3e-12      1.000      -0.001       0.001
C(item_nbr)[T.19]  -1.339e-15      0.000  -3.19e-12      1.000      -0.001       0.001
C(item_nbr)[T.20]  -1.305e-15      0.000  -3.11e-12      1.000      -0.001       0.001
C(item_nbr)[T.21]  -1.245e-15      0.000  -2.97e-12      1.000      -0.001       0.001
C(item_nbr)[T.22]  -8.066e-07      0.000     -0.002      0.998      -0.001       0.001
C(item_nbr)[T.23]  -1.281e-15      0.000  -3.05e-12      1.000      -0.001       0.001
C(item_nbr)[T.24]  -1.338e-15      0.000  -3.19e-12      1.000      -0.001       0.001
C(item_nbr)[T.25]      1.3554      0.001    905.281      0.000       1.352       1.358
C(item_nbr)[T.26]      0.6932      0.001    592.093      0.000       0.691       0.695
C(item_nbr)[T.27]  -8.963e-16      0.000  -2.13e-12      1.000      -0.001       0.001
C(item_nbr)[T.28]  -1.264e-15      0.000  -3.01e-12      1.000      -0.001       0.001
C(item_nbr)[T.29]  -1.308e-15      0.000  -3.11e-12      1.000      -0.001       0.001
C(item_nbr)[T.30]  -1.253e-15      0.000  -2.98e-12      1.000      -0.001       0.001
C(item_nbr)[T.31]  -1.264e-15      0.000  -3.01e-12      1.000      -0.001       0.001
C(item_nbr)[T.32]  -1.248e-15      0.000  -2.97e-12      1.000      -0.001       0.001
C(item_nbr)[T.33]   -5.33e-07      0.000     -0.001      0.999      -0.001       0.001
C(item_nbr)[T.34]  -1.659e-06      0.000     -0.004      0.997      -0.001       0.001
C(item_nbr)[T.35]  -1.296e-15      0.000  -3.09e-12      1.000      -0.001       0.001
C(item_nbr)[T.36]  -1.284e-15      0.000  -3.06e-12      1.000      -0.001       0.001
C(item_nbr)[T.37]  -1.279e-15      0.000  -3.05e-12      1.000      -0.001       0.001
C(item_nbr)[T.38]  -1.301e-15      0.000   -3.1e-12      1.000      -0.001       0.001
C(item_nbr)[T.39]   -1.23e-15      0.000  -2.93e-12      1.000      -0.001       0.001
C(item_nbr)[T.40]  -1.266e-15      0.000  -3.02e-12      1.000      -0.001       0.001
C(item_nbr)[T.41]  -1.301e-15      0.000   -3.1e-12      1.000      -0.001       0.001
C(item_nbr)[T.42]  -1.276e-15      0.000  -3.04e-12      1.000      -0.001       0.001
C(item_nbr)[T.43]  -1.187e-15      0.000  -2.83e-12      1.000      -0.001       0.001
C(item_nbr)[T.44]  -1.298e-15      0.000  -3.09e-12      1.000      -0.001       0.001
C(item_nbr)[T.45]  -1.261e-15      0.000     -3e-12      1.000      -0.001       0.001
C(item_nbr)[T.46]  -1.316e-15      0.000  -3.13e-12      1.000      -0.001       0.001
C(item_nbr)[T.47]  -1.244e-15      0.000  -2.96e-12      1.000      -0.001       0.001
C(item_nbr)[T.48]  -1.265e-15      0.000  -3.01e-12      1.000      -0.001       0.001
C(item_nbr)[T.49]  -1.294e-15      0.000  -3.08e-12      1.000      -0.001       0.001
C(item_nbr)[T.50]  -4.099e-06      0.000     -0.009      0.992      -0.001       0.001
C(item_nbr)[T.51]  -1.263e-15      0.000  -3.01e-12      1.000      -0.001       0.001
C(item_nbr)[T.52]  -1.281e-15      0.000  -3.05e-12      1.000      -0.001       0.001
C(item_nbr)[T.53]  -1.269e-15      0.000  -3.02e-12      1.000      -0.001       0.001
C(item_nbr)[T.54]  -1.213e-15      0.000  -2.89e-12      1.000      -0.001       0.001
C(item_nbr)[T.55]  -1.346e-15      0.000   -3.2e-12      1.000      -0.001       0.001
C(item_nbr)[T.56]  -1.263e-15      0.000  -3.01e-12      1.000      -0.001       0.001
C(item_nbr)[T.57]  -1.306e-15      0.000  -3.11e-12      1.000      -0.001       0.001
C(item_nbr)[T.58]  -1.297e-15      0.000  -3.09e-12      1.000      -0.001       0.001
C(item_nbr)[T.59]   -1.26e-15      0.000     -3e-12      1.000      -0.001       0.001
C(item_nbr)[T.60]  -1.295e-15      0.000  -3.08e-12      1.000      -0.001       0.001
C(item_nbr)[T.61]  -1.301e-15      0.000   -3.1e-12      1.000      -0.001       0.001
C(item_nbr)[T.62]  -1.253e-15      0.000  -2.99e-12      1.000      -0.001       0.001
C(item_nbr)[T.63]  -1.265e-15      0.000  -3.01e-12      1.000      -0.001       0.001
C(item_nbr)[T.64]  -1.307e-15      0.000  -3.11e-12      1.000      -0.001       0.001
C(item_nbr)[T.65]  -1.183e-15      0.000  -2.82e-12      1.000      -0.001       0.001
C(item_nbr)[T.66]  -1.287e-15      0.000  -3.07e-12      1.000      -0.001       0.001
C(item_nbr)[T.67]  -1.237e-15      0.000  -2.95e-12      1.000      -0.001       0.001
C(item_nbr)[T.68]  -1.244e-15      0.000  -2.96e-12      1.000      -0.001       0.001
C(item_nbr)[T.69]  -1.307e-15      0.000  -3.11e-12      1.000      -0.001       0.001
C(item_nbr)[T.70]   3.945e-06      0.000      0.009      0.993      -0.001       0.001
C(item_nbr)[T.71]  -1.298e-15      0.000  -3.09e-12      1.000      -0.001       0.001
C(item_nbr)[T.72]  -1.259e-15      0.000     -3e-12      1.000      -0.001       0.001
C(item_nbr)[T.73]  -1.206e-15      0.000  -2.87e-12      1.000      -0.001       0.001
C(item_nbr)[T.74]  -1.287e-15      0.000  -3.07e-12      1.000      -0.001       0.001
C(item_nbr)[T.75]  -1.336e-15      0.000  -3.18e-12      1.000      -0.001       0.001
C(item_nbr)[T.76]  -1.226e-15      0.000  -2.92e-12      1.000      -0.001       0.001
C(item_nbr)[T.77]   -1.29e-15      0.000  -3.07e-12      1.000      -0.001       0.001
C(item_nbr)[T.78]  -1.282e-15      0.000  -3.05e-12      1.000      -0.001       0.001
C(item_nbr)[T.79]  -1.284e-15      0.000  -3.06e-12      1.000      -0.001       0.001
C(item_nbr)[T.80]  -1.316e-15      0.000  -3.13e-12      1.000      -0.001       0.001
C(item_nbr)[T.81]  -1.279e-15      0.000  -3.05e-12      1.000      -0.001       0.001
C(item_nbr)[T.82]   -1.31e-15      0.000  -3.12e-12      1.000      -0.001       0.001
C(item_nbr)[T.83]   -1.29e-15      0.000  -3.07e-12      1.000      -0.001       0.001
C(item_nbr)[T.84]  -1.328e-15      0.000  -3.16e-12      1.000      -0.001       0.001
C(item_nbr)[T.85]  -1.229e-15      0.000  -2.93e-12      1.000      -0.001       0.001
C(item_nbr)[T.86]  -1.344e-15      0.000   -3.2e-12      1.000      -0.001       0.001
C(item_nbr)[T.87]   -1.28e-15      0.000  -3.05e-12      1.000      -0.001       0.001
C(item_nbr)[T.88]   1.239e-07      0.000      0.000      1.000      -0.001       0.001
C(item_nbr)[T.89]  -1.275e-15      0.000  -3.04e-12      1.000      -0.001       0.001
C(item_nbr)[T.90]  -1.332e-15      0.000  -3.17e-12      1.000      -0.001       0.001
C(item_nbr)[T.91]  -1.352e-15      0.000  -3.22e-12      1.000      -0.001       0.001
C(item_nbr)[T.92]  -1.324e-15      0.000  -3.15e-12      1.000      -0.001       0.001
C(item_nbr)[T.93]  -1.484e-07      0.000     -0.000      1.000      -0.001       0.001
C(item_nbr)[T.94]  -1.232e-15      0.000  -2.93e-12      1.000      -0.001       0.001
C(item_nbr)[T.95]  -1.381e-15      0.000  -3.29e-12      1.000      -0.001       0.001
C(item_nbr)[T.96]  -1.285e-15      0.000  -3.06e-12      1.000      -0.001       0.001
C(item_nbr)[T.97]  -1.222e-15      0.000  -2.91e-12      1.000      -0.001       0.001
C(item_nbr)[T.98]  -1.302e-15      0.000   -3.1e-12      1.000      -0.001       0.001
C(item_nbr)[T.99]  -1.214e-15      0.000  -2.89e-12      1.000      -0.001       0.001
C(item_nbr)[T.100] -1.268e-15      0.000  -3.02e-12      1.000      -0.001       0.001
C(item_nbr)[T.101] -1.352e-15      0.000  -3.22e-12      1.000      -0.001       0.001
C(item_nbr)[T.102] -1.196e-15      0.000  -2.85e-12      1.000      -0.001       0.001
C(item_nbr)[T.103] -1.176e-15      0.000   -2.8e-12      1.000      -0.001       0.001
C(item_nbr)[T.104] -1.412e-15      0.000  -3.36e-12      1.000      -0.001       0.001
C(item_nbr)[T.105] -1.292e-15      0.000  -3.08e-12      1.000      -0.001       0.001
C(item_nbr)[T.106] -1.451e-15      0.000  -3.45e-12      1.000      -0.001       0.001
C(item_nbr)[T.107]   -1.1e-15      0.000  -2.62e-12      1.000      -0.001       0.001
C(item_nbr)[T.108] -1.604e-15      0.000  -3.82e-12      1.000      -0.001       0.001
C(item_nbr)[T.109] -1.046e-15      0.000  -2.49e-12      1.000      -0.001       0.001
C(item_nbr)[T.110] -1.517e-15      0.000  -3.61e-12      1.000      -0.001       0.001
C(item_nbr)[T.111] -1.047e-15      0.000  -2.49e-12      1.000      -0.001       0.001
scale(cool)         5.108e-05   3.75e-05      1.364      0.173   -2.23e-05       0.000
scale(preciptotal) -4.757e-06   3.19e-05     -0.149      0.882   -6.73e-05    5.78e-05
scale(resultspeed)  5.099e-05   7.78e-05      0.656      0.512      -0.000       0.000
scale(avgspeed)    -2.649e-05   8.04e-05     -0.329      0.742      -0.000       0.000
==============================================================================
Omnibus:                   194376.059   Durbin-Watson:                   2.000
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       2967929768.453
Skew:                          -2.958   Prob(JB):                         0.00
Kurtosis:                     592.208   Cond. No.                         157.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### 5. VIF 재확인

In [48]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
# all_cols = ['tmax','tmin','tavg','dewpoint','wetbulb','heat','cool','preciptotal',\
#         'stnpressure','sealevel','resultspeed','avgspeed','relative_humility',\
#         'windchill', 'depart', 'sunrise', 'sunset', 'snowfall' ]
cols = ['cool', 'preciptotal', 'resultspeed', 'avgspeed']

y = df2_1.loc[:,cols]
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(y.values, i) for i in range(y.shape[1])]
vif["features"] = y.columns
vif = vif.sort_values("VIF Factor", ascending=False).reset_index(drop=True)
vif

   VIF Factor     features
0   24.920258     avgspeed
1   23.897377  resultspeed
2    1.199907  preciptotal
3    1.093131         cool

### 6. VIF 근거로 제외하고  Model 돌림.

In [49]:
# OLS - df2_1
model2_1 = sm.OLS.from_formula('log1p_units ~ scale(cool)\
                            + scale(preciptotal) + C(year) + C(month) +C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2_1)
result2_1 = model2_1.fit()
print(result2_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.988
Model:                            OLS   Adj. R-squared:                  0.988
Method:                 Least Squares   F-statistic:                 1.370e+05
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        13:23:35   Log-Likelihood:             6.0063e+05
No. Observations:              205156   AIC:                        -1.201e+06
Df Residuals:                  205027   BIC:                        -1.200e+06
Df Model:                         128
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
C(year)[2012]        6.23e-05      0.000      0.197      0.843      -0.001       0.001
C(year)[2013]          0.0001      0.000      0.329      0.742      -0.001       0.001
C(year)[2014]       5.638e-05      0.000      0.178      0.859      -0.001       0.001
C(month)[T.2]         -0.0002      0.000     -1.501      0.133      -0.000     6.1e-05
C(month)[T.3]       3.702e-05      0.000      0.280      0.779      -0.000       0.000
C(month)[T.4]      -1.164e-05      0.000     -0.088      0.930      -0.000       0.000
C(month)[T.5]        9.04e-05      0.000      0.696      0.487      -0.000       0.000
C(month)[T.6]         -0.0002      0.000     -1.666      0.096      -0.001    4.23e-05
C(month)[T.7]         -0.0002      0.000     -1.353      0.176      -0.001    9.26e-05
C(month)[T.8]         -0.0001      0.000     -0.754      0.451      -0.000       0.000
C(month)[T.9]         -0.0001      0.000     -0.916      0.360      -0.000       0.000
C(month)[T.10]      6.085e-05      0.000      0.458      0.647      -0.000       0.000
C(month)[T.11]     -9.626e-05      0.000     -0.626      0.531      -0.000       0.000
C(month)[T.12]        -0.0002      0.000     -1.319      0.187      -0.001    9.78e-05
C(weekend)[T.1]     3.724e-05   6.35e-05      0.586      0.558   -8.72e-05       0.000
C(rainY)[T.1]      -2.392e-05   6.15e-05     -0.389      0.697      -0.000    9.65e-05
C(store_nbr)[T.45]  6.734e-07   5.72e-05      0.012      0.991      -0.000       0.000
C(item_nbr)[T.2]     7.56e-16      0.000    1.8e-12      1.000      -0.001       0.001
C(item_nbr)[T.3]   -9.074e-17      0.000  -2.16e-13      1.000      -0.001       0.001
C(item_nbr)[T.4]    1.906e-06      0.000      0.004      0.996      -0.001       0.001
C(item_nbr)[T.5]   -7.703e-16      0.000  -1.83e-12      1.000      -0.001       0.001
C(item_nbr)[T.6]    4.174e-16      0.000   9.94e-13      1.000      -0.001       0.001
C(item_nbr)[T.7]    1.629e-17      0.000   3.88e-14      1.000      -0.001       0.001
C(item_nbr)[T.8]   -3.552e-17      0.000  -8.46e-14      1.000      -0.001       0.001
C(item_nbr)[T.9]       2.3246      0.001   3593.067      0.000       2.323       2.326
C(item_nbr)[T.10]  -1.275e-16      0.000  -3.04e-13      1.000      -0.001       0.001
C(item_nbr)[T.11]  -3.177e-16      0.000  -7.57e-13      1.000      -0.001       0.001
C(item_nbr)[T.12]  -1.175e-17      0.000   -2.8e-14      1.000      -0.001       0.001
C(item_nbr)[T.13]  -2.228e-16      0.000  -5.31e-13      1.000      -0.001       0.001
C(item_nbr)[T.14]     3.4e-17      0.000    8.1e-14      1.000      -0.001       0.001
C(item_nbr)[T.15]  -7.726e-07      0.000     -0.002      0.999      -0.001       0.001
C(item_nbr)[T.16]  -2.195e-16      0.000  -5.23e-13      1.000      -0.001       0.001
C(item_nbr)[T.17]  -1.761e-16      0.000  -4.19e-13      1.000      -0.001       0.001
C(item_nbr)[T.18]  -1.515e-16      0.000  -3.61e-13      1.000      -0.001       0.001
C(item_nbr)[T.19]  -1.792e-16      0.000  -4.27e-13      1.000      -0.001       0.001
C(item_nbr)[T.20]   -1.23e-16      0.000  -2.93e-13      1.000      -0.001       0.001
C(item_nbr)[T.21]  -3.009e-16      0.000  -7.17e-13      1.000      -0.001       0.001
C(item_nbr)[T.22]  -8.194e-07      0.000     -0.002      0.998      -0.001       0.001
C(item_nbr)[T.23]  -1.896e-16      0.000  -4.52e-13      1.000      -0.001       0.001
C(item_nbr)[T.24]  -2.079e-16      0.000  -4.95e-13      1.000      -0.001       0.001
C(item_nbr)[T.25]      1.3554      0.001    905.292      0.000       1.352       1.358
C(item_nbr)[T.26]      0.6932      0.001    592.096      0.000       0.691       0.695
C(item_nbr)[T.27]    2.31e-16      0.000    5.5e-13      1.000      -0.001       0.001
C(item_nbr)[T.28]  -1.442e-16      0.000  -3.43e-13      1.000      -0.001       0.001
C(item_nbr)[T.29]   -2.17e-16      0.000  -5.17e-13      1.000      -0.001       0.001
C(item_nbr)[T.30]  -2.039e-16      0.000  -4.86e-13      1.000      -0.001       0.001
C(item_nbr)[T.31]  -1.294e-16      0.000  -3.08e-13      1.000      -0.001       0.001
C(item_nbr)[T.32]  -1.792e-16      0.000  -4.27e-13      1.000      -0.001       0.001
C(item_nbr)[T.33]  -1.013e-06      0.000     -0.002      0.998      -0.001       0.001
C(item_nbr)[T.34]  -1.826e-06      0.000     -0.004      0.997      -0.001       0.001
C(item_nbr)[T.35]  -1.392e-16      0.000  -3.32e-13      1.000      -0.001       0.001
C(item_nbr)[T.36]  -1.851e-16      0.000  -4.41e-13      1.000      -0.001       0.001
C(item_nbr)[T.37]  -8.454e-17      0.000  -2.01e-13      1.000      -0.001       0.001
C(item_nbr)[T.38]  -1.497e-16      0.000  -3.56e-13      1.000      -0.001       0.001
C(item_nbr)[T.39]  -1.745e-16      0.000  -4.16e-13      1.000      -0.001       0.001
C(item_nbr)[T.40]  -1.473e-16      0.000  -3.51e-13      1.000      -0.001       0.001
C(item_nbr)[T.41]  -1.024e-16      0.000  -2.44e-13      1.000      -0.001       0.001
C(item_nbr)[T.42]  -1.453e-16      0.000  -3.46e-13      1.000      -0.001       0.001
C(item_nbr)[T.43]  -8.304e-17      0.000  -1.98e-13      1.000      -0.001       0.001
C(item_nbr)[T.44]  -1.392e-16      0.000  -3.32e-13      1.000      -0.001       0.001
C(item_nbr)[T.45]  -1.758e-16      0.000  -4.19e-13      1.000      -0.001       0.001
C(item_nbr)[T.46]  -2.285e-16      0.000  -5.44e-13      1.000      -0.001       0.001
C(item_nbr)[T.47]  -1.358e-16      0.000  -3.24e-13      1.000      -0.001       0.001
C(item_nbr)[T.48]  -1.632e-16      0.000  -3.89e-13      1.000      -0.001       0.001
C(item_nbr)[T.49]  -1.357e-16      0.000  -3.23e-13      1.000      -0.001       0.001
C(item_nbr)[T.50]   -4.46e-06      0.000     -0.010      0.992      -0.001       0.001
C(item_nbr)[T.51]  -1.351e-16      0.000  -3.22e-13      1.000      -0.001       0.001
C(item_nbr)[T.52]  -1.653e-16      0.000  -3.94e-13      1.000      -0.001       0.001
C(item_nbr)[T.53]  -1.689e-16      0.000  -4.02e-13      1.000      -0.001       0.001
C(item_nbr)[T.54]  -1.519e-16      0.000  -3.62e-13      1.000      -0.001       0.001
C(item_nbr)[T.55]  -1.991e-16      0.000  -4.74e-13      1.000      -0.001       0.001
C(item_nbr)[T.56]  -1.744e-16      0.000  -4.15e-13      1.000      -0.001       0.001
C(item_nbr)[T.57]  -1.007e-16      0.000   -2.4e-13      1.000      -0.001       0.001
C(item_nbr)[T.58]  -7.913e-17      0.000  -1.88e-13      1.000      -0.001       0.001
C(item_nbr)[T.59]  -1.082e-16      0.000  -2.58e-13      1.000      -0.001       0.001
C(item_nbr)[T.60]  -1.782e-16      0.000  -4.25e-13      1.000      -0.001       0.001
C(item_nbr)[T.61]  -1.047e-16      0.000  -2.49e-13      1.000      -0.001       0.001
C(item_nbr)[T.62]  -2.339e-16      0.000  -5.57e-13      1.000      -0.001       0.001
C(item_nbr)[T.63]  -1.817e-16      0.000  -4.33e-13      1.000      -0.001       0.001
C(item_nbr)[T.64]  -8.197e-17      0.000  -1.95e-13      1.000      -0.001       0.001
C(item_nbr)[T.65]  -2.162e-16      0.000  -5.15e-13      1.000      -0.001       0.001
C(item_nbr)[T.66]  -1.538e-16      0.000  -3.66e-13      1.000      -0.001       0.001
C(item_nbr)[T.67]   -1.37e-16      0.000  -3.26e-13      1.000      -0.001       0.001
C(item_nbr)[T.68]  -1.521e-16      0.000  -3.62e-13      1.000      -0.001       0.001
C(item_nbr)[T.69]  -1.532e-16      0.000  -3.65e-13      1.000      -0.001       0.001
C(item_nbr)[T.70]   4.241e-06      0.000      0.010      0.992      -0.001       0.001
C(item_nbr)[T.71]  -1.396e-16      0.000  -3.32e-13      1.000      -0.001       0.001
C(item_nbr)[T.72]  -1.691e-16      0.000  -4.03e-13      1.000      -0.001       0.001
C(item_nbr)[T.73]  -2.026e-16      0.000  -4.82e-13      1.000      -0.001       0.001
C(item_nbr)[T.74]  -1.166e-16      0.000  -2.78e-13      1.000      -0.001       0.001
C(item_nbr)[T.75]  -1.283e-16      0.000  -3.06e-13      1.000      -0.001       0.001
C(item_nbr)[T.76]  -2.133e-16      0.000  -5.08e-13      1.000      -0.001       0.001
C(item_nbr)[T.77]  -1.593e-16      0.000  -3.79e-13      1.000      -0.001       0.001
C(item_nbr)[T.78]    -1.1e-16      0.000  -2.62e-13      1.000      -0.001       0.001
C(item_nbr)[T.79]  -8.131e-17      0.000  -1.94e-13      1.000      -0.001       0.001
C(item_nbr)[T.80]  -1.011e-16      0.000  -2.41e-13      1.000      -0.001       0.001
C(item_nbr)[T.81]  -1.817e-16      0.000  -4.33e-13      1.000      -0.001       0.001
C(item_nbr)[T.82]  -1.929e-16      0.000  -4.59e-13      1.000      -0.001       0.001
C(item_nbr)[T.83]  -1.958e-16      0.000  -4.66e-13      1.000      -0.001       0.001
C(item_nbr)[T.84]  -7.626e-17      0.000  -1.82e-13      1.000      -0.001       0.001
C(item_nbr)[T.85]   -1.89e-16      0.000   -4.5e-13      1.000      -0.001       0.001
C(item_nbr)[T.86]  -1.781e-16      0.000  -4.24e-13      1.000      -0.001       0.001
C(item_nbr)[T.87]  -2.132e-16      0.000  -5.08e-13      1.000      -0.001       0.001
C(item_nbr)[T.88]   1.548e-07      0.000      0.000      1.000      -0.001       0.001
C(item_nbr)[T.89]  -1.462e-16      0.000  -3.48e-13      1.000      -0.001       0.001
C(item_nbr)[T.90]  -1.192e-16      0.000  -2.84e-13      1.000      -0.001       0.001
C(item_nbr)[T.91]  -2.768e-16      0.000  -6.59e-13      1.000      -0.001       0.001
C(item_nbr)[T.92]  -1.189e-16      0.000  -2.83e-13      1.000      -0.001       0.001
C(item_nbr)[T.93]  -6.487e-08      0.000     -0.000      1.000      -0.001       0.001
C(item_nbr)[T.94]  -3.434e-16      0.000  -8.18e-13      1.000      -0.001       0.001
C(item_nbr)[T.95]  -3.326e-17      0.000  -7.92e-14      1.000      -0.001       0.001
C(item_nbr)[T.96]  -1.559e-16      0.000  -3.71e-13      1.000      -0.001       0.001
C(item_nbr)[T.97]   -1.62e-16      0.000  -3.86e-13      1.000      -0.001       0.001
C(item_nbr)[T.98]  -1.896e-16      0.000  -4.52e-13      1.000      -0.001       0.001
C(item_nbr)[T.99]  -6.478e-17      0.000  -1.54e-13      1.000      -0.001       0.001
C(item_nbr)[T.100] -1.832e-16      0.000  -4.36e-13      1.000      -0.001       0.001
C(item_nbr)[T.101]  8.528e-17      0.000   2.03e-13      1.000      -0.001       0.001
C(item_nbr)[T.102]  6.443e-17      0.000   1.53e-13      1.000      -0.001       0.001
C(item_nbr)[T.103]  1.898e-16      0.000   4.52e-13      1.000      -0.001       0.001
C(item_nbr)[T.104] -1.879e-16      0.000  -4.48e-13      1.000      -0.001       0.001
C(item_nbr)[T.105]  -1.05e-16      0.000   -2.5e-13      1.000      -0.001       0.001
C(item_nbr)[T.106]  1.343e-17      0.000    3.2e-14      1.000      -0.001       0.001
C(item_nbr)[T.107]  2.668e-17      0.000   6.35e-14      1.000      -0.001       0.001
C(item_nbr)[T.108] -5.508e-16      0.000  -1.31e-12      1.000      -0.001       0.001
C(item_nbr)[T.109] -6.913e-16      0.000  -1.65e-12      1.000      -0.001       0.001
C(item_nbr)[T.110]  -4.23e-16      0.000  -1.01e-12      1.000      -0.001       0.001
C(item_nbr)[T.111] -3.988e-16      0.000   -9.5e-13      1.000      -0.001       0.001
scale(cool)          5.47e-05   3.72e-05      1.469      0.142   -1.83e-05       0.000
scale(preciptotal) -3.516e-06   3.09e-05     -0.114      0.909    -6.4e-05     5.7e-05
==============================================================================
Omnibus:                   194372.607   Durbin-Watson:                   2.000
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       2967926962.093
Skew:                          -2.958   Prob(JB):                         0.00
Kurtosis:                     592.207   Cond. No.                         123.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### Anova 분석을 통해 p-value가 0.05보다 큰것은 제외

In [50]:
anova_result2_1 = sm.stats.anova_lm(result2_1).sort_values(by=['PR(>F)'], ascending = False)
anova_result2_1[anova_result2_1['PR(>F)'] <= 0.05]

C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)

                 df       sum_sq    mean_sq              F         PR(>F)
C(rainY)        1.0     0.023462   0.023462     139.795789   3.022470e-32
C(weekend)      1.0     0.059698   0.059698     355.707887   2.828115e-79
C(store_nbr)    1.0     0.061106   0.061106     364.093999   4.252491e-81
C(month)       11.0     0.185301   0.016846     100.372941  3.188750e-229
C(year)         3.0     9.256960   3.085653   18385.682456   0.000000e+00
C(item_nbr)   110.0  2941.745846  26.743144  159347.443380   0.000000e+00

### 최종 Anova 분석과 TIF 통과한 변수들을 바탕으로 최종 모델생성

In [53]:
# OLS - df2_1_1
model2_1 = sm.OLS.from_formula('log1p_units ~ C(year) + C(month) +C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2_1)

result = model2_1.fit()
result2_1 = model2_1.fit()
print(result2_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.988
Model:                            OLS   Adj. R-squared:                  0.988
Method:                 Least Squares   F-statistic:                 1.391e+05
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        13:27:17   Log-Likelihood:             6.0063e+05
No. Observations:              205156   AIC:                        -1.201e+06
Df Residuals:                  205029   BIC:                        -1.200e+06
Df Model:                         126
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
C(year)[2012]       4.349e-05      0.000      0.138      0.890      -0.001       0.001
C(year)[2013]       8.572e-05      0.000      0.272      0.786      -0.001       0.001
C(year)[2014]       3.038e-05      0.000      0.096      0.923      -0.001       0.001
C(month)[T.2]         -0.0002      0.000     -1.504      0.133      -0.000    6.06e-05
C(month)[T.3]       2.675e-05      0.000      0.203      0.839      -0.000       0.000
C(month)[T.4]      -9.967e-06      0.000     -0.076      0.940      -0.000       0.000
C(month)[T.5]       9.377e-05      0.000      0.722      0.470      -0.000       0.000
C(month)[T.6]         -0.0002      0.000     -1.352      0.177      -0.000    8.46e-05
C(month)[T.7]         -0.0001      0.000     -0.762      0.446      -0.000       0.000
C(month)[T.8]      -3.412e-05      0.000     -0.252      0.801      -0.000       0.000
C(month)[T.9]      -9.837e-05      0.000     -0.736      0.462      -0.000       0.000
C(month)[T.10]      6.362e-05      0.000      0.479      0.632      -0.000       0.000
C(month)[T.11]        -0.0001      0.000     -0.674      0.500      -0.000       0.000
C(month)[T.12]        -0.0002      0.000     -1.347      0.178      -0.001    9.33e-05
C(weekend)[T.1]     3.786e-05   6.34e-05      0.597      0.551   -8.65e-05       0.000
C(rainY)[T.1]      -2.302e-05   5.76e-05     -0.400      0.689      -0.000    8.98e-05
C(store_nbr)[T.45]  6.764e-07   5.72e-05      0.012      0.991      -0.000       0.000
C(item_nbr)[T.2]    1.694e-15      0.000   4.04e-12      1.000      -0.001       0.001
C(item_nbr)[T.3]    9.411e-16      0.000   2.24e-12      1.000      -0.001       0.001
C(item_nbr)[T.4]    1.666e-06      0.000      0.004      0.997      -0.001       0.001
C(item_nbr)[T.5]    1.131e-15      0.000   2.69e-12      1.000      -0.001       0.001
C(item_nbr)[T.6]    1.342e-15      0.000    3.2e-12      1.000      -0.001       0.001
C(item_nbr)[T.7]    9.941e-16      0.000   2.37e-12      1.000      -0.001       0.001
C(item_nbr)[T.8]    9.181e-16      0.000   2.19e-12      1.000      -0.001       0.001
C(item_nbr)[T.9]       2.3246      0.001   3593.070      0.000       2.323       2.326
C(item_nbr)[T.10]    9.68e-16      0.000   2.31e-12      1.000      -0.001       0.001
C(item_nbr)[T.11]   9.001e-16      0.000   2.14e-12      1.000      -0.001       0.001
C(item_nbr)[T.12]   8.842e-16      0.000   2.11e-12      1.000      -0.001       0.001
C(item_nbr)[T.13]   8.718e-16      0.000   2.08e-12      1.000      -0.001       0.001
C(item_nbr)[T.14]   1.061e-15      0.000   2.53e-12      1.000      -0.001       0.001
C(item_nbr)[T.15]  -7.673e-07      0.000     -0.002      0.999      -0.001       0.001
C(item_nbr)[T.16]   9.599e-16      0.000   2.29e-12      1.000      -0.001       0.001
C(item_nbr)[T.17]    9.83e-16      0.000   2.34e-12      1.000      -0.001       0.001
C(item_nbr)[T.18]   9.107e-16      0.000   2.17e-12      1.000      -0.001       0.001
C(item_nbr)[T.19]   9.398e-16      0.000   2.24e-12      1.000      -0.001       0.001
C(item_nbr)[T.20]   9.485e-16      0.000   2.26e-12      1.000      -0.001       0.001
C(item_nbr)[T.21]   9.382e-16      0.000   2.23e-12      1.000      -0.001       0.001
C(item_nbr)[T.22]  -4.578e-07      0.000     -0.001      0.999      -0.001       0.001
C(item_nbr)[T.23]    9.17e-16      0.000   2.18e-12      1.000      -0.001       0.001
C(item_nbr)[T.24]    8.72e-16      0.000   2.08e-12      1.000      -0.001       0.001
C(item_nbr)[T.25]      1.3554      0.001    905.299      0.000       1.352       1.358
C(item_nbr)[T.26]      0.6932      0.001    592.096      0.000       0.691       0.695
C(item_nbr)[T.27]   1.353e-15      0.000   3.22e-12      1.000      -0.001       0.001
C(item_nbr)[T.28]   9.605e-16      0.000   2.29e-12      1.000      -0.001       0.001
C(item_nbr)[T.29]   9.185e-16      0.000   2.19e-12      1.000      -0.001       0.001
C(item_nbr)[T.30]   9.328e-16      0.000   2.22e-12      1.000      -0.001       0.001
C(item_nbr)[T.31]   9.271e-16      0.000   2.21e-12      1.000      -0.001       0.001
C(item_nbr)[T.32]   9.721e-16      0.000   2.32e-12      1.000      -0.001       0.001
C(item_nbr)[T.33]  -9.461e-07      0.000     -0.002      0.998      -0.001       0.001
C(item_nbr)[T.34]  -1.859e-06      0.000     -0.004      0.996      -0.001       0.001
C(item_nbr)[T.35]   9.418e-16      0.000   2.24e-12      1.000      -0.001       0.001
C(item_nbr)[T.36]   9.046e-16      0.000   2.15e-12      1.000      -0.001       0.001
C(item_nbr)[T.37]   9.196e-16      0.000   2.19e-12      1.000      -0.001       0.001
C(item_nbr)[T.38]   9.635e-16      0.000   2.29e-12      1.000      -0.001       0.001
C(item_nbr)[T.39]   8.937e-16      0.000   2.13e-12      1.000      -0.001       0.001
C(item_nbr)[T.40]   9.132e-16      0.000   2.17e-12      1.000      -0.001       0.001
C(item_nbr)[T.41]   9.323e-16      0.000   2.22e-12      1.000      -0.001       0.001
C(item_nbr)[T.42]   9.238e-16      0.000    2.2e-12      1.000      -0.001       0.001
C(item_nbr)[T.43]   9.795e-16      0.000   2.33e-12      1.000      -0.001       0.001
C(item_nbr)[T.44]   9.332e-16      0.000   2.22e-12      1.000      -0.001       0.001
C(item_nbr)[T.45]   8.975e-16      0.000   2.14e-12      1.000      -0.001       0.001
C(item_nbr)[T.46]   9.935e-16      0.000   2.37e-12      1.000      -0.001       0.001
C(item_nbr)[T.47]   9.684e-16      0.000   2.31e-12      1.000      -0.001       0.001
C(item_nbr)[T.48]   9.201e-16      0.000   2.19e-12      1.000      -0.001       0.001
C(item_nbr)[T.49]   8.826e-16      0.000    2.1e-12      1.000      -0.001       0.001
C(item_nbr)[T.50]  -4.424e-06      0.000     -0.010      0.992      -0.001       0.001
C(item_nbr)[T.51]   9.188e-16      0.000   2.19e-12      1.000      -0.001       0.001
C(item_nbr)[T.52]   8.956e-16      0.000   2.13e-12      1.000      -0.001       0.001
C(item_nbr)[T.53]   9.125e-16      0.000   2.17e-12      1.000      -0.001       0.001
C(item_nbr)[T.54]   9.236e-16      0.000    2.2e-12      1.000      -0.001       0.001
C(item_nbr)[T.55]   9.189e-16      0.000   2.19e-12      1.000      -0.001       0.001
C(item_nbr)[T.56]   9.339e-16      0.000   2.22e-12      1.000      -0.001       0.001
C(item_nbr)[T.57]   9.148e-16      0.000   2.18e-12      1.000      -0.001       0.001
C(item_nbr)[T.58]   9.804e-16      0.000   2.33e-12      1.000      -0.001       0.001
C(item_nbr)[T.59]   9.062e-16      0.000   2.16e-12      1.000      -0.001       0.001
C(item_nbr)[T.60]   9.133e-16      0.000   2.18e-12      1.000      -0.001       0.001
C(item_nbr)[T.61]   9.584e-16      0.000   2.28e-12      1.000      -0.001       0.001
C(item_nbr)[T.62]   9.859e-16      0.000   2.35e-12      1.000      -0.001       0.001
C(item_nbr)[T.63]   9.129e-16      0.000   2.17e-12      1.000      -0.001       0.001
C(item_nbr)[T.64]   9.684e-16      0.000   2.31e-12      1.000      -0.001       0.001
C(item_nbr)[T.65]   9.464e-16      0.000   2.25e-12      1.000      -0.001       0.001
C(item_nbr)[T.66]    9.13e-16      0.000   2.17e-12      1.000      -0.001       0.001
C(item_nbr)[T.67]    9.49e-16      0.000   2.26e-12      1.000      -0.001       0.001
C(item_nbr)[T.68]   9.397e-16      0.000   2.24e-12      1.000      -0.001       0.001
C(item_nbr)[T.69]   9.564e-16      0.000   2.28e-12      1.000      -0.001       0.001
C(item_nbr)[T.70]   4.329e-06      0.000      0.010      0.992      -0.001       0.001
C(item_nbr)[T.71]    9.03e-16      0.000   2.15e-12      1.000      -0.001       0.001
C(item_nbr)[T.72]   9.254e-16      0.000    2.2e-12      1.000      -0.001       0.001
C(item_nbr)[T.73]   9.268e-16      0.000   2.21e-12      1.000      -0.001       0.001
C(item_nbr)[T.74]   8.814e-16      0.000    2.1e-12      1.000      -0.001       0.001
C(item_nbr)[T.75]   9.346e-16      0.000   2.23e-12      1.000      -0.001       0.001
C(item_nbr)[T.76]   8.868e-16      0.000   2.11e-12      1.000      -0.001       0.001
C(item_nbr)[T.77]   8.309e-16      0.000   1.98e-12      1.000      -0.001       0.001
C(item_nbr)[T.78]   9.465e-16      0.000   2.25e-12      1.000      -0.001       0.001
C(item_nbr)[T.79]   8.843e-16      0.000   2.11e-12      1.000      -0.001       0.001
C(item_nbr)[T.80]   8.438e-16      0.000   2.01e-12      1.000      -0.001       0.001
C(item_nbr)[T.81]   9.699e-16      0.000   2.31e-12      1.000      -0.001       0.001
C(item_nbr)[T.82]   9.782e-16      0.000   2.33e-12      1.000      -0.001       0.001
C(item_nbr)[T.83]   9.428e-16      0.000   2.25e-12      1.000      -0.001       0.001
C(item_nbr)[T.84]   8.655e-16      0.000   2.06e-12      1.000      -0.001       0.001
C(item_nbr)[T.85]   8.954e-16      0.000   2.13e-12      1.000      -0.001       0.001
C(item_nbr)[T.86]   1.021e-15      0.000   2.43e-12      1.000      -0.001       0.001
C(item_nbr)[T.87]   8.301e-16      0.000   1.98e-12      1.000      -0.001       0.001
C(item_nbr)[T.88]   3.485e-08      0.000   8.25e-05      1.000      -0.001       0.001
C(item_nbr)[T.89]   9.269e-16      0.000   2.21e-12      1.000      -0.001       0.001
C(item_nbr)[T.90]   1.021e-15      0.000   2.43e-12      1.000      -0.001       0.001
C(item_nbr)[T.91]   8.513e-16      0.000   2.03e-12      1.000      -0.001       0.001
C(item_nbr)[T.92]   9.387e-16      0.000   2.24e-12      1.000      -0.001       0.001
C(item_nbr)[T.93]  -9.222e-08      0.000     -0.000      1.000      -0.001       0.001
C(item_nbr)[T.94]   9.481e-16      0.000   2.26e-12      1.000      -0.001       0.001
C(item_nbr)[T.95]   8.921e-16      0.000   2.12e-12      1.000      -0.001       0.001
C(item_nbr)[T.96]   8.349e-16      0.000   1.99e-12      1.000      -0.001       0.001
C(item_nbr)[T.97]   8.839e-16      0.000   2.11e-12      1.000      -0.001       0.001
C(item_nbr)[T.98]   9.292e-16      0.000   2.21e-12      1.000      -0.001       0.001
C(item_nbr)[T.99]   1.047e-15      0.000   2.49e-12      1.000      -0.001       0.001
C(item_nbr)[T.100]  1.013e-15      0.000   2.41e-12      1.000      -0.001       0.001
C(item_nbr)[T.101]  9.049e-16      0.000   2.16e-12      1.000      -0.001       0.001
C(item_nbr)[T.102]  9.024e-16      0.000   2.15e-12      1.000      -0.001       0.001
C(item_nbr)[T.103]  8.902e-16      0.000   2.12e-12      1.000      -0.001       0.001
C(item_nbr)[T.104]  9.024e-16      0.000   2.15e-12      1.000      -0.001       0.001
C(item_nbr)[T.105]  5.861e-16      0.000    1.4e-12      1.000      -0.001       0.001
C(item_nbr)[T.106]   8.34e-16      0.000   1.99e-12      1.000      -0.001       0.001
C(item_nbr)[T.107]  1.127e-15      0.000   2.68e-12      1.000      -0.001       0.001
C(item_nbr)[T.108]  9.845e-16      0.000   2.34e-12      1.000      -0.001       0.001
C(item_nbr)[T.109]  8.705e-16      0.000   2.07e-12      1.000      -0.001       0.001
C(item_nbr)[T.110]  2.398e-16      0.000   5.71e-13      1.000      -0.001       0.001
C(item_nbr)[T.111]  1.972e-15      0.000    4.7e-12      1.000      -0.001       0.001
==============================================================================
Omnibus:                   194371.557   Durbin-Watson:                   2.000
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       2967927276.109
Skew:                          -2.958   Prob(JB):                         0.00
Kurtosis:                     592.207   Cond. No.                         121.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [54]:
from patsy import dmatrix
# 독립변수와 종속변수로 나누기
df2_1_X = df2_1.drop(columns=['log1p_units'])
df2_1_target = df2_1['log1p_units']

In [55]:
formula = 'C(year) + C(month) + C(weekend) + C(item_nbr) + 0'
dfX = dmatrix(formula, df2_1_X, return_type='dataframe')
dfy = pd.DataFrame(df2_1_target, columns=["log1p_units"])

In [56]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold
from sklearn.metrics import r2_score

model = LinearRegression()
cv = KFold(10)

scores = np.zeros(10)
for i, (train_index, test_index) in enumerate(cv.split(dfX)):
    X_train = dfX.values[train_index]
    y_train = dfy.values[train_index]
    X_test = dfX.values[test_index]
    y_test = dfy.values[test_index]
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    scores[i] = r2_score(y_test, y_pred)

scores

array([0.99013256, 0.988091  , 0.98574209, 0.98998727, 0.98901424,
       0.99025732, 0.98742604, 0.98804902, 0.98734554, 0.98869103])