In [1]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import KFold
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

In [2]:
weather = pd.read_csv("weather3_180703.csv")
weather['date'] = pd.to_datetime(weather["date"])
station = weather[weather['station_nbr'] == 14]

In [3]:
station['date'].count()

1035

In [4]:
# ls == 모든 값이 0인 것

ls = []
ls1 = []
for i in station.columns:
    if station[i].count() == 0:
        ls.append(i)
    if station[i].isna().sum() != 0:
        ls1.append(i)
ls, ls1

([], ['depart', 'sunrise', 'sunset', 'resultdir', 'daytime'])

In [5]:
for i in station.columns:
    count_null = station[i].isna().sum()
    print(i, ":", count_null, "(",round((count_null / len(station) * 100),2),"%",")")

station_nbr : 0 ( 0.0 % )
date : 0 ( 0.0 % )
tmax : 0 ( 0.0 % )
tmin : 0 ( 0.0 % )
tavg : 0 ( 0.0 % )
depart : 31 ( 3.0 % )
dewpoint : 0 ( 0.0 % )
wetbulb : 0 ( 0.0 % )
heat : 0 ( 0.0 % )
cool : 0 ( 0.0 % )
sunrise : 31 ( 3.0 % )
sunset : 31 ( 3.0 % )
codesum : 0 ( 0.0 % )
snowfall : 0 ( 0.0 % )
preciptotal : 0 ( 0.0 % )
stnpressure : 0 ( 0.0 % )
sealevel : 0 ( 0.0 % )
resultspeed : 0 ( 0.0 % )
resultdir : 2 ( 0.19 % )
avgspeed : 0 ( 0.0 % )
year : 0 ( 0.0 % )
month : 0 ( 0.0 % )
day : 0 ( 0.0 % )
relative_humility : 0 ( 0.0 % )
windchill : 0 ( 0.0 % )
daytime : 31 ( 3.0 % )
week7 : 0 ( 0.0 % )
weekend : 0 ( 0.0 % )
code_change : 0 ( 0.0 % )
rainY : 0 ( 0.0 % )
otherY : 0 ( 0.0 % )
nothing : 0 ( 0.0 % )

In [6]:
train = pd.read_csv("train.csv")
train.date = pd.to_datetime(train.date)
train.tail()

              date  store_nbr  item_nbr  units
4617595 2014-10-31         45       107      0
4617596 2014-10-31         45       108      0
4617597 2014-10-31         45       109      0
4617598 2014-10-31         45       110      0
4617599 2014-10-31         45       111      0

In [7]:
key = pd.read_csv("key.csv")
station = station.merge(key)

In [8]:
station = station.merge(train)
station.tail()

,station_nbr,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,...,daytime,week7,weekend,code_change,rainY,otherY,nothing,store_nbr,item_nbr,units
388495,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,107,0
388496,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,108,0
388497,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,109,0
388498,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,110,0
388499,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,111,0

In [9]:
station['log1p_units'] = np.log1p(station.units)

In [10]:
target1 = station['units']
target2 = station['log1p_units']

station.drop(columns=['units','log1p_units'],inplace=True)
station.tail()

,station_nbr,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,...,windchill,daytime,week7,weekend,code_change,rainY,otherY,nothing,store_nbr,item_nbr
388495,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,44.019672,10.766667,4,0,0,0,0,1,42,107
388496,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,44.019672,10.766667,4,0,0,0,0,1,42,108
388497,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,44.019672,10.766667,4,0,0,0,0,1,42,109
388498,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,44.019672,10.766667,4,0,0,0,0,1,42,110
388499,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,44.019672,10.766667,4,0,0,0,0,1,42,111

In [11]:
df1 = pd.concat([station,target1], axis=1)
df2 = pd.concat([station,target2], axis=1)

In [12]:
df2.to_csv('station14.csv', sep=',', index=False)

In [13]:
if df2.columns.tolist() and ls:
    print('공통 변수 있음')
    print(df2.columns.tolist() and ls)
else:
    print('공통 변수 없음')

공통 변수 없음

In [14]:
df2.columns

Index(['station_nbr', 'date', 'tmax', 'tmin', 'tavg', 'depart', 'dewpoint',
       'wetbulb', 'heat', 'cool', 'sunrise', 'sunset', 'codesum', 'snowfall',
       'preciptotal', 'stnpressure', 'sealevel', 'resultspeed', 'resultdir',
       'avgspeed', 'year', 'month', 'day', 'relative_humility', 'windchill',
       'daytime', 'week7', 'weekend', 'code_change', 'rainY', 'otherY',
       'nothing', 'store_nbr', 'item_nbr', 'log1p_units'],
      dtype='object')

In [15]:
ls, ls1

([], ['depart', 'sunrise', 'sunset', 'resultdir', 'daytime'])

### 1. 변수변환: df2 (log1p_units)

In [19]:
all_var = 'log1p_units ~ scale(tmax) + scale(tmin) + scale(tavg) + scale(depart) + scale(dewpoint) + scale(wetbulb) + scale(heat) + scale(cool)\
                            + scale(sunrise) + scale(sunset) + scale(snowfall) + scale(preciptotal) + scale(stnpressure) + scale(sealevel) + scale(resultspeed)  \
                            + C(resultdir) + scale(avgspeed) + C(year) + C(month) + scale(relative_humility) + scale(windchill) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + C(daytime) + 0'

In [16]:
model2 = sm.OLS.from_formula('log1p_units ~ scale(tmax) + scale(tmin) + scale(tavg) + scale(dewpoint) + scale(wetbulb) + scale(heat) + scale(cool)\
                            + scale(snowfall) + scale(preciptotal) + scale(stnpressure) + scale(sealevel) + scale(resultspeed)  \
                            + scale(avgspeed) + C(year) + C(month) + scale(relative_humility) + scale(windchill) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2)
result2 = model2.fit()
print(result2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.527
Model:                            OLS   Adj. R-squared:                  0.526
Method:                 Least Squares   F-statistic:                     3041.
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:42:41   Log-Likelihood:            -1.8333e+05
No. Observations:              388500   AIC:                         3.669e+05
Df Residuals:                  388357   BIC:                         3.685e+05
Df Model:                         142
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
C(year)[2012]                0.0072      0.007      1.007      0.314      -0.007       0.021
C(year)[2013]                0.0042      0.007      0.584      0.559      -0.010       0.018
C(year)[2014]                0.0014      0.007      0.195      0.846      -0.013       0.016
C(month)[T.2]               -0.0019      0.003     -0.660      0.509      -0.008       0.004
C(month)[T.3]               -0.0014      0.003     -0.462      0.644      -0.007       0.004
C(month)[T.4]               -0.0014      0.004     -0.402      0.687      -0.008       0.006
C(month)[T.5]               -0.0005      0.004     -0.126      0.900      -0.008       0.007
C(month)[T.6]                0.0010      0.005      0.227      0.820      -0.008       0.010
C(month)[T.7]                0.0030      0.005      0.573      0.566      -0.007       0.013
C(month)[T.8]                0.0004      0.005      0.078      0.938      -0.009       0.010
C(month)[T.9]            -3.555e-05      0.004     -0.008      0.993      -0.009       0.008
C(month)[T.10]              -0.0026      0.003     -0.756      0.450      -0.009       0.004
C(month)[T.11]              -0.0022      0.003     -0.664      0.507      -0.009       0.004
C(month)[T.12]              -0.0026      0.003     -0.803      0.422      -0.009       0.004
C(weekend)[T.1]              0.0047      0.001      3.360      0.001       0.002       0.007
C(rainY)[T.1]                0.0010      0.002      0.538      0.590      -0.003       0.004
C(store_nbr)[T.6]           -0.0094      0.002     -5.360      0.000      -0.013      -0.006
C(store_nbr)[T.38]           0.0014      0.002      0.813      0.416      -0.002       0.005
C(store_nbr)[T.42]          -0.0144      0.002     -8.207      0.000      -0.018      -0.011
C(item_nbr)[T.2]          1.574e-14      0.009    1.7e-12      1.000      -0.018       0.018
C(item_nbr)[T.3]          1.694e-14      0.009   1.83e-12      1.000      -0.018       0.018
C(item_nbr)[T.4]          1.449e-14      0.009   1.56e-12      1.000      -0.018       0.018
C(item_nbr)[T.5]             1.8709      0.009    201.740      0.000       1.853       1.889
C(item_nbr)[T.6]          1.357e-14      0.009   1.46e-12      1.000      -0.018       0.018
C(item_nbr)[T.7]          2.565e-14      0.009   2.77e-12      1.000      -0.018       0.018
C(item_nbr)[T.8]          1.203e-14      0.009    1.3e-12      1.000      -0.018       0.018
C(item_nbr)[T.9]             2.0233      0.009    218.169      0.000       2.005       2.041
C(item_nbr)[T.10]         1.108e-15      0.009    1.2e-13      1.000      -0.018       0.018
C(item_nbr)[T.11]            0.0931      0.009     10.043      0.000       0.075       0.111
C(item_nbr)[T.12]         1.398e-14      0.009   1.51e-12      1.000      -0.018       0.018
C(item_nbr)[T.13]         1.596e-14      0.009   1.72e-12      1.000      -0.018       0.018
C(item_nbr)[T.14]            0.0445      0.009      4.799      0.000       0.026       0.063
C(item_nbr)[T.15]         1.647e-14      0.009   1.78e-12      1.000      -0.018       0.018
C(item_nbr)[T.16]         1.213e-14      0.009   1.31e-12      1.000      -0.018       0.018
C(item_nbr)[T.17]         1.059e-14      0.009   1.14e-12      1.000      -0.018       0.018
C(item_nbr)[T.18]         1.577e-14      0.009    1.7e-12      1.000      -0.018       0.018
C(item_nbr)[T.19]         1.358e-14      0.009   1.46e-12      1.000      -0.018       0.018
C(item_nbr)[T.20]         1.985e-14      0.009   2.14e-12      1.000      -0.018       0.018
C(item_nbr)[T.21]         1.321e-14      0.009   1.42e-12      1.000      -0.018       0.018
C(item_nbr)[T.22]         1.624e-14      0.009   1.75e-12      1.000      -0.018       0.018
C(item_nbr)[T.23]         1.281e-14      0.009   1.38e-12      1.000      -0.018       0.018
C(item_nbr)[T.24]         9.863e-15      0.009   1.06e-12      1.000      -0.018       0.018
C(item_nbr)[T.25]         1.363e-14      0.009   1.47e-12      1.000      -0.018       0.018
C(item_nbr)[T.26]         1.409e-14      0.009   1.52e-12      1.000      -0.018       0.018
C(item_nbr)[T.27]         1.429e-14      0.009   1.54e-12      1.000      -0.018       0.018
C(item_nbr)[T.28]         1.497e-14      0.009   1.61e-12      1.000      -0.018       0.018
C(item_nbr)[T.29]         1.346e-14      0.009   1.45e-12      1.000      -0.018       0.018
C(item_nbr)[T.30]         2.018e-14      0.009   2.18e-12      1.000      -0.018       0.018
C(item_nbr)[T.31]         1.208e-14      0.009    1.3e-12      1.000      -0.018       0.018
C(item_nbr)[T.32]         1.508e-14      0.009   1.63e-12      1.000      -0.018       0.018
C(item_nbr)[T.33]         1.476e-14      0.009   1.59e-12      1.000      -0.018       0.018
C(item_nbr)[T.34]         2.169e-14      0.009   2.34e-12      1.000      -0.018       0.018
C(item_nbr)[T.35]         1.287e-14      0.009   1.39e-12      1.000      -0.018       0.018
C(item_nbr)[T.36]         1.751e-14      0.009   1.89e-12      1.000      -0.018       0.018
C(item_nbr)[T.37]         1.556e-14      0.009   1.68e-12      1.000      -0.018       0.018
C(item_nbr)[T.38]         1.297e-14      0.009    1.4e-12      1.000      -0.018       0.018
C(item_nbr)[T.39]         2.081e-14      0.009   2.24e-12      1.000      -0.018       0.018
C(item_nbr)[T.40]          1.21e-14      0.009    1.3e-12      1.000      -0.018       0.018
C(item_nbr)[T.41]         1.802e-14      0.009   1.94e-12      1.000      -0.018       0.018
C(item_nbr)[T.42]         1.415e-14      0.009   1.53e-12      1.000      -0.018       0.018
C(item_nbr)[T.43]         2.114e-14      0.009   2.28e-12      1.000      -0.018       0.018
C(item_nbr)[T.44]            1.2157      0.009    131.087      0.000       1.198       1.234
C(item_nbr)[T.45]            3.1864      0.009    343.595      0.000       3.168       3.205
C(item_nbr)[T.46]          1.46e-14      0.009   1.57e-12      1.000      -0.018       0.018
C(item_nbr)[T.47]         1.143e-14      0.009   1.23e-12      1.000      -0.018       0.018
C(item_nbr)[T.48]         1.209e-14      0.009    1.3e-12      1.000      -0.018       0.018
C(item_nbr)[T.49]         1.433e-14      0.009   1.54e-12      1.000      -0.018       0.018
C(item_nbr)[T.50]         1.357e-14      0.009   1.46e-12      1.000      -0.018       0.018
C(item_nbr)[T.51]         1.139e-14      0.009   1.23e-12      1.000      -0.018       0.018
C(item_nbr)[T.52]            0.1229      0.009     13.253      0.000       0.105       0.141
C(item_nbr)[T.53]         1.383e-14      0.009   1.49e-12      1.000      -0.018       0.018
C(item_nbr)[T.54]         1.412e-14      0.009   1.52e-12      1.000      -0.018       0.018
C(item_nbr)[T.55]         1.385e-14      0.009   1.49e-12      1.000      -0.018       0.018
C(item_nbr)[T.56]         1.352e-14      0.009   1.46e-12      1.000      -0.018       0.018
C(item_nbr)[T.57]         1.387e-14      0.009    1.5e-12      1.000      -0.018       0.018
C(item_nbr)[T.58]         1.103e-14      0.009   1.19e-12      1.000      -0.018       0.018
C(item_nbr)[T.59]          1.96e-14      0.009   2.11e-12      1.000      -0.018       0.018
C(item_nbr)[T.60]         1.369e-14      0.009   1.48e-12      1.000      -0.018       0.018
C(item_nbr)[T.61]         1.233e-14      0.009   1.33e-12      1.000      -0.018       0.018
C(item_nbr)[T.62]         1.473e-14      0.009   1.59e-12      1.000      -0.018       0.018
C(item_nbr)[T.63]         9.549e-15      0.009   1.03e-12      1.000      -0.018       0.018
C(item_nbr)[T.64]         1.267e-14      0.009   1.37e-12      1.000      -0.018       0.018
C(item_nbr)[T.65]         1.396e-14      0.009   1.51e-12      1.000      -0.018       0.018
C(item_nbr)[T.66]         1.433e-14      0.009   1.55e-12      1.000      -0.018       0.018
C(item_nbr)[T.67]         1.007e-14      0.009   1.09e-12      1.000      -0.018       0.018
C(item_nbr)[T.68]         1.367e-14      0.009   1.47e-12      1.000      -0.018       0.018
C(item_nbr)[T.69]         1.305e-14      0.009   1.41e-12      1.000      -0.018       0.018
C(item_nbr)[T.70]          1.33e-14      0.009   1.43e-12      1.000      -0.018       0.018
C(item_nbr)[T.71]         1.059e-14      0.009   1.14e-12      1.000      -0.018       0.018
C(item_nbr)[T.72]          1.17e-14      0.009   1.26e-12      1.000      -0.018       0.018
C(item_nbr)[T.73]         1.254e-14      0.009   1.35e-12      1.000      -0.018       0.018
C(item_nbr)[T.74]         1.379e-14      0.009   1.49e-12      1.000      -0.018       0.018
C(item_nbr)[T.75]         1.336e-14      0.009   1.44e-12      1.000      -0.018       0.018
C(item_nbr)[T.76]          1.29e-14      0.009   1.39e-12      1.000      -0.018       0.018
C(item_nbr)[T.77]         1.445e-14      0.009   1.56e-12      1.000      -0.018       0.018
C(item_nbr)[T.78]         1.311e-14      0.009   1.41e-12      1.000      -0.018       0.018
C(item_nbr)[T.79]         1.354e-14      0.009   1.46e-12      1.000      -0.018       0.018
C(item_nbr)[T.80]         1.235e-14      0.009   1.33e-12      1.000      -0.018       0.018
C(item_nbr)[T.81]         1.214e-14      0.009   1.31e-12      1.000      -0.018       0.018
C(item_nbr)[T.82]            0.0737      0.009      7.947      0.000       0.056       0.092
C(item_nbr)[T.83]         1.272e-14      0.009   1.37e-12      1.000      -0.018       0.018
C(item_nbr)[T.84]         1.413e-14      0.009   1.52e-12      1.000      -0.018       0.018
C(item_nbr)[T.85]            0.0170      0.009      1.831      0.067      -0.001       0.035
C(item_nbr)[T.86]            0.0105      0.009      1.133      0.257      -0.008       0.029
C(item_nbr)[T.87]         1.486e-14      0.009    1.6e-12      1.000      -0.018       0.018
C(item_nbr)[T.88]         1.326e-14      0.009   1.43e-12      1.000      -0.018       0.018
C(item_nbr)[T.89]         1.354e-14      0.009   1.46e-12      1.000      -0.018       0.018
C(item_nbr)[T.90]         1.443e-14      0.009   1.56e-12      1.000      -0.018       0.018
C(item_nbr)[T.91]         1.082e-14      0.009   1.17e-12      1.000      -0.018       0.018
C(item_nbr)[T.92]         1.074e-14      0.009   1.16e-12      1.000      -0.018       0.018
C(item_nbr)[T.93]            0.1091      0.009     11.764      0.000       0.091       0.127
C(item_nbr)[T.94]         1.324e-14      0.009   1.43e-12      1.000      -0.018       0.018
C(item_nbr)[T.95]         1.321e-14      0.009   1.42e-12      1.000      -0.018       0.018
C(item_nbr)[T.96]         1.217e-14      0.009   1.31e-12      1.000      -0.018       0.018
C(item_nbr)[T.97]         1.473e-14      0.009   1.59e-12      1.000      -0.018       0.018
C(item_nbr)[T.98]            0.0748      0.009      8.071      0.000       0.057       0.093
C(item_nbr)[T.99]         1.278e-14      0.009   1.38e-12      1.000      -0.018       0.018
C(item_nbr)[T.100]        1.227e-14      0.009   1.32e-12      1.000      -0.018       0.018
C(item_nbr)[T.101]         1.44e-14      0.009   1.55e-12      1.000      -0.018       0.018
C(item_nbr)[T.102]        1.025e-14      0.009    1.1e-12      1.000      -0.018       0.018
C(item_nbr)[T.103]        1.507e-14      0.009   1.62e-12      1.000      -0.018       0.018
C(item_nbr)[T.104]        1.173e-14      0.009   1.26e-12      1.000      -0.018       0.018
C(item_nbr)[T.105]        1.576e-14      0.009    1.7e-12      1.000      -0.018       0.018
C(item_nbr)[T.106]        1.269e-14      0.009   1.37e-12      1.000      -0.018       0.018
C(item_nbr)[T.107]           0.0716      0.009      7.717      0.000       0.053       0.090
C(item_nbr)[T.108]        9.441e-15      0.009   1.02e-12      1.000      -0.018       0.018
C(item_nbr)[T.109]        1.263e-14      0.009   1.36e-12      1.000      -0.018       0.018
C(item_nbr)[T.110]        1.501e-14      0.009   1.62e-12      1.000      -0.018       0.018
C(item_nbr)[T.111]        1.151e-14      0.009   1.24e-12      1.000      -0.018       0.018
scale(tmax)                  0.0025      0.009      0.280      0.780      -0.015       0.020
scale(tmin)                  0.0039      0.008      0.462      0.644      -0.013       0.020
scale(tavg)                  0.0032      0.009      0.377      0.706      -0.014       0.020
scale(dewpoint)             -0.0009      0.011     -0.086      0.931      -0.022       0.020
scale(wetbulb)               0.0011      0.010      0.108      0.914      -0.018       0.020
scale(heat)                  0.0024      0.006      0.415      0.678      -0.009       0.014
scale(cool)                 -0.0015      0.004     -0.393      0.694      -0.009       0.006
scale(snowfall)              0.0002      0.001      0.265      0.791      -0.001       0.001
scale(preciptotal)           0.0005      0.001      0.731      0.465      -0.001       0.002
scale(stnpressure)          -0.0004      0.004     -0.097      0.923      -0.008       0.007
scale(sealevel)              0.0002      0.004      0.043      0.966      -0.008       0.009
scale(resultspeed)          -0.0008      0.001     -0.571      0.568      -0.003       0.002
scale(avgspeed)              0.0005      0.002      0.313      0.754      -0.003       0.004
scale(relative_humility)     0.0002      0.004      0.054      0.957      -0.007       0.008
scale(windchill)            -0.0074      0.022     -0.336      0.737      -0.051       0.036
==============================================================================
Omnibus:                   177002.795   Durbin-Watson:                   2.465
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         29506315.405
Skew:                           1.121   Prob(JB):                         0.00
Kurtosis:                      45.635   Cond. No.                     2.25e+15
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 6.23e-25. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

### 2. 변수변환 : df2 (log1p_units) + 아웃라이어 제거

In [17]:
# 아웃라이어 제거
# Cook's distance > 2 인 값 제거
influence = result2.get_influence()
cooks_d2, pvals = influence.cooks_distance
fox_cr = 4 / (len(df2) - 2)
idx_outlier = np.where(cooks_d2 > fox_cr)[0]
len(idx_outlier)

14505

In [18]:
idx = list(set(range(len(df2))).difference(idx_outlier))
df2_1 = df2.iloc[idx, :].reset_index(drop=True)
df2_1

,station_nbr,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,...,daytime,week7,weekend,code_change,rainY,otherY,nothing,store_nbr,item_nbr,log1p_units
0,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,1,0.0
1,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,2,0.0
2,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,3,0.0
3,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,4,0.0
4,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,6,0.0
5,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,7,0.0
6,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,8,0.0
7,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,10,0.0
8,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,11,0.0
9,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,12,0.0
10,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,13,0.0
11,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,14,0.0
12,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,15,0.0
13,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,16,0.0
14,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,17,0.0
15,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,18,0.0
16,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,19,0.0
17,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,20,0.0
18,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,21,0.0
19,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,22,0.0
20,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,23,0.0
21,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,24,0.0
22,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,25,0.0
23,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,26,0.0
24,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,27,0.0
25,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,28,0.0
26,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,29,0.0
27,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,30,0.0
28,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,31,0.0
29,14,2012-01-01,50.0,34.0,42.0,5.0,25.0,35.0,23.0,0.0,...,9.833333,6,1,0,0,0,1,2,32,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373965,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,82,0.0
373966,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,83,0.0
373967,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,84,0.0
373968,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,85,0.0
373969,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,86,0.0
373970,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,87,0.0
373971,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,88,0.0
373972,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,89,0.0
373973,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,90,0.0
373974,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,91,0.0
373975,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,92,0.0
373976,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,93,0.0
373977,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,94,0.0
373978,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,95,0.0
373979,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,96,0.0
373980,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,97,0.0
373981,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,98,0.0
373982,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,99,0.0
373983,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,100,0.0
373984,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,101,0.0
373985,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,102,0.0
373986,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,103,0.0
373987,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,104,0.0
373988,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,105,0.0
373989,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,106,0.0
373990,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,107,0.0
373991,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,108,0.0
373992,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,109,0.0
373993,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,110,0.0
373994,14,2014-10-31,60.0,38.0,49.0,-7.0,31.0,42.0,16.0,0.0,...,10.766667,4,0,0,0,0,1,42,111,0.0

In [19]:
# OLS - df2_1
model2_1 = sm.OLS.from_formula('log1p_units ~ scale(tmax) + scale(tmin) + scale(tavg) + scale(dewpoint) + scale(wetbulb) + scale(heat) + scale(cool)\
                            + scale(snowfall) + scale(preciptotal) + scale(stnpressure) + scale(sealevel) + scale(resultspeed)  \
                            + scale(avgspeed) + C(year) + C(month) + scale(relative_humility) + scale(windchill) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2_1)
result2_1 = model2_1.fit()
print(result2_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.942
Model:                            OLS   Adj. R-squared:                  0.941
Method:                 Least Squares   F-statistic:                 4.268e+04
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:47:35   Log-Likelihood:             7.2459e+05
No. Observations:              373995   AIC:                        -1.449e+06
Df Residuals:                  373853   BIC:                        -1.447e+06
Df Model:                         141
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
C(year)[2012]                0.0004      0.001      0.609      0.543      -0.001       0.002
C(year)[2013]               -0.0002      0.001     -0.332      0.740      -0.001       0.001
C(year)[2014]               -0.0009      0.001     -1.420      0.156      -0.002       0.000
C(month)[T.2]              9.72e-05      0.000      0.363      0.717      -0.000       0.001
C(month)[T.3]                0.0001      0.000      0.395      0.693      -0.000       0.001
C(month)[T.4]             9.138e-05      0.000      0.282      0.778      -0.001       0.001
C(month)[T.5]             1.471e-05      0.000      0.042      0.967      -0.001       0.001
C(month)[T.6]               -0.0001      0.000     -0.259      0.795      -0.001       0.001
C(month)[T.7]               -0.0001      0.000     -0.226      0.821      -0.001       0.001
C(month)[T.8]             5.076e-05      0.000      0.114      0.909      -0.001       0.001
C(month)[T.9]               -0.0002      0.000     -0.600      0.548      -0.001       0.001
C(month)[T.10]              -0.0007      0.000     -2.280      0.023      -0.001      -0.000
C(month)[T.11]              -0.0003      0.000     -1.076      0.282      -0.001       0.000
C(month)[T.12]           -8.163e-05      0.000     -0.271      0.787      -0.001       0.001
C(weekend)[T.1]              0.0001      0.000      1.021      0.307      -0.000       0.000
C(rainY)[T.1]                0.0002      0.000      1.200      0.230      -0.000       0.001
C(store_nbr)[T.6]           -0.0006      0.000     -3.772      0.000      -0.001      -0.000
C(store_nbr)[T.38]           0.0015      0.000      9.133      0.000       0.001       0.002
C(store_nbr)[T.42]          -0.0002      0.000     -1.525      0.127      -0.001    7.02e-05
C(item_nbr)[T.2]         -6.296e-16      0.001  -7.55e-13      1.000      -0.002       0.002
C(item_nbr)[T.3]         -2.773e-15      0.001  -3.33e-12      1.000      -0.002       0.002
C(item_nbr)[T.4]         -8.538e-16      0.001  -1.02e-12      1.000      -0.002       0.002
C(item_nbr)[T.5]             2.1984      0.003    673.328      0.000       2.192       2.205
C(item_nbr)[T.6]           -9.5e-16      0.001  -1.14e-12      1.000      -0.002       0.002
C(item_nbr)[T.7]         -2.622e-16      0.001  -3.15e-13      1.000      -0.002       0.002
C(item_nbr)[T.8]         -1.672e-15      0.001  -2.01e-12      1.000      -0.002       0.002
C(item_nbr)[T.9]             2.3932      0.005    467.358      0.000       2.383       2.403
C(item_nbr)[T.10]        -3.754e-15      0.001   -4.5e-12      1.000      -0.002       0.002
C(item_nbr)[T.11]            0.0257      0.001     30.419      0.000       0.024       0.027
C(item_nbr)[T.12]         7.017e-16      0.001   8.42e-13      1.000      -0.002       0.002
C(item_nbr)[T.13]        -5.792e-16      0.001  -6.95e-13      1.000      -0.002       0.002
C(item_nbr)[T.14]            0.0166      0.001     19.806      0.000       0.015       0.018
C(item_nbr)[T.15]        -2.131e-15      0.001  -2.56e-12      1.000      -0.002       0.002
C(item_nbr)[T.16]        -8.636e-16      0.001  -1.04e-12      1.000      -0.002       0.002
C(item_nbr)[T.17]        -4.865e-16      0.001  -5.84e-13      1.000      -0.002       0.002
C(item_nbr)[T.18]         2.647e-16      0.001   3.18e-13      1.000      -0.002       0.002
C(item_nbr)[T.19]        -5.506e-16      0.001  -6.61e-13      1.000      -0.002       0.002
C(item_nbr)[T.20]        -1.191e-15      0.001  -1.43e-12      1.000      -0.002       0.002
C(item_nbr)[T.21]         -9.17e-16      0.001   -1.1e-12      1.000      -0.002       0.002
C(item_nbr)[T.22]        -7.518e-16      0.001  -9.02e-13      1.000      -0.002       0.002
C(item_nbr)[T.23]        -6.317e-16      0.001  -7.58e-13      1.000      -0.002       0.002
C(item_nbr)[T.24]        -7.809e-16      0.001  -9.37e-13      1.000      -0.002       0.002
C(item_nbr)[T.25]        -8.051e-16      0.001  -9.66e-13      1.000      -0.002       0.002
C(item_nbr)[T.26]        -6.384e-16      0.001  -7.66e-13      1.000      -0.002       0.002
C(item_nbr)[T.27]          -7.2e-16      0.001  -8.64e-13      1.000      -0.002       0.002
C(item_nbr)[T.28]        -6.601e-16      0.001  -7.92e-13      1.000      -0.002       0.002
C(item_nbr)[T.29]        -5.562e-16      0.001  -6.67e-13      1.000      -0.002       0.002
C(item_nbr)[T.30]        -7.129e-16      0.001  -8.55e-13      1.000      -0.002       0.002
C(item_nbr)[T.31]        -6.222e-16      0.001  -7.47e-13      1.000      -0.002       0.002
C(item_nbr)[T.32]        -6.238e-16      0.001  -7.48e-13      1.000      -0.002       0.002
C(item_nbr)[T.33]        -5.766e-16      0.001  -6.92e-13      1.000      -0.002       0.002
C(item_nbr)[T.34]        -8.044e-16      0.001  -9.65e-13      1.000      -0.002       0.002
C(item_nbr)[T.35]         -6.96e-16      0.001  -8.35e-13      1.000      -0.002       0.002
C(item_nbr)[T.36]        -6.034e-16      0.001  -7.24e-13      1.000      -0.002       0.002
C(item_nbr)[T.37]         -8.19e-16      0.001  -9.83e-13      1.000      -0.002       0.002
C(item_nbr)[T.38]        -9.337e-16      0.001  -1.12e-12      1.000      -0.002       0.002
C(item_nbr)[T.39]         -8.46e-16      0.001  -1.01e-12      1.000      -0.002       0.002
C(item_nbr)[T.40]        -4.823e-16      0.001  -5.79e-13      1.000      -0.002       0.002
C(item_nbr)[T.41]        -8.304e-16      0.001  -9.96e-13      1.000      -0.002       0.002
C(item_nbr)[T.42]        -6.099e-16      0.001  -7.32e-13      1.000      -0.002       0.002
C(item_nbr)[T.43]        -7.265e-16      0.001  -8.72e-13      1.000      -0.002       0.002
C(item_nbr)[T.45]            3.8077      0.002   2172.903      0.000       3.804       3.811
C(item_nbr)[T.46]         -7.37e-16      0.001  -8.84e-13      1.000      -0.002       0.002
C(item_nbr)[T.47]        -7.276e-16      0.001  -8.73e-13      1.000      -0.002       0.002
C(item_nbr)[T.48]        -6.962e-16      0.001  -8.35e-13      1.000      -0.002       0.002
C(item_nbr)[T.49]        -6.922e-16      0.001   -8.3e-13      1.000      -0.002       0.002
C(item_nbr)[T.50]         -7.26e-16      0.001  -8.71e-13      1.000      -0.002       0.002
C(item_nbr)[T.51]        -7.955e-16      0.001  -9.54e-13      1.000      -0.002       0.002
C(item_nbr)[T.52]            0.0433      0.001     51.059      0.000       0.042       0.045
C(item_nbr)[T.53]        -7.336e-16      0.001   -8.8e-13      1.000      -0.002       0.002
C(item_nbr)[T.54]        -8.451e-16      0.001  -1.01e-12      1.000      -0.002       0.002
C(item_nbr)[T.55]        -7.063e-16      0.001  -8.47e-13      1.000      -0.002       0.002
C(item_nbr)[T.56]        -8.682e-16      0.001  -1.04e-12      1.000      -0.002       0.002
C(item_nbr)[T.57]        -7.074e-16      0.001  -8.49e-13      1.000      -0.002       0.002
C(item_nbr)[T.58]        -7.487e-16      0.001  -8.98e-13      1.000      -0.002       0.002
C(item_nbr)[T.59]        -7.659e-16      0.001  -9.19e-13      1.000      -0.002       0.002
C(item_nbr)[T.60]        -7.903e-16      0.001  -9.48e-13      1.000      -0.002       0.002
C(item_nbr)[T.61]        -6.889e-16      0.001  -8.26e-13      1.000      -0.002       0.002
C(item_nbr)[T.62]        -7.105e-16      0.001  -8.52e-13      1.000      -0.002       0.002
C(item_nbr)[T.63]        -7.077e-16      0.001  -8.49e-13      1.000      -0.002       0.002
C(item_nbr)[T.64]        -9.377e-16      0.001  -1.13e-12      1.000      -0.002       0.002
C(item_nbr)[T.65]        -7.779e-16      0.001  -9.33e-13      1.000      -0.002       0.002
C(item_nbr)[T.66]        -7.088e-16      0.001   -8.5e-13      1.000      -0.002       0.002
C(item_nbr)[T.67]        -7.837e-16      0.001   -9.4e-13      1.000      -0.002       0.002
C(item_nbr)[T.68]         -7.57e-16      0.001  -9.08e-13      1.000      -0.002       0.002
C(item_nbr)[T.69]        -7.397e-16      0.001  -8.87e-13      1.000      -0.002       0.002
C(item_nbr)[T.70]        -8.201e-16      0.001  -9.84e-13      1.000      -0.002       0.002
C(item_nbr)[T.71]        -6.957e-16      0.001  -8.35e-13      1.000      -0.002       0.002
C(item_nbr)[T.72]        -7.564e-16      0.001  -9.07e-13      1.000      -0.002       0.002
C(item_nbr)[T.73]        -6.899e-16      0.001  -8.28e-13      1.000      -0.002       0.002
C(item_nbr)[T.74]        -7.609e-16      0.001  -9.13e-13      1.000      -0.002       0.002
C(item_nbr)[T.75]        -7.279e-16      0.001  -8.73e-13      1.000      -0.002       0.002
C(item_nbr)[T.76]        -8.683e-16      0.001  -1.04e-12      1.000      -0.002       0.002
C(item_nbr)[T.77]        -7.153e-16      0.001  -8.58e-13      1.000      -0.002       0.002
C(item_nbr)[T.78]        -7.577e-16      0.001  -9.09e-13      1.000      -0.002       0.002
C(item_nbr)[T.79]        -7.127e-16      0.001  -8.55e-13      1.000      -0.002       0.002
C(item_nbr)[T.80]        -7.863e-16      0.001  -9.43e-13      1.000      -0.002       0.002
C(item_nbr)[T.81]         -7.63e-16      0.001  -9.15e-13      1.000      -0.002       0.002
C(item_nbr)[T.82]            0.0372      0.001     44.294      0.000       0.036       0.039
C(item_nbr)[T.83]        -7.879e-16      0.001  -9.45e-13      1.000      -0.002       0.002
C(item_nbr)[T.84]         -7.12e-16      0.001  -8.54e-13      1.000      -0.002       0.002
C(item_nbr)[T.85]            0.0086      0.001     10.272      0.000       0.007       0.010
C(item_nbr)[T.86]            0.0058      0.001      6.919      0.000       0.004       0.007
C(item_nbr)[T.87]        -7.636e-16      0.001  -9.16e-13      1.000      -0.002       0.002
C(item_nbr)[T.88]         -7.64e-16      0.001  -9.17e-13      1.000      -0.002       0.002
C(item_nbr)[T.89]        -8.054e-16      0.001  -9.66e-13      1.000      -0.002       0.002
C(item_nbr)[T.90]        -6.975e-16      0.001  -8.37e-13      1.000      -0.002       0.002
C(item_nbr)[T.91]        -7.963e-16      0.001  -9.55e-13      1.000      -0.002       0.002
C(item_nbr)[T.92]        -8.104e-16      0.001  -9.72e-13      1.000      -0.002       0.002
C(item_nbr)[T.93]            0.0145      0.001     17.170      0.000       0.013       0.016
C(item_nbr)[T.94]         -7.12e-16      0.001  -8.54e-13      1.000      -0.002       0.002
C(item_nbr)[T.95]        -7.351e-16      0.001  -8.82e-13      1.000      -0.002       0.002
C(item_nbr)[T.96]        -8.122e-16      0.001  -9.74e-13      1.000      -0.002       0.002
C(item_nbr)[T.97]        -7.855e-16      0.001  -9.42e-13      1.000      -0.002       0.002
C(item_nbr)[T.98]            0.0272      0.001     32.296      0.000       0.026       0.029
C(item_nbr)[T.99]        -7.697e-16      0.001  -9.23e-13      1.000      -0.002       0.002
C(item_nbr)[T.100]       -6.728e-16      0.001  -8.07e-13      1.000      -0.002       0.002
C(item_nbr)[T.101]       -8.113e-16      0.001  -9.73e-13      1.000      -0.002       0.002
C(item_nbr)[T.102]       -8.008e-16      0.001  -9.61e-13      1.000      -0.002       0.002
C(item_nbr)[T.103]       -9.524e-16      0.001  -1.14e-12      1.000      -0.002       0.002
C(item_nbr)[T.104]        -7.56e-16      0.001  -9.07e-13      1.000      -0.002       0.002
C(item_nbr)[T.105]        -8.77e-16      0.001  -1.05e-12      1.000      -0.002       0.002
C(item_nbr)[T.106]       -7.956e-16      0.001  -9.54e-13      1.000      -0.002       0.002
C(item_nbr)[T.107]           0.0099      0.001     11.728      0.000       0.008       0.012
C(item_nbr)[T.108]       -9.221e-16      0.001  -1.11e-12      1.000      -0.002       0.002
C(item_nbr)[T.109]       -4.678e-16      0.001  -5.61e-13      1.000      -0.002       0.002
C(item_nbr)[T.110]       -6.323e-16      0.001  -7.59e-13      1.000      -0.002       0.002
C(item_nbr)[T.111]       -1.073e-15      0.001  -1.29e-12      1.000      -0.002       0.002
scale(tmax)                 -0.0004      0.001     -0.508      0.611      -0.002       0.001
scale(tmin)                 -0.0002      0.001     -0.260      0.795      -0.002       0.001
scale(tavg)                 -0.0003      0.001     -0.400      0.689      -0.002       0.001
scale(dewpoint)            8.48e-06      0.001      0.009      0.993      -0.002       0.002
scale(wetbulb)               0.0011      0.001      1.197      0.232      -0.001       0.003
scale(heat)                 -0.0007      0.001     -1.275      0.202      -0.002       0.000
scale(cool)                  0.0003      0.000      0.790      0.429      -0.000       0.001
scale(snowfall)          -5.242e-05   6.15e-05     -0.852      0.394      -0.000    6.81e-05
scale(preciptotal)       -6.292e-05   6.29e-05     -1.001      0.317      -0.000    6.03e-05
scale(stnpressure)           0.0003      0.000      0.716      0.474      -0.000       0.001
scale(sealevel)             -0.0002      0.000     -0.428      0.669      -0.001       0.001
scale(resultspeed)        6.877e-05      0.000      0.558      0.577      -0.000       0.000
scale(avgspeed)             -0.0002      0.000     -1.109      0.268      -0.000       0.000
scale(relative_humility)    -0.0002      0.000     -0.659      0.510      -0.001       0.000
scale(windchill)            -0.0009      0.002     -0.461      0.645      -0.005       0.003
==============================================================================
Omnibus:                   736499.930   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       1900694671.874
Skew:                          15.974   Prob(JB):                         0.00
Kurtosis:                     350.780   Cond. No.                     1.85e+15
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 8.9e-25. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [20]:
ls1

['depart', 'sunrise', 'sunset', 'resultdir', 'daytime']

### 3. VIF 확인

In [21]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
# all_cols = ['tmax','tmin','tavg','dewpoint','wetbulb','heat','cool','preciptotal',\
#         'stnpressure','sealevel','resultspeed','avgspeed','relative_humility',\
#         'windchill', 'depart', 'sunrise', 'sunset', 'snowfall' ]
cols = ['tmax','tmin','tavg','dewpoint','wetbulb','heat','cool','preciptotal',\
        'stnpressure','sealevel','resultspeed','avgspeed','relative_humility',\
        'windchill', 'snowfall']

y = df2_1.loc[:,cols]
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(y.values, i) for i in range(y.shape[1])]
vif["features"] = y.columns
vif = vif.sort_values("VIF Factor", ascending=False).reset_index(drop=True)
vif

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\stats\outliers_influence.py:167: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)

      VIF Factor           features
0            inf               tmax
1            inf               tmin
2            inf               tavg
3   1.042388e+06           sealevel
4   1.032478e+06        stnpressure
5   9.559696e+03          windchill
6   2.891425e+03            wetbulb
7   2.036382e+03           dewpoint
8   5.289556e+02  relative_humility
9   1.306042e+02               heat
10  5.736802e+01               cool
11  4.660071e+01           avgspeed
12  2.027880e+01        resultspeed
13  1.213516e+00        preciptotal
14  1.128072e+00           snowfall

### 4. VIF 근거 변수 빼고 다시 Model 돌림.

In [22]:
# OLS - df2_1
model2_1 = sm.OLS.from_formula('log1p_units ~ scale(cool)\
                            + scale(snowfall) + scale(preciptotal) + scale(resultspeed)  \
                            + scale(avgspeed) + C(year) + C(month) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2_1)
result2_1 = model2_1.fit()
print(result2_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.942
Model:                            OLS   Adj. R-squared:                  0.941
Method:                 Least Squares   F-statistic:                 4.559e+04
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        12:13:24   Log-Likelihood:             7.2458e+05
No. Observations:              373995   AIC:                        -1.449e+06
Df Residuals:                  373862   BIC:                        -1.447e+06
Df Model:                         132
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
C(year)[2012]          0.0002      0.001      0.296      0.767      -0.001       0.001
C(year)[2013]         -0.0004      0.001     -0.692      0.489      -0.002       0.001
C(year)[2014]         -0.0012      0.001     -1.810      0.070      -0.002    9.53e-05
C(month)[T.2]          0.0001      0.000      0.538      0.590      -0.000       0.001
C(month)[T.3]          0.0003      0.000      1.006      0.315      -0.000       0.001
C(month)[T.4]          0.0004      0.000      1.327      0.185      -0.000       0.001
C(month)[T.5]          0.0004      0.000      1.239      0.215      -0.000       0.001
C(month)[T.6]          0.0003      0.000      0.849      0.396      -0.000       0.001
C(month)[T.7]          0.0003      0.000      0.707      0.480      -0.001       0.001
C(month)[T.8]          0.0005      0.000      1.288      0.198      -0.000       0.001
C(month)[T.9]          0.0002      0.000      0.509      0.611      -0.000       0.001
C(month)[T.10]        -0.0004      0.000     -1.697      0.090      -0.001     6.8e-05
C(month)[T.11]        -0.0001      0.000     -0.474      0.635      -0.001       0.000
C(month)[T.12]        -0.0002      0.000     -0.674      0.501      -0.001       0.000
C(weekend)[T.1]        0.0001      0.000      0.983      0.326      -0.000       0.000
C(rainY)[T.1]          0.0002      0.000      1.157      0.247      -0.000       0.000
C(store_nbr)[T.6]     -0.0006      0.000     -3.773      0.000      -0.001      -0.000
C(store_nbr)[T.38]     0.0015      0.000      9.133      0.000       0.001       0.002
C(store_nbr)[T.42]    -0.0002      0.000     -1.525      0.127      -0.001    7.02e-05
C(item_nbr)[T.2]    2.978e-15      0.001   3.57e-12      1.000      -0.002       0.002
C(item_nbr)[T.3]   -1.892e-15      0.001  -2.27e-12      1.000      -0.002       0.002
C(item_nbr)[T.4]     3.88e-16      0.001   4.65e-13      1.000      -0.002       0.002
C(item_nbr)[T.5]       2.1984      0.003    673.337      0.000       2.192       2.205
C(item_nbr)[T.6]    4.577e-16      0.001   5.49e-13      1.000      -0.002       0.002
C(item_nbr)[T.7]    1.145e-15      0.001   1.37e-12      1.000      -0.002       0.002
C(item_nbr)[T.8]    2.097e-15      0.001   2.52e-12      1.000      -0.002       0.002
C(item_nbr)[T.9]       2.3932      0.005    467.363      0.000       2.383       2.403
C(item_nbr)[T.10]   1.416e-15      0.001    1.7e-12      1.000      -0.002       0.002
C(item_nbr)[T.11]      0.0257      0.001     30.422      0.000       0.024       0.027
C(item_nbr)[T.12]   7.575e-16      0.001   9.09e-13      1.000      -0.002       0.002
C(item_nbr)[T.13]   8.351e-16      0.001      1e-12      1.000      -0.002       0.002
C(item_nbr)[T.14]      0.0166      0.001     19.806      0.000       0.015       0.018
C(item_nbr)[T.15]   7.289e-16      0.001   8.74e-13      1.000      -0.002       0.002
C(item_nbr)[T.16]   7.468e-16      0.001   8.96e-13      1.000      -0.002       0.002
C(item_nbr)[T.17]   7.305e-16      0.001   8.76e-13      1.000      -0.002       0.002
C(item_nbr)[T.18]   9.374e-16      0.001   1.12e-12      1.000      -0.002       0.002
C(item_nbr)[T.19]   8.669e-16      0.001   1.04e-12      1.000      -0.002       0.002
C(item_nbr)[T.20]   7.785e-16      0.001   9.34e-13      1.000      -0.002       0.002
C(item_nbr)[T.21]   7.529e-16      0.001   9.03e-13      1.000      -0.002       0.002
C(item_nbr)[T.22]   8.556e-16      0.001   1.03e-12      1.000      -0.002       0.002
C(item_nbr)[T.23]   8.353e-16      0.001      1e-12      1.000      -0.002       0.002
C(item_nbr)[T.24]   8.767e-16      0.001   1.05e-12      1.000      -0.002       0.002
C(item_nbr)[T.25]   8.094e-16      0.001   9.71e-13      1.000      -0.002       0.002
C(item_nbr)[T.26]   8.382e-16      0.001   1.01e-12      1.000      -0.002       0.002
C(item_nbr)[T.27]   8.678e-16      0.001   1.04e-12      1.000      -0.002       0.002
C(item_nbr)[T.28]   7.675e-16      0.001   9.21e-13      1.000      -0.002       0.002
C(item_nbr)[T.29]   1.009e-15      0.001   1.21e-12      1.000      -0.002       0.002
C(item_nbr)[T.30]   8.437e-16      0.001   1.01e-12      1.000      -0.002       0.002
C(item_nbr)[T.31]   8.386e-16      0.001   1.01e-12      1.000      -0.002       0.002
C(item_nbr)[T.32]   1.052e-15      0.001   1.26e-12      1.000      -0.002       0.002
C(item_nbr)[T.33]   9.507e-16      0.001   1.14e-12      1.000      -0.002       0.002
C(item_nbr)[T.34]   7.563e-16      0.001   9.07e-13      1.000      -0.002       0.002
C(item_nbr)[T.35]   7.748e-16      0.001    9.3e-13      1.000      -0.002       0.002
C(item_nbr)[T.36]   1.001e-15      0.001    1.2e-12      1.000      -0.002       0.002
C(item_nbr)[T.37]   7.058e-16      0.001   8.47e-13      1.000      -0.002       0.002
C(item_nbr)[T.38]   7.825e-16      0.001   9.39e-13      1.000      -0.002       0.002
C(item_nbr)[T.39]   8.931e-16      0.001   1.07e-12      1.000      -0.002       0.002
C(item_nbr)[T.40]   9.449e-16      0.001   1.13e-12      1.000      -0.002       0.002
C(item_nbr)[T.41]       7e-16      0.001    8.4e-13      1.000      -0.002       0.002
C(item_nbr)[T.42]   7.915e-16      0.001    9.5e-13      1.000      -0.002       0.002
C(item_nbr)[T.43]   9.614e-16      0.001   1.15e-12      1.000      -0.002       0.002
C(item_nbr)[T.45]      3.8077      0.002   2172.935      0.000       3.804       3.811
C(item_nbr)[T.46]   7.496e-16      0.001   8.99e-13      1.000      -0.002       0.002
C(item_nbr)[T.47]   8.425e-16      0.001   1.01e-12      1.000      -0.002       0.002
C(item_nbr)[T.48]   7.991e-16      0.001   9.59e-13      1.000      -0.002       0.002
C(item_nbr)[T.49]   8.112e-16      0.001   9.73e-13      1.000      -0.002       0.002
C(item_nbr)[T.50]   8.451e-16      0.001   1.01e-12      1.000      -0.002       0.002
C(item_nbr)[T.51]   8.278e-16      0.001   9.93e-13      1.000      -0.002       0.002
C(item_nbr)[T.52]      0.0433      0.001     51.061      0.000       0.042       0.045
C(item_nbr)[T.53]   8.439e-16      0.001   1.01e-12      1.000      -0.002       0.002
C(item_nbr)[T.54]   7.485e-16      0.001   8.98e-13      1.000      -0.002       0.002
C(item_nbr)[T.55]    7.69e-16      0.001   9.23e-13      1.000      -0.002       0.002
C(item_nbr)[T.56]   8.312e-16      0.001   9.97e-13      1.000      -0.002       0.002
C(item_nbr)[T.57]   8.066e-16      0.001   9.68e-13      1.000      -0.002       0.002
C(item_nbr)[T.58]   7.747e-16      0.001   9.29e-13      1.000      -0.002       0.002
C(item_nbr)[T.59]   7.633e-16      0.001   9.16e-13      1.000      -0.002       0.002
C(item_nbr)[T.60]   7.802e-16      0.001   9.36e-13      1.000      -0.002       0.002
C(item_nbr)[T.61]   7.749e-16      0.001    9.3e-13      1.000      -0.002       0.002
C(item_nbr)[T.62]   7.994e-16      0.001   9.59e-13      1.000      -0.002       0.002
C(item_nbr)[T.63]   8.007e-16      0.001   9.61e-13      1.000      -0.002       0.002
C(item_nbr)[T.64]    7.91e-16      0.001   9.49e-13      1.000      -0.002       0.002
C(item_nbr)[T.65]   7.156e-16      0.001   8.58e-13      1.000      -0.002       0.002
C(item_nbr)[T.66]   9.639e-16      0.001   1.16e-12      1.000      -0.002       0.002
C(item_nbr)[T.67]   7.149e-16      0.001   8.58e-13      1.000      -0.002       0.002
C(item_nbr)[T.68]    8.31e-16      0.001   9.97e-13      1.000      -0.002       0.002
C(item_nbr)[T.69]   8.117e-16      0.001   9.74e-13      1.000      -0.002       0.002
C(item_nbr)[T.70]   8.118e-16      0.001   9.74e-13      1.000      -0.002       0.002
C(item_nbr)[T.71]   8.025e-16      0.001   9.63e-13      1.000      -0.002       0.002
C(item_nbr)[T.72]   8.076e-16      0.001   9.69e-13      1.000      -0.002       0.002
C(item_nbr)[T.73]   7.535e-16      0.001   9.04e-13      1.000      -0.002       0.002
C(item_nbr)[T.74]   7.585e-16      0.001    9.1e-13      1.000      -0.002       0.002
C(item_nbr)[T.75]   8.806e-16      0.001   1.06e-12      1.000      -0.002       0.002
C(item_nbr)[T.76]   8.561e-16      0.001   1.03e-12      1.000      -0.002       0.002
C(item_nbr)[T.77]   8.831e-16      0.001   1.06e-12      1.000      -0.002       0.002
C(item_nbr)[T.78]   7.468e-16      0.001   8.96e-13      1.000      -0.002       0.002
C(item_nbr)[T.79]   8.433e-16      0.001   1.01e-12      1.000      -0.002       0.002
C(item_nbr)[T.80]   7.733e-16      0.001   9.28e-13      1.000      -0.002       0.002
C(item_nbr)[T.81]   7.484e-16      0.001   8.98e-13      1.000      -0.002       0.002
C(item_nbr)[T.82]      0.0372      0.001     44.295      0.000       0.036       0.039
C(item_nbr)[T.83]   7.588e-16      0.001    9.1e-13      1.000      -0.002       0.002
C(item_nbr)[T.84]   8.233e-16      0.001   9.88e-13      1.000      -0.002       0.002
C(item_nbr)[T.85]      0.0086      0.001     10.273      0.000       0.007       0.010
C(item_nbr)[T.86]      0.0058      0.001      6.919      0.000       0.004       0.007
C(item_nbr)[T.87]   7.645e-16      0.001   9.17e-13      1.000      -0.002       0.002
C(item_nbr)[T.88]   8.317e-16      0.001   9.98e-13      1.000      -0.002       0.002
C(item_nbr)[T.89]   8.502e-16      0.001   1.02e-12      1.000      -0.002       0.002
C(item_nbr)[T.90]   7.956e-16      0.001   9.54e-13      1.000      -0.002       0.002
C(item_nbr)[T.91]   7.609e-16      0.001   9.13e-13      1.000      -0.002       0.002
C(item_nbr)[T.92]   7.536e-16      0.001   9.04e-13      1.000      -0.002       0.002
C(item_nbr)[T.93]      0.0145      0.001     17.168      0.000       0.013       0.016
C(item_nbr)[T.94]   7.281e-16      0.001   8.73e-13      1.000      -0.002       0.002
C(item_nbr)[T.95]   8.439e-16      0.001   1.01e-12      1.000      -0.002       0.002
C(item_nbr)[T.96]   7.504e-16      0.001      9e-13      1.000      -0.002       0.002
C(item_nbr)[T.97]    7.65e-16      0.001   9.18e-13      1.000      -0.002       0.002
C(item_nbr)[T.98]      0.0272      0.001     32.296      0.000       0.026       0.029
C(item_nbr)[T.99]   7.431e-16      0.001   8.91e-13      1.000      -0.002       0.002
C(item_nbr)[T.100]   7.92e-16      0.001    9.5e-13      1.000      -0.002       0.002
C(item_nbr)[T.101]    7.7e-16      0.001   9.24e-13      1.000      -0.002       0.002
C(item_nbr)[T.102]  8.008e-16      0.001   9.61e-13      1.000      -0.002       0.002
C(item_nbr)[T.103]  6.195e-16      0.001   7.43e-13      1.000      -0.002       0.002
C(item_nbr)[T.104]  6.806e-16      0.001   8.17e-13      1.000      -0.002       0.002
C(item_nbr)[T.105]  7.408e-16      0.001   8.89e-13      1.000      -0.002       0.002
C(item_nbr)[T.106]  6.883e-16      0.001   8.26e-13      1.000      -0.002       0.002
C(item_nbr)[T.107]     0.0099      0.001     11.729      0.000       0.008       0.012
C(item_nbr)[T.108]  8.506e-16      0.001   1.02e-12      1.000      -0.002       0.002
C(item_nbr)[T.109]  7.114e-16      0.001   8.54e-13      1.000      -0.002       0.002
C(item_nbr)[T.110]  4.346e-16      0.001   5.21e-13      1.000      -0.002       0.002
C(item_nbr)[T.111]  9.963e-16      0.001    1.2e-12      1.000      -0.002       0.002
scale(cool)           -0.0001      0.000     -0.974      0.330      -0.000       0.000
scale(snowfall)    -7.582e-05   5.93e-05     -1.278      0.201      -0.000    4.05e-05
scale(preciptotal) -6.111e-05   6.23e-05     -0.981      0.327      -0.000     6.1e-05
scale(resultspeed)     0.0001      0.000      0.980      0.327      -0.000       0.000
scale(avgspeed)       -0.0002      0.000     -1.504      0.133      -0.000     5.4e-05
==============================================================================
Omnibus:                   736507.254   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       1900880198.178
Skew:                          15.975   Prob(JB):                         0.00
Kurtosis:                     350.797   Cond. No.                         153.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### 5. VIF 재확인 (tmax, tmin, tavg 제외함)

In [23]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
# all_cols = ['tmax','tmin','tavg','dewpoint','wetbulb','heat','cool','preciptotal',\
#         'stnpressure','sealevel','resultspeed','avgspeed','relative_humility',\
#         'windchill', 'depart', 'sunrise', 'sunset', 'snowfall' ]
cols = ['cool', 'snowfall', 'preciptotal', 'resultspeed', 'avgspeed']

y = df2_1.loc[:,cols]
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(y.values, i) for i in range(y.shape[1])]
vif["features"] = y.columns
vif = vif.sort_values("VIF Factor", ascending=False).reset_index(drop=True)
vif

   VIF Factor     features
0   17.770309     avgspeed
1   17.474920  resultspeed
2    1.372002         cool
3    1.094665  preciptotal
4    1.033673     snowfall

### 6. VIF 근거 avg speed, result speed 제외하고  Model 돌림.

In [24]:
# OLS - df2_1
model2_1 = sm.OLS.from_formula('log1p_units ~ scale(cool)\
                            + scale(snowfall) + scale(preciptotal) \
                            + C(year) + C(month) + C(weekend) \
                            + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2_1)
result2_1 = model2_1.fit()
print(result2_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.942
Model:                            OLS   Adj. R-squared:                  0.941
Method:                 Least Squares   F-statistic:                 4.629e+04
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        12:19:07   Log-Likelihood:             7.2458e+05
No. Observations:              373995   AIC:                        -1.449e+06
Df Residuals:                  373864   BIC:                        -1.447e+06
Df Model:                         130
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
C(year)[2012]          0.0002      0.001      0.239      0.811      -0.001       0.001
C(year)[2013]         -0.0005      0.001     -0.746      0.455      -0.002       0.001
C(year)[2014]         -0.0012      0.001     -1.913      0.056      -0.002    2.97e-05
C(month)[T.2]          0.0001      0.000      0.542      0.588      -0.000       0.001
C(month)[T.3]          0.0002      0.000      0.972      0.331      -0.000       0.001
C(month)[T.4]          0.0004      0.000      1.349      0.177      -0.000       0.001
C(month)[T.5]          0.0004      0.000      1.361      0.173      -0.000       0.001
C(month)[T.6]          0.0004      0.000      1.067      0.286      -0.000       0.001
C(month)[T.7]          0.0004      0.000      1.057      0.291      -0.000       0.001
C(month)[T.8]          0.0006      0.000      1.696      0.090   -9.43e-05       0.001
C(month)[T.9]          0.0003      0.000      0.892      0.373      -0.000       0.001
C(month)[T.10]        -0.0004      0.000     -1.522      0.128      -0.001       0.000
C(month)[T.11]        -0.0001      0.000     -0.424      0.672      -0.001       0.000
C(month)[T.12]        -0.0002      0.000     -0.588      0.557      -0.001       0.000
C(weekend)[T.1]        0.0001      0.000      1.070      0.284      -0.000       0.000
C(rainY)[T.1]          0.0001      0.000      1.038      0.299      -0.000       0.000
C(store_nbr)[T.6]     -0.0006      0.000     -3.773      0.000      -0.001      -0.000
C(store_nbr)[T.38]     0.0015      0.000      9.133      0.000       0.001       0.002
C(store_nbr)[T.42]    -0.0002      0.000     -1.525      0.127      -0.001    7.02e-05
C(item_nbr)[T.2]    4.901e-16      0.001   5.88e-13      1.000      -0.002       0.002
C(item_nbr)[T.3]    1.861e-15      0.001   2.23e-12      1.000      -0.002       0.002
C(item_nbr)[T.4]   -5.967e-16      0.001  -7.16e-13      1.000      -0.002       0.002
C(item_nbr)[T.5]       2.1984      0.003    673.336      0.000       2.192       2.205
C(item_nbr)[T.6]   -1.053e-16      0.001  -1.26e-13      1.000      -0.002       0.002
C(item_nbr)[T.7]   -1.088e-16      0.001  -1.31e-13      1.000      -0.002       0.002
C(item_nbr)[T.8]   -1.577e-16      0.001  -1.89e-13      1.000      -0.002       0.002
C(item_nbr)[T.9]       2.3932      0.005    467.364      0.000       2.383       2.403
C(item_nbr)[T.10]  -2.938e-17      0.001  -3.53e-14      1.000      -0.002       0.002
C(item_nbr)[T.11]      0.0257      0.001     30.421      0.000       0.024       0.027
C(item_nbr)[T.12]   -2.61e-16      0.001  -3.13e-13      1.000      -0.002       0.002
C(item_nbr)[T.13]   -4.74e-16      0.001  -5.69e-13      1.000      -0.002       0.002
C(item_nbr)[T.14]      0.0166      0.001     19.806      0.000       0.015       0.018
C(item_nbr)[T.15]  -2.915e-16      0.001   -3.5e-13      1.000      -0.002       0.002
C(item_nbr)[T.16]  -3.977e-16      0.001  -4.77e-13      1.000      -0.002       0.002
C(item_nbr)[T.17]  -2.621e-16      0.001  -3.14e-13      1.000      -0.002       0.002
C(item_nbr)[T.18]  -4.338e-16      0.001  -5.21e-13      1.000      -0.002       0.002
C(item_nbr)[T.19]  -3.329e-16      0.001  -3.99e-13      1.000      -0.002       0.002
C(item_nbr)[T.20]  -3.598e-16      0.001  -4.32e-13      1.000      -0.002       0.002
C(item_nbr)[T.21]  -1.854e-16      0.001  -2.22e-13      1.000      -0.002       0.002
C(item_nbr)[T.22]  -4.541e-16      0.001  -5.45e-13      1.000      -0.002       0.002
C(item_nbr)[T.23]  -4.126e-16      0.001  -4.95e-13      1.000      -0.002       0.002
C(item_nbr)[T.24]  -3.448e-16      0.001  -4.14e-13      1.000      -0.002       0.002
C(item_nbr)[T.25]  -3.792e-16      0.001  -4.55e-13      1.000      -0.002       0.002
C(item_nbr)[T.26]  -4.358e-16      0.001  -5.23e-13      1.000      -0.002       0.002
C(item_nbr)[T.27]  -3.147e-16      0.001  -3.78e-13      1.000      -0.002       0.002
C(item_nbr)[T.28]  -3.113e-16      0.001  -3.73e-13      1.000      -0.002       0.002
C(item_nbr)[T.29]  -2.018e-16      0.001  -2.42e-13      1.000      -0.002       0.002
C(item_nbr)[T.30]   -3.82e-16      0.001  -4.58e-13      1.000      -0.002       0.002
C(item_nbr)[T.31]  -4.285e-16      0.001  -5.14e-13      1.000      -0.002       0.002
C(item_nbr)[T.32]  -3.662e-16      0.001  -4.39e-13      1.000      -0.002       0.002
C(item_nbr)[T.33]  -2.795e-16      0.001  -3.35e-13      1.000      -0.002       0.002
C(item_nbr)[T.34]  -3.489e-16      0.001  -4.19e-13      1.000      -0.002       0.002
C(item_nbr)[T.35]  -3.498e-16      0.001   -4.2e-13      1.000      -0.002       0.002
C(item_nbr)[T.36]  -3.311e-16      0.001  -3.97e-13      1.000      -0.002       0.002
C(item_nbr)[T.37]  -5.433e-16      0.001  -6.52e-13      1.000      -0.002       0.002
C(item_nbr)[T.38]  -5.668e-16      0.001   -6.8e-13      1.000      -0.002       0.002
C(item_nbr)[T.39]  -3.984e-16      0.001  -4.78e-13      1.000      -0.002       0.002
C(item_nbr)[T.40]    -2.4e-16      0.001  -2.88e-13      1.000      -0.002       0.002
C(item_nbr)[T.41]  -4.558e-16      0.001  -5.47e-13      1.000      -0.002       0.002
C(item_nbr)[T.42]  -4.068e-16      0.001  -4.88e-13      1.000      -0.002       0.002
C(item_nbr)[T.43]  -2.887e-16      0.001  -3.46e-13      1.000      -0.002       0.002
C(item_nbr)[T.45]      3.8077      0.002   2172.946      0.000       3.804       3.811
C(item_nbr)[T.46]  -3.466e-16      0.001  -4.16e-13      1.000      -0.002       0.002
C(item_nbr)[T.47]  -4.711e-16      0.001  -5.65e-13      1.000      -0.002       0.002
C(item_nbr)[T.48]  -3.328e-16      0.001  -3.99e-13      1.000      -0.002       0.002
C(item_nbr)[T.49]  -5.532e-16      0.001  -6.64e-13      1.000      -0.002       0.002
C(item_nbr)[T.50]  -4.991e-16      0.001  -5.99e-13      1.000      -0.002       0.002
C(item_nbr)[T.51]  -3.295e-16      0.001  -3.95e-13      1.000      -0.002       0.002
C(item_nbr)[T.52]      0.0433      0.001     51.061      0.000       0.042       0.045
C(item_nbr)[T.53]  -3.762e-16      0.001  -4.51e-13      1.000      -0.002       0.002
C(item_nbr)[T.54]  -3.764e-16      0.001  -4.52e-13      1.000      -0.002       0.002
C(item_nbr)[T.55]  -3.539e-16      0.001  -4.25e-13      1.000      -0.002       0.002
C(item_nbr)[T.56]  -3.606e-16      0.001  -4.33e-13      1.000      -0.002       0.002
C(item_nbr)[T.57]  -4.278e-16      0.001  -5.13e-13      1.000      -0.002       0.002
C(item_nbr)[T.58]  -5.046e-16      0.001  -6.05e-13      1.000      -0.002       0.002
C(item_nbr)[T.59]  -4.983e-16      0.001  -5.98e-13      1.000      -0.002       0.002
C(item_nbr)[T.60]  -3.031e-16      0.001  -3.64e-13      1.000      -0.002       0.002
C(item_nbr)[T.61]  -4.605e-16      0.001  -5.52e-13      1.000      -0.002       0.002
C(item_nbr)[T.62]  -4.564e-16      0.001  -5.48e-13      1.000      -0.002       0.002
C(item_nbr)[T.63]  -4.549e-16      0.001  -5.46e-13      1.000      -0.002       0.002
C(item_nbr)[T.64]   -5.92e-16      0.001   -7.1e-13      1.000      -0.002       0.002
C(item_nbr)[T.65]  -2.427e-16      0.001  -2.91e-13      1.000      -0.002       0.002
C(item_nbr)[T.66]  -2.511e-16      0.001  -3.01e-13      1.000      -0.002       0.002
C(item_nbr)[T.67]  -4.883e-16      0.001  -5.86e-13      1.000      -0.002       0.002
C(item_nbr)[T.68]  -3.091e-16      0.001  -3.71e-13      1.000      -0.002       0.002
C(item_nbr)[T.69]  -4.548e-16      0.001  -5.46e-13      1.000      -0.002       0.002
C(item_nbr)[T.70]  -4.545e-16      0.001  -5.45e-13      1.000      -0.002       0.002
C(item_nbr)[T.71]  -5.196e-16      0.001  -6.23e-13      1.000      -0.002       0.002
C(item_nbr)[T.72]  -3.975e-16      0.001  -4.77e-13      1.000      -0.002       0.002
C(item_nbr)[T.73]  -4.416e-16      0.001   -5.3e-13      1.000      -0.002       0.002
C(item_nbr)[T.74]  -5.079e-16      0.001  -6.09e-13      1.000      -0.002       0.002
C(item_nbr)[T.75]  -2.901e-16      0.001  -3.48e-13      1.000      -0.002       0.002
C(item_nbr)[T.76]  -5.571e-16      0.001  -6.68e-13      1.000      -0.002       0.002
C(item_nbr)[T.77]  -5.181e-16      0.001  -6.22e-13      1.000      -0.002       0.002
C(item_nbr)[T.78]  -5.287e-16      0.001  -6.34e-13      1.000      -0.002       0.002
C(item_nbr)[T.79]  -4.361e-16      0.001  -5.23e-13      1.000      -0.002       0.002
C(item_nbr)[T.80]  -5.724e-16      0.001  -6.87e-13      1.000      -0.002       0.002
C(item_nbr)[T.81]    -5.8e-16      0.001  -6.96e-13      1.000      -0.002       0.002
C(item_nbr)[T.82]      0.0372      0.001     44.295      0.000       0.036       0.039
C(item_nbr)[T.83]  -2.997e-16      0.001   -3.6e-13      1.000      -0.002       0.002
C(item_nbr)[T.84]   -4.43e-16      0.001  -5.32e-13      1.000      -0.002       0.002
C(item_nbr)[T.85]      0.0086      0.001     10.273      0.000       0.007       0.010
C(item_nbr)[T.86]      0.0058      0.001      6.919      0.000       0.004       0.007
C(item_nbr)[T.87]  -1.007e-16      0.001  -1.21e-13      1.000      -0.002       0.002
C(item_nbr)[T.88]  -9.421e-17      0.001  -1.13e-13      1.000      -0.002       0.002
C(item_nbr)[T.89]  -6.447e-16      0.001  -7.73e-13      1.000      -0.002       0.002
C(item_nbr)[T.90]  -3.953e-16      0.001  -4.74e-13      1.000      -0.002       0.002
C(item_nbr)[T.91]  -6.261e-16      0.001  -7.51e-13      1.000      -0.002       0.002
C(item_nbr)[T.92]  -3.126e-16      0.001  -3.75e-13      1.000      -0.002       0.002
C(item_nbr)[T.93]      0.0145      0.001     17.168      0.000       0.013       0.016
C(item_nbr)[T.94]   -4.84e-16      0.001  -5.81e-13      1.000      -0.002       0.002
C(item_nbr)[T.95]  -4.966e-16      0.001  -5.96e-13      1.000      -0.002       0.002
C(item_nbr)[T.96]  -7.265e-16      0.001  -8.72e-13      1.000      -0.002       0.002
C(item_nbr)[T.97]  -2.728e-17      0.001  -3.27e-14      1.000      -0.002       0.002
C(item_nbr)[T.98]      0.0272      0.001     32.297      0.000       0.026       0.029
C(item_nbr)[T.99]   -8.19e-16      0.001  -9.83e-13      1.000      -0.002       0.002
C(item_nbr)[T.100] -4.701e-16      0.001  -5.64e-13      1.000      -0.002       0.002
C(item_nbr)[T.101] -7.386e-16      0.001  -8.86e-13      1.000      -0.002       0.002
C(item_nbr)[T.102]  -3.37e-16      0.001  -4.04e-13      1.000      -0.002       0.002
C(item_nbr)[T.103]  3.651e-16      0.001   4.38e-13      1.000      -0.002       0.002
C(item_nbr)[T.104] -6.342e-16      0.001  -7.61e-13      1.000      -0.002       0.002
C(item_nbr)[T.105] -3.698e-16      0.001  -4.44e-13      1.000      -0.002       0.002
C(item_nbr)[T.106]  2.444e-16      0.001   2.93e-13      1.000      -0.002       0.002
C(item_nbr)[T.107]     0.0099      0.001     11.729      0.000       0.008       0.012
C(item_nbr)[T.108]  -1.33e-15      0.001   -1.6e-12      1.000      -0.002       0.002
C(item_nbr)[T.109] -9.189e-16      0.001   -1.1e-12      1.000      -0.002       0.002
C(item_nbr)[T.110]   -2.2e-15      0.001  -2.64e-12      1.000      -0.002       0.002
C(item_nbr)[T.111] -3.478e-15      0.001  -4.17e-12      1.000      -0.002       0.002
scale(cool)           -0.0001      0.000     -1.208      0.227      -0.000    8.75e-05
scale(snowfall)    -7.565e-05   5.92e-05     -1.279      0.201      -0.000    4.03e-05
scale(preciptotal) -7.002e-05    6.2e-05     -1.129      0.259      -0.000    5.15e-05
==============================================================================
Omnibus:                   736510.188   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       1900909058.063
Skew:                          15.975   Prob(JB):                         0.00
Kurtosis:                     350.799   Cond. No.                         123.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### Anova 분석을 통해 p-value가 0.05보다 큰것은 제외

In [25]:
anova_result2_1 = sm.stats.anova_lm(result2_1).sort_values(by=['PR(>F)'], ascending = False)
anova_result2_1[anova_result2_1['PR(>F)'] <= 0.05]

C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)

                 df       sum_sq    mean_sq             F         PR(>F)
C(rainY)        1.0     0.044425   0.044425     36.539267   1.497624e-09
C(weekend)      1.0     0.638783   0.638783    525.399489  3.405796e-116
C(month)       11.0     0.940881   0.085535     70.352291  1.136054e-158
C(year)         3.0    20.306340   6.768780   5567.325115   0.000000e+00
C(store_nbr)    3.0     6.087030   2.029010   1668.861688   0.000000e+00
C(item_nbr)   109.0  7307.972801  67.045622  55145.059923   0.000000e+00

### 최종 Anova 분석과 TIF 통과한 변수들을 바탕으로 최종 모델생성

In [27]:
# OLS - df2_1_1
model2_1 = sm.OLS.from_formula('log1p_units ~ C(year) + C(month) + \
C(weekend) + C(rainY) + C(store_nbr) + C(item_nbr) + 0', data = df2_1)

result = model2_1.fit()
result2_1 = model2_1.fit()
print(result2_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            log1p_units   R-squared:                       0.942
Model:                            OLS   Adj. R-squared:                  0.941
Method:                 Least Squares   F-statistic:                 4.738e+04
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        12:22:06   Log-Likelihood:             7.2458e+05
No. Observations:              373995   AIC:                        -1.449e+06
Df Residuals:                  373867   BIC:                        -1.448e+06
Df Model:                         127
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
C(year)[2012]          0.0003      0.001      0.413      0.680      -0.001       0.001
C(year)[2013]         -0.0003      0.001     -0.551      0.581      -0.002       0.001
C(year)[2014]         -0.0011      0.001     -1.712      0.087      -0.002       0.000
C(month)[T.2]       9.805e-05      0.000      0.377      0.706      -0.000       0.001
C(month)[T.3]          0.0002      0.000      0.880      0.379      -0.000       0.001
C(month)[T.4]          0.0003      0.000      1.196      0.232      -0.000       0.001
C(month)[T.5]          0.0003      0.000      1.059      0.290      -0.000       0.001
C(month)[T.6]          0.0001      0.000      0.431      0.666      -0.000       0.001
C(month)[T.7]       9.231e-05      0.000      0.324      0.746      -0.000       0.001
C(month)[T.8]          0.0003      0.000      1.176      0.240      -0.000       0.001
C(month)[T.9]       8.692e-05      0.000      0.333      0.739      -0.000       0.001
C(month)[T.10]        -0.0004      0.000     -1.760      0.078      -0.001    5.07e-05
C(month)[T.11]        -0.0001      0.000     -0.417      0.677      -0.001       0.000
C(month)[T.12]        -0.0001      0.000     -0.486      0.627      -0.001       0.000
C(weekend)[T.1]        0.0001      0.000      1.097      0.273      -0.000       0.000
C(rainY)[T.1]       8.355e-05      0.000      0.671      0.502      -0.000       0.000
C(store_nbr)[T.6]     -0.0006      0.000     -3.773      0.000      -0.001      -0.000
C(store_nbr)[T.38]     0.0015      0.000      9.133      0.000       0.001       0.002
C(store_nbr)[T.42]    -0.0002      0.000     -1.525      0.127      -0.001    7.01e-05
C(item_nbr)[T.2]   -3.031e-15      0.001  -3.64e-12      1.000      -0.002       0.002
C(item_nbr)[T.3]   -2.476e-15      0.001  -2.97e-12      1.000      -0.002       0.002
C(item_nbr)[T.4]   -3.023e-15      0.001  -3.63e-12      1.000      -0.002       0.002
C(item_nbr)[T.5]       2.1984      0.003    673.339      0.000       2.192       2.205
C(item_nbr)[T.6]   -4.006e-15      0.001  -4.81e-12      1.000      -0.002       0.002
C(item_nbr)[T.7]   -2.327e-15      0.001  -2.79e-12      1.000      -0.002       0.002
C(item_nbr)[T.8]   -2.689e-15      0.001  -3.23e-12      1.000      -0.002       0.002
C(item_nbr)[T.9]       2.3933      0.005    467.370      0.000       2.383       2.403
C(item_nbr)[T.10]  -2.731e-15      0.001  -3.28e-12      1.000      -0.002       0.002
C(item_nbr)[T.11]      0.0257      0.001     30.421      0.000       0.024       0.027
C(item_nbr)[T.12]  -2.693e-15      0.001  -3.23e-12      1.000      -0.002       0.002
C(item_nbr)[T.13]  -2.716e-15      0.001  -3.26e-12      1.000      -0.002       0.002
C(item_nbr)[T.14]      0.0166      0.001     19.806      0.000       0.015       0.018
C(item_nbr)[T.15]  -2.782e-15      0.001  -3.34e-12      1.000      -0.002       0.002
C(item_nbr)[T.16]  -2.762e-15      0.001  -3.31e-12      1.000      -0.002       0.002
C(item_nbr)[T.17]   -2.69e-15      0.001  -3.23e-12      1.000      -0.002       0.002
C(item_nbr)[T.18]  -2.729e-15      0.001  -3.27e-12      1.000      -0.002       0.002
C(item_nbr)[T.19]  -2.725e-15      0.001  -3.27e-12      1.000      -0.002       0.002
C(item_nbr)[T.20]  -2.735e-15      0.001  -3.28e-12      1.000      -0.002       0.002
C(item_nbr)[T.21]   -2.71e-15      0.001  -3.25e-12      1.000      -0.002       0.002
C(item_nbr)[T.22]  -2.644e-15      0.001  -3.17e-12      1.000      -0.002       0.002
C(item_nbr)[T.23]  -2.762e-15      0.001  -3.31e-12      1.000      -0.002       0.002
C(item_nbr)[T.24]  -2.745e-15      0.001  -3.29e-12      1.000      -0.002       0.002
C(item_nbr)[T.25]  -2.899e-15      0.001  -3.48e-12      1.000      -0.002       0.002
C(item_nbr)[T.26]  -2.803e-15      0.001  -3.36e-12      1.000      -0.002       0.002
C(item_nbr)[T.27]  -2.688e-15      0.001  -3.23e-12      1.000      -0.002       0.002
C(item_nbr)[T.28]  -2.726e-15      0.001  -3.27e-12      1.000      -0.002       0.002
C(item_nbr)[T.29]   -2.61e-15      0.001  -3.13e-12      1.000      -0.002       0.002
C(item_nbr)[T.30]  -2.704e-15      0.001  -3.24e-12      1.000      -0.002       0.002
C(item_nbr)[T.31]  -2.731e-15      0.001  -3.28e-12      1.000      -0.002       0.002
C(item_nbr)[T.32]  -2.806e-15      0.001  -3.37e-12      1.000      -0.002       0.002
C(item_nbr)[T.33]   -2.65e-15      0.001  -3.18e-12      1.000      -0.002       0.002
C(item_nbr)[T.34]  -2.716e-15      0.001  -3.26e-12      1.000      -0.002       0.002
C(item_nbr)[T.35]  -2.852e-15      0.001  -3.42e-12      1.000      -0.002       0.002
C(item_nbr)[T.36]  -2.669e-15      0.001   -3.2e-12      1.000      -0.002       0.002
C(item_nbr)[T.37]  -2.817e-15      0.001  -3.38e-12      1.000      -0.002       0.002
C(item_nbr)[T.38]  -2.871e-15      0.001  -3.44e-12      1.000      -0.002       0.002
C(item_nbr)[T.39]  -2.769e-15      0.001  -3.32e-12      1.000      -0.002       0.002
C(item_nbr)[T.40]   -2.66e-15      0.001  -3.19e-12      1.000      -0.002       0.002
C(item_nbr)[T.41]  -2.838e-15      0.001   -3.4e-12      1.000      -0.002       0.002
C(item_nbr)[T.42]  -2.717e-15      0.001  -3.26e-12      1.000      -0.002       0.002
C(item_nbr)[T.43]  -2.649e-15      0.001  -3.18e-12      1.000      -0.002       0.002
C(item_nbr)[T.45]      3.8077      0.002   2172.960      0.000       3.804       3.811
C(item_nbr)[T.46]   -2.74e-15      0.001  -3.29e-12      1.000      -0.002       0.002
C(item_nbr)[T.47]  -2.734e-15      0.001  -3.28e-12      1.000      -0.002       0.002
C(item_nbr)[T.48]  -2.807e-15      0.001  -3.37e-12      1.000      -0.002       0.002
C(item_nbr)[T.49]  -2.711e-15      0.001  -3.25e-12      1.000      -0.002       0.002
C(item_nbr)[T.50]  -2.777e-15      0.001  -3.33e-12      1.000      -0.002       0.002
C(item_nbr)[T.51]  -2.749e-15      0.001   -3.3e-12      1.000      -0.002       0.002
C(item_nbr)[T.52]      0.0433      0.001     51.062      0.000       0.042       0.045
C(item_nbr)[T.53]  -2.769e-15      0.001  -3.32e-12      1.000      -0.002       0.002
C(item_nbr)[T.54]  -2.758e-15      0.001  -3.31e-12      1.000      -0.002       0.002
C(item_nbr)[T.55]  -2.747e-15      0.001   -3.3e-12      1.000      -0.002       0.002
C(item_nbr)[T.56]  -2.783e-15      0.001  -3.34e-12      1.000      -0.002       0.002
C(item_nbr)[T.57]   -2.74e-15      0.001  -3.29e-12      1.000      -0.002       0.002
C(item_nbr)[T.58]   -2.87e-15      0.001  -3.44e-12      1.000      -0.002       0.002
C(item_nbr)[T.59]  -2.707e-15      0.001  -3.25e-12      1.000      -0.002       0.002
C(item_nbr)[T.60]  -2.719e-15      0.001  -3.26e-12      1.000      -0.002       0.002
C(item_nbr)[T.61]    -2.8e-15      0.001  -3.36e-12      1.000      -0.002       0.002
C(item_nbr)[T.62]  -2.732e-15      0.001  -3.28e-12      1.000      -0.002       0.002
C(item_nbr)[T.63]  -2.752e-15      0.001   -3.3e-12      1.000      -0.002       0.002
C(item_nbr)[T.64]  -2.771e-15      0.001  -3.32e-12      1.000      -0.002       0.002
C(item_nbr)[T.65]  -2.846e-15      0.001  -3.41e-12      1.000      -0.002       0.002
C(item_nbr)[T.66]  -2.594e-15      0.001  -3.11e-12      1.000      -0.002       0.002
C(item_nbr)[T.67]  -2.779e-15      0.001  -3.33e-12      1.000      -0.002       0.002
C(item_nbr)[T.68]  -2.698e-15      0.001  -3.24e-12      1.000      -0.002       0.002
C(item_nbr)[T.69]  -2.853e-15      0.001  -3.42e-12      1.000      -0.002       0.002
C(item_nbr)[T.70]  -2.828e-15      0.001  -3.39e-12      1.000      -0.002       0.002
C(item_nbr)[T.71]  -2.629e-15      0.001  -3.15e-12      1.000      -0.002       0.002
C(item_nbr)[T.72]   -2.84e-15      0.001  -3.41e-12      1.000      -0.002       0.002
C(item_nbr)[T.73]  -2.711e-15      0.001  -3.25e-12      1.000      -0.002       0.002
C(item_nbr)[T.74]  -2.757e-15      0.001  -3.31e-12      1.000      -0.002       0.002
C(item_nbr)[T.75]  -2.713e-15      0.001  -3.25e-12      1.000      -0.002       0.002
C(item_nbr)[T.76]  -2.866e-15      0.001  -3.44e-12      1.000      -0.002       0.002
C(item_nbr)[T.77]  -2.684e-15      0.001  -3.22e-12      1.000      -0.002       0.002
C(item_nbr)[T.78]  -2.683e-15      0.001  -3.22e-12      1.000      -0.002       0.002
C(item_nbr)[T.79]  -2.752e-15      0.001   -3.3e-12      1.000      -0.002       0.002
C(item_nbr)[T.80]  -2.698e-15      0.001  -3.24e-12      1.000      -0.002       0.002
C(item_nbr)[T.81]  -2.706e-15      0.001  -3.25e-12      1.000      -0.002       0.002
C(item_nbr)[T.82]      0.0372      0.001     44.295      0.000       0.036       0.039
C(item_nbr)[T.83]  -2.678e-15      0.001  -3.21e-12      1.000      -0.002       0.002
C(item_nbr)[T.84]  -2.781e-15      0.001  -3.34e-12      1.000      -0.002       0.002
C(item_nbr)[T.85]      0.0086      0.001     10.274      0.000       0.007       0.010
C(item_nbr)[T.86]      0.0058      0.001      6.919      0.000       0.004       0.007
C(item_nbr)[T.87]  -2.571e-15      0.001  -3.08e-12      1.000      -0.002       0.002
C(item_nbr)[T.88]  -2.735e-15      0.001  -3.28e-12      1.000      -0.002       0.002
C(item_nbr)[T.89]  -2.879e-15      0.001  -3.45e-12      1.000      -0.002       0.002
C(item_nbr)[T.90]  -2.745e-15      0.001  -3.29e-12      1.000      -0.002       0.002
C(item_nbr)[T.91]  -2.978e-15      0.001  -3.57e-12      1.000      -0.002       0.002
C(item_nbr)[T.92]  -2.975e-15      0.001  -3.57e-12      1.000      -0.002       0.002
C(item_nbr)[T.93]      0.0145      0.001     17.170      0.000       0.013       0.016
C(item_nbr)[T.94]  -2.656e-15      0.001  -3.19e-12      1.000      -0.002       0.002
C(item_nbr)[T.95]  -2.548e-15      0.001  -3.06e-12      1.000      -0.002       0.002
C(item_nbr)[T.96]  -2.767e-15      0.001  -3.32e-12      1.000      -0.002       0.002
C(item_nbr)[T.97]  -2.815e-15      0.001  -3.38e-12      1.000      -0.002       0.002
C(item_nbr)[T.98]      0.0272      0.001     32.298      0.000       0.026       0.029
C(item_nbr)[T.99]  -2.692e-15      0.001  -3.23e-12      1.000      -0.002       0.002
C(item_nbr)[T.100] -2.925e-15      0.001  -3.51e-12      1.000      -0.002       0.002
C(item_nbr)[T.101] -2.644e-15      0.001  -3.17e-12      1.000      -0.002       0.002
C(item_nbr)[T.102] -2.691e-15      0.001  -3.23e-12      1.000      -0.002       0.002
C(item_nbr)[T.103]  -2.52e-15      0.001  -3.02e-12      1.000      -0.002       0.002
C(item_nbr)[T.104] -2.793e-15      0.001  -3.35e-12      1.000      -0.002       0.002
C(item_nbr)[T.105] -2.797e-15      0.001  -3.36e-12      1.000      -0.002       0.002
C(item_nbr)[T.106] -2.654e-15      0.001  -3.18e-12      1.000      -0.002       0.002
C(item_nbr)[T.107]     0.0099      0.001     11.729      0.000       0.008       0.012
C(item_nbr)[T.108] -2.902e-15      0.001  -3.48e-12      1.000      -0.002       0.002
C(item_nbr)[T.109] -2.976e-15      0.001  -3.57e-12      1.000      -0.002       0.002
C(item_nbr)[T.110] -2.759e-15      0.001  -3.31e-12      1.000      -0.002       0.002
C(item_nbr)[T.111]  -3.02e-15      0.001  -3.62e-12      1.000      -0.002       0.002
==============================================================================
Omnibus:                   736516.263   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       1901002106.218
Skew:                          15.975   Prob(JB):                         0.00
Kurtosis:                     350.808   Cond. No.                         105.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [28]:
from patsy import dmatrix
# 독립변수와 종속변수로 나누기
df2_1_X = df2_1.drop(columns=['log1p_units'])
df2_1_target = df2_1['log1p_units']

In [29]:
formula = 'C(year) + C(month) + C(weekend) \
        + C(rainY) + C(store_nbr) + C(item_nbr) + 0'
dfX = dmatrix(formula, df2_1_X, return_type='dataframe')
dfy = pd.DataFrame(df2_1_target, columns=["log1p_units"])

In [30]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold
from sklearn.metrics import r2_score

model = LinearRegression()
cv = KFold(10)

scores = np.zeros(10)
for i, (train_index, test_index) in enumerate(cv.split(dfX)):
    X_train = dfX.values[train_index]
    y_train = dfy.values[train_index]
    X_test = dfX.values[test_index]
    y_test = dfy.values[test_index]
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    scores[i] = r2_score(y_test, y_pred)

scores

array([0.91234521, 0.88995094, 0.86880832, 0.93505502, 0.90409244,
       0.92914693, 0.94627414, 0.96090479, 0.97230464, 0.97701019])