In [1]:
from patsy import dmatrix
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold
from sklearn.metrics import r2_score

In [2]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [3]:
stations_name = ["station"+str(i) for i in range(1, 21)]
print(stations_name)

['station1', 'station2', 'station3', 'station4', 'station5', 'station6', 'station7', 'station8', 'station9', 'station10', 'station11', 'station12', 'station13', 'station14', 'station15', 'station16', 'station17', 'station18', 'station19', 'station20']

In [4]:
# 파일불러오기
station1 = pd.read_csv("station1.csv")
station2 = pd.read_csv("station2.csv")
station3 = pd.read_csv("station3.csv")
station4 = pd.read_csv("station4.csv")
station5 = pd.read_csv("station5.csv")
station6 = pd.read_csv("station6.csv")
station7 = pd.read_csv("station7.csv")
station8 = pd.read_csv("station8.csv")
station9 = pd.read_csv("station9.csv")
station10 = pd.read_csv("station10.csv")
station11 = pd.read_csv("station11.csv")
station12 = pd.read_csv("station12.csv")
station13 = pd.read_csv("station13.csv")
station14 = pd.read_csv("station14.csv")
station15 = pd.read_csv("station15.csv")
station16 = pd.read_csv("station16.csv")
station17 = pd.read_csv("station17.csv")
station18 = pd.read_csv("station18.csv")
station19 = pd.read_csv("station19.csv")
station20 = pd.read_csv("station20.csv")

In [26]:
data_weather = pd.read_csv('weather3_180703.csv')
data_key = pd.read_csv('key.csv')
data_test = pd.read_csv('test.csv')

In [27]:
len(test)

526917

In [30]:
test = data_test.merge(data_key, on = ('store_nbr'))
test

              date  store_nbr  item_nbr  station_nbr
0       2013-04-01          2         1           14
1       2013-04-01          2         2           14
2       2013-04-01          2         3           14
3       2013-04-01          2         4           14
4       2013-04-01          2         5           14
5       2013-04-01          2         6           14
6       2013-04-01          2         7           14
7       2013-04-01          2         8           14
8       2013-04-01          2         9           14
9       2013-04-01          2        10           14
10      2013-04-01          2        11           14
11      2013-04-01          2        12           14
12      2013-04-01          2        13           14
13      2013-04-01          2        14           14
14      2013-04-01          2        15           14
15      2013-04-01          2        16           14
16      2013-04-01          2        17           14
17      2013-04-01          2        18           14
18      2013-04-01          2        19           14
19      2013-04-01          2        20           14
20      2013-04-01          2        21           14
21      2013-04-01          2        22           14
22      2013-04-01          2        23           14
23      2013-04-01          2        24           14
24      2013-04-01          2        25           14
25      2013-04-01          2        26           14
26      2013-04-01          2        27           14
27      2013-04-01          2        28           14
28      2013-04-01          2        29           14
29      2013-04-01          2        30           14
30      2013-04-01          2        31           14
31      2013-04-01          2        32           14
32      2013-04-01          2        33           14
33      2013-04-01          2        34           14
34      2013-04-01          2        35           14
35      2013-04-01          2        36           14
36      2013-04-01          2        37           14
37      2013-04-01          2        38           14
38      2013-04-01          2        39           14
39      2013-04-01          2        40           14
40      2013-04-01          2        41           14
41      2013-04-01          2        42           14
42      2013-04-01          2        43           14
43      2013-04-01          2        44           14
44      2013-04-01          2        45           14
45      2013-04-01          2        46           14
46      2013-04-01          2        47           14
47      2013-04-01          2        48           14
48      2013-04-01          2        49           14
49      2013-04-01          2        50           14
50      2013-04-01          2        51           14
51      2013-04-01          2        52           14
52      2013-04-01          2        53           14
53      2013-04-01          2        54           14
54      2013-04-01          2        55           14
55      2013-04-01          2        56           14
56      2013-04-01          2        57           14
57      2013-04-01          2        58           14
58      2013-04-01          2        59           14
59      2013-04-01          2        60           14
60      2013-04-01          2        61           14
61      2013-04-01          2        62           14
62      2013-04-01          2        63           14
63      2013-04-01          2        64           14
64      2013-04-01          2        65           14
65      2013-04-01          2        66           14
66      2013-04-01          2        67           14
67      2013-04-01          2        68           14
68      2013-04-01          2        69           14
69      2013-04-01          2        70           14
70      2013-04-01          2        71           14
71      2013-04-01          2        72           14
72      2013-04-01          2        73           14
73      2013-04-01          2        74           14
74      2013-04-01          2        75           14
75      2013-04-01          2        76           14
76      2013-04-01          2        77           14
77      2013-04-01          2        78           14
78      2013-04-01          2        79           14
79      2013-04-01          2        80           14
80      2013-04-01          2        81           14
81      2013-04-01          2        82           14
82      2013-04-01          2        83           14
83      2013-04-01          2        84           14
84      2013-04-01          2        85           14
85      2013-04-01          2        86           14
86      2013-04-01          2        87           14
87      2013-04-01          2        88           14
88      2013-04-01          2        89           14
89      2013-04-01          2        90           14
90      2013-04-01          2        91           14
91      2013-04-01          2        92           14
92      2013-04-01          2        93           14
93      2013-04-01          2        94           14
94      2013-04-01          2        95           14
95      2013-04-01          2        96           14
96      2013-04-01          2        97           14
97      2013-04-01          2        98           14
98      2013-04-01          2        99           14
99      2013-04-01          2       100           14
100     2013-04-01          2       101           14
101     2013-04-01          2       102           14
102     2013-04-01          2       103           14
103     2013-04-01          2       104           14
104     2013-04-01          2       105           14
105     2013-04-01          2       106           14
106     2013-04-01          2       107           14
107     2013-04-01          2       108           14
108     2013-04-01          2       109           14
109     2013-04-01          2       110           14
110     2013-04-01          2       111           14
111     2013-04-02          2         1           14
112     2013-04-02          2         2           14
113     2013-04-02          2         3           14
114     2013-04-02          2         4           14
115     2013-04-02          2         5           14
116     2013-04-02          2         6           14
117     2013-04-02          2         7           14
118     2013-04-02          2         8           14
119     2013-04-02          2         9           14
120     2013-04-02          2        10           14
121     2013-04-02          2        11           14
122     2013-04-02          2        12           14
123     2013-04-02          2        13           14
124     2013-04-02          2        14           14
125     2013-04-02          2        15           14
126     2013-04-02          2        16           14
127     2013-04-02          2        17           14
128     2013-04-02          2        18           14
129     2013-04-02          2        19           14
130     2013-04-02          2        20           14
131     2013-04-02          2        21           14
132     2013-04-02          2        22           14
133     2013-04-02          2        23           14
134     2013-04-02          2        24           14
135     2013-04-02          2        25           14
136     2013-04-02          2        26           14
137     2013-04-02          2        27           14
138     2013-04-02          2        28           14
139     2013-04-02          2        29           14
140     2013-04-02          2        30           14
141     2013-04-02          2        31           14
142     2013-04-02          2        32           14
143     2013-04-02          2        33           14
144     2013-04-02          2        34           14
145     2013-04-02          2        35           14
146     2013-04-02          2        36           14
147     2013-04-02          2        37           14
148     2013-04-02          2        38           14
149     2013-04-02          2        39           14
150     2013-04-02          2        40           14
151     2013-04-02          2        41           14
152     2013-04-02          2        42           14
153     2013-04-02          2        43           14
154     2013-04-02          2        44           14
155     2013-04-02          2        45           14
156     2013-04-02          2        46           14
157     2013-04-02          2        47           14
158     2013-04-02          2        48           14
159     2013-04-02          2        49           14
160     2013-04-02          2        50           14
161     2013-04-02          2        51           14
162     2013-04-02          2        52           14
163     2013-04-02          2        53           14
164     2013-04-02          2        54           14
165     2013-04-02          2        55           14
166     2013-04-02          2        56           14
167     2013-04-02          2        57           14
168     2013-04-02          2        58           14
169     2013-04-02          2        59           14
170     2013-04-02          2        60           14
171     2013-04-02          2        61           14
172     2013-04-02          2        62           14
173     2013-04-02          2        63           14
174     2013-04-02          2        64           14
175     2013-04-02          2        65           14
176     2013-04-02          2        66           14
177     2013-04-02          2        67           14
178     2013-04-02          2        68           14
179     2013-04-02          2        69           14
180     2013-04-02          2        70           14
181     2013-04-02          2        71           14
182     2013-04-02          2        72           14
183     2013-04-02          2        73           14
184     2013-04-02          2        74           14
185     2013-04-02          2        75           14
186     2013-04-02          2        76           14
187     2013-04-02          2        77           14
188     2013-04-02          2        78           14
189     2013-04-02          2        79           14
190     2013-04-02          2        80           14
191     2013-04-02          2        81           14
192     2013-04-02          2        82           14
193     2013-04-02          2        83           14
194     2013-04-02          2        84           14
195     2013-04-02          2        85           14
196     2013-04-02          2        86           14
197     2013-04-02          2        87           14
198     2013-04-02          2        88           14
199     2013-04-02          2        89           14
200     2013-04-02          2        90           14
201     2013-04-02          2        91           14
202     2013-04-02          2        92           14
203     2013-04-02          2        93           14
204     2013-04-02          2        94           14
205     2013-04-02          2        95           14
206     2013-04-02          2        96           14
207     2013-04-02          2        97           14
208     2013-04-02          2        98           14
209     2013-04-02          2        99           14
210     2013-04-02          2       100           14
211     2013-04-02          2       101           14
212     2013-04-02          2       102           14
213     2013-04-02          2       103           14
214     2013-04-02          2       104           14
215     2013-04-02          2       105           14
216     2013-04-02          2       106           14
217     2013-04-02          2       107           14
218     2013-04-02          2       108           14
219     2013-04-02          2       109           14
220     2013-04-02          2       110           14
221     2013-04-02          2       111           14
222     2013-04-03          2         1           14
223     2013-04-03          2         2           14
224     2013-04-03          2         3           14
225     2013-04-03          2         4           14
226     2013-04-03          2         5           14
227     2013-04-03          2         6           14
228     2013-04-03          2         7           14
229     2013-04-03          2         8           14
230     2013-04-03          2         9           14
231     2013-04-03          2        10           14
232     2013-04-03          2        11           14
233     2013-04-03          2        12           14
234     2013-04-03          2        13           14
235     2013-04-03          2        14           14
236     2013-04-03          2        15           14
237     2013-04-03          2        16           14
238     2013-04-03          2        17           14
239     2013-04-03          2        18           14
240     2013-04-03          2        19           14
241     2013-04-03          2        20           14
242     2013-04-03          2        21           14
243     2013-04-03          2        22           14
244     2013-04-03          2        23           14
245     2013-04-03          2        24           14
246     2013-04-03          2        25           14
247     2013-04-03          2        26           14
248     2013-04-03          2        27           14
249     2013-04-03          2        28           14
...            ...        ...       ...          ...
526667  2014-07-31         40        84           13
526668  2014-07-31         40        85           13
526669  2014-07-31         40        86           13
526670  2014-07-31         40        87           13
526671  2014-07-31         40        88           13
526672  2014-07-31         40        89           13
526673  2014-07-31         40        90           13
526674  2014-07-31         40        91           13
526675  2014-07-31         40        92           13
526676  2014-07-31         40        93           13
526677  2014-07-31         40        94           13
526678  2014-07-31         40        95           13
526679  2014-07-31         40        96           13
526680  2014-07-31         40        97           13
526681  2014-07-31         40        98           13
526682  2014-07-31         40        99           13
526683  2014-07-31         40       100           13
526684  2014-07-31         40       101           13
526685  2014-07-31         40       102           13
526686  2014-07-31         40       103           13
526687  2014-07-31         40       104           13
526688  2014-07-31         40       105           13
526689  2014-07-31         40       106           13
526690  2014-07-31         40       107           13
526691  2014-07-31         40       108           13
526692  2014-07-31         40       109           13
526693  2014-07-31         40       110           13
526694  2014-07-31         40       111           13
526695  2014-08-01         40         1           13
526696  2014-08-01         40         2           13
526697  2014-08-01         40         3           13
526698  2014-08-01         40         4           13
526699  2014-08-01         40         5           13
526700  2014-08-01         40         6           13
526701  2014-08-01         40         7           13
526702  2014-08-01         40         8           13
526703  2014-08-01         40         9           13
526704  2014-08-01         40        10           13
526705  2014-08-01         40        11           13
526706  2014-08-01         40        12           13
526707  2014-08-01         40        13           13
526708  2014-08-01         40        14           13
526709  2014-08-01         40        15           13
526710  2014-08-01         40        16           13
526711  2014-08-01         40        17           13
526712  2014-08-01         40        18           13
526713  2014-08-01         40        19           13
526714  2014-08-01         40        20           13
526715  2014-08-01         40        21           13
526716  2014-08-01         40        22           13
526717  2014-08-01         40        23           13
526718  2014-08-01         40        24           13
526719  2014-08-01         40        25           13
526720  2014-08-01         40        26           13
526721  2014-08-01         40        27           13
526722  2014-08-01         40        28           13
526723  2014-08-01         40        29           13
526724  2014-08-01         40        30           13
526725  2014-08-01         40        31           13
526726  2014-08-01         40        32           13
526727  2014-08-01         40        33           13
526728  2014-08-01         40        34           13
526729  2014-08-01         40        35           13
526730  2014-08-01         40        36           13
526731  2014-08-01         40        37           13
526732  2014-08-01         40        38           13
526733  2014-08-01         40        39           13
526734  2014-08-01         40        40           13
526735  2014-08-01         40        41           13
526736  2014-08-01         40        42           13
526737  2014-08-01         40        43           13
526738  2014-08-01         40        44           13
526739  2014-08-01         40        45           13
526740  2014-08-01         40        46           13
526741  2014-08-01         40        47           13
526742  2014-08-01         40        48           13
526743  2014-08-01         40        49           13
526744  2014-08-01         40        50           13
526745  2014-08-01         40        51           13
526746  2014-08-01         40        52           13
526747  2014-08-01         40        53           13
526748  2014-08-01         40        54           13
526749  2014-08-01         40        55           13
526750  2014-08-01         40        56           13
526751  2014-08-01         40        57           13
526752  2014-08-01         40        58           13
526753  2014-08-01         40        59           13
526754  2014-08-01         40        60           13
526755  2014-08-01         40        61           13
526756  2014-08-01         40        62           13
526757  2014-08-01         40        63           13
526758  2014-08-01         40        64           13
526759  2014-08-01         40        65           13
526760  2014-08-01         40        66           13
526761  2014-08-01         40        67           13
526762  2014-08-01         40        68           13
526763  2014-08-01         40        69           13
526764  2014-08-01         40        70           13
526765  2014-08-01         40        71           13
526766  2014-08-01         40        72           13
526767  2014-08-01         40        73           13
526768  2014-08-01         40        74           13
526769  2014-08-01         40        75           13
526770  2014-08-01         40        76           13
526771  2014-08-01         40        77           13
526772  2014-08-01         40        78           13
526773  2014-08-01         40        79           13
526774  2014-08-01         40        80           13
526775  2014-08-01         40        81           13
526776  2014-08-01         40        82           13
526777  2014-08-01         40        83           13
526778  2014-08-01         40        84           13
526779  2014-08-01         40        85           13
526780  2014-08-01         40        86           13
526781  2014-08-01         40        87           13
526782  2014-08-01         40        88           13
526783  2014-08-01         40        89           13
526784  2014-08-01         40        90           13
526785  2014-08-01         40        91           13
526786  2014-08-01         40        92           13
526787  2014-08-01         40        93           13
526788  2014-08-01         40        94           13
526789  2014-08-01         40        95           13
526790  2014-08-01         40        96           13
526791  2014-08-01         40        97           13

In [34]:
test['count'] = test.index.astype(str).astype(int)

In [36]:
test.tail()

              date  store_nbr  item_nbr  station_nbr   count
526912  2014-08-02         40       107           13  526912
526913  2014-08-02         40       108           13  526913
526914  2014-08-02         40       109           13  526914
526915  2014-08-02         40       110           13  526915
526916  2014-08-02         40       111           13  526916

In [37]:
test = data_weather.merge(test, on=('date', 'station_nbr'))

In [39]:
test.head()

   station_nbr        date  tmax  tmin  tavg  depart  dewpoint  wetbulb  heat  cool  sunrise  sunset codesum  snowfall  preciptotal  stnpressure  sealevel  resultspeed  resultdir  avgspeed  year  month  day  relative_humility  windchill  daytime  week7  weekend  code_change  rainY  otherY  nothing  store_nbr  item_nbr   count
0            1  2013-06-04  70.0  53.0  61.5     NaN      42.0     52.0   3.0   0.0      NaN     NaN      MD       NaN          0.0        29.77     29.96          7.3       31.0       8.0  2013      6    4          48.697432  60.769718      NaN      1        0            0      0       0        1          1         1  484293
1            1  2013-06-04  70.0  53.0  61.5     NaN      42.0     52.0   3.0   0.0      NaN     NaN      MD       NaN          0.0        29.77     29.96          7.3       31.0       8.0  2013      6    4          48.697432  60.769718      NaN      1        0            0      0       0        1          1         2  484294
2            1  2013-06-04  70.0  53.0  61.5     NaN      42.0     52.0   3.0   0.0      NaN     NaN      MD       NaN          0.0        29.77     29.96          7.3       31.0       8.0  2013      6    4          48.697432  60.769718      NaN      1        0            0      0       0        1          1         3  484295
3            1  2013-06-04  70.0  53.0  61.5     NaN      42.0     52.0   3.0   0.0      NaN     NaN      MD       NaN          0.0        29.77     29.96          7.3       31.0       8.0  2013      6    4          48.697432  60.769718      NaN      1        0            0      0       0        1          1         4  484296
4            1  2013-06-04  70.0  53.0  61.5     NaN      42.0     52.0   3.0   0.0      NaN     NaN      MD       NaN          0.0        29.77     29.96          7.3       31.0       8.0  2013      6    4          48.697432  60.769718      NaN      1        0            0      0       0        1          1         5  484297

In [40]:
len(test)

526917

In [44]:
test = test.sort_values(by='count')

In [45]:
for i in
test

        station_nbr        date  tmax  tmin  tavg  depart  dewpoint    wetbulb  heat  cool  sunrise  sunset        codesum  snowfall  preciptotal  stnpressure  sealevel  resultspeed  resultdir  avgspeed  year  month  day  relative_humility  windchill    daytime  week7  weekend  code_change  rainY  otherY  nothing  store_nbr  item_nbr   count
326118           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2         1       0
326119           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2         2       1
326120           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2         3       2
326121           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2         4       3
326122           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2         5       4
326123           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2         6       5
326124           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2         7       6
326125           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2         8       7
326126           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2         9       8
326127           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        10       9
326128           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        11      10
326129           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        12      11
326130           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        13      12
326131           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        14      13
326132           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        15      14
326133           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        16      15
326134           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        17      16
326135           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        18      17
326136           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        19      18
326137           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        20      19
326138           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        21      20
326139           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        22      21
326140           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        23      22
326141           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        24      23
326142           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        25      24
326143           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        26      25
326144           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        27      26
326145           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        28      27
326146           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        29      28
326147           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        30      29
326148           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        31      30
326149           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        32      31
326150           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        33      32
326151           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        34      33
326152           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        35      34
326153           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        36      35
326154           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        37      36
326155           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        38      37
326156           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        39      38
326157           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        40      39
326158           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        41      40
326159           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        42      41
326160           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        43      42
326161           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        44      43
326162           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        45      44
326163           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        46      45
326164           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        47      46
326165           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        48      47
326166           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        49      48
326167           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        50      49
326168           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        51      50
326169           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        52      51
326170           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        53      52
326171           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        54      53
326172           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        55      54
326173           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        56      55
326174           14  2013-04-01  71.0  42.0  56.5     1.0      41.0  48.000000   8.0   0.0    617.0  1851.0             RA       0.0        0.005        28.68     30.05          9.3        4.0      11.0  2013      4    1          56.021743  53.835501  12.566667      0        0            2      1       0        0          2        57      56

In [47]:
data_set1 = test[test["station_nbr"] == 1]  
data_set2 = test[test["station_nbr"] == 2]  
data_set3 = test[test["station_nbr"] == 3]  
data_set4 = test[test["station_nbr"] == 4]  
data_set5 = test[test["station_nbr"] == 5]  
data_set6 = test[test["station_nbr"] == 6]  
data_set7 = test[test["station_nbr"] == 7]  
data_set8 = test[test["station_nbr"] == 8]  
data_set9 = test[test["station_nbr"] == 9]  
data_set10 = test[test["station_nbr"] == 10]
data_set11 = test[test["station_nbr"] == 11]
data_set12 = test[test["station_nbr"] == 12]
data_set13 = test[test["station_nbr"] == 13]
data_set14 = test[test["station_nbr"] == 14]
data_set15 = test[test["station_nbr"] == 15]
data_set16 = test[test["station_nbr"] == 16]
data_set17 = test[test["station_nbr"] == 17]
data_set18 = test[test["station_nbr"] == 18]
data_set19 = test[test["station_nbr"] == 19]
data_set20 = test[test["station_nbr"] == 20]

data_set = [data_set1, data_set2, data_set3, data_set4, data_set5, data_set6, data_set7, data_set8, data_set9, data_set10, data_set11, data_set12, data_set13, data_set14, data_set15, data_set16, data_set17, data_set18, data_set19, data_set20]

In [51]:
def make_model(i, station):
    d_variables = "np.log1p(units) ~ " + "".join(stations_var_c[i-1]) + "+0"
    model1 = sm.OLS.from_formula(d_variables, data = station)
    result1 = model1.fit()

    # 아웃라이어 제거
    # Cook's distance > 2 인 값 제거
    influence = result1.get_influence()
    cooks_d2, pvals = influence.cooks_distance
    fox_cr = 4 / (len(station) - 2)
    idx_outlier = np.where(cooks_d2 > fox_cr)[0]

    idx = list(set(range(len(station))).difference(idx_outlier))
    station_1 = station.iloc[idx, :].reset_index(drop=True)

    model2 = sm.OLS.from_formula(d_variables, station_1)
    result2 = model2.fit()
    b = data_set[i-1]
    predict_value = result2.predict(b)
    b["y"] = predict_value
    
    return data_set[i-1]

In [52]:
acuum_1 = make_model(1, station1)

MemoryError: